import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const OTO_ELEKTRIK_CSS: Record<string, string> = {
  '--container-default': '1200px',
  '--section-py': '80px',
  '--radius-md': '12px',
  '--radius-lg': '24px',
  '--color-bg': '#0B0F19',
  '--color-surface': '#111827',
  '--color-surface-elevated': '#1F2937',
  '--color-surface-muted': '#0F172A',
  '--color-text': '#F9FAFB',
  '--color-text-secondary': '#9CA3AF',
  '--color-text-muted': '#4B5563',
  '--color-text-on-accent': '#0B0F19',
  '--color-text-on-dark': '#F9FAFB',
  '--color-accent': '#6366F1',
  '--color-accent-hover': '#4F46E5',
  '--color-accent-active': '#4338CA',
  '--color-accent-light': '#1E1B4B',
  '--color-border': '#374151',
  '--color-border-subtle': '#1F2937',
  '--font-heading': "'Syne', sans-serif",
  '--font-body': "'Plus Jakarta Sans', sans-serif",
}

export const OTO_ELEKTRIK_BUSINESS = {
  name: 'Voltaj Oto Elektrik & Beyin Onarım',
  ownerName: 'Cemil Usta',
  ownerTitle: 'Kurucu ve Başteknisyen',
  sectorId: 'Oto',
  slogan: 'Aracınızın tüm elektrik ve elektronik sistemlerine profesyonel çözümler',
  phone: '0216 555 12 16',
  phoneClean: '902165551216',
  whatsapp: '905325551216',
  email: 'iletisim@voltajotoelektrik.com',
  address: 'Bostancı Sanayi Sitesi C Blok No:18, Ataşehir/İstanbul',
  city: 'İstanbul',
  district: 'Ataşehir',
  neighborhood: 'Bostancı Sanayi',
  coordinates: { lat: 40.9712, lng: 29.1132 },
  socialMedia: { instagram: 'https://instagram.com/voltajotoelektrik' },
  photos: [],
  foundedYear: 2018,
  experience: '15 yıllık uzmanlık',
  customerCount: '3.800+',
  rating: 4.8,
  reviewCount: 290,
  services: [
    {
      id: 's1',
      name: 'Oto Beyin (ECU) Onarım & Kodlama',
      price: 'Arıza durumuna göre',
      duration: '1-2 gün',
      description: 'Motor beyni onarımı, ABS, airbag, konfor beyni kodlama ve tamiratı. Orijinal yazılım güncellemeleri.',
    },
    {
      id: 's2',
      name: 'Elektrik Tesisat Revizyonu',
      price: '3.000 TL\'den başlayan',
      duration: '4-8 saat',
      description: 'Yıpranmış kablo tesisatlarının yenilenmesi, kısa devre tespit ve giderme, sigorta kutusu onarımı.',
    },
    {
      id: 's3',
      name: 'Marş & Şarj Dinamosu Tamiri',
      price: '1.500 TL',
      duration: '90 dk',
      description: 'Kömür değişimi, kollektör temizliği, bilye değişimi ve dinamoların sıfır ayarına getirilmesi.',
    },
    {
      id: 's4',
      name: 'Merkezi Kilit & Cam Motoru Onarımı',
      price: '800 TL\'den başlayan',
      duration: '45 dk',
      description: 'Kapı kilit motoru değişimi, cam kaldırma mekanizması onarımı ve kumanda kodlaması.',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Salı', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Çarşamba', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Perşembe', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Cuma', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Cumartesi', open: '08:30', close: '16:00', isOpen: true },
    { day: 'Pazar', open: null, close: null, isOpen: false },
  ],
} as unknown as BusinessData

export const OTO_ELEKTRIK_CONFIG = {
  id: 'oto-elektrik',
  name: 'Elektrik',
  sectorId: 'oto',
  plan: 'growth',
  description: 'Oto elektrik, beyin yazılımı ve elektronik arıza odaklı modern teknolojik tema',
  designPhilosophy: 'Teknolojiyi çağrıştıran indigo/neon mor tonları, modern fütüristik Syne başlıkları',
  isDark: true,
  cssVariables: OTO_ELEKTRIK_CSS,
  fonts: {
    heading: {
      family: 'Syne',
      weights: [700, 800],
      subsets: ['latin'],
    },
    body: {
      family: 'Plus Jakarta Sans',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'AutoRepair',
  sectorSections: ['vehicle_brands', 'warranty_badge', 'service_area'],
  performanceBudget: {
    maxJS: '120kb',
    maxLCP: '2.2s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: OTO_ELEKTRIK_BUSINESS.name },
        menuItems: [
          { label: 'Servis Hizmetleri', href: '#hizmetler' },
          { label: 'Uzmanlık Alanları', href: '#ekip' },
          { label: 'Rezervasyon', href: '#iletisim' },
        ],
        cta: { text: 'WhatsApp', href: 'https://wa.me/905325551216', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'dark', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: OTO_ELEKTRIK_BUSINESS.name,
        copyright: '© 2026 Voltaj Oto Elektrik & Beyin Onarım. Tüm hakları saklıdır.',
        contact: {
          phone: OTO_ELEKTRIK_BUSINESS.phone,
          email: OTO_ELEKTRIK_BUSINESS.email,
          address: OTO_ELEKTRIK_BUSINESS.address,
        },
        social: [{ platform: 'instagram', url: 'https://instagram.com/voltajotoelektrik', icon: 'instagram' }],
        legal: [
          { label: 'Gizlilik Bildirimi', href: '/gizlilik' },
          { label: 'KVKK Bildirgesi', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1000, removable: false, animation: 'none' },
      defaultContent: { phone: '905325551216', message: 'Elektrik arıza tespiti ve beyin kodlama için randevu oluşturmak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${OTO_ELEKTRIK_BUSINESS.name} — Bostancı Akıllı Beyin Tamiratı`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'BİLGİSAYARLI ARIZA TESPİT',
            title: OTO_ELEKTRIK_BUSINESS.name,
            subtitle: OTO_ELEKTRIK_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Stüdyo İsmi', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
          ],
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: {
            badge: 'TEKNİK ALTYAPI',
            title: 'Hızlı Dinamik Akım Çözümleri',
          },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'ELEKTRONİK MENÜSÜ',
            title: 'Modern Akıllı Çözümlerimiz',
          },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'KOLTUĞUNUZU AYIRTIN',
            title: 'Teknik Bölüme Randevu Alın',
          },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
