/**
 * @kepenk/templates — lastikci-ticari Theme Configuration
 *
 * Ticari arac ve filo lastik servisi
 * Plan: growth (9 page sections, 4 global sections)
 * Font: Bebas Neue/Inter | Accent: #37474F
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const LASTIKCI_TICARI_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#37474F',
  '--color-accent-hover': '#37474F',
  '--color-accent-active': '#37474F',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'Bebas Neue\', sans-serif',
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const LASTIKCI_TICARI_BUSINESS = {
  name: 'FiloTek Ticari Lastik Merkezi',
  ownerName: 'Ibrahim Aslan',
  sectorId: 'Lastikci',
  slogan: 'Filonuz yollarda, biz arkanizda',
  phone: '0534 192 67 30',
  phoneClean: '905341926730',
  whatsapp: '905341926730',
  email: 'info@filotek.com.tr',
  address: 'Gunesli Mah. Evren Cad. No:34, Bagcilar/Istanbul',
  city: 'Istanbul',
  district: 'Bagcilar',
  neighborhood: 'Gunesli',
  coordinates: { lat: 41.0145, lng: 28.8512 },
  socialMedia: {
    instagram: 'https://instagram.com/filoteklastik',
    facebook: 'https://facebook.com/filotek',
    linkedin: 'https://linkedin.com/company/filotek',
  },
  photos: [],
  foundedYear: 2009,
  experience: '17 yil',
  customerCount: '3.500+',
  rating: 4.8,
  reviewCount: 640,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '07:00',
      close: '21:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '07:00',
      close: '21:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '07:00',
      close: '21:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '07:00',
      close: '21:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '07:00',
      close: '21:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '07:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '08:00',
      close: '14:00',
      isOpen: true,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'TIR/Kamyon Lastik Degisimi',
      price: '600 TL/adet',
      duration: '45 dk/adet',
      description: 'Agir vasita lastik sokme/takma, balans. Vinc ve hidrolik ekipmanla.',
    },
    {
      id: 's2',
      name: 'Ticari Arac Lastik Satisi',
      price: 'degisken',
      duration: 'hazir',
      description: 'TIR, kamyon, otobus, minibus icin 50+ marka lastik. Stoktan teslim.',
    },
    {
      id: 's3',
      name: 'Filo Lastik Yonetimi',
      price: 'Teklif uzerine',
      duration: 'surekli',
      description: 'Filonuzdaki tum araclarin lastik takibi, rotasyon plani, maliyet optimizasyonu.',
    },
    {
      id: 's4',
      name: 'Kaplama (Retreading)',
      price: '1.500 - 3.000 TL/adet',
      duration: '5-7 gun',
      description: 'Kullanilmis TIR lastigine yeni dis kaplama. Maliyet %40-60 tasarruf.',
    },
    {
      id: 's5',
      name: 'Mobil Lastik Servisi',
      price: '+200 TL',
      duration: '60 dk',
      description: 'Yol kenari, depo ve sanayi bolgesi icin mobil servis araci ile yerinde mudahale.',
    },
    {
      id: 's6',
      name: 'Lastik Basınc Izleme (TPMS)',
      price: '2.000 TL/arac',
      duration: '2 saat',
      description: 'Lastik basinc sensoru montaji, uzaktan izleme. Yakit tasarrufu ve guvenlik.',
    },
    {
      id: 's7',
      name: 'Rot-Balans (Agir Vasita)',
      price: '800 TL',
      duration: '45 dk',
      description: 'Agir vasita icin ozel rot ve balans ayari. Lastik omrunu %20 uzatir.',
    },
    {
      id: 's8',
      name: 'Lastik Analiz Raporu',
      price: 'Ucretsiz',
      duration: '30 dk',
      description: 'Mevcut lastiklerinizin asinma analizi, kalan omur tahmini, degisim onerisi.',
    },
    {
      id: 's9',
      name: '7/24 Yol Yardim',
      price: '500 - 1.500 TL',
      duration: '60-120 dk',
      description: 'Sehirlerarasi yollarda lastik patlama, civi batmasi icin 7/24 mobil mudahale.',
    },
    {
      id: 's10',
      name: 'Sezonluk Depolama (Ticari)',
      price: '500 TL/set',
      duration: 'sezonluk',
      description: 'Ticari arac lastikleri icin genis depo alani. Etiketli ve sigortali saklama.',
    },
  ],
  team: [
    {
      name: 'Ibrahim Aslan',
      role: 'Kurucu & Genel Mudur',
      bio: '2. nesil lastikci. Babasi 1985\'ten beri sektorde. Ticari arac lastiklerinde 17 yil deneyim.',
    },
    {
      name: 'Serkan Dogan',
      role: 'Filo Yonetim Uzmani',
      bio: '100+ filo musterisinin lastik yonetiminden sorumlu. Maliyet optimizasyonu ve rotasyon planlama.',
    },
    {
      name: 'Mehmet Kara',
      role: 'Mobil Servis Ekip Sefi',
      bio: '12 yillik agir vasita lastik ustasi. 3 mobil servis aracı ve 6 kisilik ekip yonetiyor.',
    },
    {
      name: 'Elif Sahin',
      role: 'Satis & Musteri Iliskileri',
      bio: 'Kurumsal satis ve filo anlasmalari. 8 yillik B2B satis deneyimi.',
    },
  ],
  testimonials: [
    {
      name: 'Aras Kargo Istanbul Bolgesi',
      district: 'Gunesli',
      date: '2025-11',
      rating: 5,
      comment: '150 araclik filomuzun lastik yonetimini FiloTek yapiyor. Rotasyon plani ve maliyet raporu sayesinde lastik giderimiz %25 dustu.',
    },
    {
      name: 'Cetin Nakliyat',
      district: 'Bagcilar',
      date: '2025-10',
      rating: 5,
      comment: 'TIR\'larimiz icin kaplama hizmeti aliyoruz. Yeni lastik maliyetinin yarisina kaliteli lastik kullaniyoruz. 2 yildir sorunsuz.',
    },
    {
      name: 'Ozgur Ozturk (Otobus Isletmeci)',
      district: 'Esenyurt',
      date: '2025-09',
      rating: 5,
      comment: 'Gece 2\'de TIR\'imiz yolda kaldi, 7/24 yol yardimi aradik. 1 saatte geldiler, lastik degistirdiler. Hayat kurtarici hizmet.',
    },
    {
      name: 'Metro Lojistik',
      district: 'Hadimkoy',
      date: '2025-08',
      rating: 4,
      comment: 'TPMS sistemi kurdurduk, yakit tasarrufu fark edilir seviyede. Basinc takibi uzaktan yapilabiliyor, cok pratik.',
    },
    {
      name: 'Yilmaz Turizm',
      district: 'Sultanbeyli',
      date: '2025-07',
      rating: 5,
      comment: '20 otobusumuzun lastik ihtiyacini FiloTek karsilayor. Sezonluk depolama ve lastik analiz raporlari isimizi cok kolaylastiriyor.',
    },
    {
      name: 'DHL Supply Chain',
      district: 'Tuzla',
      date: '2025-12',
      rating: 5,
      comment: 'Kurumsal filo sozlesmemiz 3. yilinda. Mobil servis hizi ve lastik stok genisligi sektorde en iyilerden.',
    },
  ],
  faq: [
    { q: 'Kaplama (retreading) guvenli mi?', a: 'Evet, modern sicak kaplama teknolojisiyle uretilen lastikler yeni lastikle ayni guvenlik standartlarini karsilar. ECE R109 sertifikali urunler kullaniyoruz.' },
    { q: 'Filo lastik yonetimi ne icerir?', a: 'Lastik envanteri, rotasyon planlama, asinma analizi, degisim zamanlama, maliyet raporlama. Aylik rapor ve yillik tasarruf ozeti sunuyoruz.' },
    { q: 'Mobil servis hangi bolgelere geliyor?', a: 'Istanbul ve Marmara Bolgesi\'ne mobil servis veriyoruz. Sehirlerarasi yollarda 7/24 yol yardim hizmetimiz de mevcuttur.' },
    { q: 'TPMS sistemi zorunlu mu?', a: '2024\'ten itibaren yeni ticari araclarda zorunludur. Mevcut araclara da retrofit montaj yapiyoruz. Yakit tasarrufu ve guvenlik icin siddtle oneriyoruz.' },
    { q: 'Kurumsal sozlesme avantajlari nelerdir?', a: 'Sabit fiyat garantisi, oncelikli servis, ucretsiz mobil mudahale, aylik raporlama ve yillik %10-15 maliyet tasarrufu.' },
    { q: 'Lastik analiz raporu nedir?', a: 'Mevcut lastiklerinizin dis derinligi, asinma paterni ve kalan omrunu olcer. Hangi lastiklerin ne zaman degismesi gerektigini gosteren ucretsiz rapor.' },
    { q: 'Hangi marka ticari lastikler satiyorsunuz?', a: 'Michelin, Bridgestone, Continental, Goodyear, Pirelli ve Lassa basta olmak uzere 50+ markanin ticari serileri stokumuzda.' },
    { q: 'Taksit ve vadeli odeme var mi?', a: 'Evet, kurumsal musterilere 30-60 gun vadeli odeme, bireysel musterilere 12 taksit imkani sunuyoruz.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const LASTIKCI_TICARI_CONFIG = {
  id: 'lastikci-ticari',
  name: 'Ticari',
  sectorId: 'lastikci',
  plan: 'growth',
  description: 'Ticari arac ve filo lastik servisi',
  designPhilosophy: 'Profesyonel, endustriyel, guclu',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#37474F',
    '--color-accent-hover': '#37474F',
    '--color-accent-active': '#37474F',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'Bebas Neue\', sans-serif',
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Bebas Neue',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'TireShop',
  sectorSections: [],
  performanceBudget: {
    maxJS: '180kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'FiloTek Ticari Lastik Merkezi' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905341926730',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'FiloTek Ticari Lastik Merkezi',
        copyright: '© 2026 FiloTek Ticari Lastik Merkezi',
        contact: {
          phone: '0534 192 67 30',
          email: 'info@filotek.com.tr',
          address: 'Gunesli Mah. Evren Cad. No:34, Bagcilar/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/filoteklastik',
            icon: 'instagram',
          },
          {
            platform: 'facebook',
            url: 'https://facebook.com/filotek',
            icon: 'facebook',
          },
          {
            platform: 'linkedin',
            url: 'https://linkedin.com/company/filotek',
            icon: 'linkedin',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905341926730', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'FiloTek Ticari Lastik Merkezi — Bagcilar',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: LASTIKCI_TICARI_BUSINESS.name, subtitle: LASTIKCI_TICARI_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
