/**
 * @kepenk/templates — lastikci-kis Theme Configuration
 *
 * Lastik ve jant merkezi, genis stok
 * Plan: starter (6 page sections, 4 global sections)
 * Font: DM Sans/Inter | Accent: #1565C0
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const LASTIKCI_KIS_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#1565C0',
  '--color-accent-hover': '#1565C0',
  '--color-accent-active': '#1565C0',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'DM Sans\', sans-serif',
  '--font-body': "'Source Sans 3', system-ui, sans-serif",
}

// ═══ DEMO BUSINESS DATA ═══

export const LASTIKCI_KIS_BUSINESS = {
  name: 'JantPark Lastik & Jant Merkezi',
  ownerName: 'Ozgur Demir',
  sectorId: 'Lastikci',
  slogan: 'Lastik ve jantta tek adres',
  phone: '0533 481 72 90',
  phoneClean: '905334817290',
  whatsapp: '905334817290',
  email: 'info@jantpark.com.tr',
  address: 'Yenisahra Mah. Ataturk Cad. No:142, Atasehir/Istanbul',
  city: 'Istanbul',
  district: 'Atasehir',
  neighborhood: 'Yenisahra',
  coordinates: { lat: 40.985, lng: 29.092 },
  socialMedia: { instagram: 'https://instagram.com/jantpark', facebook: 'https://facebook.com/jantpark' },
  photos: [],
  foundedYear: 2015,
  experience: '11 yil',
  customerCount: '15.000+',
  rating: 4.7,
  reviewCount: 820,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '08:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '10:00',
      close: '15:00',
      isOpen: true,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Lastik Satis & Montaj',
      price: 'degisken',
      duration: '45 dk',
      description: '50+ marka, 500+ model lastik stoku. Montaj ve balans dahil fiyat.',
    },
    {
      id: 's2',
      name: 'Jant Satis & Degisimi',
      price: 'degisken',
      duration: '60 dk',
      description: 'Orijinal ve aftermarket jant secenekleri. Aracınıza uygun jant danismanligi.',
    },
    {
      id: 's3',
      name: 'Rot Ayari',
      price: '500 TL',
      duration: '30 dk',
      description: '3D rot ayar cihazi ile hassas olcum ve ayarlama. Lastik omru uzatma.',
    },
    {
      id: 's4',
      name: 'Lastik Tamiri',
      price: '200 TL',
      duration: '15 dk',
      description: 'Mantar yama, sicak yama ve tubeless tamir secenekleri.',
    },
    {
      id: 's5',
      name: 'Jant Boyama',
      price: '800 TL/adet',
      duration: '2-3 gun',
      description: 'Jant boyama, renk degisimi, kurumsal renk uyumu. Toz boya teknolojisi.',
    },
    {
      id: 's6',
      name: 'Lastik Otel',
      price: '300 TL/set',
      duration: 'sezonluk',
      description: 'Iklimlendirmeli depoda sezonluk lastik saklama. Sigorta dahil.',
    },
  ],
  team: [
    {
      name: 'Ozgur Demir',
      role: 'Kurucu & Genel Mudur',
      bio: 'Otomotiv muhendisligi mezunu. 11 yillik lastik ve jant sektoru deneyimi.',
    },
    {
      name: 'Emre Koc',
      role: 'Teknik Sef',
      bio: '15 yillik lastik montaj ustasi. 3D rot ve balans cihazlarinda uzman.',
    },
  ],
  testimonials: [
    {
      name: 'Ali Yildiz',
      district: 'Atasehir',
      date: '2025-11',
      rating: 5,
      comment: '4 lastik + jant degisimi yaptirdim. Stok cok genis, istedigim modeli hemen buldular. 3D rot ayari da dahildi, harika hizmet.',
    },
    {
      name: 'Seda Ozkan',
      district: 'Kadikoy',
      date: '2025-09',
      rating: 5,
      comment: 'Kis lastigi icin geldim, Ozgur Bey aracima uygun en iyi fiyat/performans lastigi onerdi. Montaj 30 dakikada bitti.',
    },
    {
      name: 'Murat Arslan',
      district: 'Maltepe',
      date: '2025-10',
      rating: 4,
      comment: 'Jant boyama yaptirdim, sonuc cok guzel. Tek sorun: teslim suresi plananandan 1 gun fazla surdu.',
    },
  ],
  faq: [
    { q: 'Hangi marka lastikler bulunuyor?', a: 'Michelin, Bridgestone, Continental, Pirelli, Goodyear, Hankook, Lassa, Petlas dahil 50\'den fazla marka stokumuzda.' },
    { q: 'Jant seciminde yardimci oluyor musunuz?', a: 'Evet, arac modelinize uygun jant boyutu, offset ve bolt pattern konusunda uzman danismanlik veriyoruz.' },
    { q: '3D rot ayari nedir?', a: 'Lazer sensor teknolojisiyle lastik acillarini hassas olcen ve ayarlayan sistemdir. Lastik asinmasini esitler, direksiyonda sapma engeller.' },
    { q: 'Jant boyama kac gunde hazir olur?', a: 'Toz boya ile boyama 2-3 is gunu surmektedir. Arac teslim alinir, jant sokulur, boyanir ve monte edilir.' },
    { q: 'Taksit imkani var mi?', a: 'Evet, lastik ve jant alimlarinda 6-12 taksit imkani sunuyoruz. Kampanya donmelerinde ek taksit secenekleri de olabilir.' },
    { q: 'Mobil lastik servisi var mi?', a: 'Su anda mobil servis sunmuyoruz ancak yol kenarinda lastik patlamasi durumunda en yakin noktada hizli mudahale yapabiliriz.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const LASTIKCI_KIS_CONFIG = {
  id: 'lastikci-kis',
  name: 'Kis',
  sectorId: 'lastikci',
  plan: 'starter',
  description: 'Lastik ve jant merkezi, genis stok',
  designPhilosophy: 'Guclu, dinamik, otomotiv',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#1565C0',
    '--color-accent-hover': '#1565C0',
    '--color-accent-active': '#1565C0',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'DM Sans\', sans-serif',
    '--font-body': "'Source Sans 3', system-ui, sans-serif",
  },
  fonts: {
    heading: {
      family: 'DM Sans',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Source Sans 3',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'TireShop',
  sectorSections: [],
  performanceBudget: {
    maxJS: '120kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-basic',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'JantPark Lastik & Jant Merkezi' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905334817290',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'JantPark Lastik & Jant Merkezi',
        copyright: '© 2026 JantPark Lastik & Jant Merkezi',
        contact: {
          phone: '0533 481 72 90',
          email: 'info@jantpark.com.tr',
          address: 'Yenisahra Mah. Ataturk Cad. No:142, Atasehir/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/jantpark',
            icon: 'instagram',
          },
          {
            platform: 'facebook',
            url: 'https://facebook.com/jantpark',
            icon: 'facebook',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905334817290', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'JantPark Lastik & Jant Merkezi — Atasehir',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: LASTIKCI_KIS_BUSINESS.name, subtitle: LASTIKCI_KIS_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
