/**
 * Page SEO Settings API
 * ──────────────────────
 * GET    /api/v1/marketing/seo/pages/[pageId] — Get page SEO
 * PUT    /api/v1/marketing/seo/pages/[pageId] — Update page SEO
 * POST   /api/v1/marketing/seo/pages/[pageId] — Auto-generate SEO with AI
 */

import { NextResponse } from 'next/server'
import { adminDb } from '@/lib/firebaseAdmin'
import { oturumDogrulaServer } from '@/lib/sessionManager'
import { generateMetaTags, turkishSlugify } from '@/lib/seo/metaTagEngine'

interface RouteParams { params: Promise<{ pageId: string }> }

export async function GET(request: Request, { params }: RouteParams) {
  try {
    const esnafId = await oturumDogrulaServer()
    if (!esnafId) return NextResponse.json({ error: 'Yetkisiz erişim' }, { status: 401 })

    const { pageId } = await params
    const doc = await adminDb.collection('esnaflar').doc(esnafId).collection('pages').doc(pageId).get()
    if (!doc.exists) return NextResponse.json({ error: 'Sayfa bulunamadı' }, { status: 404 })

    const page = doc.data()!
    return NextResponse.json({
      ok: true,
      seo: page.seo || {},
      slug: page.slug,
      pageTitle: page.title,
    })
  } catch (error: any) {
    return NextResponse.json({ error: 'Getirilemedi', detay: error.message }, { status: 500 })
  }
}

export async function PUT(request: Request, { params }: RouteParams) {
  try {
    const esnafId = await oturumDogrulaServer()
    if (!esnafId) return NextResponse.json({ error: 'Yetkisiz erişim' }, { status: 401 })

    const { pageId } = await params
    const body = await request.json()
    const now = new Date().toISOString()

    const docRef = adminDb.collection('esnaflar').doc(esnafId).collection('pages').doc(pageId)
    const doc = await docRef.get()
    if (!doc.exists) return NextResponse.json({ error: 'Sayfa bulunamadı' }, { status: 404 })

    const oldSlug = doc.data()?.slug
    const updates: Record<string, any> = { updatedAt: now }

    if (body.title) updates['seo.title'] = body.title
    if (body.description) updates['seo.description'] = body.description
    if (body.ogImage) updates['seo.ogImage'] = body.ogImage
    if (body.robots) updates['seo.robots'] = body.robots
    if (body.canonicalUrl) updates['seo.canonicalUrl'] = body.canonicalUrl

    // Slug change → auto redirect
    if (body.slug && body.slug !== oldSlug) {
      updates.slug = turkishSlugify(body.slug)

      // Create 301 redirect from old slug
      if (oldSlug) {
        await adminDb.collection('esnaflar').doc(esnafId).collection('redirects').add({
          from: `/${oldSlug}`,
          to: `/${updates.slug}`,
          type: 301,
          reason: 'slug_change',
          createdAt: now,
        })
      }
    }

    await docRef.update(updates)
    return NextResponse.json({ ok: true, mesaj: 'SEO ayarları güncellendi' })
  } catch (error: any) {
    return NextResponse.json({ error: 'Güncelleme başarısız', detay: error.message }, { status: 500 })
  }
}

export async function POST(request: Request, { params }: RouteParams) {
  try {
    const esnafId = await oturumDogrulaServer()
    if (!esnafId) return NextResponse.json({ error: 'Yetkisiz erişim' }, { status: 401 })

    const { pageId } = await params
    const doc = await adminDb.collection('esnaflar').doc(esnafId).collection('pages').doc(pageId).get()
    if (!doc.exists) return NextResponse.json({ error: 'Sayfa bulunamadı' }, { status: 404 })

    const page = doc.data()!
    const esnafDoc = await adminDb.collection('esnaflar').doc(esnafId).get()
    const esnaf = esnafDoc.data() || {}

    // Auto-generate meta tags
    const generated = generateMetaTags({
      pageTitle: page.title || 'Sayfa',
      businessName: esnaf.name || 'İşletme',
      sector: esnaf.sector || 'default',
      district: esnaf.address?.district || '',
      city: esnaf.address?.city || 'İstanbul',
      phone: esnaf.phone,
      pageSlug: page.slug || '',
      domain: esnaf.domain || 'site.kepenk.ai',
      imageUrl: page.ogImage || esnaf.logoUrl,
      pageType: page.type || 'other',
    })

    // Save generated SEO
    await adminDb.collection('esnaflar').doc(esnafId).collection('pages').doc(pageId).update({
      'seo.title': generated.title,
      'seo.description': generated.description,
      'seo.canonical': generated.canonical,
      'seo.og': generated.og,
      'seo.autoGenerated': true,
      updatedAt: new Date().toISOString(),
    })

    return NextResponse.json({ ok: true, generated })
  } catch (error: any) {
    return NextResponse.json({ error: 'Otomatik SEO başarısız', detay: error.message }, { status: 500 })
  }
}
