import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const ORGANIK_CIFTLIK_BUSINESS: BusinessData = {
  name: 'Ciftlik Urunleri',
  ownerName: 'Ayse Ciftlik',
  sectorId: 'organik',
  slogan: 'Ciftlikten sofraniza',
  phone: '0533 400 22 33',
  phoneClean: '905334002233',
  whatsapp: '905334002233',
  email: 'iletisim@ciftlikurunleri.com',
  address: 'Sinanpasa Mah. No:15, Besiktas, Istanbul',
  city: 'Istanbul',
  district: 'Besiktas',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"07:00","close":"20:00"},{"day":"tuesday","dayTr":"Sali","open":"07:00","close":"20:00"},{"day":"wednesday","dayTr":"Carsamba","open":"07:00","close":"20:00"},{"day":"thursday","dayTr":"Persembe","open":"07:00","close":"20:00"},{"day":"friday","dayTr":"Cuma","open":"07:00","close":"20:00"},{"day":"saturday","dayTr":"Cumartesi","open":"07:00","close":"20:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/organik-ciftlik"},
  photos: [],
  services: []
}
export const ORGANIK_CIFTLIK_CONFIG: ThemeConfig = { id: 'organik-ciftlik', name: 'Çiftlik Ürünleri', sectorId: 'organik', plan: 'growth', isDark: false, cssVariables: { '--color-bg': '#FFFFFF', '--color-surface': '#F8FAFC', '--color-text': '#0F172A', '--color-accent': '#D97706',
    '--color-accent-light': '#f1fce8',
    '--color-accent-hover': '#5aad1f',
    '--color-accent-active': '#519c1c', '--color-text-on-accent': '#FFFFFF', '--color-border': '#E2E8F0', '--font-heading': "'Lora', serif", '--font-body': "'Inter', sans-serif" }, fonts: { heading: { family: 'Lora', weights: [500] }, body: { family: 'Inter', weights: [400] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Ciftlik Urunleri' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Ciftlik Urunleri',
        copyright: '© 2026 Ciftlik Urunleri',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'Taze Çiftlik', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'xl', containerWidth: 'xl', visible: true }, defaultContent: { badge: 'DOĞAL HASAT', title: 'Tarladan Sofranıza Katkısız Lezzetler' } } ] }] }