import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const OTO_DETAY_CSS: Record<string, string> = {
  '--container-default': '1200px',
  '--section-py': '80px',
  '--radius-md': '8px',
  '--radius-lg': '16px',
  '--color-bg': '#0F172A',
  '--color-surface': '#1E293B',
  '--color-surface-elevated': '#334155',
  '--color-surface-muted': '#020617',
  '--color-text': '#F8FAFC',
  '--color-text-secondary': '#94A3B8',
  '--color-text-muted': '#64748B',
  '--color-text-on-accent': '#0F172A',
  '--color-text-on-dark': '#F8FAFC',
  '--color-accent': '#F59E0B',
  '--color-accent-hover': '#D97706',
  '--color-accent-active': '#B45309',
  '--color-accent-light': '#451A03',
  '--color-border': '#334155',
  '--color-border-subtle': '#1E293B',
  '--font-heading': "'Inter', sans-serif",
  '--font-body': "'Inter', sans-serif",
}

export const OTO_DETAY_BUSINESS = {
  name: 'Gloss Detailing Car Care',
  ownerName: 'Erkan Soylu',
  sectorId: 'Oto',
  slogan: 'Aracınız için kusursuz parlaklık ve koruma',
  phone: '0216 555 12 13',
  phoneClean: '902165551213',
  whatsapp: '905335551213',
  email: 'iletisim@glossdetailing.com',
  address: 'Atatürk Oto Sanayi Sitesi 2. Kısım 24. Sokak No:80, Maslak/İstanbul',
  city: 'İstanbul',
  district: 'Maslak',
  neighborhood: 'Atatürk Oto Sanayi',
  coordinates: { lat: 41.1124, lng: 29.0211 },
  socialMedia: { instagram: 'https://instagram.com/glossdetailing' },
  photos: [],
  foundedYear: 2015,
  experience: '9 yıldır',
  customerCount: '4.200+',
  rating: 4.9,
  reviewCount: 380,
  services: [
    {
      id: 's1',
      name: 'Premium Seramik Kaplama',
      price: '12.000 TL\'den başlayan',
      duration: '2 gün',
      description: '9H sertlikte nano seramik kaplama uygulaması, hare giderme ve 3 aşamalı pasta cila işlemi.',
    },
    {
      id: 's2',
      name: 'Detaylı İç Temizlik & Sterilizasyon',
      price: '4.500 TL',
      duration: '6-8 saat',
      description: 'Koltuk tavan, taban ve kapı döşemelerinin buharlı temizliği, deri bakımı ve ozonla dezenfeksiyon.',
    },
    {
      id: 's3',
      name: 'Boya Koruma & Pasta Cila',
      price: '5.000 TL',
      duration: '24 saat',
      description: 'Çizik giderme, parlaklık kazandırma ve boya yüzeyine özel wax koruyucu katman uygulaması.',
    },
    {
      id: 's4',
      name: 'Motor Detaylı Temizlik & Koruma',
      price: '1.500 TL',
      duration: '90 dk',
      description: 'Motorun su bazlı ve dielectric sıvılarla susuz temizliği ve plastik koruyucu kaplama.',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '09:00', close: '19:30', isOpen: true },
    { day: 'Salı', open: '09:00', close: '19:30', isOpen: true },
    { day: 'Çarşamba', open: '09:00', close: '19:30', isOpen: true },
    { day: 'Perşembe', open: '09:00', close: '19:30', isOpen: true },
    { day: 'Cuma', open: '09:00', close: '19:30', isOpen: true },
    { day: 'Cumartesi', open: '09:00', close: '17:00', isOpen: true },
    { day: 'Pazar', open: null, close: null, isOpen: false },
  ],
} as unknown as BusinessData

export const OTO_DETAY_CONFIG = {
  id: 'oto-detay',
  name: 'Detay',
  sectorId: 'oto',
  plan: 'pro',
  description: 'Premium oto detailing, seramik kaplama ve lüks araç temizliği odaklı koyu tema',
  designPhilosophy: 'Şık ve gizemli koyu slate arka plan, altın sarısı dinamik vurgular ve modern monokrom çizgiler',
  isDark: true,
  cssVariables: OTO_DETAY_CSS,
  fonts: {
    heading: {
      family: 'Inter',
      weights: [600, 700],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'AutoRepair',
  sectorSections: ['vehicle_brands', 'warranty_badge', 'service_area'],
  performanceBudget: {
    maxJS: '100kb',
    maxLCP: '2.2s',
    animationLevel: 'framer-basic',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: OTO_DETAY_BUSINESS.name },
        menuItems: [
          { label: 'Detay Hizmetleri', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'Rezervasyon', href: '#iletisim' },
        ],
        cta: { text: 'Arayın', href: 'tel:902165551213', variant: 'outline' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'dark', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: OTO_DETAY_BUSINESS.name,
        copyright: '© 2026 Gloss Detailing Car Care. Tüm hakları saklıdır.',
        contact: {
          phone: OTO_DETAY_BUSINESS.phone,
          email: OTO_DETAY_BUSINESS.email,
          address: OTO_DETAY_BUSINESS.address,
        },
        social: [{ platform: 'instagram', url: 'https://instagram.com/glossdetailing', icon: 'instagram' }],
        legal: [
          { label: 'Kullanım Koşulları', href: '/sartlar' },
          { label: 'KVKK Hakları', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1000, removable: false, animation: 'none' },
      defaultContent: { phone: '905335551213', message: 'Seramik kaplama ve detaylı temizlik paketleriniz için bilgi almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${OTO_DETAY_BUSINESS.name} — Maslak Lüks Araç Detaylı Temizlik`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_asymmetric_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'PREMIUM DETALILING',
            title: OTO_DETAY_BUSINESS.name,
            subtitle: OTO_DETAY_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Alt Başlık / Açıklama', type: 'richtext' },
          ],
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_asymmetric_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: {
            badge: 'İŞÇİLİK DETAYDA SAKLIDIR',
            title: 'Kusursuz Parlaklık İçin Doğru Dokunuşlar',
          },
          editableFields: [
            { path: 'badge', label: 'Küçük Rozet', type: 'text' },
            { path: 'title', label: 'Galeri Bölüm Başlığı', type: 'text' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_asymmetric_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'DETAILING HİZMETLERİ',
            title: 'Özel Koruma ve Temizlik Kartımız',
          },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_asymmetric_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'REZERVASYON YAPIN',
            title: 'Aracınızı Profesyonellere Emanet Edin',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
