import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const BERBER_KLASIK_CSS: Record<string, string> = {
  '--container-default': '960px',
  '--section-py': '64px',
  '--radius-md': '2px',
  '--radius-lg': '4px',
  '--color-bg': '#FAF8F5',
  '--color-surface': '#F5EFEB',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#EFECE6',
  '--color-text': '#1D1B19',
  '--color-text-secondary': '#5A5450',
  '--color-text-muted': '#968E89',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#FAF8F5',
  '--color-accent': '#8E2C1E',
  '--color-accent-hover': '#722014',
  '--color-accent-active': '#55150C',
  '--color-accent-light': '#FCEEEB',
  '--color-border': '#D6CFC9',
  '--color-border-subtle': '#EFECE6',
  '--font-heading': "'Cormorant Garamond', serif",
  '--font-body': "'Source Sans 3', sans-serif",
}

export const BERBER_KLASIK_BUSINESS = {
  name: 'Klasik Makas Berber Salonu',
  ownerName: 'Ahmet Yılmaz',
  sectorId: 'Berber',
  slogan: 'Geleneksel tıraşın Kadıköy temsilcisi',
  phone: '0216 333 01 13',
  phoneClean: '902163330113',
  whatsapp: '905353331113',
  email: 'ahmet@klasikmakas.com',
  address: 'Moda Cad. No:45/A, Caferağa, Kadıköy/İstanbul',
  city: 'İstanbul',
  district: 'Kadıköy',
  neighborhood: 'Caferağa',
  coordinates: { lat: 40.9856, lng: 29.0261 },
  socialMedia: { instagram: 'https://instagram.com/klasikmakas.moda' },
  photos: [],
  foundedYear: 1995,
  experience: '28 yıllık tecrübe',
  customerCount: '10.000+',
  rating: 4.7,
  reviewCount: 350,
  services: [
    {
      id: 's1',
      name: 'Saç Kesimi & Yıkama',
      price: '500 TL',
      duration: '35 dk',
      description: 'Klasik makas ve tarak teknikleriyle saç kesimi, yıkama ve kurutma.',
    },
    {
      id: 's2',
      name: 'Sakal Tıraşı (Sıcak Havlu)',
      price: '300 TL',
      duration: '20 dk',
      description: 'Sıcak havlu kompresi, köpüklü ustura tıraşı ve şap masajı.',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '08:30', close: '20:30', isOpen: true },
    { day: 'Salı', open: '08:30', close: '20:30', isOpen: true },
    { day: 'Çarşamba', open: '08:30', close: '20:30', isOpen: true },
    { day: 'Perşembe', open: '08:30', close: '20:30', isOpen: true },
    { day: 'Cuma', open: '08:30', close: '20:30', isOpen: true },
    { day: 'Cumartesi', open: '08:30', close: '20:00', isOpen: true },
    { day: 'Pazar', open: null, close: null, isOpen: false },
  ],
} as unknown as BusinessData

export const BERBER_KLASIK_CONFIG = {
  id: 'berber-klasik',
  name: 'Klasik',
  sectorId: 'berber',
  plan: 'free',
  description: 'Nostaljik, samimi ve geleneksel mahalle berberi tasarımı',
  designPhilosophy: 'Bordo vurgular, krem arka plan ve nostaljik şıklık',
  isDark: false,
  cssVariables: BERBER_KLASIK_CSS,
  fonts: {
    heading: {
      family: 'Cormorant Garamond',
      weights: [600, 700],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Source Sans 3',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'BarberShop',
  sectorSections: ['before_after', 'booking'],
  performanceBudget: {
    maxJS: '60kb',
    maxLCP: '2.5s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: BERBER_KLASIK_BUSINESS.name },
        menuItems: [
          { label: 'Hizmetlerimiz', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: { text: 'Arayın', href: 'tel:902163330113', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'dark', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: BERBER_KLASIK_BUSINESS.name,
        copyright: '© 2026 Klasik Makas Berber Salonu. Tüm hakları saklıdır.',
        contact: {
          phone: BERBER_KLASIK_BUSINESS.phone,
          email: BERBER_KLASIK_BUSINESS.email,
          address: BERBER_KLASIK_BUSINESS.address,
        },
        social: [{ platform: 'instagram', url: 'https://instagram.com/klasikmakas.moda', icon: 'instagram' }],
        legal: [{ label: 'KVKK Sözleşmesi', href: '/kvkk' }],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${BERBER_KLASIK_BUSINESS.name} — Moda Geleneksel Berber`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'EST. 1995',
            title: BERBER_KLASIK_BUSINESS.name,
            subtitle: BERBER_KLASIK_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Eski Kurdele Yazısı', type: 'text' },
            { path: 'title', label: 'Dükkan Adı', type: 'text' },
            { path: 'subtitle', label: 'Slogan / Alt Metin', type: 'richtext' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 2,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'BERBER MENÜSÜ',
            title: 'Tıraş Hizmetlerimiz',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'Servis Menüsü Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 3,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'MAHALLE ADRESİMİZ',
            title: 'Dükkana Yol Tarifi Alın',
          },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
