import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const NAKLIYAT_PARCA_BUSINESS: BusinessData = {
  name: 'Parca Tasima',
  ownerName: 'Emre Parca',
  sectorId: 'nakliyat',
  slogan: 'Parca esya tasima',
  phone: '0535 500 44 55',
  phoneClean: '905355004455',
  whatsapp: '905355004455',
  email: 'info@parcatasima.com',
  address: 'Incirli Cad. No:10, Bakirkoy, Istanbul',
  city: 'Istanbul',
  district: 'Bakirkoy',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"07:00","close":"20:00"},{"day":"tuesday","dayTr":"Sali","open":"07:00","close":"20:00"},{"day":"wednesday","dayTr":"Carsamba","open":"07:00","close":"20:00"},{"day":"thursday","dayTr":"Persembe","open":"07:00","close":"20:00"},{"day":"friday","dayTr":"Cuma","open":"07:00","close":"20:00"},{"day":"saturday","dayTr":"Cumartesi","open":"07:00","close":"20:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/nakliyat-parca"},
  photos: [],
  services: []
}
export const NAKLIYAT_PARCA_CONFIG: ThemeConfig = { id: 'nakliyat-parca', name: 'Parça Yük Taşıma', sectorId: 'nakliyat', plan: 'growth', isDark: false, cssVariables: { '--color-bg': '#FFFFFF', '--color-surface': '#F8FAFC', '--color-text': '#0F172A', '--color-accent': '#10B981',
    '--color-accent-light': '#fcebe8',
    '--color-accent-hover': '#ad341f',
    '--color-accent-active': '#9c2f1c', '--color-text-on-accent': '#FFFFFF', '--color-border': '#E2E8F0', '--font-heading': "'Outfit', sans-serif", '--font-body': "'Inter', sans-serif" }, fonts: { heading: { family: 'Outfit', weights: [600] }, body: { family: 'DM Sans', weights: [400] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Parca Tasima' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Parca Tasima',
        copyright: '© 2026 Parca Tasima',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'Ekspres Parça', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'xl', containerWidth: 'xl', visible: true }, defaultContent: { badge: 'HIZLI ÇÖZÜM', title: 'Tek Parça Bile Olsa Hemen Kapınızda' } } ] }] }