import type { ActionCardProtocol } from '@kepenk/action-card-schema'

export const DEMO_ACTION_CARDS: ActionCardProtocol[] = [
  {
    protocolVersion: '1',
    cardId: 'demo-booking-cancelled',
    businessId: 'demo-business',
    dedupeKey: 'booking:appointment-1530:cancelled',
    revision: 2,
    source: {
      domain: 'booking',
      eventRef: { id: 'evt-booking-1', type: 'appointment.cancelled' },
      occurredAt: '2026-09-24T15:00:00+03:00',
      subjectRefs: [{ type: 'appointment', id: 'appointment-1530' }],
      evidenceRefs: [{ id: 'booking-row-1530', kind: 'booking', label: '15:30 rezervasyon kaydı' }],
    },
    attention: {
      urgency: 'high',
      importance: 82,
      riskClass: 'low',
      deadlineAt: '2026-09-24T16:00:00+03:00',
    },
    presentation: {
      title: '15:30 randevusu iptal edildi.',
      context: '90 dakikalık boşluk oluştu. Bekleme listesindeki 3 müşteri bu aralık için uygun görünüyor.',
      reason: 'İptal edilen rezervasyon 15:30–17:00 aralığını boşalttı.',
      tone: 'warning',
    },
    actions: [
      {
        actionId: 'fill-gap',
        label: 'Boşluğu doldur',
        mode: 'command',
        capability: { name: 'booking.waitlist.offer', permission: 'booking.write' },
        idempotencyKey: 'demo-booking-cancelled:fill-gap',
        primary: true,
        requiresHumanConfirmation: true,
      },
      { actionId: 'snooze', label: 'Daha sonra', mode: 'snooze', primary: false, requiresHumanConfirmation: false },
      { actionId: 'dismiss', label: 'Kapat', mode: 'dismiss', primary: false, requiresHumanConfirmation: false },
    ],
    suppressionGroup: 'booking-capacity',
    state: 'new',
  },
  {
    protocolVersion: '1',
    cardId: 'demo-payment-attention',
    businessId: 'demo-business',
    dedupeKey: 'finance:receivables:attention',
    revision: 1,
    source: {
      domain: 'finance',
      eventRef: { id: 'evt-finance-1', type: 'receivable.attention_required' },
      occurredAt: '2026-09-24T12:00:00+03:00',
      subjectRefs: [{ type: 'receivable_group', id: 'open-receivables' }],
      evidenceRefs: [{ id: 'open-tickets-3', kind: 'finance_projection', label: '3 açık adisyon' }],
    },
    attention: { urgency: 'normal', importance: 68, riskClass: 'medium' },
    presentation: {
      title: '₺12.450 tahsilat bekliyor.',
      context: 'Üç açık adisyon ödeme bekliyor. En eski kayıt iki gün önce oluşturuldu.',
      reason: 'Bu kart finansal gerçeği hesaplamaz; canonical Finance projection sonucunu yalnız sunar.',
      tone: 'info',
    },
    actions: [
      {
        actionId: 'review-receivables',
        label: 'Tahsilatları incele',
        mode: 'navigate',
        href: '/dashboard/manage/odemeler',
        primary: true,
        requiresHumanConfirmation: false,
      },
      { actionId: 'snooze', label: 'Daha sonra', mode: 'snooze', primary: false, requiresHumanConfirmation: false },
      { actionId: 'dismiss', label: 'Kapat', mode: 'dismiss', primary: false, requiresHumanConfirmation: false },
    ],
    suppressionGroup: 'finance-attention',
    state: 'new',
  },
  {
    protocolVersion: '1',
    cardId: 'demo-stock-risk',
    businessId: 'demo-business',
    dedupeKey: 'inventory:forecast:low:3',
    revision: 1,
    source: {
      domain: 'inventory',
      eventRef: { id: 'evt-inventory-1', type: 'stock.projected_low' },
      occurredAt: '2026-09-24T10:00:00+03:00',
      subjectRefs: [{ type: 'inventory_group', id: 'salon-consumables' }],
      evidenceRefs: [
        { id: 'stock-snapshot-1', kind: 'inventory', label: 'Mevcut stok' },
        { id: 'booking-demand-1', kind: 'booking_projection', label: 'Yaklaşan randevu talebi' },
      ],
    },
    attention: { urgency: 'high', importance: 76, riskClass: 'medium' },
    presentation: {
      title: '3 ürün 4 gün içinde bitebilir.',
      context: 'Yaklaşan randevu yoğunluğuna göre açıcı ve iki sarf kaleminde stok riski oluşuyor.',
      reason: 'Stok ve planlı talep aynı kartta yalnız kanıt referansları üzerinden buluşur.',
      tone: 'critical',
    },
    actions: [
      {
        actionId: 'view-supply',
        label: 'Sipariş seçeneklerini gör',
        mode: 'navigate',
        href: '/dashboard/manage/tedarik',
        primary: true,
        requiresHumanConfirmation: false,
      },
      { actionId: 'snooze', label: 'Daha sonra', mode: 'snooze', primary: false, requiresHumanConfirmation: false },
      { actionId: 'dismiss', label: 'Kapat', mode: 'dismiss', primary: false, requiresHumanConfirmation: false },
    ],
    suppressionGroup: 'inventory-risk',
    state: 'new',
  },
  {
    protocolVersion: '1',
    cardId: 'demo-property-match',
    businessId: 'demo-business',
    dedupeKey: 'property:match:ayse:20260924',
    revision: 1,
    source: {
      domain: 'property',
      eventRef: { id: 'evt-property-1', type: 'property.match.created' },
      occurredAt: '2026-09-24T09:20:00+03:00',
      subjectRefs: [{ type: 'customer', id: 'ayse-demo' }],
      evidenceRefs: [{ id: 'match-set-1', kind: 'property_match', label: '3 portföy eşleşmesi' }],
    },
    attention: { urgency: 'low', importance: 56, riskClass: 'low' },
    presentation: {
      title: 'Ayşe Hanım için 3 yeni eşleşme var.',
      context: 'İki mülk bütçe ve lokasyon tercihleriyle güçlü biçimde eşleşiyor.',
      reason: 'Müşteri talebi ile aktif portföyün deterministik eşleştirme sonucu.',
      tone: 'positive',
    },
    actions: [
      {
        actionId: 'review-matches',
        label: 'Eşleşmeleri incele',
        mode: 'navigate',
        href: '/dashboard/emlak',
        primary: true,
        requiresHumanConfirmation: false,
      },
      { actionId: 'dismiss', label: 'Kapat', mode: 'dismiss', primary: false, requiresHumanConfirmation: false },
    ],
    suppressionGroup: 'property-matches',
    batchHint: 'daily-opportunities',
    state: 'new',
  },
]
