/**
 * @kepenk/templates — avukat-ticaret Theme Configuration
 *
 * Uluslararasi hukuk firması, elit ve koyu tema
 * Plan: enterprise (14 page sections, 4 global sections)
 * Font: Cormorant Garamond/Inter | Accent: #C9A84C
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const AVUKAT_TICARET_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#E8E6E1',
  '--color-accent': '#931f84',
  '--color-accent-hover': '#C9A84C',
  '--color-accent-active': '#C9A84C',
  '--color-accent-light': '#1A1008',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'Cormorant Garamond\', sans-serif',
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const AVUKAT_TICARET_BUSINESS = {
  name: 'Bayraktar Kaplan Uluslararasi Hukuk',
  ownerName: 'Ozge Bayraktar',
  sectorId: 'Avukat',
  slogan: 'Global vizyonla yerel guc',
  phone: '0212 380 22 33',
  phoneClean: '902123802233',
  whatsapp: '905551234567',
  email: 'contact@bayraktarkaplan.law',
  address: 'Maslak Mah. AOS 55. Sok. No:2 42Maslak Kat:28, Sariyer/Istanbul',
  city: 'Istanbul',
  district: 'Sariyer',
  neighborhood: 'Maslak',
  coordinates: { lat: 41.1089, lng: 29.0201 },
  socialMedia: {
    instagram: 'https://instagram.com/bayraktarkaplanlaw',
    linkedin: 'https://linkedin.com/company/bayraktarkaplan',
    twitter: 'https://twitter.com/bklaw_istanbul',
  },
  photos: [],
  foundedYear: 1998,
  experience: '28 yil',
  customerCount: '25.000+',
  rating: 4.9,
  reviewCount: 3200,
  services: [
    {
      id: 's1',
      name: 'Uluslararasi Ticaret Hukuku',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'Sinir otesi ticaret, ihracat-ithalat sozlesmeleri, gumruk hukuku, CISG uygulamasi ve uluslararasi ticari uyusmazlik cozumu.',
    },
    {
      id: 's2',
      name: 'Yabanci Yatirim Danismanligi',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'Dogrudan yabanci yatirim, sirket kurulusu, ortaklik yapisi, yatirim tesvik mevzuati ve serbest bolge islemleri.',
    },
    {
      id: 's3',
      name: 'M&A (Birlesme & Devralma)',
      price: 'Proje bazli',
      duration: '3-12 ay',
      description: 'Due diligence, sirket degerleme, hisse devri, varlik devri, rekabet kurulu basvurulari ve kapani sonrasi entegrasyon.',
    },
    {
      id: 's4',
      name: 'Sermaye Piyasasi Hukuku',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'Halka arz, tahvil ihraci, SPK uyum surecleri, ozel sermaye fonlari ve risk sermayesi yapilandirmasi.',
    },
    {
      id: 's5',
      name: 'Bankacilik & Finans Hukuku',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'Kredi sozlesmeleri, proje finansmani, sendikasyon kredileri, BDDK mevzuati ve finansal yeniden yapilandirma.',
    },
    {
      id: 's6',
      name: 'Rekabet Hukuku',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'Rekabet Kurumu sorusturmalari, birlesme-devralma bildirimi, rekabet uyum programlari ve hakim durumun kotuye kullanimi davalari.',
    },
    {
      id: 's7',
      name: 'Fikri Mulkiyet & Teknoloji',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'Patent, marka, telif hakki korumasi. Yazilim lisanslama, veri koruma, siber guvenlik hukuku ve dijital platform mevzuati.',
    },
    {
      id: 's8',
      name: 'Insaat & Altyapi Hukuku',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'FIDIC sozlesmeleri, KOI (Kamu-Ozel Is birligi), insaat tahkimi, proje gelistirme ve cevresel etki degerlendirmesi.',
    },
    {
      id: 's9',
      name: 'Enerji & Dogal Kaynaklar',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'Enerji lisanslari, yenilenebilir enerji projeleri, petrol-gaz hukuku, EPDK surecleri ve enerji ticaret sozlesmeleri.',
    },
    {
      id: 's10',
      name: 'Denizcilik Hukuku',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'Deniz tasimaciligi, gemi insasi, P&I sigortasi, deniz kazasi tazminati, liman isletme ve deniz ticareti.',
    },
    {
      id: 's11',
      name: 'Uluslararasi Tahkim',
      price: 'Proje bazli',
      duration: '6-24 ay',
      description: 'ICC, LCIA, ICSID, ISTAC tahkim davalarinda temsil. Yatirimci-devlet tahkimi, ticari tahkim ve tahkim karari tenfizi.',
    },
    {
      id: 's12',
      name: 'Saglik & Ilac Hukuku',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'Ilac ruhsatlari, klinik arastirma hukuku, hastane isletmeciligi, saglik turizmi ve tibbi cihaz mevzuati.',
    },
    {
      id: 's13',
      name: 'Is Hukuku & Sosyal Guvenlik',
      price: 'Aylik danismanlik',
      duration: 'Surekli',
      description: 'Is sozlesmeleri, toplu is hukuku, sendikayla muzakere, yabanci calisan izinleri, SGK islemleri ve is guvenligi.',
    },
    {
      id: 's14',
      name: 'Gayrimenkul Yatirim',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'GYO yapilandirmasi, gayrimenkul fonlari, otel yatirimi, AVM hukuku, kira sozlesmeleri ve tapu islemleri.',
    },
    {
      id: 's15',
      name: 'Vergi Planlamasi & Uyusmazlik',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'Uluslararasi vergi planlamasi, cifte vergilendirme, transfer fiyatlandirmasi, vergi incelemesi ve vergi cezasi davalari.',
    },
    {
      id: 's16',
      name: 'Veri Koruma & Siber Guvenlik',
      price: '12.000 TL\'den baslayan',
      duration: '4-8 hafta',
      description: 'KVKK ve GDPR uyum surecleri, veri ihlali mudahalesi, sinir otesi veri aktarimi ve siber guvenlik hukuku.',
    },
    {
      id: 's17',
      name: 'Gumruk & Dis Ticaret',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'Gumruk vergisi uyusmazliklari, anti-damping sorusturmalari, serbest bolge islemleri ve ihracat kontrolleri.',
    },
    {
      id: 's18',
      name: 'Kripto & Blockchain Hukuku',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'Kripto para mevzuati, ICO/STO yapilandirmasi, DeFi hukuku, NFT telif haklari ve MASAK uyum surecleri.',
    },
    {
      id: 's19',
      name: 'Cevre Hukuku',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'CED raporu surecleri, cevre cezalarina itiraz, karbon ticareti, surdurulebilirlik raporlamasi ve ESG uyumu.',
    },
    {
      id: 's20',
      name: 'White Collar Crime',
      price: 'Proje bazli',
      duration: 'Degisken',
      description: 'Ekonomik suclar, dolandiricilik, zimmet, kara para aklama, OFAC yaptirimlari ve ic sorusturma yonetimi.',
    },
  ],
  team: [
    {
      name: 'Av. Ozge Bayraktar',
      title: 'Yonetici Ortak | Uluslararasi Ticaret',
      bio: 'Istanbul Universitesi Hukuk, Harvard LLM. 28 yillik uluslararasi hukuk deneyimi. ICC Tahkim Komisyonu uyesi. 3 dil: Turkce, Ingilizce, Fransizca.',
      photo: '',
    },
    {
      name: 'Av. Cenk Kaplan',
      title: 'Yonetici Ortak | M&A & Sermaye Piyasasi',
      bio: 'Bilkent Universitesi Hukuk, Columbia LLM. 25 yillik M&A deneyimi. Fortune 500 sirketlerine danismanlik. 2 dil: Turkce, Ingilizce.',
      photo: '',
    },
    {
      name: 'Av. Dr. Leyla Sahin',
      title: 'Ortak | Rekabet & Enerji Hukuku',
      bio: 'ODTU, Heidelberg Universitesi Doktora. Rekabet Kurumu eski raportoru. AB rekabet hukuku uzmani. 3 dil: Turkce, Almanca, Ingilizce.',
      photo: '',
    },
    {
      name: 'Av. Riza Karatas',
      title: 'Ortak | Bankacilik & Finans',
      bio: 'Koc Universitesi Hukuk & MBA. 15 yil uluslararasi banka hukuk departmanlarinda deneyim sonrasi avukatliga gecis.',
      photo: '',
    },
    {
      name: 'Av. Sophie Laurent',
      title: 'Of Counsel | Fransiz Hukuku',
      bio: 'Paris Pantheon-Sorbonne, Istanbul Bilgi Universitesi. Fransiz-Turk ticari iliskileri uzmani. 3 dil: Fransizca, Ingilizce, Turkce.',
      photo: '',
    },
    {
      name: 'Av. Gokhan Oztürk',
      title: 'Kidemli Avukat | Insaat & Altyapi',
      bio: 'Yeditepe Universitesi Hukuk. FIDIC sozlesmeleri ve KOI projeleri uzmanı. Mega insaat projelerinde 10 yillik deneyim.',
      photo: '',
    },
    {
      name: 'Av. Melis Acar',
      title: 'Kidemli Avukat | IP & Teknoloji',
      bio: 'Sabanci Universitesi Hukuk & Bilisim. Startup ekosistemi ve fintech hukuku uzmani. Patent vekili.',
      photo: '',
    },
    {
      name: 'Av. Dmitry Volkov',
      title: 'Of Counsel | Rusya & BDT Hukuku',
      bio: 'Moskova Devlet Universitesi Hukuk, Galatasaray Universitesi. Rus-Turk ticari iliskileri ve yatirim danismanligi. 3 dil: Rusca, Turkce, Ingilizce.',
      photo: '',
    },
  ],
  workingHours: [
    {
      day: 'Pazartesi',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '10:00',
      close: '16:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: null,
      close: null,
      isOpen: false,
    },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const AVUKAT_TICARET_CONFIG = {
  id: 'avukat-ticaret',
  name: 'Ticaret',
  sectorId: 'avukat',
  plan: 'enterprise',
  description: 'Uluslararasi hukuk firması, elit ve koyu tema',
  designPhilosophy: 'Koyu, lukseri, otoriter, uluslararasi',
  isDark: true,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#E8E6E1',
    '--color-accent': '#C9A84C',
    '--color-accent-hover': '#C9A84C',
    '--color-accent-active': '#C9A84C',
    '--color-accent-light': '#1A1008',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'Cormorant Garamond\', sans-serif',
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Cormorant Garamond',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'LegalService',
  sectorSections: ['practice_areas', 'case_results', 'confidentiality'],
  performanceBudget: {
    maxJS: '350kb',
    maxLCP: '2.5s',
    animationLevel: 'gsap-allowed',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Bayraktar Kaplan Uluslararasi Hukuk' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905551234567',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Bayraktar Kaplan Uluslararasi Hukuk',
        copyright: '© 2026 Bayraktar Kaplan Uluslararasi Hukuk',
        contact: {
          phone: '0212 380 22 33',
          email: 'contact@bayraktarkaplan.law',
          address: 'Maslak Mah. AOS 55. Sok. No:2 42Maslak Kat:28, Sariyer/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/bayraktarkaplanlaw',
            icon: 'instagram',
          },
          {
            platform: 'linkedin',
            url: 'https://linkedin.com/company/bayraktarkaplan',
            icon: 'linkedin',
          },
          {
            platform: 'twitter',
            url: 'https://twitter.com/bklaw_istanbul',
            icon: 'twitter',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905551234567', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Bayraktar Kaplan Uluslararasi Hukuk — Sariyer',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: AVUKAT_TICARET_BUSINESS.name, subtitle: AVUKAT_TICARET_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
