/**
 * @kepenk/templates — haliyikama-ev Theme Configuration
 *
 * Ev halisi toplama ve yikama hizmeti
 * Plan: free (3 page sections, 3 global sections)
 * Font: Inter/Inter | Accent: #2196F3
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const HALIYIKAMA_EV_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#2196F3',
  '--color-accent-hover': '#2196F3',
  '--color-accent-active': '#2196F3',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': "'DM Sans', sans-serif",
  '--font-body': "'DM Sans', system-ui, sans-serif",
}

// ═══ DEMO BUSINESS DATA ═══

export const HALIYIKAMA_EV_BUSINESS = {
  name: 'Temiz Hali Yikama',
  ownerName: 'Ahmet Demir',
  sectorId: 'Hali Yikama',
  slogan: 'Haliniz bizde, temizlik garantimizle',
  phone: '0532 417 68 30',
  phoneClean: '905324176830',
  whatsapp: '905324176830',
  email: 'info@temizhaliyikama.com',
  address: 'Caferaga Mah. Moda Cad. No:72/A, Kadikoy/Istanbul',
  city: 'Istanbul',
  district: 'Kadikoy',
  neighborhood: 'Caferaga',
  coordinates: { lat: 40.987, lng: 29.0265 },
  socialMedia: { instagram: 'https://instagram.com/temizhaliyikama' },
  photos: [],
  foundedYear: 2015,
  experience: '11 yil',
  customerCount: '18.000+',
  rating: 4.6,
  reviewCount: 640,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '09:00',
      close: '17:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '00:00',
      close: '00:00',
      isOpen: false,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Makine Halisi Yikama',
      price: '80 TL/m2',
      duration: '2-3 gun',
      description: 'Makine halisi ve dokuma hali profesyonel yikama. Ucretsiz toplama ve teslim.',
    },
    {
      id: 's2',
      name: 'Yun Hali Yikama',
      price: '120 TL/m2',
      duration: '3-5 gun',
      description: 'El dokuma ve yun halilara ozel hassas yikama. Lif koruma garantili.',
    },
    {
      id: 's3',
      name: 'Hali Leke Cikarma',
      price: '150 TL/m2',
      duration: '3-5 gun',
      description: 'Inatci lekeler icin ozel islem. Cay, kahve, boya, pet lekeleri.',
    },
    {
      id: 's4',
      name: 'Hali Teslim Al-Gotyr',
      price: 'Ucretsiz',
      duration: 'aynii gun',
      description: 'Kadikoy ve cevre ilcelerde ucretsiz hali toplama ve teslim hizmeti.',
    },
  ],
  team: [],
  testimonials: [],
  faq: [
    { q: 'Hali yikama kac gun suruyor?', a: 'Makine halilari 2-3 gun, yun ve el dokuma halillar 3-5 gun icinde teslim edilir. Acil durumlarda 24 saat ekspres hizmetimiz de vardir.' },
    { q: 'Toplama ve teslim ucretsiz mi?', a: 'Evet, Kadikoy ve cevre ilcelerde (Uskudar, Atasehir, Maltepe) toplama ve teslim tamamen ucretsizdir.' },
    { q: 'Hali zarar gorur mu?', a: 'Hayir, hali tipine uygun yikama yontemi secilir. Yun halillar dusuk sicaklikta, makine halilari normal programda yikanir. Lif bozulmasi olmaz.' },
    { q: 'Fiyat nasil hesaplaniyor?', a: 'Fiyatlandirma metrekare uzerinden yapilir. Halinizin olcusu alinir ve tipine gore metrekare birim fiyati uygulanir.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const HALIYIKAMA_EV_CONFIG = {
  id: 'haliyikama-ev',
  name: 'Ev',
  sectorId: 'haliyikama',
  plan: 'free',
  description: 'Ev halisi toplama ve yikama hizmeti',
  designPhilosophy: 'Sade, guvenilir, ekonomik',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#2196F3',
    '--color-accent-hover': '#2196F3',
    '--color-accent-active': '#2196F3',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': "'DM Sans', sans-serif",
    '--font-body': "'DM Sans', system-ui, sans-serif",
  },
  fonts: {
    heading: {
      family: 'DM Sans',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'DM Sans',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'DryCleaningOrLaundry',
  sectorSections: [],
  performanceBudget: {
    maxJS: '80kb',
    maxLCP: '3.0s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Temiz Hali Yikama' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905324176830',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Temiz Hali Yikama',
        copyright: '© 2026 Temiz Hali Yikama',
        contact: {
          phone: '0532 417 68 30',
          email: 'info@temizhaliyikama.com',
          address: 'Caferaga Mah. Moda Cad. No:72/A, Kadikoy/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/temizhaliyikama',
            icon: 'instagram',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905324176830', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Temiz Hali Yikama — Kadikoy',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: HALIYIKAMA_EV_BUSINESS.name, subtitle: HALIYIKAMA_EV_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
