/**
 * @kepenk/templates — elektrikci-ev Theme Configuration
 *
 * Mahalle elektrikcisi, ev tipi isler
 * Plan: free (3 page sections, 3 global sections)
 * Font: Inter/Inter | Accent: #F59E0B
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const ELEKTRIKCI_EV_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#F59E0B',
  '--color-accent-hover': '#F59E0B',
  '--color-accent-active': '#F59E0B',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': "'DM Sans', sans-serif",
  '--font-body': "'DM Sans', system-ui, sans-serif",
}

// ═══ DEMO BUSINESS DATA ═══

export const ELEKTRIKCI_EV_BUSINESS = {
  name: 'Volkan Usta Elektrik',
  ownerName: 'Volkan Demir',
  sectorId: 'Elektrikci',
  slogan: 'Evinizin elektrik guvenligio bizden sorulur',
  phone: '0532 876 54 32',
  phoneClean: '905328765432',
  whatsapp: '905328765432',
  email: 'info@volkanelektrik.com',
  address: 'Goztepe Mah. Fahrettin Kerim Gokay Cad. No:82, Kadikoy/Istanbul',
  city: 'Istanbul',
  district: 'Kadikoy',
  mapEmbed: '',
  foundedYear: 2005,
  experience: '21 yil',
  employeeCount: 2,
  customerCount: '12.000+',
  rating: 4.7,
  reviewCount: 680,
  workingHours: [
    {
      day: 'Pazartesi',
      dayTr: 'Pazartesi',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      dayTr: 'Sali',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      dayTr: 'Carsamba',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      dayTr: 'Persembe',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      dayTr: 'Cuma',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      dayTr: 'Cumartesi',
      open: '09:00',
      close: '17:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      dayTr: 'Pazar',
      open: '',
      close: '',
      isOpen: false,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Elektrik Ariza Tespiti',
      price: '200-400 TL',
      duration: '30-60 dk',
      description: 'Evinizdeki elektrik arizalarinin profesyonel tespit ve onarimI. Kisa devre, sigorta attirma, priz arizasi gibi sorunlara hizli cozum.',
      icon: 'Zap',
    },
    {
      id: 's2',
      name: 'Priz & Anahtar Montaji',
      price: '150-250 TL',
      duration: '30 dk',
      description: 'Yeni priz, anahtar, dimmer ve USB\'li priz montaji. Schneider, Legrand gibi kaliteli markalarla calisiyoruz.',
      icon: 'PlugZap',
    },
    {
      id: 's3',
      name: 'Avize & Aydinlatma Montaji',
      price: '200-500 TL',
      duration: '45 dk',
      description: 'Her turlu avize, spot lamba, LED serit ve dis mekan aydinlatma montaji. Elektrik hatti cekimi dahil.',
      icon: 'Lightbulb',
    },
    {
      id: 's4',
      name: 'Sigorta Tablosu Yenileme',
      price: '800-2.000 TL',
      duration: '2-4 saat',
      description: 'Eski sigorta tablonuzu modern kacak akim korumali tabloya yukseltme. Topraklama kontrolu dahil.',
      icon: 'ShieldCheck',
    },
  ],
  team: [],
  testimonials: [],
  gallery: [],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const ELEKTRIKCI_EV_CONFIG = {
  id: 'elektrikci-ev',
  name: 'Ev',
  sectorId: 'elektrikci',
  plan: 'free',
  description: 'Mahalle elektrikcisi, ev tipi isler',
  designPhilosophy: 'Guvenilir, sade, samimi',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#F59E0B',
    '--color-accent-hover': '#F59E0B',
    '--color-accent-active': '#F59E0B',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': "'DM Sans', sans-serif",
    '--font-body': "'DM Sans', system-ui, sans-serif",
  },
  fonts: {
    heading: {
      family: 'DM Sans',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'DM Sans',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'Electrician',
  sectorSections: [],
  performanceBudget: {
    maxJS: '80kb',
    maxLCP: '3.0s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Volkan Usta Elektrik' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905328765432',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Volkan Usta Elektrik',
        copyright: '© 2026 Volkan Usta Elektrik',
        contact: {
          phone: '0532 876 54 32',
          email: 'info@volkanelektrik.com',
          address: 'Goztepe Mah. Fahrettin Kerim Gokay Cad. No:82, Kadikoy/Istanbul',
        },
        social: [],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905328765432', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Volkan Usta Elektrik — Kadikoy',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: ELEKTRIKCI_EV_BUSINESS.name, subtitle: ELEKTRIKCI_EV_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
