import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const KUYUMCU_OZEL_CSS: Record<string, string> = { '--color-bg': '#FFFFFF', '--color-surface': '#F8FAFC', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#F1F5F9', '--color-text': '#0F172A', '--color-text-secondary': '#475569', '--color-text-muted': '#94A3B8', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#DB2777', '--color-accent-hover': '#BE185D',
    '--color-accent-active': '#127d29', '--color-accent-light': '#FDF2F8', '--color-border': '#E2E8F0', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const KUYUMCU_OZEL_BUSINESS: BusinessData = { name: 'Artisan Jewel', ownerName: 'Zeynep Tasarim', sector: 'kuyumcu', slogan: 'Ozel Tasarim kuyumcu', phone: '0535 800 80 90', phoneClean: '905358008090', whatsapp: '905358008090', email: 'info@kuyumcuozel.com.tr', address: 'Kadikoy, Istanbul', city: 'Istanbul', district: 'Kadikoy', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '18:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '18:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '18:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '18:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '18:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '14:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/kuyumcuozel' }, photos: [], services: [{ id: 's1', name: 'Ozel Tasarim', icon: '💎' }], team: [{ id: 't1', name: 'Zeynep Tasarim', role: 'Yonetici', experience: '12 yil' }], experience: '12 yil', rating: 4.9, reviewCount: 500, foundedYear: 2012 }
export const KUYUMCU_OZEL_CONFIG: ThemeConfig = { id: 'kuyumcu-ozel', name: 'Ozel Tasarim', sectorId: 'kuyumcu', plan: 'pro', description: 'Ozel Tasarim kuyumcu. Kadikoy.', designPhilosophy: 'Ozel Tasarim theme.', isDark: false, cssVariables: KUYUMCU_OZEL_CSS, fonts: { heading: { family: 'Bodoni Moda', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'JewelryStore', sectorSections: [], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'auto', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Artisan Jewel' }, menuItems: [{ label: 'Hizmetler', href: '#hizmetler' },{ label: 'Iletisim', href: '#iletisim' }], cta: { text: 'Iletisim', href: '#iletisim', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'auto', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Artisan Jewel', copyright: '© 2024', contact: { phone: '0535 800 80 90', address: 'Kadikoy, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/kuyumcuozel', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905358008090', message: 'Merhaba, bilgi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Artisan Jewel — Kadikoy", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'kuyumcu_ozel_full', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: {}, editableFields: [] }
    ]
  }]
}
