/**
 * @kepenk/templates — terzi-gelin Theme Configuration
 *
 * Gelinlik ve abiye odakli kadin terzisi
 * Plan: growth (9 page sections, 4 global sections)
 * Font: Cormorant Garamond/Inter | Accent: #C4788C
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const TERZI_GELIN_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#C4788C',
  '--color-accent-hover': '#C4788C',
  '--color-accent-active': '#C4788C',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'Cormorant Garamond\', sans-serif',
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const TERZI_GELIN_BUSINESS = {
  name: 'Atölye Nur Gelinlik & Abiye',
  ownerName: 'Nur Aksoy',
  sectorId: 'Terzi',
  slogan: 'Hayalinizdeki gelinlik, ellerimizde hayat bulur',
  phone: '0534 891 62 30',
  phoneClean: '905348916230',
  whatsapp: '905348916230',
  email: 'info@atolyenur.com.tr',
  address: 'Cankurtaran Mah. Akbiyik Cad. No:18, Fatih/Istanbul',
  city: 'Istanbul',
  district: 'Fatih',
  neighborhood: 'Cankurtaran',
  coordinates: { lat: 41.0054, lng: 28.9782 },
  socialMedia: {
    instagram: 'https://instagram.com/atolyenurgelinlik',
    facebook: 'https://facebook.com/atolyenur',
    pinterest: 'https://pinterest.com/atolyenur',
  },
  photos: [],
  foundedYear: 2010,
  experience: '16 yil',
  customerCount: '4.500+',
  rating: 4.9,
  reviewCount: 1100,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '10:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '10:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '10:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '10:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '10:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '10:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '00:00',
      close: '00:00',
      isOpen: false,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Ismarlama Gelinlik',
      price: '15.000 - 80.000 TL',
      duration: '8-12 hafta',
      description: 'Sifirdan tasarim, kumas secimi, el islemesi detaylar. 4-5 prova ile mukemmel kalip.',
    },
    {
      id: 's2',
      name: 'Gelinlik Tadilatı',
      price: '2.000 - 8.000 TL',
      duration: '2-3 hafta',
      description: 'Mevcut gelinlik beden ayarlama, dantel ekleme, kol/etek mudahale.',
    },
    {
      id: 's3',
      name: 'Ismarlama Abiye',
      price: '5.000 - 25.000 TL',
      duration: '4-6 hafta',
      description: 'Ozel gun icin tasarlanmis abiye elbise. Kumas, renk ve model tamamen size ozel.',
    },
    {
      id: 's4',
      name: 'Nisan/Soz Elbisesi',
      price: '4.000 - 15.000 TL',
      duration: '3-4 hafta',
      description: 'Nisan ve soz torenleri icin sik ve zarif elbise dikimi.',
    },
    {
      id: 's5',
      name: 'Kina Kiyafeti',
      price: '3.000 - 10.000 TL',
      duration: '2-3 hafta',
      description: 'Geleneksel veya modern kina gecesi kiyafeti. El nakisi ve boncuk isleme.',
    },
    {
      id: 's6',
      name: 'Anne/Kayinvalide Kiyafeti',
      price: '4.000 - 12.000 TL',
      duration: '3-4 hafta',
      description: 'Dugun gunu icin anne ve kayinvalide abiyeleri. Sik ve yas grubuna uygun.',
    },
    {
      id: 's7',
      name: 'Nedime/Drujba Elbisesi',
      price: '2.000 - 6.000 TL',
      duration: '3 hafta',
      description: 'Tema ve renge uygun nedime elbiseleri. Grup siparislerinde indirim.',
    },
    {
      id: 's8',
      name: 'Duvak & Aksesuar',
      price: '500 - 3.000 TL',
      duration: '1 hafta',
      description: 'El yapimi duvak, tac, sac aksesuari. Gelinlik ile uyumlu tasarim.',
    },
    {
      id: 's9',
      name: 'Dugun Danismanligi',
      price: 'Ucretsiz',
      duration: '60 dk',
      description: 'Dugun temasina, mekana ve mevsime gore kiyafet planlamasi.',
    },
    {
      id: 's10',
      name: 'Gelinlik Koruma & Temizlik',
      price: '1.500 TL',
      duration: '1 hafta',
      description: 'Dugun sonrasi profesyonel temizlik, ozel kutu ile saklama.',
    },
  ],
  team: [
    {
      name: 'Nur Aksoy',
      role: 'Kurucu & Bas Tasarimci',
      bio: 'Mimar Sinan Guzel Sanatlar tekstil bolumu mezunu. 16 yildir gelinlik ve abiye tasarliyor. 3.000+ gelinlik dikmis.',
    },
    {
      name: 'Sevgi Kara',
      role: 'Dantel & Isleme Uzmani',
      bio: '25 yillik el islemesi ustasi. Fransiz danteli, boncuk ve payetli islemeler konusunda uzman.',
    },
    {
      name: 'Derya Polat',
      role: 'Kalipci & Prova Sorumlusu',
      bio: 'Teknik kalipcilik ve drapaj uzmani. Vucuda ozel kalip cikartma ve ayarlamada 12 yil deneyim.',
    },
    {
      name: 'Elif Candan',
      role: 'Stil Danismani',
      bio: 'Moda tasarimi mezunu. Gelin adaylarina kiyafet, aksesuar ve renk danismanligi yapiyor.',
    },
  ],
  testimonials: [
    {
      name: 'Merve Yilmaz',
      district: 'Uskudar',
      date: '2025-10',
      rating: 5,
      comment: 'Hayalimde bir gelinlik vardi, Nur Hanim aynen hayal ettigim gibi tasarladi. Her provada heyecanim artti. Dugun gununde gozlerim doldu, o kadar guzel olmustu.',
    },
    {
      name: 'Selin Demir',
      district: 'Kadikoy',
      date: '2025-09',
      rating: 5,
      comment: 'Annem icin dugun kiyafeti diktirdik. 58 yasinda ama cok sik ve yas grubuna uygun bir abiye oldu. Nur Hanim annemi dinledi, tam istedigini yapti.',
    },
    {
      name: 'Busra Ozcan',
      district: 'Beyoglu',
      date: '2025-11',
      rating: 5,
      comment: '5 nedime elbisesi diktirdik, hepsi ayni renk farkli model. Her biri kendi vucuduna uygun oldu. Fotgraflarda muhtesem gorunduler.',
    },
    {
      name: 'Tugce Sahin',
      district: 'Fatih',
      date: '2025-08',
      rating: 5,
      comment: 'Kina kiyafetim el nakisiyla bezenmisti, herkes nereden aldigimi sordu. El islemesi detaylar gercekten fark yaratiyor.',
    },
    {
      name: 'Aylin Korkmaz',
      district: 'Bakirkoy',
      date: '2025-07',
      rating: 4,
      comment: 'Abiye diktirdim, cok guzel oldu. Tek sorunum teslimatın planlanandan 5 gun gecikmesiydi ama sonuc buna degerdi.',
    },
    {
      name: 'Zehra Aksoy',
      district: 'Eyupsultan',
      date: '2025-12',
      rating: 5,
      comment: 'Gelinligimi anneannemin gelinliginden esinlenerek yaptirdim. Nur Hanim eski fotograflardan ilham aldi, modern bir yorum katti. Aile buyukleri cok duygulandı.',
    },
  ],
  faq: [
    { q: 'Gelinlik dikimi ne kadar once baslamali?', a: 'Ideal olarak dugun tarihinden 4-6 ay once baslamanizi oneririz. Yogun sezon (Haziran-Eylul) oncesi erken rezervasyon onemlidir.' },
    { q: 'Kendi tasarimimi getirebilir miyim?', a: 'Evet, Pinterest, dergi veya cizim olarak getirdiginiz tasarimlari uyarliyoruz. Vucudunuza ve butcenize gore oneriler de sunuyoruz.' },
    { q: 'Kac prova yapiliyor?', a: 'Gelinlikte ortalama 4-5 prova, abiyelerde 2-3 prova yapiyoruz. Her prova yaklasik 45-60 dakika surer.' },
    { q: 'Yurtdisindan siparis alıyor musunuz?', a: 'Evet, yurtdisindan gelen gelin adaylarimiz var. Ilk olcu ve tasarim gorusmesi icin Istanbul\'a bir kez gelmeniz yeterli, sonraki provalar video ile de yurutulebilir.' },
    { q: 'Abiye kiralaması yapiyor musunuz?', a: 'Hayir, tum kiyafetlerimiz ismarlama dikimdir. Her parca o kisi icin ozel olarak uretilir.' },
    { q: 'Grup indirimi var mi?', a: 'Evet, 3 ve ustu nedime elbisesi siparislerinde %10, anne + kayinvalide + gelin paketinde %15 indirim uyguluyoruz.' },
    { q: 'Gelinlik saklama hizmeti nedir?', a: 'Dugun sonrasi gelinliginizi profesyonel olarak temizliyor, asitsiz kutuya yerlestirip uzun sure saklanabilir hale getiriyoruz.' },
    { q: 'Odeme plani sunuyor musunuz?', a: 'Evet, siparis onayinda %40, ikinci provada %30, teslimatta %30 olmak uzere 3 taksit ile odeme plani sunuyoruz.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const TERZI_GELIN_CONFIG = {
  id: 'terzi-gelin',
  name: 'Gelin',
  sectorId: 'terzi',
  plan: 'growth',
  description: 'Gelinlik ve abiye odakli kadin terzisi',
  designPhilosophy: 'Romantik, zarif, feminin',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#C4788C',
    '--color-accent-hover': '#C4788C',
    '--color-accent-active': '#C4788C',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'Cormorant Garamond\', sans-serif',
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Cormorant Garamond',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'TailorShop',
  sectorSections: [],
  performanceBudget: {
    maxJS: '180kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Atölye Nur Gelinlik & Abiye' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905348916230',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Atölye Nur Gelinlik & Abiye',
        copyright: '© 2026 Atölye Nur Gelinlik & Abiye',
        contact: {
          phone: '0534 891 62 30',
          email: 'info@atolyenur.com.tr',
          address: 'Cankurtaran Mah. Akbiyik Cad. No:18, Fatih/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/atolyenurgelinlik',
            icon: 'instagram',
          },
          {
            platform: 'facebook',
            url: 'https://facebook.com/atolyenur',
            icon: 'facebook',
          },
          {
            platform: 'pinterest',
            url: 'https://pinterest.com/atolyenur',
            icon: 'pinterest',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905348916230', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Atölye Nur Gelinlik & Abiye — Fatih',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: TERZI_GELIN_BUSINESS.name, subtitle: TERZI_GELIN_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
