/**
 * @kepenk/templates — cicekci-dugun Theme Configuration
 *
 * Dugun ve organizasyon cicek dekorasyonu
 * Plan: growth (9 page sections, 4 global sections)
 * Font: Cormorant Garamond/Inter | Accent: #B5838D
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const CICEKCI_DUGUN_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#B5838D',
  '--color-accent-hover': '#B5838D',
  '--color-accent-active': '#B5838D',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'Cormorant Garamond\', sans-serif',
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const CICEKCI_DUGUN_BUSINESS = {
  name: 'Bloom & Petal Dugun Cicekleri',
  ownerName: 'Elif Duman',
  sectorId: 'Cicekci',
  slogan: 'Dugun gununuz, hayalinizdeki ciceklerle',
  phone: '0534 612 38 70',
  phoneClean: '905346123870',
  whatsapp: '905346123870',
  email: 'info@bloomandpetal.com.tr',
  address: 'Kuruçesme Mah. Muallim Naci Cad. No:65/A, Besiktas/Istanbul',
  city: 'Istanbul',
  district: 'Besiktas',
  neighborhood: 'Kurucesme',
  coordinates: { lat: 41.0625, lng: 29.0315 },
  socialMedia: {
    instagram: 'https://instagram.com/bloomandpetal',
    facebook: 'https://facebook.com/bloomandpetal',
    pinterest: 'https://pinterest.com/bloomandpetal',
  },
  photos: [],
  foundedYear: 2015,
  experience: '11 yil',
  customerCount: '2.800+',
  rating: 4.9,
  reviewCount: 920,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '09:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '09:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '09:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '09:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '09:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '08:00',
      close: '22:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '08:00',
      close: '22:00',
      isOpen: true,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Gelin Buketi',
      price: '1.500 - 5.000 TL',
      duration: 'hazirlik',
      description: 'Gelin temasina uygun ozel tasarim el buketi. Gul, sakkayik, orkide, lilyum secenekleri.',
    },
    {
      id: 's2',
      name: 'Gelin Araba Susu',
      price: '800 - 2.500 TL',
      duration: '45 dk',
      description: 'Araba ustu cicek susu, kurdele ve puf detayli. Aracın rengine uygun tasarim.',
    },
    {
      id: 's3',
      name: 'Masa Aranjmani',
      price: '400 - 1.500 TL/masa',
      duration: 'yerinde',
      description: 'Dugun masalari icin merkez cicek aranjmani. Mum, vazo ve aksesuar dahil.',
    },
    {
      id: 's4',
      name: 'Salon Dekorasyonu',
      price: '5.000 - 30.000 TL',
      duration: '4-8 saat',
      description: 'Dugun salonu tam dekorasyon. Giiris kemeri, sahne cicegi, sutun sarma, tavan susleme.',
    },
    {
      id: 's5',
      name: 'Nikah Masasi Susleme',
      price: '1.000 - 3.000 TL',
      duration: '1 saat',
      description: 'Nikah masasi cicek duzenleme, mum ve aksesuar.',
    },
    {
      id: 's6',
      name: 'Kir Dugunu Dekorasyonu',
      price: '8.000 - 50.000 TL',
      duration: '6-10 saat',
      description: 'Acik hava dugun dekorasyonu. Kemer, oturma duzeni, yol kenarı, altar cicekleri.',
    },
    {
      id: 's7',
      name: 'Nedime Buketi',
      price: '500 - 1.200 TL/adet',
      duration: 'hazirlik',
      description: 'Gelin buketiyle uyumlu, daha kucuk boyutlu nedime buketleri.',
    },
    {
      id: 's8',
      name: 'Yaka Cicegi',
      price: '100 - 300 TL/adet',
      duration: 'hazirlik',
      description: 'Damat ve sagdic icin yaka cicegi. Gelin buketiyle uyumlu.',
    },
    {
      id: 's9',
      name: 'Konsept Tasarim Danismanligi',
      price: 'Ucretsiz',
      duration: '60 dk',
      description: 'Dugun temaniza uygun cicek ve renk paleti onerisi. Mekan gezisi dahil.',
    },
    {
      id: 's10',
      name: 'Nisan/Soz Dekorasyonu',
      price: '3.000 - 15.000 TL',
      duration: '3-5 saat',
      description: 'Nisan ve soz toreni mekan dekorasyonu. Masa, sahne ve giris susleme.',
    },
  ],
  team: [
    {
      name: 'Elif Duman',
      role: 'Kurucu & Bas Tasarimci',
      bio: 'Hollanda Aalsmeer cicek tasarim okulu mezunu. 11 yildir dugun cicekleri konusunda uzman.',
    },
    {
      name: 'Seren Aktas',
      role: 'Dekorasyon Koordinatoru',
      bio: '400+ dugun dekorasyonu koordine etmis. Mekan lojistigi ve kurulum uzmani.',
    },
    {
      name: 'Cansu Tekin',
      role: 'Cicek Tasarimcisi',
      bio: 'Guzel sanatlar mezunu, botanik ilustrasyon gecmisli. Yaratici aranjman ve kir dugunu uzmani.',
    },
    {
      name: 'Ahmet Yilmaz',
      role: 'Kurulum Ekip Sefi',
      bio: '8 yillik deneyim, agir dekorasyon kurulumu ve demontaj. 5 kisilik ekip yonetiyor.',
    },
  ],
  testimonials: [
    {
      name: 'Merve & Kagan',
      district: 'Sariyer',
      date: '2025-10',
      rating: 5,
      comment: 'Kir dugununuz icin Bloom & Petal\'i sectik, kesinlikle en iyi kararimiz. Cicek kemeri, masa aranjmanlari ve yol kenari cicekleri hayalimizdekinden bile guzel oldu.',
    },
    {
      name: 'Selin & Emre',
      district: 'Besiktas',
      date: '2025-09',
      rating: 5,
      comment: 'Salon dekorasyonu icin geldik, konsept danismanligi ucretsiz yapildi. Elif Hanim temamiza uygun renk paleti onerdi. Sonuc muhtesem, misafirlerin hepsi hayran kaldi.',
    },
    {
      name: 'Ayse & Burak',
      district: 'Beyoglu',
      date: '2025-08',
      rating: 5,
      comment: 'Gelin buketim sakkayik ve gul karisimi, tam istedigim gibi oldu. Yaka cicekleri de cok sik. Fiyat/kalite orani cok iyi.',
    },
    {
      name: 'Canan & Tolga',
      district: 'Kadikoy',
      date: '2025-07',
      rating: 4,
      comment: 'Nisan dekorasyonumuzu yaptilar. Cicekler harika ama kurulum planlanandan 1 saat gecikti. Sonuc olarak guzel oldu.',
    },
    {
      name: 'Nil & Serkan',
      district: 'Uskudar',
      date: '2025-11',
      rating: 5,
      comment: '200 kisilik dugunda 25 masa aranjmani yapildi. Hepsi birbirinden guzel ve tutarli. Cansu Hanim\'in yaratici aranjmanlari cok begennildi.',
    },
    {
      name: 'Ebru & Deniz',
      district: 'Atasehir',
      date: '2025-06',
      rating: 5,
      comment: 'Araba susu ve salon girisi icin geldik. Fotograflarda cok iyi cikti. Ozellikle giris kemeri Instagram\'da cok begeni aldi.',
    },
  ],
  faq: [
    { q: 'Dugun oncesi ne kadar zaman ayirmali?', a: 'Ideal olarak 3-4 ay once gorusmemizi oneririz. Yaz sezonu icin 6 ay once basvuru yapmanizi tavsiye ederiz.' },
    { q: 'Mekan gezisi yapiyor musunuz?', a: 'Evet, Istanbul icindeki mekanlara ucretsiz gezii duzenliyoruz. Mekan boyutlarina gore dekorasyon plani olusturuyoruz.' },
    { q: 'Yapay cicek kullanir misiniz?', a: 'Tercihen taze cicek kullaniyoruz. Ancak tavan susleme veya kalici detaylarda yuksek kalite yapay cicek de kullanabiliyoruz.' },
    { q: 'Dekorasyon sonrasi demontaj dahil mi?', a: 'Evet, kurulum ve demontaj fiyata dahildir. Dugun sonrasi ekibimiz tum malzemeleri toplar.' },
    { q: 'Yagmurlu havada kir dugunu ne olur?', a: 'B plani olarak salon veya cadir alternatiifi her zaman hazirlariz. Cicek aranjmanlari kolayca tasinabilir formatta hazirllanir.' },
    { q: 'Baska sehirlere gelir misiniz?', a: 'Istanbul ve Marmara Bolgesi\'ne (Bursa, Edirne, Sakarya) geliyoruz. Uzak sehirler icin ulasim ve konaklama ucreti eklenir.' },
    { q: 'Odeme nasil yapilir?', a: '%30 kaparo siparis onayinda, kalan %70 dugun gunu oncesinde odenir. Kredi karti ve havale kabul ediyoruz.' },
    { q: 'Nedime ve damat aksesuarlari ayri mi?', a: 'Evet, nedime buketi, yaka cicegi, bileklik cicek gibi aksesuarlar adet bazinda ayri fiyatlandirilir.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const CICEKCI_DUGUN_CONFIG = {
  id: 'cicekci-dugun',
  name: 'Dugun',
  sectorId: 'cicekci',
  plan: 'growth',
  description: 'Dugun ve organizasyon cicek dekorasyonu',
  designPhilosophy: 'Romantik, sofistike, goruntusel',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#B5838D',
    '--color-accent-hover': '#B5838D',
    '--color-accent-active': '#B5838D',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'Cormorant Garamond\', sans-serif',
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Cormorant Garamond',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'Florist',
  sectorSections: [],
  performanceBudget: {
    maxJS: '180kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Bloom & Petal Dugun Cicekleri' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905346123870',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Bloom & Petal Dugun Cicekleri',
        copyright: '© 2026 Bloom & Petal Dugun Cicekleri',
        contact: {
          phone: '0534 612 38 70',
          email: 'info@bloomandpetal.com.tr',
          address: 'Kuruçesme Mah. Muallim Naci Cad. No:65/A, Besiktas/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/bloomandpetal',
            icon: 'instagram',
          },
          {
            platform: 'facebook',
            url: 'https://facebook.com/bloomandpetal',
            icon: 'facebook',
          },
          {
            platform: 'pinterest',
            url: 'https://pinterest.com/bloomandpetal',
            icon: 'pinterest',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905346123870', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Bloom & Petal Dugun Cicekleri — Besiktas',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: CICEKCI_DUGUN_BUSINESS.name, subtitle: CICEKCI_DUGUN_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
