/**
 * @kepenk/templates — boyaci-endustriyel Theme Configuration
 *
 * Endustriyel boyama ve koruyucu kaplama
 * Plan: pro (11 page sections, 4 global sections)
 * Font: Playfair Display/Inter | Accent: #0369A1
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const BOYACI_ENDUSTRIYEL_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '0px',
  '--radius-lg': '0px',
  '--color-bg': '#0F172A',
  '--color-surface': '#1E293B',
  '--color-surface-elevated': '#334155',
  '--color-surface-muted': '#0B1120',
  '--color-text': '#F8FAFC',
  '--color-text-secondary': '#94A3B8',
  '--color-text-muted': '#475569',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#0369A1',
  '--color-accent-hover': '#075985',
  '--color-accent-active': '#0369A1',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#334155',
  '--color-border-subtle': '#1E293B',
  '--font-heading': '\'Playfair Display\', sans-serif',
  '--font-body': "'Source Sans 3', system-ui, sans-serif",
}

// ═══ DEMO BUSINESS DATA ═══

export const BOYACI_ENDUSTRIYEL_BUSINESS = {
  name: 'EndPaint Endustriyel Boyama Sistemleri',
  ownerName: 'Okan Sener',
  sectorId: 'Boyaci',
  slogan: 'Endustriyel yuzeyler icin muhendislik boyaciligi',
  phone: '0532 845 12 33',
  phoneClean: '905328451233',
  whatsapp: '905328451233',
  email: 'info@endpaint.com.tr',
  address: 'Aydini Mah. E-5 Yan Yol No:220, Tuzla/Istanbul',
  city: 'Istanbul',
  district: 'Tuzla',
  neighborhood: 'Aydini',
  coordinates: { lat: 40.826, lng: 29.295 },
  socialMedia: { instagram: 'https://instagram.com/endpaint', linkedin: 'https://linkedin.com/company/endpaint' },
  photos: [],
  foundedYear: 2001,
  experience: '23 yil',
  customerCount: '4.500+',
  rating: 4.8,
  reviewCount: 780,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '07:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '07:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '07:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '07:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '07:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '08:00',
      close: '14:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: 'Kapali',
      close: 'Kapali',
      isOpen: false,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Celik Konstruksiyon Boyama',
      price: '65 TL/m2',
      duration: '5-15 gun',
      description: 'Fabrika, hangar ve celik yapilar icin antipas + astar + son kat boya uygulamasi.',
    },
    {
      id: 's2',
      name: 'Epoksi Zemin Boyama',
      price: '120 TL/m2',
      duration: '3-5 gun',
      description: 'Fabrika, otopark ve depo zeminleri icin dayanikli epoksi kaplama.',
    },
    {
      id: 's3',
      name: 'Polyurea Kaplama',
      price: '180 TL/m2',
      duration: '1-3 gun',
      description: 'Yuksek asinma direncli elastik su yalitim ve zemin kaplama sistemi.',
    },
    {
      id: 's4',
      name: 'Elektrostatik Toz Boya',
      price: '45 TL/parca',
      duration: '1-2 gun',
      description: 'Metal parcalar icin firinli toz boya uygulamasi. Yuksek dayaniklilik.',
    },
    {
      id: 's5',
      name: 'Yangin Geciktirici Boya',
      price: '95 TL/m2',
      duration: '2-5 gun',
      description: 'Celik ve ahsap yapilarda yangin dayanim suresi artiran ozel boyalar.',
    },
    {
      id: 's6',
      name: 'Korozyon Koruma Sistemi',
      price: '85 TL/m2',
      duration: '3-7 gun',
      description: 'Deniz ortami, kimyasal tesisler ve agresif kosullar icin korozyon koruma.',
    },
    {
      id: 's7',
      name: 'Silo ve Tank Boyama',
      price: '75 TL/m2',
      duration: '5-10 gun',
      description: 'Gida, kimya ve petrol sektorlerinde silo ve depolama tanki boyama.',
    },
    {
      id: 's8',
      name: 'Boru Hatti Boyama',
      price: '55 TL/m',
      duration: '3-7 gun',
      description: 'Endustriyel boru hatlari icin renk kodlamali koruyucu boyama.',
    },
    {
      id: 's9',
      name: 'Kumlama ve Yuzey Hazirlama',
      price: '40 TL/m2',
      duration: '2-5 gun',
      description: 'Boya oncesi metal yuzey hazirlama. Sa 2.5 standartinda kumlama.',
    },
    {
      id: 's10',
      name: 'Gemi ve Yat Boyama',
      price: '150 TL/m2',
      duration: '10-20 gun',
      description: 'Deniz araclari icin antifouling ve koruyucu boya uygulamasi.',
    },
    {
      id: 's11',
      name: 'Kule ve Direk Boyama',
      price: '70 TL/m2',
      duration: '3-7 gun',
      description: 'Enerji nakil hatlari, GSM kuleleri ve aydinlatma direkleri boyama.',
    },
    {
      id: 's12',
      name: 'Isi Yalitim Boyasi',
      price: '110 TL/m2',
      duration: '2-4 gun',
      description: 'Isiya dayanikli termal bariyer boyalar. 600°C\'ye kadar dayanim.',
    },
    {
      id: 's13',
      name: 'Endustriyel Cizgi Cekme',
      price: '25 TL/m',
      duration: '1-2 gun',
      description: 'Fabrika zemini, otopark ve yol cizgi uygulamasi.',
    },
    {
      id: 's14',
      name: 'Boyama Sozlesmesi ve Danismanlik',
      price: '5.000 TL',
      duration: '3-5 gun',
      description: 'Boya secimi, yuzey analizi, maliyet hesaplama ve proje planlama danismanligi.',
    },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const BOYACI_ENDUSTRIYEL_CONFIG = {
  id: 'boyaci-endustriyel',
  name: 'Endustriyel',
  sectorId: 'boyaci',
  plan: 'pro',
  description: 'Endustriyel boyama ve koruyucu kaplama',
  designPhilosophy: 'Teknik, guclu, kurumsal',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '0px',
    '--radius-lg': '0px',
    '--color-bg': '#0F172A',
    '--color-surface': '#1E293B',
    '--color-surface-elevated': '#334155',
    '--color-surface-muted': '#0B1120',
    '--color-text': '#F8FAFC',
    '--color-text-secondary': '#94A3B8',
    '--color-text-muted': '#475569',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#0369A1',
    '--color-accent-hover': '#075985',
    '--color-accent-active': '#0369A1',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#334155',
    '--color-border-subtle': '#1E293B',
    '--font-heading': '\'Playfair Display\', sans-serif',
    '--font-body': "'Source Sans 3', system-ui, sans-serif",
  },
  fonts: {
    heading: {
      family: 'Playfair Display',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Source Sans 3',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'HousePainter',
  sectorSections: [],
  performanceBudget: {
    maxJS: '250kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'EndPaint Endustriyel Boyama Sistemleri' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905328451233',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'EndPaint Endustriyel Boyama Sistemleri',
        copyright: '© 2026 EndPaint Endustriyel Boyama Sistemleri',
        contact: {
          phone: '0532 845 12 33',
          email: 'info@endpaint.com.tr',
          address: 'Aydini Mah. E-5 Yan Yol No:220, Tuzla/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/endpaint',
            icon: 'instagram',
          },
          {
            platform: 'linkedin',
            url: 'https://linkedin.com/company/endpaint',
            icon: 'linkedin',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905328451233', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'EndPaint Endustriyel Boyama Sistemleri — Tuzla',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_asymmetric_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'VİZYON', title: BOYACI_ENDUSTRIYEL_BUSINESS.name, subtitle: BOYACI_ENDUSTRIYEL_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'about',
          variant: 'tier1_asymmetric_about',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { title: 'Fark Yaratan Vizyon' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_asymmetric_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'OPERASYON', title: 'Çözüm Odaklı Yaklaşım' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_asymmetric_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { title: 'Bağlantı Kurun' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
