import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const OTO_EKSPER_CSS: Record<string, string> = {
  '--container-default': '1280px',
  '--section-py': '96px',
  '--radius-md': '4px',
  '--radius-lg': '8px',
  '--color-bg': '#FAF9F6',
  '--color-surface': '#FFFFFF',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#EFECE6',
  '--color-text': '#1C1917',
  '--color-text-secondary': '#6B6661',
  '--color-text-muted': '#A8A29E',
  '--color-text-on-accent': '#FAF9F6',
  '--color-text-on-dark': '#FAF9F6',
  '--color-accent': '#DC2626',
  '--color-accent-hover': '#B91C1C',
  '--color-accent-active': '#991B1B',
  '--color-accent-light': '#FEE2E2',
  '--color-border': '#E7E5E4',
  '--color-border-subtle': '#F5F5F4',
  '--font-heading': "'Cinzel', serif",
  '--font-body': "'Montserrat', sans-serif",
}

export const OTO_EKSPER_BUSINESS = {
  name: 'Tekniker Oto Ekspertiz',
  ownerName: 'Salih Soydan',
  sectorId: 'Oto',
  slogan: 'İkinci el araç alımında tarafsız ve garantili raporlama',
  phone: '0212 555 12 15',
  phoneClean: '902125551215',
  whatsapp: '905355551215',
  email: 'iletisim@teknikerekspertiz.com',
  address: 'Oto Center Sanayi Sitesi B Blok No:45, Bağcılar/İstanbul',
  city: 'İstanbul',
  district: 'Bağcılar',
  neighborhood: 'Oto Center',
  coordinates: { lat: 41.0432, lng: 28.8411 },
  socialMedia: { instagram: 'https://instagram.com/teknikerekspertiz' },
  photos: [],
  foundedYear: 2012,
  experience: '12 yıldır',
  customerCount: '15.000+',
  rating: 4.7,
  reviewCount: 920,
  services: [
    {
      id: 's1',
      name: 'Full Plus Ekspertiz Paketi',
      price: '4.500 TL',
      duration: '60 dk',
      description: 'Boya, kaporta, mekanik, motor, süspansiyon, fren testleri, OBD arıza tespit ve yol sürüş simülasyonu.',
    },
    {
      id: 's2',
      name: 'Motor & Mekanik Test',
      price: '2.500 TL',
      duration: '35 dk',
      description: 'Dyno test (motor gücü ölçümü), şanzıman kaçak kontrolü, ön takım ve alt taban mekanik muayenesi.',
    },
    {
      id: 's3',
      name: 'Boya & Kaporta Kontrolü',
      price: '1.800 TL',
      duration: '25 dk',
      description: 'Mikron ölçüm cihazıyla boya ve değişen kontrolü, şase, podye, direk ve panel kontrolleri.',
    },
    {
      id: 's4',
      name: 'Mobil (Yerinde) Ekspertiz',
      price: '5.500 TL',
      duration: '90 dk',
      description: 'Siz gelemiyorsanız usta ekibimiz aracın bulunduğu konuma giderek ekspertiz yapar ve raporu cebe gönderir.',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Salı', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Çarşamba', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Perşembe', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Cuma', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Cumartesi', open: '08:30', close: '17:00', isOpen: true },
    { day: 'Pazar', open: '10:00', close: '15:00', isOpen: true },
  ],
} as unknown as BusinessData

export const OTO_EKSPER_CONFIG = {
  id: 'oto-eksper',
  name: 'Eksper',
  sectorId: 'oto',
  plan: 'enterprise',
  description: 'Garantili oto ekspertiz, tarafsız test merkezi lüks tasarımı',
  designPhilosophy: 'Asil Cinzel başlıkları, keskin kırmızı kurumsal renkler ve detaylı teknik şema tasarımı',
  isDark: false,
  cssVariables: OTO_EKSPER_CSS,
  fonts: {
    heading: {
      family: 'Cinzel',
      weights: [500, 700],
      subsets: ['latin'],
    },
    body: {
      family: 'Montserrat',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'AutoRepair',
  sectorSections: ['vehicle_brands', 'warranty_badge', 'service_area'],
  performanceBudget: {
    maxJS: '120kb',
    maxLCP: '2.0s',
    animationLevel: 'gsap-allowed',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: OTO_EKSPER_BUSINESS.name },
        menuItems: [
          { label: 'Ekspertiz Paketleri', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: { text: 'Rezervasyon', href: 'https://wa.me/905355551215', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'dark', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: OTO_EKSPER_BUSINESS.name,
        copyright: '© 2026 Tekniker Oto Ekspertiz. Tüm hakları saklıdır.',
        contact: {
          phone: OTO_EKSPER_BUSINESS.phone,
          email: OTO_EKSPER_BUSINESS.email,
          address: OTO_EKSPER_BUSINESS.address,
        },
        social: [{ platform: 'instagram', url: 'https://instagram.com/teknikerekspertiz', icon: 'instagram' }],
        legal: [
          { label: 'Kullanım Koşulları', href: '/sartlar' },
          { label: 'TSE KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1000, removable: false, animation: 'none' },
      defaultContent: { phone: '905355551215', message: 'Araç ekspertizi randevusu almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${OTO_EKSPER_BUSINESS.name} — Bağcılar Tarafsız Oto Test Raporu`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_editorial_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'TARAFIZ TEST MERKEZİ',
            title: OTO_EKSPER_BUSINESS.name,
            subtitle: OTO_EKSPER_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Kuruluş Yılı / Etiket', type: 'text' },
            { path: 'title', label: 'Kulüp İsmi', type: 'text' },
            { path: 'subtitle', label: 'Alt Başlık / Slogan', type: 'richtext' },
          ],
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_editorial_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: {
            badge: 'TSE BELGELİ HİZMET',
            title: 'Saniyeler İçinde Doğru Teşhis',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'Felsefe Başlığı', type: 'text' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_editorial_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'EKSPERTİZ SEANSLARI',
            title: 'Hassas Ölçüm İstasyonlarımız',
          },
          editableFields: [
            { path: 'badge', label: 'Küçük Etiket', type: 'text' },
            { path: 'title', label: 'Ana Bölüm Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_editorial_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'ULAŞIN VE GÖRÜŞÜN',
            title: 'Hemen Tarafsız Rapor Alın',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
