import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const BERBER_GENTLEMAN_CSS: Record<string, string> = {
  '--container-default': '1120px',
  '--section-py': '80px',
  '--radius-md': '8px',
  '--radius-lg': '16px',
  '--color-bg': '#0F1A1C',
  '--color-surface': '#162527',
  '--color-surface-elevated': '#1B2E30',
  '--color-surface-muted': '#121F21',
  '--color-text': '#E8ECE9',
  '--color-text-secondary': '#A1AEA8',
  '--color-text-muted': '#5D6B65',
  '--color-text-on-accent': '#0F1A1C',
  '--color-text-on-dark': '#E8ECE9',
  '--color-accent': '#1E8E62',
  '--color-accent-hover': '#15754E',
  '--color-accent-active': '#0D543B',
  '--color-accent-light': '#18342C',
  '--color-border': '#223835',
  '--color-border-subtle': '#1B2E30',
  '--font-heading': "'Playfair Display', serif",
  '--font-body': "'Inter', sans-serif",
}

export const BERBER_GENTLEMAN_BUSINESS = {
  name: 'Gentleman\'s Choice Barber',
  ownerName: 'Turgut Özdemir',
  sectorId: 'Berber',
  slogan: 'Centilmenliğin zamansız adresi',
  phone: '0216 444 02 12',
  phoneClean: '902164440212',
  whatsapp: '905334442212',
  email: 'turgut@gentlemansbarber.com',
  address: 'Bağdat Cad. No:212/B, Suadiye, Kadıköy/İstanbul',
  city: 'İstanbul',
  district: 'Kadıköy',
  neighborhood: 'Suadiye',
  coordinates: { lat: 40.9634, lng: 29.0831 },
  socialMedia: { instagram: 'https://instagram.com/gentlemansbarber.suadiye' },
  photos: [],
  foundedYear: 2012,
  experience: '20+ yıl tecrübe',
  customerCount: '6.000+',
  rating: 4.8,
  reviewCount: 420,
  services: [
    {
      id: 's1',
      name: 'Saç Kesimi & Yıkama',
      price: '800 TL',
      duration: '40 dk',
      description: 'Saç yıkama, kafa derisi masajı, uzman saç kesimi ve şekillendirme.',
    },
    {
      id: 's2',
      name: 'Klasik Sakal Tıraşı',
      price: '500 TL',
      duration: '25 dk',
      description: 'Sakalın sıcak buhar eşliğinde yumuşatılması ve usta işi ustura kesimi.',
    },
    {
      id: 's3',
      name: 'Çocuk Saç Kesimi',
      price: '550 TL',
      duration: '30 dk',
      description: '12 yaş altı çocuklar için sabırlı, eğlenceli ve şık kesim seansı.',
    },
    {
      id: 's4',
      name: 'Saç Boyama & Kamuflaj',
      price: '1.100 TL',
      duration: '50 dk',
      description: 'Beyaz saçları kırmadan, doğal tonlarda kamuflaj ve saç boyama.',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '09:00', close: '21:00', isOpen: true },
    { day: 'Salı', open: '09:00', close: '21:00', isOpen: true },
    { day: 'Çarşamba', open: '09:00', close: '21:00', isOpen: true },
    { day: 'Perşembe', open: '09:00', close: '21:00', isOpen: true },
    { day: 'Cuma', open: '09:00', close: '21:00', isOpen: true },
    { day: 'Cumartesi', open: '09:00', close: '20:00', isOpen: true },
    { day: 'Pazar', open: null, close: null, isOpen: false },
  ],
} as unknown as BusinessData

export const BERBER_GENTLEMAN_CONFIG = {
  id: 'berber-gentleman',
  name: 'Gentleman',
  sectorId: 'berber',
  plan: 'pro',
  description: 'Klasik ingiliz berberi esintili tasarım',
  designPhilosophy: 'Orman yeşili detaylar, asil yazı tipleri ve şık centilmen atmosferi',
  isDark: true,
  cssVariables: BERBER_GENTLEMAN_CSS,
  fonts: {
    heading: {
      family: 'Playfair Display',
      weights: [600, 700],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'BarberShop',
  sectorSections: ['before_after', 'booking'],
  performanceBudget: {
    maxJS: '100kb',
    maxLCP: '2.5s',
    animationLevel: 'framer-basic',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: BERBER_GENTLEMAN_BUSINESS.name },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Randevu', href: '#iletisim' },
        ],
        cta: { text: '0216 444 02 12', href: 'tel:902164440212', variant: 'outline' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'dark', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: BERBER_GENTLEMAN_BUSINESS.name,
        copyright: '© 2026 Gentleman\'s Choice Barber. Tüm hakları saklıdır.',
        contact: {
          phone: BERBER_GENTLEMAN_BUSINESS.phone,
          email: BERBER_GENTLEMAN_BUSINESS.email,
          address: BERBER_GENTLEMAN_BUSINESS.address,
        },
        social: [{ platform: 'instagram', url: 'https://instagram.com/gentlemansbarber.suadiye', icon: 'instagram' }],
        legal: [
          { label: 'Kullanım Koşulları', href: '/sartlar' },
          { label: 'KVKK Bilgilendirme', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1000, removable: false, animation: 'none' },
      defaultContent: { phone: '905334442212', message: 'Merhaba, saç sakal tıraşı için randevu almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${BERBER_GENTLEMAN_BUSINESS.name} — Kadıköy Klasik Berber`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_asymmetric_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'CENTİLMENLİK RİTÜELİ',
            title: BERBER_GENTLEMAN_BUSINESS.name,
            subtitle: BERBER_GENTLEMAN_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Alt Başlık / Açıklama', type: 'richtext' },
          ],
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_asymmetric_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: {
            badge: 'ZAMANSIZ SEÇİM',
            title: 'Kuşaktan Kuşağa Tıraş Geleneği',
          },
          editableFields: [
            { path: 'badge', label: 'Küçük Rozet', type: 'text' },
            { path: 'title', label: 'Galeri Bölüm Başlığı', type: 'text' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_asymmetric_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'HİZMETLERİMİZ',
            title: 'Centilmenin Bakım Kartı',
          },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_asymmetric_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'RANDEVU ALIN',
            title: 'Koltuktaki Yerinizi Ayırın',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
