import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const OZELDERS_SINIF_BUSINESS: BusinessData = {
  name: 'Sinif Egitim',
  ownerName: 'Ogr. Baris Sinif',
  sectorId: 'ozelders',
  slogan: 'Sinif ici destek',
  phone: '0536 100 55 66',
  phoneClean: '905361005566',
  whatsapp: '905361005566',
  email: 'destek@sinifegitim.com',
  address: 'Halaskargazi Cad. No:30, Sisli, Istanbul',
  city: 'Istanbul',
  district: 'Sisli',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"09:00","close":"21:00"},{"day":"tuesday","dayTr":"Sali","open":"09:00","close":"21:00"},{"day":"wednesday","dayTr":"Carsamba","open":"09:00","close":"21:00"},{"day":"thursday","dayTr":"Persembe","open":"09:00","close":"21:00"},{"day":"friday","dayTr":"Cuma","open":"09:00","close":"21:00"},{"day":"saturday","dayTr":"Cumartesi","open":"09:00","close":"21:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/ozelders-sinif"},
  photos: [],
  services: []
}
export const OZELDERS_SINIF_CONFIG: ThemeConfig = { id: 'ozelders-sinif', name: 'Sınıf & Butik Ders', sectorId: 'ozelders', plan: 'pro', isDark: true, cssVariables: { '--color-bg': '#FFFFFF', '--color-surface': '#F8FAFC', '--color-text': '#0F172A', '--color-accent': '#EC4899',
    '--color-accent-light': '#2e2e1f',
    '--color-accent-hover': '#8f8d14',
    '--color-accent-active': '#7d7b12', '--color-text-on-accent': '#FFFFFF', '--color-border': '#E2E8F0', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif" }, fonts: { heading: { family: 'Inter', weights: [700] }, body: { family: 'Inter', weights: [400] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Sinif Egitim' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Sinif Egitim',
        copyright: '© 2026 Sinif Egitim',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'Sınıf & Butik Ders Anasayfa', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'xl', containerWidth: 'xl', visible: true }, defaultContent: { badge: 'SINIF & BUTIK DERS', title: 'Profesyonel Sınıf & Butik Ders Hizmetleri' } } ] }] }