/**
 * @kepenk/templates — tesisatci-kombi Theme Configuration
 *
 * Kombi ve isitma sistemleri servisi
 * Plan: starter (6 page sections, 4 global sections)
 * Font: Poppins/Inter | Accent: #DC2626
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const TESISATCI_KOMBI_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#DC2626',
  '--color-accent-hover': '#DC2626',
  '--color-accent-active': '#DC2626',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'Poppins\', sans-serif',
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const TESISATCI_KOMBI_BUSINESS = {
  name: 'Isi Merkezi Kombi Servis',
  ownerName: 'Osman Yildiz',
  sectorId: 'Tesisatci',
  slogan: 'Sicak yuvaniz icin guvenilir kombi servisi',
  phone: '0212 456 78 12',
  phoneClean: '902124567812',
  whatsapp: '905431234567',
  email: 'info@isimerkezi.com',
  address: 'Cihangir Mah. Siraselviler Cad. No:88, Beyoglu/Istanbul',
  city: 'Istanbul',
  district: 'Beyoglu',
  mapEmbed: '',
  foundedYear: 2007,
  experience: '19 yil',
  employeeCount: 6,
  customerCount: '25.000+',
  rating: 4.8,
  reviewCount: 1850,
  workingHours: [
    {
      day: 'Pazartesi',
      dayTr: 'Pazartesi',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      dayTr: 'Sali',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      dayTr: 'Carsamba',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      dayTr: 'Persembe',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      dayTr: 'Cuma',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      dayTr: 'Cumartesi',
      open: '09:00',
      close: '17:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      dayTr: 'Pazar',
      open: '10:00',
      close: '15:00',
      isOpen: true,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Kombi Bakimi',
      price: '600-1.000 TL',
      duration: '1 saat',
      description: 'Yillik zorunlu kombi bakimi. Eşanjör temizligi, gaz ayari, baca gazi analizi, emniyet valf kontrolu ve performans testi. Tum marka komبilere.',
      icon: 'Flame',
    },
    {
      id: 's2',
      name: 'Kombi Ariza Onarimi',
      price: '300-1.500 TL',
      duration: '1-3 saat',
      description: 'Her marka ve model kombi ariza tespiti ve onarimi. Kart tamiri, fan motoru, 3 yollu vana, esanjor ve pompa degisimi.',
      icon: 'Wrench',
    },
    {
      id: 's3',
      name: 'Kombi Montaji',
      price: '1.500-3.000 TL',
      duration: 'Yarim gun',
      description: 'Yeni kombi montaji veya eski kombi degisimi. Baca ve gaz baglantisi, tesisat uyumluluk kontrolu dahil. Tum markalar.',
      icon: 'Settings',
    },
    {
      id: 's4',
      name: 'Petek Temizligi',
      price: '150-250 TL/adet',
      duration: '30 dk/adet',
      description: 'Basincli su ve kimyasal yıkama ile petek temizligi. Isitma performansinizi %30\'a kadar artirin.',
      icon: 'Thermometer',
    },
    {
      id: 's5',
      name: 'Yerden Isitma Bakimi',
      price: '800-2.000 TL',
      duration: '2-4 saat',
      description: 'Yerden isitma sistemi basinclandirma, temizleme ve ariza tespiti. Manifold, termostat ve pompa kontrolleri.',
      icon: 'Layers',
    },
    {
      id: 's6',
      name: 'Dogalgaz Tesisat',
      price: '1.000-4.000 TL',
      duration: '1-2 gun',
      description: 'Yeni dogalgaz hatti cekme, tesisat yenileme ve gaz kacagi onarimi. IGDAS projelendirme ve onay sureci dahil.',
      icon: 'Zap',
    },
  ],
  team: [
    {
      name: 'Osman Yildiz',
      title: 'Kurucu & Bas Teknisyen',
      description: '19 yillik kombi servis deneyimi. Bosch, Vaillant, Baymak ve Demirdokum yetkili servis sertifikali.',
      image: '',
    },
    {
      name: 'Erhan Sahin',
      title: 'Kombi Teknisyeni',
      description: '12 yillik deneyim. Yogusмali kombi ve yerden isitma sistemleri uzmani. Tum markalar.',
      image: '',
    },
  ],
  testimonials: [
    {
      name: 'Aysegul D.',
      location: 'Cihangir',
      date: '2025-11',
      rating: 5,
      comment: 'Kombim gece bozuldu, sabah ilk is geldiler. Eşanjör degisimi yapildi, ayni gun sicak su geldi. Cok hizli ve guvenilir.',
    },
    {
      name: 'Burak T.',
      location: 'Beyoglu',
      date: '2025-09',
      rating: 5,
      comment: 'Yillik bakim yaptirdim, kombi sanki yenilendi. Baca gazi analizi bile yapiyorlar, guvenligi elden birakmiyorlar.',
    },
    {
      name: 'Nurcan A.',
      location: 'Taksim',
      date: '2025-07',
      rating: 4,
      comment: 'Petek temizligi yaptirdim, 6 petegi yarim gunde bitirdiler. Isitma farkini hemen hissettim, odalar cok daha hizli isiniyor.',
    },
  ],
  gallery: [],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const TESISATCI_KOMBI_CONFIG = {
  id: 'tesisatci-kombi',
  name: 'Kombi',
  sectorId: 'tesisatci',
  plan: 'starter',
  description: 'Kombi ve isitma sistemleri servisi',
  designPhilosophy: 'Profesyonel, sicak, guvenilir',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#DC2626',
    '--color-accent-hover': '#DC2626',
    '--color-accent-active': '#DC2626',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'Poppins\', sans-serif',
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Poppins',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'Plumber',
  sectorSections: [],
  performanceBudget: {
    maxJS: '120kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-basic',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Isi Merkezi Kombi Servis' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905431234567',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Isi Merkezi Kombi Servis',
        copyright: '© 2026 Isi Merkezi Kombi Servis',
        contact: {
          phone: '0212 456 78 12',
          email: 'info@isimerkezi.com',
          address: 'Cihangir Mah. Siraselviler Cad. No:88, Beyoglu/Istanbul',
        },
        social: [],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905431234567', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Isi Merkezi Kombi Servis — Beyoglu',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: TESISATCI_KOMBI_BUSINESS.name, subtitle: TESISATCI_KOMBI_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
