/**
 * @kepenk/templates — dis-cocuk Theme Configuration
 *
 * Cocuk dis klinigi, eglenceli ve renkli
 * Plan: starter (6 page sections, 4 global sections)
 * Font: Quicksand/Nunito | Accent: #E67E22
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const DIS_COCUK_CSS: Record<string, string> = {
  '--container-default': '960px',
  '--section-py': '64px',
  '--radius-md': '16px',
  '--radius-lg': '32px',
  '--color-bg': '#FFFAFA',
  '--color-surface': '#FFF0F0',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#FFE4E4',
  '--color-text': '#4A3B3B',
  '--color-text-secondary': '#7A6B6B',
  '--color-text-muted': '#B3A1A1',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#E67E22',
  '--color-accent-hover': '#E67E22',
  '--color-accent-active': '#E67E22',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#FFD6D6',
  '--color-border-subtle': '#FFF0F0',
  '--font-heading': '\'Quicksand\', sans-serif',
  '--font-body': '\'Nunito\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const DIS_COCUK_BUSINESS = {
  name: 'Minidis Cocuk Dis Klinigi',
  ownerName: 'Ozlem Sahin',
  sectorId: 'Dis',
  slogan: 'Kucuk gulucukler icin buyuk ozen',
  phone: '0216 520 33 44',
  phoneClean: '902165203344',
  whatsapp: '905451234567',
  email: 'merhaba@minidis.com.tr',
  address: 'Goztepe Mah. Bagdat Cad. No:220/A, Kadikoy/Istanbul',
  city: 'Istanbul',
  district: 'Kadikoy',
  neighborhood: 'Goztepe',
  coordinates: { lat: 40.9741, lng: 29.0561 },
  socialMedia: { instagram: 'https://instagram.com/minidisklinik', youtube: 'https://youtube.com/@minidis' },
  photos: [],
  foundedYear: 2016,
  experience: '10 yil',
  customerCount: '12.000+',
  rating: 4.9,
  reviewCount: 890,
  services: [
    {
      id: 's1',
      name: 'Cocuk Dis Muayenesi',
      price: '400 TL',
      duration: '30 dk',
      description: 'Oyun ortaminda yapilan cocuk dostu dis muayenesi. Curuk risk analizi, dis sayimi ve florid uygulama onerisi.',
    },
    {
      id: 's2',
      name: 'Fissur Ortucu',
      price: '500 TL/dis',
      duration: '15 dk',
      description: 'Cocuklarin arka dislerindeki oluklarin koruyucu materyal ile kapatilmasi. Curuk olusumunu %80 azaltir.',
    },
    {
      id: 's3',
      name: 'Sut Disi Dolgusu',
      price: '700 TL',
      duration: '20-30 dk',
      description: 'Curuklu sut dislerinin renkli veya beyaz dolgu ile tedavisi. Cocugun dikkatini dagitan eglenceli ortam.',
    },
    {
      id: 's4',
      name: 'Yer Tutucu Uygulamasi',
      price: '1.200 TL',
      duration: '20 dk',
      description: 'Erken cekilen sut dislerinin yerini daimi dislere kadar korumak icin uygulanan aparey.',
    },
    {
      id: 's5',
      name: 'Sedasyon Altinda Tedavi',
      price: '3.500 TL + tedavi',
      duration: '60-120 dk',
      description: 'Dis korkusu yuksek veya cok kucuk cocuklarda bilinçli sedasyon altında tum tedavilerin tek seansta yapilmasi.',
    },
    {
      id: 's6',
      name: 'Florid (Flor) Uygulamasi',
      price: '350 TL',
      duration: '10 dk',
      description: 'Dis minesini guclendiren ve curuge karsi koruma saglayan profesyonel flor jeli uygulamasi. 6 ayda bir onerilir.',
    },
  ],
  team: [
    {
      name: 'Dt. Ozlem Sahin',
      title: 'Kurucu | Pedodonti Uzmani',
      bio: 'Marmara Universitesi Dishekimligi, Pedodonti Uzmanligi. 10 yildir sadece cocuk dis sagligi alaninda calisiyor.',
      photo: '',
    },
    {
      name: 'Dt. Baris Yalcin',
      title: 'Pedodonti Uzmani',
      bio: 'Hacettepe Universitesi Pedodonti. Ozel gereksinimli cocuklarin dis tedavisinde uzman.',
      photo: '',
    },
  ],
  workingHours: [
    {
      day: 'Pazartesi',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '10:00',
      close: '15:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: null,
      close: null,
      isOpen: false,
    },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const DIS_COCUK_CONFIG = {
  id: 'dis-cocuk',
  name: 'Cocuk',
  sectorId: 'dis',
  plan: 'starter',
  description: 'Cocuk dis klinigi, eglenceli ve renkli',
  designPhilosophy: 'Canli, samimi, cocuk dostu',
  isDark: false,
  cssVariables: {
    '--container-default': '960px',
    '--section-py': '64px',
    '--radius-md': '16px',
    '--radius-lg': '32px',
    '--color-bg': '#FFFAFA',
    '--color-surface': '#FFF0F0',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#FFE4E4',
    '--color-text': '#4A3B3B',
    '--color-text-secondary': '#7A6B6B',
    '--color-text-muted': '#B3A1A1',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#E67E22',
    '--color-accent-hover': '#E67E22',
    '--color-accent-active': '#E67E22',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#FFD6D6',
    '--color-border-subtle': '#FFF0F0',
    '--font-heading': '\'Quicksand\', sans-serif',
    '--font-body': '\'Nunito\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Quicksand',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Nunito',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'Dentist',
  sectorSections: ['smile_gallery', 'fear_reducer', 'technology_showcase'],
  performanceBudget: {
    maxJS: '120kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-basic',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Minidis Cocuk Dis Klinigi' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905451234567',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Minidis Cocuk Dis Klinigi',
        copyright: '© 2026 Minidis Cocuk Dis Klinigi',
        contact: {
          phone: '0216 520 33 44',
          email: 'merhaba@minidis.com.tr',
          address: 'Goztepe Mah. Bagdat Cad. No:220/A, Kadikoy/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/minidisklinik',
            icon: 'instagram',
          },
          {
            platform: 'youtube',
            url: 'https://youtube.com/@minidis',
            icon: 'youtube',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905451234567', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Minidis Cocuk Dis Klinigi — Kadikoy',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: DIS_COCUK_BUSINESS.name, subtitle: DIS_COCUK_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
