import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const OTO_MEKANIK_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '4px',
  '--radius-lg': '8px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F9F9F9',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F0F0F0',
  '--color-text': '#111111',
  '--color-text-secondary': '#666666',
  '--color-text-muted': '#999999',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#000000',
  '--color-accent-hover': '#222222',
  '--color-accent-active': '#444444',
  '--color-accent-light': '#F5F5F5',
  '--color-border': '#E5E2DB',
  '--color-border-subtle': '#F0F0F0',
  '--font-heading': "'Inter', sans-serif",
  '--font-body': "'Inter', sans-serif",
}

export const OTO_MEKANIK_BUSINESS = {
  name: 'Akademi Ağır Motor Onarım',
  ownerName: 'Yavuz Usta',
  sectorId: 'Oto',
  slogan: 'Motor ve şanzıman rektifiyesinde usta işi çözümler',
  phone: '0212 555 12 17',
  phoneClean: '902125551217',
  whatsapp: '905355551217',
  email: 'iletisim@akademiotomotor.com',
  address: 'Bağcılar Güngören Sanayi Sitesi 14. Blok No:18, Güngören/İstanbul',
  city: 'İstanbul',
  district: 'Güngören',
  neighborhood: 'Bağcılar Güngören Sanayi',
  coordinates: { lat: 41.0265, lng: 28.8712 },
  socialMedia: { instagram: 'https://instagram.com/akademiotomotor' },
  photos: [],
  foundedYear: 2011,
  experience: '13 yıldır',
  customerCount: '5.200+',
  rating: 4.7,
  reviewCount: 450,
  services: [
    {
      id: 's1',
      name: 'Komple Motor Rektifiyesi',
      price: 'Fiyat tespiti sonrası',
      duration: '3-5 gün',
      description: 'Motor bloku, silindir kapağı ve krank mili onarımı. Segman ve piston yenilemesi ile sıfır motor ayarı.',
    },
    {
      id: 's2',
      name: 'Manuel/Otomatik Şanzıman Onarımı',
      price: '4.000 TL\'den başlayan',
      duration: '1-2 gün',
      description: 'Dişli grubu, senkromeç değişimi, kavrama ve baskı balata set montajı, şanzıman yağı revizyonu.',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Salı', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Çarşamba', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Perşembe', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Cuma', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Cumartesi', open: '08:30', close: '15:00', isOpen: true },
    { day: 'Pazar', open: null, close: null, isOpen: false },
  ],
} as unknown as BusinessData

export const OTO_MEKANIK_CONFIG = {
  id: 'oto-mekanik',
  name: 'Mekanik',
  sectorId: 'oto',
  plan: 'free',
  description: 'Oto ağır motor tamiri ve şanzıman rektifiyesi odaklı düz sade şablon',
  designPhilosophy: 'Yalın monokrom tasarım, siyah-beyaz netlik ve mekanik şema okunabilirliği',
  isDark: false,
  cssVariables: OTO_MEKANIK_CSS,
  fonts: {
    heading: {
      family: 'Inter',
      weights: [600, 700],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'AutoRepair',
  sectorSections: ['vehicle_brands', 'warranty_badge', 'service_area'],
  performanceBudget: {
    maxJS: '50kb',
    maxLCP: '2.0s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: OTO_MEKANIK_BUSINESS.name },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: { text: 'Arayın', href: 'tel:902125551217', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'default', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: OTO_MEKANIK_BUSINESS.name,
        copyright: '© 2026 Akademi Ağır Motor Onarım. Tüm hakları saklıdır.',
        contact: {
          phone: OTO_MEKANIK_BUSINESS.phone,
          email: OTO_MEKANIK_BUSINESS.email,
          address: OTO_MEKANIK_BUSINESS.address,
        },
        social: [],
        legal: [{ label: 'TSE KVKK', href: '/kvkk' }],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${OTO_MEKANIK_BUSINESS.name} — Güngören Garantili Motor Rektifiyesi`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'HEAVY MOTOR REPAIR',
            title: OTO_MEKANIK_BUSINESS.name,
            subtitle: OTO_MEKANIK_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Eski Kurdele Yazısı', type: 'text' },
            { path: 'title', label: 'Dükkan Adı', type: 'text' },
            { path: 'subtitle', label: 'Slogan / Alt Metin', type: 'richtext' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 2,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'MOTOR HİZMETLERİ',
            title: 'Net ve Detaylı Mekanik Kartımız',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'Servis Menüsü Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 3,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'SANAYİ KONUMU',
            title: 'Usta Güvencesiyle Gelin',
          },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
