/**
 * @kepenk/templates — lastikci-yaz Theme Configuration
 *
 * Mahalle lastikçisi, yaz/kis lastik degisimi
 * Plan: free (3 page sections, 3 global sections)
 * Font: Inter/Inter | Accent: #D84315
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const LASTIKCI_YAZ_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#D84315',
  '--color-accent-hover': '#D84315',
  '--color-accent-active': '#D84315',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': "'Raleway', sans-serif",
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const LASTIKCI_YAZ_BUSINESS = {
  name: 'Anadolu Lastik Servisi',
  ownerName: 'Cengiz Yilmaz',
  sectorId: 'Lastikci',
  slogan: 'Guvenli yolculugun ilk adimi',
  phone: '0532 871 42 60',
  phoneClean: '905328714260',
  whatsapp: '905328714260',
  email: 'info@anadolulastik.com',
  address: 'Kozyatagi Mah. Bostanci Yolu Cad. No:58, Kadikoy/Istanbul',
  city: 'Istanbul',
  district: 'Kadikoy',
  neighborhood: 'Kozyatagi',
  coordinates: { lat: 40.9722, lng: 29.0798 },
  socialMedia: { instagram: 'https://instagram.com/anadolulastik' },
  photos: [],
  foundedYear: 2010,
  experience: '16 yil',
  customerCount: '20.000+',
  rating: 4.6,
  reviewCount: 580,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '08:30',
      close: '17:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '00:00',
      close: '00:00',
      isOpen: false,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Lastik Degisimi (4 Adet)',
      price: '400 TL',
      duration: '30 dk',
      description: 'Yaz/kis lastik degisimi, balans ayari dahil.',
    },
    {
      id: 's2',
      name: 'Lastik Tamiri (Yama)',
      price: '150 TL',
      duration: '15 dk',
      description: 'Civi, vida gibi delinmelerde profesyonel yama tamiri.',
    },
    {
      id: 's3',
      name: 'Rot Balans',
      price: '300 TL',
      duration: '20 dk',
      description: '4 lastik balans ayari, titresim ve asimetrik asinma onleme.',
    },
    {
      id: 's4',
      name: 'Lastik Otel (Sezonluk)',
      price: '200 TL/set',
      duration: 'sezonluk',
      description: 'Yaz veya kis lastiklerinizi uygun kosullarda sakliyoruz.',
    },
  ],
  team: [],
  testimonials: [],
  faq: [
    { q: 'Lastik degisimi ne kadar suruyor?', a: '4 lastik degisimi ortalama 30 dakika surmektedir. Yogun sezonlarda bekleme olabilir, randevu almanizi oneririz.' },
    { q: 'Kis lastigine ne zaman gecmeliyim?', a: 'Hava sicakligi duzenli olarak 7°C\'nin altina dustugunde kis lastigine gecmenizi oneririz. Istanbul icin genellikle Kasim ortasi idealdir.' },
    { q: 'Lastik otel hizmeti nasil calisiyor?', a: 'Sezonluk lastiklerinizi numarali etiketle depomuzda sakliyoruz. Degisim zamani geldiginde sizi arariz.' },
    { q: 'Hangi marka lastikler satiyorsunuz?', a: 'Michelin, Bridgestone, Goodyear, Pirelli, Lassa ve Continental gibi markalarin genis urun yelpazesi mevcuttur.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const LASTIKCI_YAZ_CONFIG = {
  id: 'lastikci-yaz',
  name: 'Yaz',
  sectorId: 'lastikci',
  plan: 'free',
  description: 'Mahalle lastikçisi, yaz/kis lastik degisimi',
  designPhilosophy: 'Sade, guvenilir, islevsel',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#D84315',
    '--color-accent-hover': '#D84315',
    '--color-accent-active': '#D84315',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': "'Raleway', sans-serif",
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Raleway',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'TireShop',
  sectorSections: [],
  performanceBudget: {
    maxJS: '80kb',
    maxLCP: '3.0s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Anadolu Lastik Servisi' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905328714260',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Anadolu Lastik Servisi',
        copyright: '© 2026 Anadolu Lastik Servisi',
        contact: {
          phone: '0532 871 42 60',
          email: 'info@anadolulastik.com',
          address: 'Kozyatagi Mah. Bostanci Yolu Cad. No:58, Kadikoy/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/anadolulastik',
            icon: 'instagram',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905328714260', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Anadolu Lastik Servisi — Kadikoy',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: LASTIKCI_YAZ_BUSINESS.name, subtitle: LASTIKCI_YAZ_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
