import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const RESTORAN_TABLEDOT_CSS: Record<string, string> = {
  '--container-default': '1120px',
  '--section-py': '80px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#2563EB',
  '--color-accent-hover': '#1D4ED8',
  '--color-accent-active': '#1E40AF',
  '--color-accent-light': '#DBEAFE',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': "'Plus Jakarta Sans', sans-serif",
  '--font-body': "'Plus Jakarta Sans', sans-serif",
}

export const RESTORAN_TABLEDOT_BUSINESS = {
  name: 'Plaza Gurme Tabildot & Catering',
  ownerName: 'Burak Şahin',
  sectorId: 'Restoran',
  slogan: 'İş yerleri ve plazalar için kaliteli, hijyenik tabildot menü',
  phone: '0212 555 12 19',
  phoneClean: '902125551219',
  whatsapp: '905325551219',
  email: 'iletisim@plazagurmetabildot.com',
  address: 'Maslak Plaza Sanayi, G-3 Blok No:12, Şişli/İstanbul',
  city: 'İstanbul',
  district: 'Şişli',
  neighborhood: 'Maslak Plaza Sanayi',
  coordinates: { lat: 41.1145, lng: 29.0165 },
  socialMedia: { instagram: 'https://instagram.com/plazagurmetabildot' },
  photos: [],
  foundedYear: 2015,
  experience: '13 yıldır sanayi catering tecrübesi',
  customerCount: '150.000+ porsiyon/yıl',
  rating: 4.8,
  reviewCount: 520,
  services: [
    {
      id: 's1',
      name: 'Plaza 4 Kap Yemek Menüsü',
      price: '160 TL',
      duration: '15 dk',
      description: 'Günlük olarak değişen; Çorba, Ana Yemek, Yardımcı Yemek (Pilav/Makarna) ve Tatlı/Meyve/Yoğurt.',
    },
    {
      id: 's2',
      name: 'Kurumsal Catering Hizmeti (Kişi Başı)',
      price: 'Anlaşmaya göre',
      duration: 'Yıllık sözleşmeli',
      description: 'Ofis ve fabrikalarınız için sıcak/soğuk yemek taşıma, yerinde servis ve temizlik dahil catering çözümü.',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '08:00', close: '18:00', isOpen: true },
    { day: 'Salı', open: '08:00', close: '18:00', isOpen: true },
    { day: 'Çarşamba', open: '08:00', close: '18:00', isOpen: true },
    { day: 'Perşembe', open: '08:00', close: '18:00', isOpen: true },
    { day: 'Cuma', open: '08:00', close: '18:00', isOpen: true },
    { day: 'Cumartesi', open: '08:00', close: '14:00', isOpen: true },
    { day: 'Pazar', open: null, close: null, isOpen: false },
  ],
} as unknown as BusinessData

export const RESTORAN_TABLEDOT_CONFIG = {
  id: 'restoran-tabledot',
  name: 'Tabildot',
  sectorId: 'restoran',
  plan: 'starter',
  description: 'Hijyenik, kurumsal, plaza ve sanayi tabildot yemek servisi odaklı net tasarım',
  designPhilosophy: 'Güven veren temiz mavi vurgular, okunaklı modern sans-serif Plus Jakarta tipografisi',
  isDark: false,
  cssVariables: RESTORAN_TABLEDOT_CSS,
  fonts: {
    heading: {
      family: 'Plus Jakarta Sans',
      weights: [600, 700],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Plus Jakarta Sans',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'Restaurant',
  sectorSections: ['menu_display', 'daily_special', 'reservation'],
  performanceBudget: {
    maxJS: '70kb',
    maxLCP: '2.8s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: RESTORAN_TABLEDOT_BUSINESS.name },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: { text: 'WhatsApp', href: 'https://wa.me/905325551219', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'dark', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: RESTORAN_TABLEDOT_BUSINESS.name,
        copyright: '© 2026 Plaza Gurme Tabildot & Catering. Tüm hakları saklıdır.',
        contact: {
          phone: RESTORAN_TABLEDOT_BUSINESS.phone,
          email: RESTORAN_TABLEDOT_BUSINESS.email,
          address: RESTORAN_TABLEDOT_BUSINESS.address,
        },
        social: [{ platform: 'instagram', url: 'https://instagram.com/plazagurmetabildot', icon: 'instagram' }],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1000, removable: false, animation: 'none' },
      defaultContent: { phone: '905325551219', message: 'Tabildot menü alımı ve catering hizmetleriniz için teklif almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${RESTORAN_TABLEDOT_BUSINESS.name} — Maslak Kurumsal Taşıma Yemek`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'ISO 22000 HİJYEN BELGELİ',
            title: RESTORAN_TABLEDOT_BUSINESS.name,
            subtitle: RESTORAN_TABLEDOT_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Eski Kurdele Yazısı', type: 'text' },
            { path: 'title', label: 'Dükkan Adı', type: 'text' },
            { path: 'subtitle', label: 'Slogan / Alt Metin', type: 'richtext' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 2,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'CATERING HİZMETLERİ',
            title: 'Hijyenik ve Ekonomik Tabildot Seçeneği',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'Servis Menüsü Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 3,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'ULAŞIM VE DETAYLAR',
            title: 'Merkez Mutfağımızın Konumu',
          },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
