/**
 * @kepenk/templates — fitness-pilates Theme Configuration
 *
 * Reformer pilates studyosu, premium
 * Plan: pro (11 page sections, 4 global sections)
 * Font: Cormorant Garamond/Lato | Accent: #C07A58
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const FITNESS_PILATES_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#C07A58',
  '--color-accent-hover': '#C07A58',
  '--color-accent-active': '#C07A58',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'Cormorant Garamond\', sans-serif',
  '--font-body': '\'Lato\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const FITNESS_PILATES_BUSINESS = {
  name: 'Studio B Pilates',
  ownerName: 'Basak Taner',
  sectorId: 'Fitness',
  slogan: 'Bedeninizi dinleyin, gucunuzu hissedin',
  phone: '0535 248 71 30',
  phoneClean: '905352487130',
  whatsapp: '905352487130',
  email: 'info@studiobpilates.com',
  address: 'Fenerbahce Mah. Bagdat Cad. No:245/3, Kadikoy/Istanbul',
  city: 'Istanbul',
  district: 'Kadikoy',
  neighborhood: 'Fenerbahce',
  coordinates: { lat: 40.9715, lng: 29.0482 },
  socialMedia: {
    instagram: 'https://instagram.com/studiobpilates',
    facebook: 'https://facebook.com/studiobpilates',
    youtube: 'https://youtube.com/@studiobpilates',
    tiktok: 'https://tiktok.com/@studiobpilates',
  },
  photos: [],
  foundedYear: 2016,
  experience: '10 yil',
  customerCount: '9.500+',
  rating: 4.9,
  reviewCount: 1350,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '07:00',
      close: '21:30',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '07:00',
      close: '21:30',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '07:00',
      close: '21:30',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '07:00',
      close: '21:30',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '07:00',
      close: '21:30',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '08:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '09:00',
      close: '15:00',
      isOpen: true,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Reformer Pilates (Grup)',
      price: '450 TL/ders',
      duration: '55 dk',
      description: 'Maksimum 6 kisilik siniflarda reformer uzerinde pilates. Kor guclenme, esneklik ve durus duzeltme.',
    },
    {
      id: 's2',
      name: 'Reformer Pilates (Ozel)',
      price: '900 TL/ders',
      duration: '55 dk',
      description: 'Birebir reformer calismasi. Ozel ihtiyaclara, sakatlik rehabilitasyonuna uygun program.',
    },
    {
      id: 's3',
      name: 'Mat Pilates',
      price: '300 TL/ders',
      duration: '50 dk',
      description: 'Kucuk ekipmanlarla mat uzerinde pilates. Kor guclenme ve esneklik odakli.',
    },
    {
      id: 's4',
      name: 'Barre Pilates',
      price: '400 TL/ders',
      duration: '55 dk',
      description: 'Bale barri, pilates ve yoga bilesimmi. Uzun, ince kas yapisi icin.',
    },
    {
      id: 's5',
      name: 'Prenatal Pilates',
      price: '500 TL/ders',
      duration: '45 dk',
      description: 'Hamilelikte guvenli pilates. Pelvik taban guclenme, sirt agrisi onleme.',
    },
    {
      id: 's6',
      name: 'Postnatal Pilates',
      price: '500 TL/ders',
      duration: '45 dk',
      description: 'Dogum sonrasi toparlanma programi. Karin ve pelvik taban rehabilitasyonu.',
    },
    {
      id: 's7',
      name: 'Skolyoz/Durus Duzeltme',
      price: '800 TL/ders',
      duration: '55 dk',
      description: 'BASI pilates metoduyla skolyoz ve durus bozukluklarina ozel birebir program.',
    },
    {
      id: 's8',
      name: 'Cadillac/Tower Calismasi',
      price: '700 TL/ders',
      duration: '55 dk',
      description: 'Cadillac ve tower ekipmanlariyla ileri pilates. Omurga mobilizasyonu ve guclenme.',
    },
    {
      id: 's9',
      name: 'Pilates + Beslenme Paketi',
      price: '4.500 TL/ay',
      duration: 'degisken',
      description: 'Hafta 3 reformer ders + aylik beslenme programi + vucut analizi.',
    },
    {
      id: 's10',
      name: '10\'lu Kart (Reformer Grup)',
      price: '4.000 TL',
      duration: '55 dk',
      description: '10 ders iceren kart, 3 ay gecerlilik. Ucretsiz vucut analizi dahil.',
    },
    {
      id: 's11',
      name: 'Aylik Sinitsiz (Reformer)',
      price: '5.500 TL/ay',
      duration: 'sinitsiz',
      description: 'Tum reformer grup derslerine sinitsiz katilim. Oncelikli rezervasyon hakki.',
    },
    {
      id: 's12',
      name: 'Corporate Wellness',
      price: 'Teklif uzerine',
      duration: 'degisken',
      description: 'Sirketler icin ofise veya studyoda grup pilates programlari.',
    },
    {
      id: 's13',
      name: 'Durus Analizi',
      price: '600 TL',
      duration: '30 dk',
      description: 'PostureScreen ile dijital durus analizi, kisisellestirilmis duzeltme programi onerisi.',
    },
    {
      id: 's14',
      name: 'Esneklik Degerlendirmesi',
      price: 'Ucretsiz',
      duration: '15 dk',
      description: 'Eklem hareket acikligi ve kas esnekligi olcumu. Ilk kayitta ucretsiz.',
    },
  ],
  team: [
    {
      name: 'Basak Taner',
      role: 'Kurucu & Master Egitmen',
      bio: 'Polestar Pilates diplomali. 15 yillik egitmenlik deneyimi. BASI pilates skolyoz sertifikali.',
    },
    {
      name: 'Yagmur Celik',
      role: 'Reformer & Barre Egitmeni',
      bio: 'Balanced Body sertifikali. Profesyonel bale gecmisli. 8 yillik pilates deneyimi.',
    },
    {
      name: 'Ece Sarikaya',
      role: 'Prenatal/Postnatal Uzman Egitmen',
      bio: 'Fizyoterapist ve pilates egitmeni. Hamileler ve dogum sonrasi icin ozel programlar.',
    },
    {
      name: 'Aylin Demirel',
      role: 'Mat & Tower Egitmeni',
      bio: 'STOTT Pilates sertifikali. Omurga sagligi ve rehabilitasyon odakli egitim.',
    },
    {
      name: 'Defne Akman',
      role: 'Beslenme Danismani',
      bio: 'Diyetisyen, sporcu beslenmesi uzmani. Pilates ile entegre beslenme programlari.',
    },
    {
      name: 'Cem Tezcan',
      role: 'Reformer Egitmeni',
      bio: 'Beden egitimi ogretmeni, Balanced Body sertifikali. Erkeklere ozel pilates programlari.',
    },
  ],
  testimonials: [
    {
      name: 'Fulya Ozcan',
      district: 'Fenerbahce',
      date: '2025-12',
      rating: 5,
      comment: '3 yildir Studio B\'ye geliyorum. Kronik bel agrim tamamen gecti, durus bozuklugum duzeldı. Basak Hocam\'in BASI metodu mucize gibi.',
    },
    {
      name: 'Sinem Arslan',
      district: 'Caddebostan',
      date: '2025-10',
      rating: 5,
      comment: 'Hamilelik boyunca prenatal pilates aldim, dogum cok kolay gecti. Ece Hocam tam bir uzman, her seansa ozel program yapiyor.',
    },
    {
      name: 'Melis Kaya',
      district: 'Bagdat Caddesi',
      date: '2025-11',
      rating: 5,
      comment: 'Barre pilates dersleri harika. Yagmur Hocam\'in bale gecmisi gercekten fark yaratiyor. Vucut sekillenmeleri gorulmeye basladi.',
    },
    {
      name: 'Hande Turk',
      district: 'Goztepe',
      date: '2025-08',
      rating: 5,
      comment: 'Aylik sinitsiz paket aldim, haftada 4-5 gun geliyorum. Her dersten sonra kendimi harika hissediyorum. Studyo cok temiz ve bakimli.',
    },
    {
      name: 'Kerem Sahin',
      district: 'Suadiye',
      date: '2025-09',
      rating: 4,
      comment: 'Erkek olarak reformer pilates baslama konusunda tereddutluyduum ama Cem Hoca harika motive ediyor. Sirt agrilarim azaldi, esnekligim artti.',
    },
    {
      name: 'Elif Demir',
      district: 'Bostanci',
      date: '2025-07',
      rating: 5,
      comment: 'Postnatal pilates ile dogumdan sonra 4 ayda eski formuma dondum. Pelvik taban egzersizleri cok onemliymis, keske daha once baslasamdim.',
    },
    {
      name: 'Cagla Polat',
      district: 'Erenkoy',
      date: '2025-06',
      rating: 5,
      comment: 'Corporate wellness kapsaminda ofisimize geliyorlar. 15 kisilik grubumuz var, masa basi calisanlari icin harika bir mola. Moral ve enerji artti.',
    },
    {
      name: 'Merve Yildiz',
      district: 'Kozyatagi',
      date: '2025-11',
      rating: 5,
      comment: 'Durus analizim yapildi, skolyozum varmis habersizmisim. 6 aylik ozel program ile omurgam duzelmeye basladi. Gercek bir farkindalik yaratiyor.',
    },
  ],
  faq: [
    { q: 'Reformer pilates ile mat pilates arasindaki fark nedir?', a: 'Reformer, yay direnciyle calisan ozel bir aletir. Mat pilatesden daha kontrollü ve farkli acilarda calismaya imkan tanir. Rehabilitasyon ve derin kor calismada reformer daha etkilidir.' },
    { q: 'Pilates kilo verdirir mi?', a: 'Pilates dogrudan yogun kalori yakmaz ancak kas tonusunu arttirir, metabolizmayi hizlandirir ve vucut sekillendirir. Beslenme programıyla birlikte uygulandiginda kilo vermede cok etkilidir.' },
    { q: 'Hamileyken ne zaman baslamaliyim?', a: 'Doktorunuzun onayi ile ikinci trimesterden (13. hafta) itibaren prenatal pilatese baslayabilirsiniz. Daha once pilates deneyiminiz varsa birinci trimesterde devam edebilirsiniz.' },
    { q: 'Bel fitigi olan pilates yapabilir mi?', a: 'Evet, doktor onayi ile reformer pilates bel fitigi rehabilitasyonunda cok etkilidir. Ozel ders formatinda, fizyoterapist egitmenimizle baslamanizi oneririz.' },
    { q: 'Siniflar kac kisilik?', a: 'Reformer grup dersleri maksimum 6 kisidir. Mat ve barre dersleri maksimum 10 kisidir. Bu sayede her ogrenciye bireysel ilgi gosterebiliyoruz.' },
    { q: 'Erkekler icin de uygun mu?', a: 'Kesinlikle! Erkek ogrencilerimizin sayisi giderek artiyor. Ozellikle sirt agrisi, esneklik ve core guclenme icin pilates cok etkilidir. Cem Hocamiz erkeklere ozel programlar uyguluyor.' },
    { q: 'Online ders var mi?', a: 'Mat pilates derslerimiz Zoom uzerinden de verilebilmektedir. Reformer dersler icin studyomuza gelmeniz gerekmektedir.' },
    { q: 'Nasil kayit olabilirim?', a: 'Telefon, WhatsApp veya Instagram DM uzerinden kayit olabilirsiniz. Ilk gelisinizde ucretsiz esneklik degerlendirmesi ve studyo turu yapiyoruz.' },
    { q: 'Iptal politikaniz nedir?', a: 'Dersten 6 saat oncesine kadar ucretsiz iptal veya erteleme yapabilirsiniz. Gec iptallerde ders hakkiniz duseru.' },
    { q: 'Hangi marka reformer kullaniyorsunuz?', a: 'Balanced Body marka reformer ve Cadillac ekipman kullaniyoruz. Tum aletlerimiz profesyonel sinif, duzenli bakim ve sterilizasyon yapilmaktadir.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const FITNESS_PILATES_CONFIG = {
  id: 'fitness-pilates',
  name: 'Pilates',
  sectorId: 'fitness',
  plan: 'pro',
  description: 'Reformer pilates studyosu, premium',
  designPhilosophy: 'Zarif, feminin, luks',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#C07A58',
    '--color-accent-hover': '#C07A58',
    '--color-accent-active': '#C07A58',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'Cormorant Garamond\', sans-serif',
    '--font-body': '\'Lato\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Cormorant Garamond',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Lato',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'HealthClub',
  sectorSections: ['class_schedule', 'membership_pricing', 'transformation'],
  performanceBudget: {
    maxJS: '250kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Studio B Pilates' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905352487130',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Studio B Pilates',
        copyright: '© 2026 Studio B Pilates',
        contact: {
          phone: '0535 248 71 30',
          email: 'info@studiobpilates.com',
          address: 'Fenerbahce Mah. Bagdat Cad. No:245/3, Kadikoy/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/studiobpilates',
            icon: 'instagram',
          },
          {
            platform: 'facebook',
            url: 'https://facebook.com/studiobpilates',
            icon: 'facebook',
          },
          {
            platform: 'youtube',
            url: 'https://youtube.com/@studiobpilates',
            icon: 'youtube',
          },
          {
            platform: 'tiktok',
            url: 'https://tiktok.com/@studiobpilates',
            icon: 'tiktok',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905352487130', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Studio B Pilates — Kadikoy',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: FITNESS_PILATES_BUSINESS.name, subtitle: FITNESS_PILATES_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
