import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const RESTORAN_SOFRA_CSS: Record<string, string> = {
  '--container-default': '960px',
  '--section-py': '64px',
  '--radius-md': '2px',
  '--radius-lg': '4px',
  '--color-bg': '#FAF8F5',
  '--color-surface': '#F5EFEB',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#EFECE6',
  '--color-text': '#1D1B19',
  '--color-text-secondary': '#5A5450',
  '--color-text-muted': '#968E89',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#FAF8F5',
  '--color-accent': '#8E2C1E',
  '--color-accent-hover': '#722014',
  '--color-accent-active': '#55150C',
  '--color-accent-light': '#FCEEEB',
  '--color-border': '#D6CFC9',
  '--color-border-subtle': '#EFECE6',
  '--font-heading': "'Cormorant Garamond', serif",
  '--font-body': "'Source Sans 3', sans-serif",
}

export const RESTORAN_SOFRA_BUSINESS = {
  name: 'Sofra Ev Yemekleri & Ev Sıcaklığı',
  ownerName: 'Ayşe Hanım',
  sectorId: 'Restoran',
  slogan: 'Anne eli değmiş gibi, günlük ve taptaze ev yemekleri',
  phone: '0216 333 01 18',
  phoneClean: '902163330118',
  whatsapp: '905353331118',
  email: 'iletisim@sofraevyemekleri.com',
  address: 'Moda Cad. No:62/B, Caferağa, Kadıköy/İstanbul',
  city: 'İstanbul',
  district: 'Kadıköy',
  neighborhood: 'Caferağa',
  coordinates: { lat: 40.9836, lng: 29.0271 },
  socialMedia: { instagram: 'https://instagram.com/sofraevyemekleri.moda' },
  photos: [],
  foundedYear: 2010,
  experience: '13 yıldır',
  customerCount: '15.000+',
  rating: 4.7,
  reviewCount: 420,
  services: [
    {
      id: 's1',
      name: 'Günün Ev Yemeği Menüsü',
      price: '220 TL',
      duration: '10 dk',
      description: 'Ana yemek (etli/sebzeli), çorba, pirinç pilavı veya makarna, cacık veya salata eşliğinde.',
    },
    {
      id: 's2',
      name: 'Zeytinyağlı Tabak Seçkisi',
      price: '180 TL',
      duration: '5 dk',
      description: 'Zeytinyağlı taze fasulye, barbunya, yaprak sarma ve imambayıldıdan oluşan hafif gurme tabağı.',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '08:30', close: '21:00', isOpen: true },
    { day: 'Salı', open: '08:30', close: '21:00', isOpen: true },
    { day: 'Çarşamba', open: '08:30', close: '21:00', isOpen: true },
    { day: 'Perşembe', open: '08:30', close: '21:00', isOpen: true },
    { day: 'Cuma', open: '08:30', close: '21:00', isOpen: true },
    { day: 'Cumartesi', open: '08:30', close: '20:00', isOpen: true },
    { day: 'Pazar', open: null, close: null, isOpen: false },
  ],
} as unknown as BusinessData

export const RESTORAN_SOFRA_CONFIG = {
  id: 'restoran-sofra',
  name: 'Sofra',
  sectorId: 'restoran',
  plan: 'free',
  description: 'Nostaljik, sıcak, esnaf lokantası ve mahalle ev yemekleri restoranı şablonu',
  designPhilosophy: 'Nostaljik bordo vurgular, yumuşak krem arka plan, samimi iştah açıcı düzen',
  isDark: false,
  cssVariables: RESTORAN_SOFRA_CSS,
  fonts: {
    heading: {
      family: 'Cormorant Garamond',
      weights: [600, 700],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Source Sans 3',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'Restaurant',
  sectorSections: ['menu_display', 'daily_special', 'reservation'],
  performanceBudget: {
    maxJS: '60kb',
    maxLCP: '2.5s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: RESTORAN_SOFRA_BUSINESS.name },
        menuItems: [
          { label: 'Hizmetlerimiz', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: { text: 'Arayın', href: 'tel:902163330118', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'dark', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: RESTORAN_SOFRA_BUSINESS.name,
        copyright: '© 2026 Sofra Ev Yemekleri & Ev Sıcaklığı. Tüm hakları saklıdır.',
        contact: {
          phone: RESTORAN_SOFRA_BUSINESS.phone,
          email: RESTORAN_SOFRA_BUSINESS.email,
          address: RESTORAN_SOFRA_BUSINESS.address,
        },
        social: [{ platform: 'instagram', url: 'https://instagram.com/sofraevyemekleri.moda', icon: 'instagram' }],
        legal: [{ label: 'KVKK Sözleşmesi', href: '/kvkk' }],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${RESTORAN_SOFRA_BUSINESS.name} — Moda Ev Sıcaklığında Lokanta`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'EST. 2010',
            title: RESTORAN_SOFRA_BUSINESS.name,
            subtitle: RESTORAN_SOFRA_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Eski Kurdele Yazısı', type: 'text' },
            { path: 'title', label: 'Dükkan Adı', type: 'text' },
            { path: 'subtitle', label: 'Slogan / Alt Metin', type: 'richtext' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 2,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'EV YEMEĞİ MENÜSÜ',
            title: 'Sıcak Yemek Seçeneklerimiz',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'Servis Menüsü Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 3,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'MAHALLE ADRESİMİZ',
            title: 'Sıcak Soframıza Yol Tarifi Alın',
          },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
