/**
 * @kepenk/templates — P0 Berber Themes (5 themes)
 */

import type { P0ThemeDef } from './p0-themes'

export const BERBER_THEMES: P0ThemeDef[] = [
  {
    id: 'berber-sade',
    name: 'Sade',
    sectorId: 'berber',
    plan: 'free',
    description: 'Ultra minimal berber teması. Siyah-beyaz, tek font, tek sayfa.',
    designPhilosophy: 'Az çoktur. Inter tek font — yükleme hızı maksimum. Siyah accent zamansız ve maskülen. Hiçbir dekoratif element yok, sadece bilgi.',
    isDark: false,
    fonts: {
      heading: { family: 'Inter', weights: [600, 700] },
      body: { family: 'Inter', weights: [400, 500] },
    },
    cssOverrides: {
      '--color-accent': '#1A1A1A',
      '--color-accent-hover': '#374151',
      '--color-accent-light': '#F3F4F6',
      '--font-heading': "'Inter', sans-serif",
      '--font-body': "'Inter', system-ui, sans-serif",
    },
    homeSections: ['hero::fullscreen_overlay', 'services::card_grid', 'about::split_left', 'working_hours::compact', 'map::full_width', 'contact::simple_form'],
    pages: ['home'],
    sectorSections: ['before_after', 'booking'],
    animationLevel: 'css-only',
    demoBusinessKey: 'sade',
  },
  {
    id: 'berber-klasik',
    name: 'Klasik',
    sectorId: 'berber',
    plan: 'starter',
    description: 'Vintage berber dükkanı hissi. Krem kağıt dokusu, serif başlıklar, altın accent.',
    designPhilosophy: 'Playfair Display başlıklarda eski dünya hissi, DM Sans gövdede modern okuma. Sıcak tonlar, altın detaylar.',
    isDark: false,
    fonts: {
      heading: { family: 'Playfair Display', weights: [400, 600, 700] },
      body: { family: 'DM Sans', weights: [400, 500, 700] },
    },
    cssOverrides: {
      '--color-bg': '#FAF8F3',
      '--color-surface': '#F0ECE3',
      '--color-accent': '#8B6914',
      '--color-accent-hover': '#705510',
      '--color-accent-light': '#F5F0E0',
      '--color-text': '#2C2014',
      '--font-heading': "'Playfair Display', serif",
      '--font-body': "'DM Sans', sans-serif", },
    homeSections: ['hero::split_left', 'services::card_grid', 'before_after::slider', 'gallery::masonry', 'team::card_horizontal', 'testimonials::carousel', 'booking::inline_calendar', 'stats::animated_row', 'working_hours::compact', 'map::full_width', 'contact::split_form_map'],
    pages: ['home', 'hizmetler', 'iletisim'],
    sectorSections: ['before_after', 'booking'],
    animationLevel: 'framer-basic',
    demoBusinessKey: 'klasik',
  },
  {
    id: 'berber-blade',
    name: 'Blade',
    sectorId: 'berber',
    plan: 'growth',
    description: 'Agresif, koyu, neon turuncu vurgulu. Video hero, hover-reveal, yatay snap scroll.',
    designPhilosophy: 'Siyah arka planda turuncu çizgiler — çok kontrast. Syne heading — güçlü. Video hero, curtain reveal, mono→color ekip.',
    isDark: true,
    fonts: {
      heading: { family: 'Oswald', weights: [500, 600, 700] },
      body: { family: 'Inter', weights: [400, 500] },
    },
    cssOverrides: {
      '--color-accent': '#F97316',
      '--color-accent-hover': '#FB923C',
      '--color-text-on-accent': '#000000',
      '--font-heading': "'Oswald', sans-serif",
    },
    homeSections: ['hero::video_cinematic', 'services::hover_reveal', 'before_after::curtain_reveal', 'gallery::horizontal_snap', 'team::mono_to_color', 'stats::dark_bar', 'testimonials::marquee', 'instagram_feed', 'cta::full_width_banner', 'booking::cta_only'],
    pages: ['home', 'hizmetler', 'galeri', 'ekip', 'iletisim'],
    sectorSections: ['before_after', 'booking'],
    animationLevel: 'framer-full',
    demoBusinessKey: 'blade',
  },
  {
    id: 'berber-gentleman',
    name: 'Gentleman',
    sectorId: 'berber',
    plan: 'pro',
    description: 'Lüks berber kulübü. Altın detaylar, Ken Burns zoom hero, editoryal dergi layout.',
    designPhilosophy: 'Cormorant Garamond başlıklarda eski dünya lüksü. Sticky-scroll hizmet bölümü. Film grain texture. Blog destekli.',
    isDark: false,
    fonts: {
      heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] },
      body: { family: 'DM Sans', weights: [400, 500] },
    },
    cssOverrides: {
      '--color-surface': '#FAF8F5',
      '--color-accent': '#C9A84C',
      '--color-accent-hover': '#B8952F',
      '--color-text': '#1A1A2E',
      '--font-heading': "'Cormorant Garamond', serif",
      '--font-body': "'DM Sans', sans-serif", },
    homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'services::sticky_scroll', 'before_after::curtain_reveal', 'team::full_page_snap', 'gallery::horizontal_snap', 'testimonials::editorial_single', 'social_proof', 'blog_preview', 'booking::inline_calendar', 'stats::gradient_bar'],
    pages: ['home', 'hizmetler', 'galeri', 'ekip', 'hakkimizda', 'blog', 'iletisim'],
    sectorSections: ['before_after', 'booking'],
    animationLevel: 'gsap-allowed',
    demoBusinessKey: 'gentleman',
  },
  {
    id: 'berber-studio',
    name: 'Studio',
    sectorId: 'berber',
    plan: 'enterprise',
    description: 'Multi-location berber zinciri / akademi. Mega menü, video showreel, e-ticaret.',
    designPhilosophy: 'Syne heading — modern, güçlü, kurumsal. Clean white base. Hızlı erişim kartları ile kullanıcıyı yönlendir.',
    isDark: false,
    fonts: {
      heading: { family: 'Montserrat', weights: [500, 600, 700, 800] },
      body: { family: 'Inter', weights: [400, 500] },
    },
    cssOverrides: {
      '--color-accent': '#1A1A2E',
      '--color-accent-hover': '#2D2B55',
      '--font-heading': "'Montserrat', sans-serif",
    },
    homeSections: ['hero::video_showreel', 'quick_access_cards', 'services::filtered_tabs', 'multi_location', 'stats::dark_bar', 'portfolio_grid::filtered_categories', 'team::filterable_grid', 'testimonials::grid_cards', 'blog_preview', 'promotions', 'loyalty_program', 'career_listings', 'franchise_section'],
    pages: ['home', 'hizmetler', 'galeri', 'ekip', 'hakkimizda', 'blog', 'akademi', 'kariyer', 'subeler', 'magaza', 'iletisim'],
    sectorSections: ['before_after', 'booking', 'multi_location', 'career_listings', 'franchise_section', 'loyalty_program', 'quick_access_cards'],
    animationLevel: 'gsap-allowed',
    demoBusinessKey: 'studio',
  },
]
