/**
 * @kepenk/templates — P0 Demo Business Data
 *
 * Demo businesses for 8 P0 sectors. Each sector has 5 demo businesses
 * corresponding to 5 plan tiers: free, starter, growth, pro, enterprise.
 */

import type { BusinessData } from '../types/section-types'

// ═══════════════════════════════════════════
// BERBER
// ═══════════════════════════════════════════

export const BERBER_DEMOS: Record<string, Partial<BusinessData>> = {
  sade: {
    name: 'Kadir Usta Kuaför',
    ownerName: 'Kadir Aydın',
    slogan: 'Sade ve temiz, her zaman güvenilir',
    phone: '0532 418 67 90',
    phoneClean: '905324186790',
    whatsapp: '905324186790',
    email: 'info@kadirustakuafor.com',
    address: 'Caferağa Mah. Moda Cad. No:48/A, Kadıköy',
    city: 'İstanbul',
    district: 'Kadıköy',
    neighborhood: 'Caferağa',
    coordinates: { lat: 40.9862, lng: 29.0293 },
    foundedYear: 2012,
    experience: '12 yıl',
    customerCount: '3000+',
    rating: 4.7,
    reviewCount: 89,
    sectorId: 'berber',
  },
  klasik: {
    name: 'Efe Berber Salonu',
    ownerName: 'Efe Karaca',
    slogan: 'Geleneksel ustalık, modern dokunuş',
    phone: '0535 912 34 56',
    phoneClean: '905359123456',
    whatsapp: '905359123456',
    email: 'info@efeberbersalonu.com',
    address: 'Rumeli Cad. No:72, Nişantaşı',
    city: 'İstanbul',
    district: 'Şişli',
    neighborhood: 'Nişantaşı',
    coordinates: { lat: 41.0485, lng: 28.9903 },
    foundedYear: 1996,
    experience: '20 yıl',
    customerCount: '8000+',
    rating: 4.9,
    reviewCount: 214,
    sectorId: 'berber',
  },
  blade: {
    name: 'BLADE Grooming',
    ownerName: 'Kaan Demir',
    slogan: 'Cut different.',
    phone: '0541 777 88 99',
    phoneClean: '905417778899',
    whatsapp: '905417778899',
    email: 'info@bladegrooming.com',
    address: 'Bağdat Cad. No:315, Kadıköy',
    city: 'İstanbul',
    district: 'Kadıköy',
    coordinates: { lat: 40.9631, lng: 29.0662 },
    foundedYear: 2016,
    experience: '8 yıl',
    rating: 4.8,
    reviewCount: 342,
    sectorId: 'berber',
  },
  gentleman: {
    name: 'The Gentleman Club',
    ownerName: 'Selim Koçer',
    slogan: 'Beyefendinin adresi',
    phone: '0533 222 44 66',
    phoneClean: '905332224466',
    whatsapp: '905332224466',
    email: 'info@thegentlemanclub.com.tr',
    address: 'Abdi İpekçi Cad. No:18, Nişantaşı',
    city: 'İstanbul',
    district: 'Şişli',
    coordinates: { lat: 41.0495, lng: 28.9925 },
    foundedYear: 1999,
    experience: '25 yıl',
    rating: 4.9,
    reviewCount: 487,
    sectorId: 'berber',
  },
  studio: {
    name: 'StudioCut Academy',
    ownerName: 'Deniz Arslan',
    slogan: 'Saç sanatının merkezi',
    phone: '0444 28 58',
    phoneClean: '904442858',
    whatsapp: '905001234567',
    email: 'info@studiocut.com.tr',
    address: 'Merkez: Bağdat Cad. No:200, Kadıköy',
    city: 'İstanbul',
    district: 'Kadıköy',
    coordinates: { lat: 40.9697, lng: 29.0578 },
    foundedYear: 2009,
    experience: '15 yıl',
    rating: 4.8,
    reviewCount: 1250,
    sectorId: 'berber',
  },
}

// ═══════════════════════════════════════════
// RESTORAN
// ═══════════════════════════════════════════

export const RESTORAN_DEMOS: Record<string, Partial<BusinessData>> = {
  sofra: {
    name: 'Anadolu Sofrası',
    ownerName: 'Mustafa Demir',
    slogan: 'Annenizin mutfağından sofralarınıza',
    phone: '0212 327 45 67',
    phoneClean: '902123274567',
    email: 'info@anadolusofrasi.com',
    address: 'Sinanpaşa Mah. Çelebioğlu Sok. No:12, Beşiktaş',
    city: 'İstanbul',
    district: 'Beşiktaş',
    coordinates: { lat: 41.0428, lng: 29.0070 },
    foundedYear: 2015,
    experience: '9 yıl',
    rating: 4.6,
    reviewCount: 156,
    sectorId: 'restoran',
  },
  lezzet: {
    name: 'Lezzet Mutfağı',
    ownerName: 'Ayşe Kara',
    slogan: 'Modern Türk lezzetleri, özgün sunumlar',
    phone: '0212 245 89 01',
    phoneClean: '902122458901',
    email: 'info@lezzetmutfagi.com',
    address: 'İstiklal Cad. Atlas Pasajı No:5, Beyoğlu',
    city: 'İstanbul',
    district: 'Beyoğlu',
    coordinates: { lat: 41.0335, lng: 28.9770 },
    foundedYear: 2018,
    rating: 4.7,
    reviewCount: 230,
    sectorId: 'restoran',
  },
  nar: {
    name: 'NÂR Kitchen & Bar',
    ownerName: 'Chef Emre Yıldız',
    slogan: 'Ateşle pişer, tutkuyla sunulur',
    phone: '0212 243 77 88',
    phoneClean: '902122437788',
    email: 'info@narkitchen.com',
    address: 'Kemankeş Cad. No:28, Karaköy',
    city: 'İstanbul',
    district: 'Beyoğlu',
    coordinates: { lat: 41.0230, lng: 28.9770 },
    foundedYear: 2020,
    rating: 4.8,
    reviewCount: 410,
    sectorId: 'restoran',
  },
  tabledot: {
    name: "Table d'Hôte",
    ownerName: 'Chef Sinan Arıkan',
    slogan: 'Lezzet bir sanattır. Biz onu yaşatıyoruz.',
    phone: '0212 230 55 66',
    phoneClean: '902122305566',
    email: 'reservation@tabledot.com.tr',
    address: 'Abdi İpekçi Cad. No:42, Nişantaşı',
    city: 'İstanbul',
    district: 'Şişli',
    coordinates: { lat: 41.0491, lng: 28.9935 },
    foundedYear: 2017,
    rating: 4.9,
    reviewCount: 580,
    sectorId: 'restoran',
  },
  zincir: {
    name: 'BurgerLab Türkiye',
    ownerName: 'Can Özkan',
    slogan: 'Laboratuvardan sofraya, bilimsel lezzet',
    phone: '0850 123 45 67',
    phoneClean: '908501234567',
    email: 'info@burgerlab.com.tr',
    address: 'Kadıköy HQ — Bağdat Cad. No:100',
    city: 'İstanbul',
    district: 'Kadıköy',
    coordinates: { lat: 40.9817, lng: 29.0344 },
    foundedYear: 2015,
    rating: 4.5,
    reviewCount: 3200,
    sectorId: 'restoran',
  },
}

// ═══════════════════════════════════════════
// DOKTOR
// ═══════════════════════════════════════════

export const DOKTOR_DEMOS: Record<string, Partial<BusinessData>> = {
  huzur: {
    name: 'Dr. Elif Aksoy',
    ownerName: 'Uzm. Dr. Elif Aksoy',
    slogan: 'Sağlığınız güvenilir ellerde',
    phone: '0216 450 34 56',
    phoneClean: '902164503456',
    email: 'info@drelifaksoy.com',
    address: 'Altunizade Mah. Kısıklı Cad. No:22/4, Üsküdar',
    city: 'İstanbul',
    district: 'Üsküdar',
    coordinates: { lat: 41.0233, lng: 29.0393 },
    foundedYear: 2014,
    experience: '12 yıl',
    rating: 4.8,
    reviewCount: 95,
    sectorId: 'doktor',
  },
  sifa: {
    name: 'Şifa Tıp Merkezi',
    ownerName: 'Dr. Hakan Özer',
    slogan: 'Her branşta uzman kadro',
    phone: '0216 345 67 89',
    phoneClean: '902163456789',
    email: 'info@sifatip.com',
    address: 'Bağdat Cad. No:180/B, Kadıköy',
    city: 'İstanbul',
    district: 'Kadıköy',
    coordinates: { lat: 40.9714, lng: 29.0565 },
    foundedYear: 2010,
    rating: 4.7,
    reviewCount: 340,
    sectorId: 'doktor',
  },
  otorite: {
    name: 'Prof. Dr. Mehmet Aras',
    ownerName: 'Prof. Dr. Mehmet Aras',
    slogan: 'Kalbiniz en iyi ellerde',
    phone: '0212 345 78 90',
    phoneClean: '902123457890',
    email: 'info@profmehmetaras.com',
    address: 'Halaskargazi Cad. No:156/8, Şişli',
    city: 'İstanbul',
    district: 'Şişli',
    coordinates: { lat: 41.0572, lng: 28.9880 },
    foundedYear: 2005,
    experience: '22 yıl',
    rating: 4.9,
    reviewCount: 620,
    sectorId: 'doktor',
  },
  vita: {
    name: 'Vita Health Center',
    ownerName: 'Dr. Zeynep Kaya',
    slogan: 'Dijital çağın sağlık merkezi',
    phone: '0212 280 90 00',
    phoneClean: '902122809000',
    email: 'info@vitahealth.com.tr',
    address: 'Büyükdere Cad. No:185, Levent',
    city: 'İstanbul',
    district: 'Beşiktaş',
    coordinates: { lat: 41.0830, lng: 29.0128 },
    foundedYear: 2019,
    rating: 4.8,
    reviewCount: 280,
    sectorId: 'doktor',
  },
  merkez: {
    name: 'İstanbul Sağlık Grubu',
    ownerName: 'Prof. Dr. Ali Demir',
    slogan: 'Sağlıkta güç birliği',
    phone: '0850 222 34 56',
    phoneClean: '908502223456',
    email: 'info@istanbulsaglik.com.tr',
    address: 'Ataşehir Bulvarı No:50, Ataşehir',
    city: 'İstanbul',
    district: 'Ataşehir',
    coordinates: { lat: 40.9914, lng: 29.1148 },
    foundedYear: 2008,
    rating: 4.7,
    reviewCount: 2100,
    sectorId: 'doktor',
  },
}

// ═══════════════════════════════════════════
// GÜZELLİK
// ═══════════════════════════════════════════

export const GUZELLIK_DEMOS: Record<string, Partial<BusinessData>> = {
  dogal: {
    name: 'Doğal Güzellik',
    ownerName: 'Sevgi Arslan',
    slogan: 'Doğal güzelliğinizi ortaya çıkarın',
    phone: '0212 542 33 44',
    phoneClean: '902125423344',
    email: 'info@dogalguzellik.com',
    address: 'İncirli Cad. No:45, Bakırköy',
    city: 'İstanbul',
    district: 'Bakırköy',
    coordinates: { lat: 40.9783, lng: 28.8715 },
    foundedYear: 2016,
    rating: 4.6,
    reviewCount: 78,
    sectorId: 'guzellik',
  },
  pembe: {
    name: 'Pink Beauty Studio',
    ownerName: 'Defne Yılmaz',
    slogan: 'Güzelliğinize dokunuyoruz',
    phone: '0212 230 55 66',
    phoneClean: '902122305566',
    email: 'info@pinkbeauty.com.tr',
    address: 'Halaskargazi Cad. No:88/A, Şişli',
    city: 'İstanbul',
    district: 'Şişli',
    coordinates: { lat: 41.0540, lng: 28.9869 },
    foundedYear: 2019,
    rating: 4.8,
    reviewCount: 195,
    sectorId: 'guzellik',
  },
  noir: {
    name: 'Noir Beauty Lounge',
    ownerName: 'Ceren Kılıç',
    slogan: 'Lüksün yeni adresi',
    phone: '0212 240 77 88',
    phoneClean: '902122407788',
    email: 'info@noirbeauty.com.tr',
    address: 'Abdi İpekçi Cad. No:30, Nişantaşı',
    city: 'İstanbul',
    district: 'Şişli',
    coordinates: { lat: 41.0493, lng: 28.9930 },
    foundedYear: 2021,
    rating: 4.9,
    reviewCount: 310,
    sectorId: 'guzellik',
  },
  atolye: {
    name: 'Güzellik Atölyesi',
    ownerName: 'İrem Demir',
    slogan: 'Güzellik bir sanattır',
    phone: '0216 330 22 33',
    phoneClean: '902163302233',
    email: 'info@guzellikatolyesi.com',
    address: 'Bahariye Cad. No:65, Kadıköy',
    city: 'İstanbul',
    district: 'Kadıköy',
    coordinates: { lat: 40.9899, lng: 29.0263 },
    foundedYear: 2017,
    rating: 4.8,
    reviewCount: 420,
    sectorId: 'guzellik',
  },
  glamour: {
    name: 'Glamour Beauty Group',
    ownerName: 'Selin Öztürk',
    slogan: 'Türkiye\'nin güzellik zinciri',
    phone: '0850 555 44 33',
    phoneClean: '908505554433',
    email: 'info@glamourbeauty.com.tr',
    address: 'Büyükdere Cad. No:120, Levent',
    city: 'İstanbul',
    district: 'Beşiktaş',
    coordinates: { lat: 41.0804, lng: 29.0118 },
    foundedYear: 2013,
    rating: 4.7,
    reviewCount: 1800,
    sectorId: 'guzellik',
  },
}

// ═══════════════════════════════════════════
// AVUKAT
// ═══════════════════════════════════════════

export const AVUKAT_DEMOS: Record<string, Partial<BusinessData>> = {
  adalet: {
    name: 'Av. Burak Yıldırım',
    ownerName: 'Av. Burak Yıldırım',
    slogan: 'Hakkınızı savunuruz',
    phone: '0212 234 56 78',
    phoneClean: '902122345678',
    email: 'info@avburakyildirim.com',
    address: 'Halaskargazi Cad. No:200/5, Şişli',
    city: 'İstanbul',
    district: 'Şişli',
    coordinates: { lat: 41.0580, lng: 28.9878 },
    foundedYear: 2015,
    experience: '11 yıl',
    rating: 4.8,
    reviewCount: 65,
    sectorId: 'avukat',
  },
  savunma: {
    name: 'Yıldırım Hukuk Bürosu',
    ownerName: 'Av. Burak Yıldırım',
    slogan: 'Güçlü savunma, adil sonuç',
    phone: '0216 450 12 34',
    phoneClean: '902164501234',
    email: 'info@yildirimhukuk.com',
    address: 'Bağdat Cad. No:220/3, Kadıköy',
    city: 'İstanbul',
    district: 'Kadıköy',
    coordinates: { lat: 40.9690, lng: 29.0590 },
    foundedYear: 2012,
    rating: 4.7,
    reviewCount: 120,
    sectorId: 'avukat',
  },
  kanun: {
    name: 'KANUN Hukuk & Danışmanlık',
    ownerName: 'Av. Cemre Başaran',
    slogan: 'Hukukun gücü, çözümün adresi',
    phone: '0212 280 90 12',
    phoneClean: '902122809012',
    email: 'info@kanunhukuk.com.tr',
    address: 'Büyükdere Cad. No:150/10, Levent',
    city: 'İstanbul',
    district: 'Beşiktaş',
    coordinates: { lat: 41.0810, lng: 29.0125 },
    foundedYear: 2016,
    rating: 4.9,
    reviewCount: 250,
    sectorId: 'avukat',
  },
  kursu: {
    name: 'Kürsü Avukatlık Ortaklığı',
    ownerName: 'Av. Prof. Dr. Kemal Toprak',
    slogan: 'Akademik derinlik, pratik çözüm',
    phone: '0312 420 56 78',
    phoneClean: '903124205678',
    email: 'info@kursuavukatlik.com',
    address: 'Tunalı Hilmi Cad. No:85/A, Çankaya',
    city: 'Ankara',
    district: 'Çankaya',
    coordinates: { lat: 39.9105, lng: 32.8545 },
    foundedYear: 2008,
    rating: 4.9,
    reviewCount: 380,
    sectorId: 'avukat',
  },
  kuresel: {
    name: 'Atlas Legal Group',
    ownerName: 'Av. Deniz Atalay',
    slogan: 'Global perspective, local expertise',
    phone: '0212 340 78 90',
    phoneClean: '902123407890',
    email: 'info@atlaslegal.com.tr',
    address: 'Levent, İstanbul — HQ',
    city: 'İstanbul',
    district: 'Beşiktaş',
    coordinates: { lat: 41.0825, lng: 29.0130 },
    foundedYear: 2005,
    rating: 4.8,
    reviewCount: 520,
    sectorId: 'avukat',
  },
}

// ═══════════════════════════════════════════
// DİŞÇİ
// ═══════════════════════════════════════════

export const DISCI_DEMOS: Record<string, Partial<BusinessData>> = {
  gulus: {
    name: 'Dr. Deniz Gülüş Kliniği',
    ownerName: 'Dt. Deniz Erdem',
    slogan: 'Gülüşünüzü tasarlıyoruz',
    phone: '0216 340 55 66',
    phoneClean: '902163405566',
    email: 'info@denisgulus.com',
    address: 'Bağdat Cad. No:160/2, Kadıköy',
    city: 'İstanbul',
    district: 'Kadıköy',
    coordinates: { lat: 40.9740, lng: 29.0530 },
    foundedYear: 2017,
    rating: 4.8,
    reviewCount: 125,
    sectorId: 'disci',
  },
  inci: {
    name: 'İnci Dental',
    ownerName: 'Dt. Merve İnci',
    slogan: 'İnci gibi dişler, güzel gülüşler',
    phone: '0212 233 44 55',
    phoneClean: '902122334455',
    email: 'info@incidental.com.tr',
    address: 'Cumhuriyet Cad. No:95/3, Şişli',
    city: 'İstanbul',
    district: 'Şişli',
    coordinates: { lat: 41.0555, lng: 28.9880 },
    foundedYear: 2014,
    rating: 4.7,
    reviewCount: 280,
    sectorId: 'disci',
  },
  parlak: {
    name: 'Parlak Gülüş Merkezi',
    ownerName: 'Dt. Serkan Parlak',
    slogan: 'Parlak gülüş, parlak hayat',
    phone: '0212 572 33 44',
    phoneClean: '902125723344',
    email: 'info@parlakgulus.com',
    address: 'İncirli Cad. No:30, Bakırköy',
    city: 'İstanbul',
    district: 'Bakırköy',
    coordinates: { lat: 40.9785, lng: 28.8710 },
    foundedYear: 2019,
    rating: 4.9,
    reviewCount: 192,
    sectorId: 'disci',
  },
  klinik: {
    name: 'DentPlus Klinik',
    ownerName: 'Dt. Aylin Akman',
    slogan: 'Teknoloji ve güven bir arada',
    phone: '0216 570 80 90',
    phoneClean: '902165708090',
    email: 'info@dentplus.com.tr',
    address: 'Ataşehir Bulvarı No:25/A, Ataşehir',
    city: 'İstanbul',
    district: 'Ataşehir',
    coordinates: { lat: 40.9920, lng: 29.1145 },
    foundedYear: 2016,
    rating: 4.8,
    reviewCount: 410,
    sectorId: 'disci',
  },
  dentgrup: {
    name: 'DentGrup Türkiye',
    ownerName: 'Prof. Dt. Kemal Gündüz',
    slogan: 'Türkiye\'nin diş sağlığı zinciri',
    phone: '0850 333 55 77',
    phoneClean: '908503335577',
    email: 'info@dentgrup.com.tr',
    address: 'İstanbul Genel Merkez',
    city: 'İstanbul',
    district: 'Kadıköy',
    coordinates: { lat: 40.9870, lng: 29.0300 },
    foundedYear: 2010,
    rating: 4.7,
    reviewCount: 3500,
    sectorId: 'disci',
  },
}

// ═══════════════════════════════════════════
// OTO TAMİR
// ═══════════════════════════════════════════

export const OTO_DEMOS: Record<string, Partial<BusinessData>> = {
  usta: {
    name: 'Usta Oto Servis',
    ownerName: 'Hasan Usta',
    slogan: 'Güvenilir el, doğru teşhis',
    phone: '0216 445 67 89',
    phoneClean: '902164456789',
    email: 'info@ustaoto.com',
    address: 'Cevizli Sanayi Sitesi No:34, Maltepe',
    city: 'İstanbul',
    district: 'Maltepe',
    coordinates: { lat: 40.9250, lng: 29.1540 },
    foundedYear: 2010,
    experience: '15 yıl',
    rating: 4.7,
    reviewCount: 110,
    sectorId: 'oto',
  },
  garaj: {
    name: 'Garaj34 Oto',
    ownerName: 'Ali Kara',
    slogan: 'Şeffaf fiyat, kaliteli işçilik',
    phone: '0216 378 90 12',
    phoneClean: '902163789012',
    email: 'info@garaj34.com',
    address: 'Yakacık Sanayi No:78, Kartal',
    city: 'İstanbul',
    district: 'Kartal',
    coordinates: { lat: 40.8920, lng: 29.1935 },
    foundedYear: 2013,
    rating: 4.8,
    reviewCount: 186,
    sectorId: 'oto',
  },
  pitstop: {
    name: 'PitStop Express',
    ownerName: 'Murat Çelik',
    slogan: 'Hızlı, güvenilir, profesyonel',
    phone: '0216 630 45 67',
    phoneClean: '902166304567',
    email: 'info@pitstopexpress.com',
    address: 'Alemdağ Cad. No:150, Ümraniye',
    city: 'İstanbul',
    district: 'Ümraniye',
    coordinates: { lat: 41.0300, lng: 29.1080 },
    foundedYear: 2017,
    rating: 4.6,
    reviewCount: 240,
    sectorId: 'oto',
  },
  motor: {
    name: 'Motor Premium Detailing',
    ownerName: 'Emre Aksoy',
    slogan: 'Aracınız sanat eserimiz',
    phone: '0212 260 33 44',
    phoneClean: '902122603344',
    email: 'info@motorpremium.com',
    address: 'Ortabayır Mah. No:55, Beşiktaş',
    city: 'İstanbul',
    district: 'Beşiktaş',
    coordinates: { lat: 41.0480, lng: 29.0050 },
    foundedYear: 2019,
    rating: 4.9,
    reviewCount: 156,
    sectorId: 'oto',
  },
  filo: {
    name: 'AutoPro Türkiye',
    ownerName: 'Serkan Doğan',
    slogan: 'Türkiye\'nin oto servis ağı',
    phone: '0850 100 34 34',
    phoneClean: '908501003434',
    email: 'info@autopro.com.tr',
    address: 'İstanbul Genel Merkez',
    city: 'İstanbul',
    district: 'Kadıköy',
    coordinates: { lat: 40.9860, lng: 29.0300 },
    foundedYear: 2012,
    rating: 4.6,
    reviewCount: 2800,
    sectorId: 'oto',
  },
}

// ═══════════════════════════════════════════
// SPOR
// ═══════════════════════════════════════════

export const SPOR_DEMOS: Record<string, Partial<BusinessData>> = {
  form: {
    name: 'Form Fitness',
    ownerName: 'Burak Yılmaz',
    slogan: 'Formunuza kavuşun',
    phone: '0216 340 22 33',
    phoneClean: '902163402233',
    email: 'info@formfitness.com',
    address: 'Moda Cad. No:80, Kadıköy',
    city: 'İstanbul',
    district: 'Kadıköy',
    coordinates: { lat: 40.9850, lng: 29.0280 },
    foundedYear: 2018,
    rating: 4.6,
    reviewCount: 92,
    sectorId: 'spor',
  },
  nabiz: {
    name: 'Nabız Spor Kulübü',
    ownerName: 'Elif Çetin',
    slogan: 'Toplulukla güçlen',
    phone: '0212 570 44 55',
    phoneClean: '902125704455',
    email: 'info@nabizsporkulubu.com',
    address: 'Zuhuratbaba Mah. No:25, Bakırköy',
    city: 'İstanbul',
    district: 'Bakırköy',
    coordinates: { lat: 40.9810, lng: 28.8680 },
    foundedYear: 2016,
    rating: 4.8,
    reviewCount: 230,
    sectorId: 'spor',
  },
  demir: {
    name: 'DEMİR Gym',
    ownerName: 'Mert Demir',
    slogan: 'Sınırlarını aş',
    phone: '0216 570 66 77',
    phoneClean: '902165706677',
    email: 'info@demirgym.com',
    address: 'Ataşehir Bulvarı No:70, Ataşehir',
    city: 'İstanbul',
    district: 'Ataşehir',
    coordinates: { lat: 40.9930, lng: 29.1140 },
    foundedYear: 2019,
    rating: 4.7,
    reviewCount: 188,
    sectorId: 'spor',
  },
  denge: {
    name: 'Denge Yoga & Wellness',
    ownerName: 'Elif Barış',
    slogan: 'Bedeninle barış, zihninle huzur',
    phone: '0212 252 88 99',
    phoneClean: '902122528899',
    email: 'info@dengeyoga.com',
    address: 'Cihangir Mah. Akarsu Cad. No:12, Beyoğlu',
    city: 'İstanbul',
    district: 'Beyoğlu',
    coordinates: { lat: 41.0336, lng: 28.9840 },
    foundedYear: 2017,
    rating: 4.9,
    reviewCount: 320,
    sectorId: 'spor',
  },
  arena: {
    name: 'Arena Sports Group',
    ownerName: 'Tolga Aydın',
    slogan: 'Sporun gücü, birlikte daha güçlü',
    phone: '0850 444 27 36',
    phoneClean: '908504442736',
    email: 'info@arenasports.com.tr',
    address: 'İstanbul Genel Merkez',
    city: 'İstanbul',
    district: 'Kadıköy',
    coordinates: { lat: 40.9860, lng: 29.0300 },
    foundedYear: 2014,
    rating: 4.7,
    reviewCount: 4500,
    sectorId: 'spor',
  },
}

/** All P0 demo businesses by sector */
export const P0_DEMO_BUSINESSES = {
  berber: BERBER_DEMOS,
  restoran: RESTORAN_DEMOS,
  doktor: DOKTOR_DEMOS,
  guzellik: GUZELLIK_DEMOS,
  avukat: AVUKAT_DEMOS,
  disci: DISCI_DEMOS,
  oto: OTO_DEMOS,
  spor: SPOR_DEMOS,
} as const
