/**
 * @kepenk/templates — P1 Fotoğrafçı + Düğün Themes (10 themes)
 */
import type { P0ThemeDef } from './p0-themes'

export const FOTOGRAFCI_THEMES: P0ThemeDef[] = [
  { id: 'foto-kare', name: 'Kare', sectorId: 'fotografci', plan: 'free', description: 'Freelance fotoğrafçı. Ultra minimal, fotoğraflar konuşsun.', designPhilosophy: 'Siyah accent, Syne heading — modern. Masonry portfolyo, minimum metin. Fotoğraflar tam ekran.', isDark: false, fonts: { heading: { family: 'Space Grotesk', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#111111', '--color-accent-hover': '#333333', '--font-heading': "'Space Grotesk', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'portfolio_grid::masonry_lightbox', 'about::split_left', 'contact::simple_form'], pages: ['home'], sectorSections: ['portfolio_grid'], animationLevel: 'css-only', demoBusinessKey: 'kare' },
  { id: 'foto-lens', name: 'Lens', sectorId: 'fotografci', plan: 'starter', description: 'Düğün fotoğrafçısı. Sıcak serif, paketler, proje hikayesi.', designPhilosophy: 'Cormorant Garamond romantik. Kahverengi sıcaklık. 3 paket fiyatlandırma, düğün hikayesi.', isDark: false, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C6048', '--color-accent-hover': '#654D3A', '--color-bg': '#FAF8F5', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'portfolio_grid::masonry_lightbox', 'project_story', 'membership_pricing::columns', 'testimonials::carousel', 'booking_inquiry', 'instagram_feed', 'contact::split_form_map'], pages: ['home', 'portfolyo', 'paketler', 'iletisim'], sectorSections: ['portfolio_grid', 'project_story', 'booking_inquiry'], animationLevel: 'framer-basic', demoBusinessKey: 'lens' },
  { id: 'foto-obturator', name: 'Obtüratör', sectorId: 'fotografci', plan: 'growth', description: 'Sinematik fotoğraf/video. Koyu, beyaz accent, showreel.', designPhilosophy: 'Siyah-beyaz sinematik minimalizm. Syne güçlü. Horizontal scroll, overlay menü.', isDark: true, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#FFFFFF', '--color-accent-hover': '#E5E5E5', '--color-text-on-accent': '#000000', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['hero::video_showreel', 'portfolio_grid::horizontal_scroll', 'project_story', 'awards_press', 'blog_preview', 'contact::simple_form'], pages: ['home', 'portfolyo', 'hikayeler', 'blog', 'iletisim'], sectorSections: ['portfolio_grid', 'project_story', 'video_showreel', 'awards_press'], animationLevel: 'framer-full', demoBusinessKey: 'obturator' },
  { id: 'foto-odak', name: 'Odak', sectorId: 'fotografci', plan: 'pro', description: 'Ticari stüdyo. Siyah, filtered categories, preset mağazası.', designPhilosophy: 'Syne modern. Video stüdyo arkası. Filtered portfolio. Dijital ürün satışı (presets).', isDark: false, fonts: { heading: { family: 'Gilda Display', weights: [400] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1A1A1A', '--color-accent-hover': '#374151', '--font-heading': "'Gilda Display', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'portfolio_grid::masonry_lightbox', 'membership_pricing::columns', 'team::card_horizontal', 'blog_preview', 'testimonials::grid_cards', 'contact::split_form_map'], pages: ['home', 'portfolyo', 'paketler', 'magaza', 'blog', 'iletisim'], sectorSections: ['portfolio_grid', 'project_story', 'booking_inquiry'], animationLevel: 'gsap-allowed', demoBusinessKey: 'odak' },
  { id: 'foto-cerceve', name: 'Çerçeve', sectorId: 'fotografci', plan: 'enterprise', description: 'Prodüksiyon ajansı. Kurumsal, çoklu stüdyo, kariyer.', designPhilosophy: 'Syne kurumsal. Multi-location stüdyolar, ekip filtresi, franchise.', isDark: false, fonts: { heading: { family: 'Archivo', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1A1A1A', '--color-accent-hover': '#374151', '--font-heading': "'Archivo', sans-serif", }, homeSections: ['hero::video_showreel', 'quick_access_cards', 'portfolio_grid::masonry_lightbox', 'multi_location', 'team::filterable_grid', 'career_listings', 'franchise_section'], pages: ['home', 'portfolyo', 'studyolar', 'ekip', 'kariyer', 'iletisim'], sectorSections: ['portfolio_grid', 'project_story', 'multi_location', 'career_listings', 'franchise_section', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'cerceve' },
]

export const DUGUN_THEMES: P0ThemeDef[] = [
  { id: 'dugun-nikah', name: 'Nikâh', sectorId: 'dugun', plan: 'free', description: 'Düğün organizasyonu. Altın-krem, romantik, serif.', designPhilosophy: 'Cormorant Garamond romantik. Altın accent evlilik simgesi. Masonry düğün galerisi.', isDark: false, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#C9A84C', '--color-accent-hover': '#B8952F', '--color-bg': '#FFFDF8', '--color-surface': '#FAF5ED', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'services::card_grid', 'about::split_left', 'gallery::masonry', 'testimonials::carousel', 'contact::simple_form'], pages: ['home'], sectorSections: ['portfolio_grid', 'booking_inquiry'], animationLevel: 'css-only', demoBusinessKey: 'nikah' },
  { id: 'dugun-gelin', name: 'Gelin', sectorId: 'dugun', plan: 'starter', description: 'Wedding planner. Pembe-altın, paketler, timeline.', designPhilosophy: 'Soft pembe romantik. Düğün paketleri + planlama timeline + vendor network.', isDark: false, fonts: { heading: { family: 'Spectral', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#DBA8A2', '--color-accent-hover': '#C99690', '--color-bg': '#FFFBF9', '--font-heading': "'Spectral', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'wedding_packages', 'planning_timeline', 'portfolio_grid::masonry_lightbox', 'vendor_partners', 'booking_inquiry', 'testimonials::carousel', 'instagram_feed', 'contact::split_form_map'], pages: ['home', 'paketler', 'galeri', 'iletisim'], sectorSections: ['portfolio_grid', 'wedding_packages', 'planning_timeline', 'vendor_partners', 'booking_inquiry'], animationLevel: 'framer-basic', demoBusinessKey: 'gelin' },
  { id: 'dugun-seremoni', name: 'Seremoni', sectorId: 'dugun', plan: 'growth', description: 'Lüks düğün. Koyu, altın, sinematik video showreel.', designPhilosophy: 'Siyah-altın ultimate lüks. Sinematik showreel, destination wedding, editoryal hikayeler.', isDark: true, fonts: { heading: { family: 'Playfair Display', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#C9A84C', '--color-accent-hover': '#B8952F', '--font-heading': "'Playfair Display', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::video_showreel', 'services::hover_reveal', 'project_story', 'gallery::horizontal_snap', 'awards_press', 'testimonials::marquee', 'instagram_feed', 'booking_inquiry'], pages: ['home', 'galeri', 'hikayeler', 'iletisim'], sectorSections: ['portfolio_grid', 'project_story', 'wedding_packages', 'video_showreel', 'awards_press', 'booking_inquiry'], animationLevel: 'framer-full', demoBusinessKey: 'seremoni' },
  { id: 'dugun-festival', name: 'Festival', sectorId: 'dugun', plan: 'pro', description: 'Çok yönlü etkinlik. Mor, düğün+kurumsal+festival.', designPhilosophy: 'Syne modern çok yönlü. Mor enerji. Düğün/kurumsal/festival tab filtre.', isDark: false, fonts: { heading: { family: 'Gilda Display', weights: [400] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--color-accent-hover': '#6D28D9', '--font-heading': "'Gilda Display', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'services::filtered_tabs', 'portfolio_grid::masonry_lightbox', 'team::card_horizontal', 'blog_preview', 'free_quote', 'testimonials::grid_cards', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'galeri', 'blog', 'iletisim'], sectorSections: ['portfolio_grid', 'project_story', 'free_quote', 'booking_inquiry'], animationLevel: 'gsap-allowed', demoBusinessKey: 'festival' },
  { id: 'dugun-saltanat', name: 'Saltanat', sectorId: 'dugun', plan: 'enterprise', description: 'Düğün ajansı zinciri. Altın, mekan rehberi, franchise.', designPhilosophy: 'Syne kurumsal. Venue directory 20+ mekan, vendor ağı, franchise.', isDark: false, fonts: { heading: { family: 'Josefin Sans', weights: [400, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#C9A84C', '--color-accent-hover': '#B8952F', '--font-heading': "'Josefin Sans', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'services::filtered_tabs', 'multi_location', 'venue_directory', 'vendor_partners', 'career_listings', 'franchise_section'], pages: ['home', 'hizmetler', 'mekanlar', 'ortaklar', 'subeler', 'kariyer', 'bayilik', 'iletisim'], sectorSections: ['portfolio_grid', 'venue_directory', 'vendor_partners', 'multi_location', 'career_listings', 'franchise_section', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'saltanat' },
]
