/**
 * @kepenk/templates — P1 Fırın + Eczane + Veteriner Themes (15 themes)
 */
import type { P0ThemeDef } from './p0-themes'

export const FIRIN_THEMES: P0ThemeDef[] = [
  { id: 'firin-maya', name: 'Maya', sectorId: 'firin', plan: 'free', description: 'Semt fırını. Altın-krem, taze ekmek.', designPhilosophy: 'Lora serif sıcak, altın accent iştah açıcı. Daily special en üstte.', isDark: false, fonts: { heading: { family: 'Merriweather', weights: [400, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#B8860B', '--color-accent-hover': '#9A7009', '--color-bg': '#FFFDF5', '--color-surface': '#F8F3E6', '--font-heading': "'Merriweather', serif",
    }, homeSections: ['daily_special::banner', 'hero::fullscreen_overlay', 'menu_display::tab_categories', 'about::split_left', 'working_hours::compact', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['menu_display', 'daily_special'], animationLevel: 'css-only', demoBusinessKey: 'maya' },
  { id: 'firin-hamur', name: 'Hamur', sectorId: 'firin', plan: 'starter', description: 'Pastane. Pembe, pasta sipariş formu.', designPhilosophy: 'Pembe neşe ve kutlama. Pasta sipariş formu kritik — tarih+tür+kişi sayısı.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#D4536A', '--color-accent-hover': '#C0425A', '--color-bg': '#FFF5F7', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['hero::soft_carousel', 'menu_display::tab_categories', 'gallery::masonry', 'booking_inquiry', 'testimonials::carousel', 'seasonal_service', 'working_hours::compact', 'contact::split_form_map'], pages: ['home', 'urunler', 'iletisim'], sectorSections: ['menu_display', 'daily_special', 'booking_inquiry', 'seasonal_service'], animationLevel: 'framer-basic', demoBusinessKey: 'hamur' },
  { id: 'firin-kabuk', name: 'Kabuk', sectorId: 'firin', plan: 'growth', description: 'Artisan sourdough. Krem-kahve, zanaatkar süreç.', designPhilosophy: 'Cormorant Garamond zanaatçılık. Process steps ekmek yapım süreci. Blog destekli.', isDark: false, fonts: { heading: { family: 'Vollkorn', weights: [400, 600, 700] }, body: { family: 'Source Sans 3', weights: [400, 600] } }, cssOverrides: { '--color-accent': '#8B6914', '--color-accent-hover': '#705510', '--color-bg': '#FAF8F0', '--font-heading': "'Vollkorn', serif", '--font-body': "'Source Sans 3', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'process_steps::horizontal_timeline', 'menu_display::tab_categories', 'gallery::horizontal_snap', 'awards_press', 'blog_preview', 'testimonials::editorial_single', 'contact::split_form_map'], pages: ['home', 'urunler', 'hikaye', 'blog', 'iletisim'], sectorSections: ['menu_display', 'daily_special', 'awards_press'], animationLevel: 'framer-full', demoBusinessKey: 'kabuk' },
  { id: 'firin-katman', name: 'Katman', sectorId: 'firin', plan: 'pro', description: 'Fransız patisserie. Mor-pembe, lüks tatlı vitrini.', designPhilosophy: 'Cormorant Garamond zarif Fransız. Mor accent lüks. Fotoğraflı ürün grid.', isDark: false, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#8B4585', '--color-accent-hover': '#753A70', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'menu_display::visual_grid', 'team::full_page_snap', 'gallery::horizontal_snap', 'awards_press', 'blog_preview', 'instagram_feed', 'testimonials::editorial_single', 'contact::split_form_map'], pages: ['home', 'urunler', 'sef', 'blog', 'iletisim'], sectorSections: ['menu_display', 'daily_special', 'awards_press'], animationLevel: 'gsap-allowed', demoBusinessKey: 'katman' },
  { id: 'firin-kovan', name: 'Kovan', sectorId: 'firin', plan: 'enterprise', description: 'Fırın zinciri. Turuncu, çoklu şube, franchise.', designPhilosophy: 'Syne kurumsal. Workshop sayfası, sadakat programı, franchise.', isDark: false, fonts: { heading: { family: 'Barlow', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#B8540A', '--color-accent-hover': '#9A4608', '--font-heading': "'Barlow', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'menu_display::visual_grid', 'multi_location', 'daily_special::card_list', 'testimonials::marquee', 'instagram_feed', 'stats::dark_bar', 'loyalty_program', 'franchise_section', 'career_listings'], pages: ['home', 'urunler', 'subeler', 'atolye', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['menu_display', 'daily_special', 'multi_location', 'loyalty_program', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'kovan' },
]

export const ECZANE_THEMES: P0ThemeDef[] = [
  { id: 'eczane-saglik', name: 'Sağlık', sectorId: 'eczane', plan: 'free', description: 'Semt eczanesi. Yeşil, nöbetçi badge kritik.', designPhilosophy: 'Yeşil sağlık. Plus Jakarta Sans modern. Nöbetçi mi? bilgisi EN ÜSTTEKİ BANT.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#16A34A', '--color-accent-hover': '#15803D', '--color-surface': '#F0FDF4', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['duty_pharmacy', 'hero::fullscreen_overlay', 'services::card_grid', 'health_tip', 'about::split_left', 'working_hours::compact', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['duty_pharmacy', 'health_tip'], animationLevel: 'css-only', demoBusinessKey: 'saglik' },
  { id: 'eczane-recete', name: 'Reçete', sectorId: 'eczane', plan: 'starter', description: 'Kapsamlı eczane. Teal, eczacı profili, sigorta.', designPhilosophy: 'Teal güven. Eczacı profili + sigorta logoları + FAQ.', isDark: false, fonts: { heading: { family: 'Rubik', weights: [400, 500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0D9488', '--color-accent-hover': '#0F766E', '--font-heading': "'Rubik', sans-serif",
    }, homeSections: ['duty_pharmacy', 'hero::split_left', 'services::card_grid', 'doctor_profile::split', 'insurance_logos::row', 'gallery::masonry', 'testimonials::carousel', 'faq::accordion', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'iletisim'], sectorSections: ['duty_pharmacy', 'health_tip', 'insurance_logos'], animationLevel: 'framer-basic', demoBusinessKey: 'recete' },
  { id: 'eczane-iksir', name: 'İksir', sectorId: 'eczane', plan: 'growth', description: 'Modern eczane. Mavi, online sipariş, kampanyalar.', designPhilosophy: 'Mavi modernlik. Promo carousel, visual grid dermokozmetik, online teslimat.', isDark: false, fonts: { heading: { family: 'IBM Plex Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'IBM Plex Sans', sans-serif",
    }, homeSections: ['duty_pharmacy', 'hero::promo_carousel', 'menu_display::visual_grid', 'delivery_zone::list_only', 'promotions', 'testimonials::carousel', 'stats::animated_row', 'contact::split_form_map'], pages: ['home', 'urunler', 'teslimat', 'iletisim'], sectorSections: ['duty_pharmacy', 'health_tip', 'delivery_zone', 'menu_display'], animationLevel: 'framer-full', demoBusinessKey: 'iksir' },
  { id: 'eczane-formul', name: 'Formül', sectorId: 'eczane', plan: 'pro', description: 'Dijital eczane. Teal, search hero, blog sağlık rehberi.', designPhilosophy: 'Teal dijital. Search hero ilaç/ürün arama. Blog sağlık rehberleri.', isDark: false, fonts: { heading: { family: 'Source Serif 4', weights: [400, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0D9488', '--color-accent-hover': '#0F766E', '--font-heading': "'Source Serif 4', serif",
    }, homeSections: ['duty_pharmacy', 'hero::search_centric', 'services::filtered_tabs', 'technology_showcase', 'blog_preview', 'newsletter', 'testimonials::grid_cards', 'contact::split_form_map'], pages: ['home', 'urunler', 'blog', 'iletisim'], sectorSections: ['duty_pharmacy', 'health_tip', 'technology_showcase'], animationLevel: 'gsap-allowed', demoBusinessKey: 'formul' },
  { id: 'eczane-zincir', name: 'Zincir', sectorId: 'eczane', plan: 'enterprise', description: 'Eczane zinciri. Yeşil, 25 şube, sadakat kartı.', designPhilosophy: 'Syne kurumsal. VitaKart sadakat, franchise, 25 şube harita.', isDark: false, fonts: { heading: { family: 'Manrope', weights: [500, 600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#16A34A', '--color-accent-hover': '#15803D', '--font-heading': "'Manrope', sans-serif", }, homeSections: ['duty_pharmacy', 'hero::promo_carousel', 'quick_access_cards', 'multi_location', 'loyalty_program', 'franchise_section', 'career_listings'], pages: ['home', 'urunler', 'subeler', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['duty_pharmacy', 'health_tip', 'multi_location', 'loyalty_program', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'zincir' },
]

export const VETERINER_THEMES: P0ThemeDef[] = [
  { id: 'vet-pati', name: 'Pati', sectorId: 'veteriner', plan: 'free', description: 'Veteriner klinik. Mavi, acil banner, hayvan türü seçici.', designPhilosophy: 'Mavi güven + sıcaklık. Nunito yuvarlak. ACİL banner en üstte. Pet species seçici.', isDark: false, fonts: { heading: { family: 'Nunito', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--color-surface': '#F0F4FF', '--font-heading': "'Nunito', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::fullscreen_overlay', 'pet_species', 'services::card_grid', 'about::split_left', 'working_hours::compact', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['emergency_banner', 'pet_species', 'vaccination_calendar'], animationLevel: 'css-only', demoBusinessKey: 'pati' },
  { id: 'vet-yuva', name: 'Yuva', sectorId: 'veteriner', plan: 'starter', description: 'Hayvan kliniği. Teal, aşı takvimi, doktor profili.', designPhilosophy: 'Teal sağlık. Aşı takvimi tablo, 2 veteriner hekim profili, klinik galeri.', isDark: false, fonts: { heading: { family: 'Poppins', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0D9488', '--color-accent-hover': '#0F766E', '--font-heading': "'Poppins', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::split_left', 'pet_species', 'services::card_grid', 'vaccination_calendar', 'doctor_profile::carousel', 'gallery::masonry', 'testimonials::carousel', 'faq::accordion', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'iletisim'], sectorSections: ['emergency_banner', 'pet_species', 'vaccination_calendar', 'doctor_profile'], animationLevel: 'framer-basic', demoBusinessKey: 'yuva' },
  { id: 'vet-veterina', name: 'Veterina', sectorId: 'veteriner', plan: 'growth', description: 'İleri veteriner. Mavi, teknoloji, video tanıtım.', designPhilosophy: 'Mavi teknoloji. Video klinik tanıtım, dijital röntgen/ultrason showcase.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1E40AF', '--color-accent-hover': '#1E3A8A', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::video_cinematic', 'pet_species', 'services::card_grid', 'technology_showcase', 'stats::animated_row', 'blog_preview', 'testimonials::carousel', 'booking::inline_calendar'], pages: ['home', 'hizmetler', 'blog', 'iletisim'], sectorSections: ['emergency_banner', 'pet_species', 'vaccination_calendar', 'technology_showcase'], animationLevel: 'framer-full', demoBusinessKey: 'veterina' },
  { id: 'vet-dost', name: 'Dost', sectorId: 'veteriner', plan: 'pro', description: 'Premium veteriner. Mor, wellness paketleri, e-ticaret.', designPhilosophy: 'Mor premium. Ken Burns doğa. Pet wellness üyelik paketleri, mama/aksesuar satışı.', isDark: false, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--color-accent-hover': '#6D28D9', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::fullscreen_kenburns', 'philosophy', 'pet_species', 'membership_pricing::columns', 'doctor_profile::carousel', 'blog_preview', 'newsletter', 'testimonials::editorial_single', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'uyelik', 'blog', 'magaza', 'iletisim'], sectorSections: ['emergency_banner', 'pet_species', 'vaccination_calendar', 'membership_pricing'], animationLevel: 'gsap-allowed', demoBusinessKey: 'dost' },
  { id: 'vet-klan', name: 'Klan', sectorId: 'veteriner', plan: 'enterprise', description: 'Hayvan hastanesi zinciri. Mavi, MRI, çoklu şube.', designPhilosophy: 'Syne kurumsal. Quick access kartlar, multi-location, 7/24 + MRI acil.', isDark: false, fonts: { heading: { family: 'Raleway', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'Raleway', sans-serif", }, homeSections: ['emergency_banner', 'hero::video_showreel', 'quick_access_cards', 'multi_location', 'pet_species', 'team::filterable_grid', 'stats::dark_bar', 'career_listings'], pages: ['home', 'hizmetler', 'subeler', 'ekip', 'kariyer', 'iletisim'], sectorSections: ['emergency_banner', 'pet_species', 'vaccination_calendar', 'multi_location', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'klan' },
]
