/**
 * @kepenk/templates — P1 Muhasebeci + Emlakçı + Özel Ders + Kuyumcu Themes (20 themes)
 */
import type { P0ThemeDef } from './p0-themes'

// ═══ MUHASEBECI ═══
export const MUHASEBECI_THEMES: P0ThemeDef[] = [
  { id: 'muhasebe-defter', name: 'Defter', sectorId: 'muhasebeci', plan: 'free', description: 'Mali müşavir. Lacivert, vergi takvimi, sektör listesi.', designPhilosophy: 'Lacivert güven. Plus Jakarta Sans. Vergi takvimi + müşteri sektörleri + gizlilik güvencesi.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1E3A5F', '--color-accent-hover': '#152D4A', '--color-surface': '#F0F4F8', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'services::card_grid', 'client_industries', 'confidentiality::banner', 'tax_calendar', 'about::split_left', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['client_industries', 'confidentiality', 'tax_calendar'], animationLevel: 'css-only', demoBusinessKey: 'defter' },
  { id: 'muhasebe-beyan', name: 'Beyan', sectorId: 'muhasebeci', plan: 'starter', description: 'Muhasebe bürosu. Teal, ekip, süreç adımları.', designPhilosophy: 'Teal profesyonellik. 3 mali müşavir ekip, process steps, istatistikler.', isDark: false, fonts: { heading: { family: 'IBM Plex Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0D9488', '--color-accent-hover': '#0F766E', '--font-heading': "'IBM Plex Sans', sans-serif",
    }, homeSections: ['hero::split_left', 'services::card_grid', 'process_steps::horizontal_timeline', 'team::card_horizontal', 'stats::animated_row', 'testimonials::carousel', 'faq::accordion', 'confidentiality::banner', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'iletisim'], sectorSections: ['client_industries', 'confidentiality', 'tax_calendar'], animationLevel: 'framer-basic', demoBusinessKey: 'beyan' },
  { id: 'muhasebe-bilanco', name: 'Bilanço', sectorId: 'muhasebeci', plan: 'growth', description: 'Dijital muhasebe. Mavi, bulut teknoloji, e-fatura vurgusu.', designPhilosophy: 'Mavi dijital. Video modern ofis. Bulut yazılım showcase, e-fatura/e-defter.', isDark: false, fonts: { heading: { family: 'Bitter', weights: [400, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'Bitter', serif",
    }, homeSections: ['hero::video_cinematic', 'services::card_grid', 'technology_showcase', 'stats::animated_row', 'blog_preview', 'testimonials::carousel', 'tax_calendar', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'blog', 'iletisim'], sectorSections: ['client_industries', 'confidentiality', 'tax_calendar', 'technology_showcase'], animationLevel: 'framer-full', demoBusinessKey: 'bilanco' },
  { id: 'muhasebe-denetim', name: 'Denetim', sectorId: 'muhasebeci', plan: 'pro', description: 'YMM bağımsız denetim. Koyu lacivert, akademik.', designPhilosophy: 'Cormorant Garamond akademik. Lacivert ciddiyet. Mevzuat makaleleri, ödüller.', isDark: false, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'Source Sans 3', weights: [400, 600] } }, cssOverrides: { '--color-accent': '#1A1A2E', '--color-accent-hover': '#0F0F1E', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'Source Sans 3', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'services::editorial_zigzag', 'team::full_page_snap', 'awards_press', 'blog_preview', 'stats::animated_row', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'ekip', 'blog', 'iletisim'], sectorSections: ['client_industries', 'confidentiality', 'tax_calendar', 'awards_press'], animationLevel: 'gsap-allowed', demoBusinessKey: 'denetim' },
  { id: 'muhasebe-holding', name: 'Holding', sectorId: 'muhasebeci', plan: 'enterprise', description: 'Muhasebe grubu. Kurumsal, ERP entegrasyon, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, ERP entegrasyon paketi, franchise.', isDark: false, fonts: { heading: { family: 'Manrope', weights: [500, 600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1E3A5F', '--color-accent-hover': '#152D4A', '--font-heading': "'Manrope', sans-serif", }, homeSections: ['hero::video_showreel', 'quick_access_cards', 'services::filtered_tabs', 'multi_location', 'corporate_membership', 'career_listings', 'franchise_section'], pages: ['home', 'hizmetler', 'ofisler', 'kurumsal', 'kariyer', 'bayilik', 'iletisim'], sectorSections: ['client_industries', 'confidentiality', 'tax_calendar', 'multi_location', 'career_listings', 'franchise_section', 'corporate_membership', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'holding' },
]

// ═══ EMLAKÇI ═══
export const EMLAKCI_THEMES: P0ThemeDef[] = [
  { id: 'emlak-anahtar', name: 'Anahtar', sectorId: 'emlakci', plan: 'free', description: 'Emlakçı. Mavi, ilan listesi, ücretsiz değerleme.', designPhilosophy: 'Mavi güven. Plus Jakarta Sans. 6 ilan kartı + ücretsiz ekspertiz CTA.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'property_listing::card_grid', 'free_valuation', 'about::split_left', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['property_listing', 'free_valuation'], animationLevel: 'css-only', demoBusinessKey: 'anahtar' },
  { id: 'emlak-vitrin', name: 'Vitrin', sectorId: 'emlakci', plan: 'starter', description: 'Gayrimenkul. Teal, search hero, satılan portföy.', designPhilosophy: 'Teal güven. Search hero filtreler. Satılan portföy istatistik + testimonials.', isDark: false, fonts: { heading: { family: 'Libre Baskerville', weights: [400, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0D9488', '--color-accent-hover': '#0F766E', '--font-heading': "'Libre Baskerville', serif",
    }, homeSections: ['hero::search_centric', 'property_search', 'property_listing::card_grid', 'sold_showcase', 'testimonials::carousel', 'faq::accordion', 'free_valuation', 'contact::split_form_map'], pages: ['home', 'ilanlar', 'iletisim'], sectorSections: ['property_search', 'property_listing', 'sold_showcase', 'free_valuation'], animationLevel: 'framer-basic', demoBusinessKey: 'vitrin' },
  { id: 'emlak-konak', name: 'Konak', sectorId: 'emlakci', plan: 'growth', description: 'Emlak danışmanlığı. Lacivert, gelişmiş filtre, blog.', designPhilosophy: 'Lacivert profesyonellik. Tab filtreleme, süreç adımları, hizmet bölgeleri.', isDark: false, fonts: { heading: { family: 'Raleway', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1E40AF', '--color-accent-hover': '#1E3A8A', '--font-heading': "'Raleway', sans-serif",
    }, homeSections: ['hero::search_centric', 'property_listing::card_grid', 'process_steps::horizontal_timeline', 'team::card_horizontal', 'stats::animated_row', 'service_area::map_districts', 'blog_preview', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'ilanlar', 'ekip', 'blog', 'iletisim'], sectorSections: ['property_search', 'property_listing', 'sold_showcase', 'free_valuation', 'service_area'], animationLevel: 'framer-full', demoBusinessKey: 'konak' },
  { id: 'emlak-prestij', name: 'Prestij', sectorId: 'emlakci', plan: 'pro', description: 'Lüks gayrimenkul. Koyu, altın, Boğaz villa.', designPhilosophy: 'Siyah-altın premium. Lüks villa/penthouse panoramik slider. Signature satışlar.', isDark: true, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#C9A84C', '--color-accent-hover': '#B8952F', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'property_listing::card_grid', 'project_story', 'gallery::horizontal_snap', 'instagram_feed', 'testimonials::editorial_single', 'contact::split_form_map'], pages: ['home', 'portfoy', 'hikayeler', 'iletisim'], sectorSections: ['property_listing', 'project_story', 'free_valuation'], animationLevel: 'gsap-allowed', demoBusinessKey: 'prestij' },
  { id: 'emlak-metropol', name: 'Metropol', sectorId: 'emlakci', plan: 'enterprise', description: 'Emlak grubu. Kurumsal, 8 ofis, mega arama, franchise.', designPhilosophy: 'Syne kurumsal. Quick access, mega arama, 8 ofis harita, franchise.', isDark: false, fonts: { heading: { family: 'Montserrat', weights: [500, 600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'Montserrat', sans-serif", }, homeSections: ['hero::search_centric', 'quick_access_cards', 'property_listing::card_grid', 'multi_location', 'property_search', 'franchise_section', 'career_listings'], pages: ['home', 'ilanlar', 'ofisler', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['property_search', 'property_listing', 'free_valuation', 'multi_location', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'metropol' },
]

// ═══ ÖZEL DERS ═══
export const OZELDERS_THEMES: P0ThemeDef[] = [
  { id: 'ders-kalem', name: 'Kalem', sectorId: 'ozelders', plan: 'free', description: 'Özel ders öğretmeni. Mor, konu grid, ücretsiz deneme.', designPhilosophy: 'Mor eğitim + motivasyon. Plus Jakarta Sans. Subject grid emoji + seviyeler. Free trial CTA.', isDark: false, fonts: { heading: { family: 'Poppins', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--color-accent-hover': '#6D28D9', '--color-surface': '#F5F3FF', '--font-heading': "'Poppins', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'subject_grid', 'about::split_left', 'free_trial::banner', 'working_hours::compact', 'contact::simple_form'], pages: ['home'], sectorSections: ['subject_grid', 'free_trial', 'success_stories'], animationLevel: 'css-only', demoBusinessKey: 'kalem' },
  { id: 'ders-sinif', name: 'Sınıf', sectorId: 'ozelders', plan: 'starter', description: 'Eğitim merkezi. Mor, paketler, başarı hikayeleri.', designPhilosophy: 'Mor güven. Pricing paketler, başarı hikayeleri, online/yüz yüze seçim.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--color-accent-hover': '#6D28D9', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['hero::split_left', 'subject_grid', 'membership_pricing::columns', 'success_stories::cards', 'online_offline_toggle', 'team::card_horizontal', 'testimonials::carousel', 'free_trial::banner', 'contact::split_form_map'], pages: ['home', 'dersler', 'iletisim'], sectorSections: ['subject_grid', 'free_trial', 'success_stories', 'online_offline_toggle', 'membership_pricing'], animationLevel: 'framer-basic', demoBusinessKey: 'sinif' },
  { id: 'ders-akademi', name: 'Akademi', sectorId: 'ozelders', plan: 'growth', description: 'Online kurs. Mor, video hero, ders programı, sınav stratejisi.', designPhilosophy: 'Mor dijital eğitim. Video online ders. Genişletilmiş sınav listesi, haftalık program.', isDark: false, fonts: { heading: { family: 'Work Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--color-accent-hover': '#6D28D9', '--font-heading': "'Work Sans', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'subject_grid', 'class_schedule::day_tabs', 'success_stories::carousel', 'stats::animated_row', 'blog_preview', 'testimonials::carousel', 'free_trial::banner', 'contact::split_form_map'], pages: ['home', 'kurslar', 'program', 'blog', 'iletisim'], sectorSections: ['subject_grid', 'free_trial', 'success_stories', 'class_schedule'], animationLevel: 'framer-full', demoBusinessKey: 'akademi' },
  { id: 'ders-kolej', name: 'Kolej', sectorId: 'ozelders', plan: 'pro', description: 'Eğitim merkezi. Lacivert, search hero, branş filtresi.', designPhilosophy: 'Lacivert akademik. Search hero "Hangi dersi arıyorsunuz?". Branş bazlı ekip filtresi.', isDark: false, fonts: { heading: { family: 'Alegreya', weights: [400, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1E40AF', '--color-accent-hover': '#1E3A8A', '--font-heading': "'Alegreya', serif",
    }, homeSections: ['hero::search_centric', 'subject_grid', 'class_schedule::table', 'team::filterable_grid', 'blog_preview', 'awards_press', 'success_stories::carousel', 'testimonials::grid_cards', 'contact::split_form_map'], pages: ['home', 'dersler', 'egitmenler', 'blog', 'iletisim'], sectorSections: ['subject_grid', 'free_trial', 'success_stories', 'class_schedule', 'awards_press'], animationLevel: 'gsap-allowed', demoBusinessKey: 'kolej' },
  { id: 'ders-kampus', name: 'Kampüs', sectorId: 'ozelders', plan: 'enterprise', description: 'Eğitim grubu zinciri. Kurumsal, çoklu şube, franchise.', designPhilosophy: 'Syne kurumsal. Quick access, multi-location, franchise, kariyer.', isDark: false, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--color-accent-hover': '#6D28D9', '--font-heading': "'Syne', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'subject_grid', 'multi_location', 'success_stories::carousel', 'franchise_section', 'career_listings'], pages: ['home', 'kurslar', 'subeler', 'basarilar', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['subject_grid', 'free_trial', 'success_stories', 'multi_location', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'kampus' },
]

// ═══ KUYUMCU ═══
export const KUYUMCU_THEMES: P0ThemeDef[] = [
  { id: 'kuyumcu-halka', name: 'Halka', sectorId: 'kuyumcu', plan: 'free', description: 'Semt kuyumcusu. Koyu, altın, canlı fiyat bandı kritik.', designPhilosophy: 'Siyah-altın lüks temel. Syne modern. gold_price_ticker HER ZAMAN header altında.', isDark: true, fonts: { heading: { family: 'EB Garamond', weights: [400, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#D4AF37', '--color-accent-hover': '#C9A22E', '--font-heading': "'EB Garamond', serif",
    }, homeSections: ['gold_price_ticker::top_bar', 'hero::fullscreen_overlay', 'jewelry_grid::carousel', 'certifications::grid', 'about::split_left', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['gold_price_ticker', 'jewelry_grid', 'certifications'], animationLevel: 'css-only', demoBusinessKey: 'halka' },
  { id: 'kuyumcu-pirlanta', name: 'Pırlanta', sectorId: 'kuyumcu', plan: 'starter', description: 'Mücevherat. Koyu, altın serif, filtered grid, eski altın alım.', designPhilosophy: 'Cormorant Garamond lüks. Altın ışıltı close-up slider. Filtreli ürün grid, eski altın alım.', isDark: true, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#D4AF37', '--color-accent-hover': '#C9A22E', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['gold_price_ticker::top_bar', 'hero::fullscreen_overlay', 'jewelry_grid::filtered_grid', 'gold_buyback', 'custom_design', 'testimonials::carousel', 'instagram_feed', 'contact::split_form_map'], pages: ['home', 'urunler', 'iletisim'], sectorSections: ['gold_price_ticker', 'jewelry_grid', 'gold_buyback', 'custom_design'], animationLevel: 'framer-basic', demoBusinessKey: 'pirlanta' },
  { id: 'kuyumcu-mucevher', name: 'Mücevher', sectorId: 'kuyumcu', plan: 'growth', description: 'Mücevher house. Koyu, altın, video tanıtım, e-ticaret.', designPhilosophy: 'Koyu lüks + video. Ürün grid e-ticaret boyutu. Tasarım süreç adımları.', isDark: true, fonts: { heading: { family: 'Playfair Display', weights: [400, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#D4AF37', '--color-accent-hover': '#C9A22E', '--font-heading': "'Playfair Display', serif",
    }, homeSections: ['gold_price_ticker::top_bar', 'hero::video_cinematic', 'jewelry_grid::filtered_grid', 'process_steps::horizontal_timeline', 'gallery::horizontal_snap', 'stats::dark_bar', 'blog_preview', 'testimonials::marquee', 'cta::full_width_banner'], pages: ['home', 'urunler', 'blog', 'iletisim'], sectorSections: ['gold_price_ticker', 'jewelry_grid', 'gold_buyback', 'custom_design'], animationLevel: 'framer-full', demoBusinessKey: 'mucevher' },
  { id: 'kuyumcu-atolye', name: 'Atölye', sectorId: 'kuyumcu', plan: 'pro', description: 'Zanaatkar kuyumcu. Koyu, bakır, el yapımı portfolyo.', designPhilosophy: 'Bakır accent zanaatçılık. Cormorant Garamond zarif. Ken Burns atölye. El yapımı işler portfolyo.', isDark: true, fonts: { heading: { family: 'Gilda Display', weights: [400] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#B87333', '--color-accent-hover': '#A06328', '--font-heading': "'Gilda Display', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['gold_price_ticker::card', 'hero::fullscreen_kenburns', 'philosophy', 'portfolio_grid::masonry_lightbox', 'team::full_page_snap', 'awards_press', 'gallery::horizontal_snap', 'booking_inquiry', 'testimonials::editorial_single', 'contact::split_form_map'], pages: ['home', 'galeri', 'usta', 'siparis', 'iletisim'], sectorSections: ['gold_price_ticker', 'jewelry_grid', 'portfolio_grid', 'booking_inquiry', 'awards_press'], animationLevel: 'gsap-allowed', demoBusinessKey: 'atolye' },
  { id: 'kuyumcu-imparator', name: 'İmparator', sectorId: 'kuyumcu', plan: 'enterprise', description: 'Altın zinciri. Beyaz+altın, 12 mağaza, al/sat, franchise.', designPhilosophy: 'Syne kurumsal. Beyaz base (enterprise farklılığı). Quick access, mega grid, franchise.', isDark: false, fonts: { heading: { family: 'Josefin Sans', weights: [400, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#D4AF37', '--color-accent-hover': '#C9A22E', '--font-heading': "'Josefin Sans', sans-serif", }, homeSections: ['gold_price_ticker::top_bar', 'hero::promo_carousel', 'quick_access_cards', 'jewelry_grid::filtered_grid', 'multi_location', 'gold_buyback', 'testimonials::marquee', 'stats::dark_bar', 'loyalty_program', 'franchise_section', 'career_listings'], pages: ['home', 'urunler', 'magazalar', 'alsat', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['gold_price_ticker', 'jewelry_grid', 'gold_buyback', 'multi_location', 'franchise_section', 'career_listings', 'quick_access_cards', 'loyalty_program'], animationLevel: 'gsap-allowed', demoBusinessKey: 'imparator' },
]
