/**
 * @kepenk/templates — P1 Elektrikçi + Tesisatçı Themes (10 themes)
 */
import type { P0ThemeDef } from './p0-themes'

export const ELEKTRIKCI_THEMES: P0ThemeDef[] = [
  { id: 'elektrik-akim', name: 'Akım', sectorId: 'elektrikci', plan: 'free', description: 'Elektrikçi. Sarı-beyaz, acil banner, sertifika.', designPhilosophy: 'Sarı enerji + uyarı. Outfit heading teknik. ACİL BANNER en üstte. Ustalık belgesi sertifika.', isDark: false, fonts: { heading: { family: 'Outfit', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#F59E0B', '--color-accent-hover': '#D97706', '--color-text-on-accent': '#000000', '--font-heading': "'Outfit', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::fullscreen_overlay', 'services::card_grid', 'certifications::grid', 'warranty_badge::row', 'service_area::list_only', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['emergency_banner', 'certifications', 'warranty_badge', 'service_area'], animationLevel: 'css-only', demoBusinessKey: 'akim' },
  { id: 'elektrik-volt', name: 'Volt', sectorId: 'elektrikci', plan: 'starter', description: 'Elektrik servisi. Koyu sarı-siyah, şeffaf fiyat.', designPhilosophy: 'Sarı-siyah endüstriyel. Tehlike şeridi estetiği. Process steps + before/after.', isDark: true, fonts: { heading: { family: 'IBM Plex Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#EAB308', '--color-accent-hover': '#CA8A04', '--color-text-on-accent': '#000000', '--color-bg': '#111111', '--font-heading': "'IBM Plex Sans', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::fullscreen_overlay', 'services::card_grid', 'process_steps::horizontal_timeline', 'work_before_after', 'testimonials::carousel', 'faq::accordion', 'warranty_badge::row', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'iletisim'], sectorSections: ['emergency_banner', 'certifications', 'warranty_badge', 'service_area', 'work_before_after'], animationLevel: 'framer-basic', demoBusinessKey: 'volt' },
  { id: 'elektrik-sebeke', name: 'Şebeke', sectorId: 'elektrikci', plan: 'growth', description: 'Akıllı ev. Mavi, teknoloji showcase, proje seçici.', designPhilosophy: 'Mavi teknoloji. Akıllı ev sistemleri showcase. Proje türü seçici yönlendirme.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::video_cinematic', 'project_type_selector', 'services::card_grid', 'technology_showcase', 'stats::animated_row', 'gallery::masonry', 'blog_preview', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'galeri', 'blog', 'iletisim'], sectorSections: ['emergency_banner', 'certifications', 'warranty_badge', 'service_area', 'project_type_selector', 'technology_showcase'], animationLevel: 'framer-full', demoBusinessKey: 'sebeke' },
  { id: 'elektrik-enerji', name: 'Enerji', sectorId: 'elektrikci', plan: 'pro', description: 'Taahhüt firması. Lacivert, proje portfolyoları, referanslar.', designPhilosophy: 'Lacivert ciddiyet. Endüstriyel projeler, referans firmalar, tamamlanan işler.', isDark: false, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1E40AF', '--color-accent-hover': '#1E3A8A', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::fullscreen_kenburns', 'services::card_grid', 'portfolio_grid::masonry_lightbox', 'team::card_horizontal', 'blog_preview', 'certifications::carousel', 'stats::animated_row', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'projeler', 'ekip', 'iletisim'], sectorSections: ['emergency_banner', 'certifications', 'warranty_badge', 'service_area', 'portfolio_grid'], animationLevel: 'gsap-allowed', demoBusinessKey: 'enerji' },
  { id: 'elektrik-grid', name: 'Grid', sectorId: 'elektrikci', plan: 'enterprise', description: 'Elektrik servis ağı. Kurumsal, bakım anlaşması, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, bakım anlaşması, franchise ağı.', isDark: false, fonts: { heading: { family: 'Archivo Black', weights: [400] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#F59E0B', '--color-accent-hover': '#D97706', '--font-heading': "'Archivo Black', sans-serif", }, homeSections: ['emergency_banner', 'hero::video_showreel', 'quick_access_cards', 'multi_location', 'corporate_membership', 'career_listings', 'franchise_section'], pages: ['home', 'hizmetler', 'subeler', 'bakim', 'kariyer', 'bayilik', 'iletisim'], sectorSections: ['emergency_banner', 'certifications', 'warranty_badge', 'service_area', 'multi_location', 'career_listings', 'franchise_section', 'corporate_membership', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'grid' },
]

export const TESISATCI_THEMES: P0ThemeDef[] = [
  { id: 'tesisat-damla', name: 'Damla', sectorId: 'tesisatci', plan: 'free', description: 'Tesisatçı. Mavi-beyaz, acil su kaçağı banner.', designPhilosophy: 'Mavi su teması. Outfit heading. SU KAÇAĞI ACİL banner. Sertifika + garanti.', isDark: false, fonts: { heading: { family: 'Rubik', weights: [400, 500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0EA5E9', '--color-accent-hover': '#0284C7', '--font-heading': "'Rubik', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::fullscreen_overlay', 'services::card_grid', 'certifications::grid', 'warranty_badge::row', 'service_area::list_only', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['emergency_banner', 'certifications', 'warranty_badge', 'service_area'], animationLevel: 'css-only', demoBusinessKey: 'damla' },
  { id: 'tesisat-boru', name: 'Boru', sectorId: 'tesisatci', plan: 'starter', description: 'Tesisat servisi. Koyu mavi-siyah, iş öncesi/sonrası.', designPhilosophy: 'Mavi-siyah endüstriyel. Before/after iş fotoğrafları, process steps.', isDark: true, fonts: { heading: { family: 'Outfit', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0EA5E9', '--color-accent-hover': '#0284C7', '--color-bg': '#111111', '--font-heading': "'Outfit', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::fullscreen_overlay', 'services::card_grid', 'process_steps::horizontal_timeline', 'work_before_after', 'testimonials::carousel', 'faq::accordion', 'warranty_badge::row', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'iletisim'], sectorSections: ['emergency_banner', 'certifications', 'warranty_badge', 'service_area', 'work_before_after'], animationLevel: 'framer-basic', demoBusinessKey: 'boru' },
  { id: 'tesisat-akis', name: 'Akış', sectorId: 'tesisatci', plan: 'growth', description: 'Tesisat & Kombi. Mavi, proje seçici, galeri.', designPhilosophy: 'Mavi modernlik. Proje türü seçici (Konut/Ticari/Kombi). Stats + galeri.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0EA5E9', '--color-accent-hover': '#0284C7', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::video_cinematic', 'project_type_selector', 'services::card_grid', 'stats::animated_row', 'gallery::masonry', 'testimonials::carousel', 'blog_preview', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'galeri', 'blog', 'iletisim'], sectorSections: ['emergency_banner', 'certifications', 'warranty_badge', 'service_area', 'project_type_selector'], animationLevel: 'framer-full', demoBusinessKey: 'akis' },
  { id: 'tesisat-kaynak', name: 'Kaynak', sectorId: 'tesisatci', plan: 'pro', description: 'Endüstriyel tesisat. Lacivert, proje portfolyo.', designPhilosophy: 'Lacivert endüstriyel ciddiyet. Tamamlanan projeler portfolyosu, referanslar.', isDark: false, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1E40AF', '--color-accent-hover': '#1E3A8A', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::fullscreen_kenburns', 'services::card_grid', 'portfolio_grid::masonry_lightbox', 'team::card_horizontal', 'certifications::carousel', 'stats::animated_row', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'projeler', 'ekip', 'iletisim'], sectorSections: ['emergency_banner', 'certifications', 'warranty_badge', 'service_area', 'portfolio_grid'], animationLevel: 'gsap-allowed', demoBusinessKey: 'kaynak' },
  { id: 'tesisat-sehirsuyu', name: 'ŞehirSuyu', sectorId: 'tesisatci', plan: 'enterprise', description: 'Tesisat grubu. Kurumsal, bakım anlaşması, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, bakım anlaşması, franchise ağı.', isDark: false, fonts: { heading: { family: 'Oswald', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0EA5E9', '--color-accent-hover': '#0284C7', '--font-heading': "'Oswald', sans-serif", }, homeSections: ['emergency_banner', 'hero::video_showreel', 'quick_access_cards', 'multi_location', 'corporate_membership', 'career_listings', 'franchise_section'], pages: ['home', 'hizmetler', 'subeler', 'bakim', 'kariyer', 'bayilik', 'iletisim'], sectorSections: ['emergency_banner', 'certifications', 'warranty_badge', 'service_area', 'multi_location', 'career_listings', 'franchise_section', 'corporate_membership', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'sehirsuyu' },
]
