/**
 * @kepenk/templates — P2 Themes Batch B: Mimarlık, Sigorta, Sürücü, Dil, Yoga (25 themes)
 */
import type { P0ThemeDef } from './p0-themes'

// ═══ MİMARLIK ═══
export const MIMARLIK_THEMES: P0ThemeDef[] = [
  { id: 'mimarlik-cizgi', name: 'Çizgi', sectorId: 'mimarlik', plan: 'free', description: 'Freelance mimar. Ultra minimal, siyah-beyaz, portfolyo odaklı.', designPhilosophy: 'Syne siyah-beyaz minimalizm. Tek güçlü fotoğraf hero. Masonry portfolyo. Metin minimum.', isDark: false, fonts: { heading: { family: 'Space Grotesk', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#111111', '--color-accent-hover': '#333333', '--font-heading': "'Space Grotesk', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'portfolio_grid::masonry_lightbox', 'about::split_left', 'contact::simple_form'], pages: ['home'], sectorSections: ['portfolio_grid'], animationLevel: 'css-only', demoBusinessKey: 'cizgi' },
  { id: 'mimarlik-perspektif', name: 'Perspektif', sectorId: 'mimarlik', plan: 'starter', description: 'Küçük mimarlık ofisi. Siyah, proje hikayeleri, süreç.', designPhilosophy: 'Syne modern. Proje hikayeleri editoryal. Süreç adımları ile profesyonellik.', isDark: false, fonts: { heading: { family: 'Libre Caslon Text', weights: [400, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#111111', '--color-accent-hover': '#333333', '--font-heading': "'Libre Caslon Text', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'portfolio_grid::masonry_lightbox', 'project_story', 'process_steps::horizontal_timeline', 'team::card_horizontal', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'projeler', 'iletisim'], sectorSections: ['portfolio_grid', 'project_story'], animationLevel: 'framer-basic', demoBusinessKey: 'perspektif' },
  { id: 'mimarlik-struktur', name: 'Strüktür', sectorId: 'mimarlik', plan: 'growth', description: 'Mimarlık firması. Koyu, gri accent, showreel, ödüller.', designPhilosophy: 'Gri-koyu minimal. Video showreel. Filtered portfolio + ödüller.', isDark: true, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#6B7280', '--color-accent-hover': '#9CA3AF', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['hero::video_showreel', 'portfolio_grid::masonry_lightbox', 'project_story', 'stats::dark_bar', 'awards_press', 'testimonials::marquee', 'contact::split_form_map'], pages: ['home', 'projeler', 'hikayeler', 'iletisim'], sectorSections: ['portfolio_grid', 'project_story', 'awards_press'], animationLevel: 'framer-full', demoBusinessKey: 'struktur' },
  { id: 'mimarlik-tasarim', name: 'Studio XYZ', sectorId: 'mimarlik', plan: 'enterprise', description: 'Brutalist Mimarlık portfolyosu.', designPhilosophy: 'Anıtsal tipografi, Edge-to-edge resimler, Space Grotesk minimalizm.', isDark: false, fonts: { heading: { family: 'Space Grotesk', weights: [400, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#FF3B00', '--font-heading': "'Space Grotesk', sans-serif" }, homeSections: ['hero::mimarlik_tasarim_hero', 'portfolio_grid::mimarlik_tasarim_portfolio', 'process_steps::mimarlik_tasarim_process', 'contact::mimarlik_tasarim_contact'], pages: ['home'], sectorSections: ['portfolio_grid'], animationLevel: 'framer-full', demoBusinessKey: 'mimarlik-tasarim' },
  { id: 'mimarlik-yapi', name: 'Yapı', sectorId: 'mimarlik', plan: 'enterprise', description: 'Büyük mimarlık ajansı. Siyah, video showreel, çoklu ofis.', designPhilosophy: 'Syne kurumsal. Multi-location ofisler, filterable ekip, kariyer.', isDark: false, fonts: { heading: { family: 'Archivo', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#111111', '--color-accent-hover': '#333333', '--font-heading': "'Archivo', sans-serif", }, homeSections: ['hero::video_showreel', 'quick_access_cards', 'portfolio_grid::masonry_lightbox', 'multi_location', 'team::filterable_grid', 'career_listings'], pages: ['home', 'projeler', 'ofisler', 'ekip', 'kariyer', 'iletisim'], sectorSections: ['portfolio_grid', 'project_story', 'multi_location', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'yapi' },
]

// ═══ SİGORTA ═══
export const SIGORTA_THEMES: P0ThemeDef[] = [
  { id: 'sigorta-kalkan', name: 'Kalkan', sectorId: 'sigorta', plan: 'free', description: 'Sigorta acentesi. Mavi, sigorta türleri grid, ücretsiz teklif.', designPhilosophy: 'Mavi güven. Sigorta türleri grid ile hızlı yönlendirme. Free quote CTA.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'services::card_grid', 'about::split_left', 'free_quote', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['free_quote'], animationLevel: 'css-only', demoBusinessKey: 'kalkan' },
  { id: 'sigorta-police', name: 'Poliçe', sectorId: 'sigorta', plan: 'starter', description: 'Sigorta acentesi. Teal, marka logoları, filtered tabs.', designPhilosophy: 'Teal profesyonellik. Sigorta firma logoları güven. FAQ.', isDark: false, fonts: { heading: { family: 'IBM Plex Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0D9488', '--color-accent-hover': '#0F766E', '--font-heading': "'IBM Plex Sans', sans-serif",
    }, homeSections: ['hero::split_left', 'services::filtered_tabs', 'insurance_logos::grid', 'free_quote', 'testimonials::carousel', 'faq::accordion', 'contact::split_form_map'], pages: ['home', 'sigortalar', 'iletisim'], sectorSections: ['free_quote', 'insurance_logos'], animationLevel: 'framer-basic', demoBusinessKey: 'police' },
  { id: 'sigorta-guvence', name: 'Güvence', sectorId: 'sigorta', plan: 'growth', description: 'Dijital sigorta. Mavi, online poliçe, teknoloji.', designPhilosophy: 'Mavi dijital. Online poliçe teknoloji showcase. Stats + blog.', isDark: false, fonts: { heading: { family: 'Libre Baskerville', weights: [400, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'Libre Baskerville', serif",
    }, homeSections: ['hero::video_cinematic', 'services::filtered_tabs', 'technology_showcase', 'stats::animated_row', 'blog_preview', 'testimonials::carousel', 'free_quote', 'contact::split_form_map'], pages: ['home', 'sigortalar', 'blog', 'iletisim'], sectorSections: ['free_quote', 'insurance_logos', 'technology_showcase'], animationLevel: 'framer-full', demoBusinessKey: 'guvence' },
  { id: 'sigorta-koruma', name: 'Koruma', sectorId: 'sigorta', plan: 'pro', description: 'Bağımsız danışman. Lacivert, editoryal, ödüller.', designPhilosophy: 'Lacivert güven. Cormorant Garamond ciddiyet. Ödüller + blog makaleler.', isDark: false, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'Source Sans 3', weights: [400, 600] } }, cssOverrides: { '--color-accent': '#1E3A5F', '--color-accent-hover': '#152D4A', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'Source Sans 3', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'services::editorial_zigzag', 'awards_press', 'blog_preview', 'testimonials::editorial_single', 'free_quote', 'contact::split_form_map'], pages: ['home', 'sigortalar', 'blog', 'iletisim'], sectorSections: ['free_quote', 'awards_press'], animationLevel: 'gsap-allowed', demoBusinessKey: 'koruma' },
  { id: 'sigorta-holding', name: 'Holding', sectorId: 'sigorta', plan: 'enterprise', description: 'Sigorta holdingi. Kurumsal, çoklu ofis, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, kariyer, franchise.', isDark: false, fonts: { heading: { family: 'Manrope', weights: [500, 600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1E40AF', '--color-accent-hover': '#1E3A8A', '--font-heading': "'Manrope', sans-serif", }, homeSections: ['hero::video_showreel', 'quick_access_cards', 'multi_location', 'franchise_section', 'career_listings'], pages: ['home', 'sigortalar', 'ofisler', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['free_quote', 'multi_location', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'holding' },
]

// ═══ SÜRÜCÜ ═══
export const SURUCU_THEMES: P0ThemeDef[] = [
  { id: 'surucu-direksiyon', name: 'Direksiyon', sectorId: 'surucu', plan: 'free', description: 'Sürücü kursu. Mavi, paketler, başarı oranı.', designPhilosophy: 'Mavi güven. Fiyat paketleri ön planda. %92 başarı rakamı büyük gösterilmeli.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'membership_pricing::columns', 'success_stories::stats_row', 'about::split_left', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['membership_pricing', 'success_stories'], animationLevel: 'css-only', demoBusinessKey: 'direksiyon' },
  { id: 'surucu-serit', name: 'Şerit', sectorId: 'surucu', plan: 'starter', description: 'Sürücü okulu. Mavi, eğitmenler, araç filosu, süreç.', designPhilosophy: 'Mavi güvenilir. Eğitmen profilleri + araç galerisi + process steps.', isDark: false, fonts: { heading: { family: 'Rubik', weights: [400, 500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'Rubik', sans-serif",
    }, homeSections: ['hero::split_left', 'membership_pricing::columns', 'team::card_horizontal', 'gallery::masonry', 'process_steps::horizontal_timeline', 'testimonials::carousel', 'faq::accordion', 'contact::split_form_map'], pages: ['home', 'kurslar', 'iletisim'], sectorSections: ['membership_pricing', 'success_stories'], animationLevel: 'framer-basic', demoBusinessKey: 'serit' },
  { id: 'surucu-pilot', name: 'Pilot', sectorId: 'surucu', plan: 'growth', description: 'Modern sürücü kursu. Mavi, video, ders programı.', designPhilosophy: 'Mavi modern. Video hero direksiyon dersi. Ders programı + istatistikler.', isDark: false, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'membership_pricing::columns', 'class_schedule::day_tabs', 'success_stories::carousel', 'stats::animated_row', 'testimonials::carousel', 'blog_preview', 'contact::split_form_map'], pages: ['home', 'kurslar', 'blog', 'iletisim'], sectorSections: ['membership_pricing', 'success_stories', 'class_schedule'], animationLevel: 'framer-full', demoBusinessKey: 'pilot' },
  { id: 'surucu-akademi', name: 'Akademi', sectorId: 'surucu', plan: 'pro', description: 'Simülatörlü. Lacivert, teknoloji showcase, ödüller.', designPhilosophy: 'Lacivert akademik. Simülatör teknoloji showcase. Blog + ödüller.', isDark: false, fonts: { heading: { family: 'Oswald', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1E40AF', '--color-accent-hover': '#1E3A8A', '--font-heading': "'Oswald', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'membership_pricing::columns', 'technology_showcase', 'team::filterable_grid', 'awards_press', 'blog_preview', 'testimonials::grid_cards', 'contact::split_form_map'], pages: ['home', 'kurslar', 'blog', 'iletisim'], sectorSections: ['membership_pricing', 'success_stories', 'technology_showcase', 'awards_press'], animationLevel: 'gsap-allowed', demoBusinessKey: 'akademi' },
  { id: 'surucu-trafik', name: 'Trafik', sectorId: 'surucu', plan: 'enterprise', description: 'Sürücü kursu zinciri. Kurumsal, filo eğitim, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, filo eğitim anlaşması, franchise.', isDark: false, fonts: { heading: { family: 'Archivo', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'Archivo', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'multi_location', 'corporate_membership', 'franchise_section', 'career_listings'], pages: ['home', 'kurslar', 'subeler', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['membership_pricing', 'success_stories', 'multi_location', 'corporate_membership', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'trafik' },
]

// ═══ DİL ═══
export const DIL_THEMES: P0ThemeDef[] = [
  { id: 'dil-alfabe', name: 'Alfabe', sectorId: 'dil', plan: 'free', description: 'Dil kursu. Mor, dil grid, seviye yolu, ücretsiz test.', designPhilosophy: 'Mor eğitim enerjisi. Dil grid bayrak emojiyle. Seviye yolu (A1→C2). Free trial.', isDark: false, fonts: { heading: { family: 'Poppins', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--color-accent-hover': '#6D28D9', '--font-heading': "'Poppins', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'subject_grid', 'level_path', 'free_trial::banner', 'about::split_left', 'contact::simple_form'], pages: ['home'], sectorSections: ['subject_grid', 'level_path', 'free_trial'], animationLevel: 'css-only', demoBusinessKey: 'alfabe' },
  { id: 'dil-kelime', name: 'Kelime', sectorId: 'dil', plan: 'starter', description: 'Dil kursu. Mor, paketler, başarı hikayeleri.', designPhilosophy: 'Mor güven. Kurs paketleri + IELTS/TOEFL başarılar + online/yüz yüze.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--color-accent-hover': '#6D28D9', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['hero::split_left', 'subject_grid', 'membership_pricing::columns', 'success_stories::cards', 'online_offline_toggle', 'team::card_horizontal', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'kurslar', 'iletisim'], sectorSections: ['subject_grid', 'level_path', 'free_trial', 'success_stories', 'online_offline_toggle', 'membership_pricing'], animationLevel: 'framer-basic', demoBusinessKey: 'kelime' },
  { id: 'dil-konus', name: 'Konuş', sectorId: 'dil', plan: 'growth', description: 'Language lab. Mor, video, ders programı, blog.', designPhilosophy: 'Mor dijital eğitim. Video ders. Ders programı + stats + blog.', isDark: false, fonts: { heading: { family: 'Alegreya', weights: [400, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--color-accent-hover': '#6D28D9', '--font-heading': "'Alegreya', serif",
    }, homeSections: ['hero::video_cinematic', 'subject_grid', 'class_schedule::day_tabs', 'success_stories::carousel', 'stats::animated_row', 'blog_preview', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'kurslar', 'program', 'blog', 'iletisim'], sectorSections: ['subject_grid', 'level_path', 'free_trial', 'success_stories', 'class_schedule'], animationLevel: 'framer-full', demoBusinessKey: 'konus' },
  { id: 'dil-poliglot', name: 'Poliglot', sectorId: 'dil', plan: 'pro', description: 'Premium dil merkezi. Lacivert, editoryal, ödüller.', designPhilosophy: 'Lacivert akademik. Cormorant Garamond. Ödüller + blog + newsletter.', isDark: false, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'Source Sans 3', weights: [400, 600] } }, cssOverrides: { '--color-accent': '#1E40AF', '--color-accent-hover': '#1E3A8A', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'Source Sans 3', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'subject_grid', 'awards_press', 'blog_preview', 'newsletter', 'testimonials::editorial_single', 'contact::split_form_map'], pages: ['home', 'kurslar', 'blog', 'iletisim'], sectorSections: ['subject_grid', 'level_path', 'free_trial', 'awards_press'], animationLevel: 'gsap-allowed', demoBusinessKey: 'poliglot' },
  { id: 'dil-global', name: 'Global', sectorId: 'dil', plan: 'enterprise', description: 'Dil grubu zinciri. Kurumsal, çoklu şube, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, franchise, kariyer.', isDark: false, fonts: { heading: { family: 'Manrope', weights: [500, 600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--color-accent-hover': '#6D28D9', '--font-heading': "'Manrope', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'subject_grid', 'multi_location', 'franchise_section', 'career_listings'], pages: ['home', 'kurslar', 'subeler', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['subject_grid', 'level_path', 'free_trial', 'multi_location', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'global' },
]

// ═══ YOGA ═══
export const YOGA_THEMES: P0ThemeDef[] = [
  { id: 'yoga-nefes', name: 'Nefes', sectorId: 'yoga', plan: 'free', description: 'Yoga stüdyo. Sage, Ken Burns doğa, ders programı.', designPhilosophy: 'Sage yeşil huzur. Cormorant Garamond zarif. Ken Burns yoga doğa. Pricing ön planda.', isDark: false, fonts: { heading: { family: 'Quicksand', weights: [500, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#5E7754', '--color-accent-hover': '#4A6040', '--color-bg': '#FAFBF5', '--color-surface': '#F2F5E8', '--font-heading': "'Quicksand', sans-serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'services::card_grid', 'class_schedule::day_tabs', 'membership_pricing::columns', 'about::split_left', 'contact::simple_form'], pages: ['home'], sectorSections: ['class_schedule', 'membership_pricing'], animationLevel: 'css-only', demoBusinessKey: 'nefes' },
  { id: 'yoga-asana', name: 'Asana', sectorId: 'yoga', plan: 'starter', description: 'Yoga & Pilates. Sage, eğitmenler, galeri.', designPhilosophy: 'Sage topluluk. Eğitmen profilleri, galeri, testimonials, newsletter.', isDark: false, fonts: { heading: { family: 'Libre Caslon Text', weights: [400, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#5E7754', '--color-accent-hover': '#4A6040', '--color-bg': '#FAFBF5', '--font-heading': "'Libre Caslon Text', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::split_left', 'services::card_grid', 'class_schedule::day_tabs', 'trainer_profile', 'gallery::masonry', 'testimonials::carousel', 'newsletter', 'membership_pricing::columns', 'contact::split_form_map'], pages: ['home', 'dersler', 'iletisim'], sectorSections: ['class_schedule', 'membership_pricing', 'trainer_profile'], animationLevel: 'framer-basic', demoBusinessKey: 'asana' },
  { id: 'yoga-reformer', name: 'Reformer', sectorId: 'yoga', plan: 'growth', description: 'Pilates stüdyo. Beyaz-gri, video, transformation.', designPhilosophy: 'Beyaz-gri modern. Video hero reformer. Dönüşüm hikayeleri + blog.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#6B7280', '--color-accent-hover': '#4B5563', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'services::card_grid', 'class_schedule::day_tabs', 'transformation::carousel', 'trainer_profile', 'blog_preview', 'stats::animated_row', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'dersler', 'blog', 'iletisim'], sectorSections: ['class_schedule', 'membership_pricing', 'trainer_profile', 'transformation'], animationLevel: 'framer-full', demoBusinessKey: 'reformer' },
  { id: 'yoga-zen', name: 'Zen', sectorId: 'yoga', plan: 'pro', description: 'Wellness center. Sage, editoryal, e-ticaret.', designPhilosophy: 'Sage zen. Cormorant Garamond zarif. Ödüller, newsletter. Yoga ekipman satışı.', isDark: false, fonts: { heading: { family: 'Spectral', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#5E7754', '--color-accent-hover': '#4A6040', '--color-bg': '#FAFBF5', '--font-heading': "'Spectral', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'services::editorial_zigzag', 'class_schedule::day_tabs', 'awards_press', 'newsletter', 'testimonials::editorial_single', 'membership_pricing::toggle', 'contact::split_form_map'], pages: ['home', 'dersler', 'magaza', 'blog', 'iletisim'], sectorSections: ['class_schedule', 'membership_pricing', 'trainer_profile', 'awards_press'], animationLevel: 'gsap-allowed', demoBusinessKey: 'zen' },
  { id: 'yoga-akis', name: 'Akış', sectorId: 'yoga', plan: 'enterprise', description: 'Yoga zinciri. Sage, çoklu stüdyo, franchise.', designPhilosophy: 'Syne kurumsal + sage. Multi-location, franchise, kariyer.', isDark: false, fonts: { heading: { family: 'Josefin Sans', weights: [400, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#5E7754', '--color-accent-hover': '#4A6040', '--font-heading': "'Josefin Sans', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'class_schedule::day_tabs', 'multi_location', 'franchise_section', 'career_listings'], pages: ['home', 'dersler', 'studyolar', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['class_schedule', 'membership_pricing', 'trainer_profile', 'multi_location', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'akis' },
]
