/**
 * @kepenk/templates — P2 Themes Batch A: Psikolog, Fast Food, Bar, Telefon, Klima (25 themes)
 */
import type { P0ThemeDef } from './p0-themes'

// ═══ PSİKOLOG ═══
export const PSIKOLOG_THEMES: P0ThemeDef[] = [
  { id: 'psikolog-huzur', name: 'Huzur', sectorId: 'psikolog', plan: 'free', description: 'Bireysel psikolog. Sage yeşil, sakin, acil hatlar.', designPhilosophy: 'Sage yeşil RAHATlatıcı. Nunito yuvarlak, sıcak. Ziyaretçi kırılgan — sakin tasarım kritik.', isDark: false, fonts: { heading: { family: 'Nunito', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#5E7754', '--color-accent-hover': '#4A6040', '--color-bg': '#FAFBF5', '--color-surface': '#F2F5E8', '--font-heading': "'Nunito', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'services::card_grid', 'confidentiality::banner', 'about::split_left', 'booking::cta_only', 'crisis_resources', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['confidentiality', 'crisis_resources', 'booking'], animationLevel: 'css-only', demoBusinessKey: 'huzur' },
  { id: 'psikolog-denge', name: 'Denge', sectorId: 'psikolog', plan: 'starter', description: 'Psikoloji merkezi. Mor, seans paketleri, online terapi.', designPhilosophy: 'Mor huzur + derinlik. Online/yüz yüze seçim, seans paketleri.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--color-accent-hover': '#6D28D9', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['hero::split_left', 'services::filtered_tabs', 'online_offline_toggle', 'membership_pricing::columns', 'team::card_horizontal', 'testimonials::carousel', 'faq::accordion', 'crisis_resources', 'contact::split_form_map'], pages: ['home', 'terapiler', 'iletisim'], sectorSections: ['confidentiality', 'crisis_resources', 'booking', 'online_offline_toggle', 'membership_pricing'], animationLevel: 'framer-basic', demoBusinessKey: 'denge' },
  { id: 'psikolog-icgoru', name: 'İçgörü', sectorId: 'psikolog', plan: 'growth', description: 'Terapi merkezi. Mavi, EMDR teknoloji, blog.', designPhilosophy: 'Mavi güven + profesyonellik. EMDR/biofeedback teknoloji showcase. Blog ile bilgi.', isDark: false, fonts: { heading: { family: 'Quicksand', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'Quicksand', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'services::filtered_tabs', 'technology_showcase', 'stats::animated_row', 'blog_preview', 'newsletter', 'testimonials::carousel', 'crisis_resources', 'contact::split_form_map'], pages: ['home', 'terapiler', 'blog', 'iletisim'], sectorSections: ['confidentiality', 'crisis_resources', 'technology_showcase'], animationLevel: 'framer-full', demoBusinessKey: 'icgoru' },
  { id: 'psikolog-bilinc', name: 'Bilinç', sectorId: 'psikolog', plan: 'pro', description: 'Klinik psikolog. Sage, editoryal, akademik yayınlar.', designPhilosophy: 'Cormorant Garamond akademik. Toprak tonları. Film grain. Yayınlar + ödüller.', isDark: false, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'Source Sans 3', weights: [400, 600] } }, cssOverrides: { '--color-accent': '#5E7754', '--color-accent-hover': '#4A6040', '--color-bg': '#FAFBF5', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'Source Sans 3', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'services::editorial_zigzag', 'awards_press', 'blog_preview', 'booking::inline_calendar', 'testimonials::editorial_single', 'crisis_resources', 'contact::split_form_map'], pages: ['home', 'terapiler', 'yayinlar', 'blog', 'iletisim'], sectorSections: ['confidentiality', 'crisis_resources', 'booking', 'awards_press'], animationLevel: 'gsap-allowed', demoBusinessKey: 'bilinc' },
  { id: 'psikolog-merkez', name: 'Merkez', sectorId: 'psikolog', plan: 'enterprise', description: 'Online terapi ağı. Lacivert, search hero, çoklu terapist.', designPhilosophy: 'Syne kurumsal. Search hero ile terapist/yaklaşım arama. Multi-location.', isDark: false, fonts: { heading: { family: 'Manrope', weights: [500, 600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1E40AF', '--color-accent-hover': '#1E3A8A', '--font-heading': "'Manrope', sans-serif", }, homeSections: ['hero::search_centric', 'quick_access_cards', 'multi_location', 'team::filterable_grid', 'career_listings', 'crisis_resources'], pages: ['home', 'terapistler', 'subeler', 'kariyer', 'iletisim'], sectorSections: ['confidentiality', 'crisis_resources', 'multi_location', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'merkez' },
]

// ═══ FAST FOOD ═══
export const FASTFOOD_THEMES: P0ThemeDef[] = [
  { id: 'fastfood-lokma', name: 'Lokma', sectorId: 'fastfood', plan: 'free', description: 'Dürümcü/fast food. Kırmızı, visual menu, WhatsApp sipariş.', designPhilosophy: 'Kırmızı iştah + aciliyet. Outfit heading. Büyük Sipariş Ver butonu. WhatsApp link.', isDark: false, fonts: { heading: { family: 'Outfit', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#DC2626', '--color-accent-hover': '#B91C1C', '--font-heading': "'Outfit', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'menu_display::visual_grid', 'delivery_zone::list_only', 'about::split_left', 'working_hours::compact', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['menu_display', 'delivery_zone'], animationLevel: 'css-only', demoBusinessKey: 'lokma' },
  { id: 'fastfood-kombo', name: 'Kombo', sectorId: 'fastfood', plan: 'starter', description: 'Burger joint. Turuncu, tab menü, kampanyalar.', designPhilosophy: 'Turuncu enerji. Syne heading. Tab menü + kampanya carousel + Instagram.', isDark: false, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#EA580C', '--color-accent-hover': '#C2410C', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['hero::soft_carousel', 'menu_display::visual_grid', 'promotions', 'testimonials::carousel', 'instagram_feed', 'delivery_zone::list_only', 'contact::split_form_map'], pages: ['home', 'menu', 'iletisim'], sectorSections: ['menu_display', 'delivery_zone', 'promotions'], animationLevel: 'framer-basic', demoBusinessKey: 'kombo' },
  { id: 'fastfood-ekspres', name: 'Ekspres', sectorId: 'fastfood', plan: 'growth', description: 'Pizza delivery. Koyu, kırmızı, video, online sipariş.', designPhilosophy: 'Kırmızı-siyah hız. Video hero pizza hazırlanırken. E-ticaret benzeri sipariş.', isDark: true, fonts: { heading: { family: 'Bebas Neue', weights: [400] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#EF4444', '--color-accent-hover': '#DC2626', '--font-heading': "'Bebas Neue', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'menu_display::visual_grid', 'delivery_zone::map_with_zones', 'stats::dark_bar', 'testimonials::marquee', 'cta::full_width_banner'], pages: ['home', 'menu', 'teslimat', 'iletisim'], sectorSections: ['menu_display', 'delivery_zone'], animationLevel: 'framer-full', demoBusinessKey: 'ekspres' },
  { id: 'fastfood-lezzet', name: 'Lezzet', sectorId: 'fastfood', plan: 'pro', description: 'Fast casual premium. Siyah, editoryal menü, şef profili.', designPhilosophy: 'Siyah accent premium fast casual. Cormorant Garamond lüks. Şef profili + blog.', isDark: false, fonts: { heading: { family: 'Archivo Black', weights: [400] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1A1A1A', '--color-accent-hover': '#374151', '--font-heading': "'Archivo Black', sans-serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'menu_display::tab_categories', 'team::full_page_snap', 'blog_preview', 'testimonials::editorial_single', 'contact::split_form_map'], pages: ['home', 'menu', 'hikaye', 'blog', 'iletisim'], sectorSections: ['menu_display'], animationLevel: 'gsap-allowed', demoBusinessKey: 'lezzet' },
  { id: 'fastfood-franchise', name: 'Franchise', sectorId: 'fastfood', plan: 'enterprise', description: 'Burger franchise. Kırmızı, çoklu şube, sadakat, uygulama.', designPhilosophy: 'Syne kurumsal. Quick access, loyalty, franchise. App download CTA.', isDark: false, fonts: { heading: { family: 'Barlow', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#DC2626', '--color-accent-hover': '#B91C1C', '--font-heading': "'Barlow', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'menu_display::visual_grid', 'multi_location', 'loyalty_program', 'franchise_section', 'career_listings'], pages: ['home', 'menu', 'subeler', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['menu_display', 'delivery_zone', 'multi_location', 'loyalty_program', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'franchise' },
]

// ═══ BAR ═══
export const BAR_THEMES: P0ThemeDef[] = [
  { id: 'bar-kadeh', name: 'Kadeh', sectorId: 'bar', plan: 'free', description: 'Meyhane. Koyu, altın, meze menüsü, atmosfer.', designPhilosophy: 'Altın-koyu meyhane sıcaklığı. Playfair Display romantik. Video meyhane atmosferi.', isDark: true, fonts: { heading: { family: 'Playfair Display', weights: [400, 600, 700] }, body: { family: 'Source Sans 3', weights: [400, 600] } }, cssOverrides: { '--color-accent': '#D4A03C', '--color-accent-hover': '#C4902C', '--font-heading': "'Playfair Display', serif", '--font-body': "'Source Sans 3', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'menu_display::drink_menu', 'gallery::masonry', 'about::split_left', 'working_hours::compact', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['menu_display'], animationLevel: 'css-only', demoBusinessKey: 'kadeh' },
  { id: 'bar-kokteyl', name: 'Kokteyl', sectorId: 'bar', plan: 'starter', description: 'Kokteyl bar. Koyu, pembe, happy hour, DJ gecesi.', designPhilosophy: 'Pembe neon-koyu kontrast. Happy hour promotion, DJ/workshop etkinlik takvimi.', isDark: true, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#EC4899', '--color-accent-hover': '#DB2777', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'menu_display::drink_menu', 'promotions', 'class_schedule', 'testimonials::carousel', 'instagram_feed', 'contact::split_form_map'], pages: ['home', 'menu', 'etkinlikler', 'iletisim'], sectorSections: ['menu_display', 'class_schedule', 'promotions'], animationLevel: 'framer-basic', demoBusinessKey: 'kokteyl' },
  { id: 'bar-sahne', name: 'Sahne', sectorId: 'bar', plan: 'growth', description: 'Canlı müzik. Koyu, kırmızı, showreel, etkinlik takvimi.', designPhilosophy: 'Kırmızı enerji. Video showreel canlı performans. Etkinlik takvimi EN KRİTİK.', isDark: true, fonts: { heading: { family: 'Crimson Text', weights: [400, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#EF4444', '--color-accent-hover': '#DC2626', '--font-heading': "'Crimson Text', serif",
    }, homeSections: ['hero::video_showreel', 'class_schedule', 'gallery::horizontal_snap', 'booking_inquiry', 'menu_display::drink_menu', 'stats::dark_bar', 'testimonials::marquee', 'instagram_feed', 'contact::split_form_map'], pages: ['home', 'etkinlikler', 'galeri', 'menu', 'rezervasyon', 'iletisim'], sectorSections: ['menu_display', 'class_schedule', 'booking_inquiry'], animationLevel: 'framer-full', demoBusinessKey: 'sahne' },
  { id: 'bar-lounge', name: 'Lounge', sectorId: 'bar', plan: 'pro', description: 'Premium lounge. Koyu, altın, signature cocktail, art deco.', designPhilosophy: 'Altın art deco. Cormorant Garamond lüks. Signature cocktail hikayeleri. Ken Burns.', isDark: true, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#C9A84C', '--color-accent-hover': '#B8952F', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'menu_display::drink_menu', 'gallery::horizontal_snap', 'awards_press', 'stats::dark_bar', 'testimonials::editorial_single', 'blog_preview', 'booking_inquiry', 'contact::split_form_map'], pages: ['home', 'kokteyl', 'galeri', 'blog', 'rezervasyon', 'iletisim'], sectorSections: ['menu_display', 'booking_inquiry', 'awards_press'], animationLevel: 'gsap-allowed', demoBusinessKey: 'lounge' },
  { id: 'bar-zincir', name: 'Zincir', sectorId: 'bar', plan: 'enterprise', description: 'Bar grubu. Koyu, çoklu mekan, sadakat, franchise.', designPhilosophy: 'Syne kurumsal koyu. Multi-location, etkinlik takvimi, sadakat programı.', isDark: true, fonts: { heading: { family: 'Oswald', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#FAFAFA', '--color-accent-hover': '#E5E5E5', '--color-text-on-accent': '#000000', '--font-heading': "'Oswald', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'multi_location', 'menu_display::drink_menu', 'class_schedule', 'gallery::masonry', 'testimonials::marquee', 'stats::dark_bar', 'loyalty_program', 'franchise_section', 'career_listings'], pages: ['home', 'mekanlar', 'etkinlikler', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['menu_display', 'class_schedule', 'multi_location', 'loyalty_program', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'zincir' },
]

// ═══ TELEFON TAMİRİ ═══
export const TELEFON_THEMES: P0ThemeDef[] = [
  { id: 'telefon-ekran', name: 'Ekran', sectorId: 'telefon', plan: 'free', description: 'Telefon tamiri. Mavi, fiyat listesi, garanti badge.', designPhilosophy: 'Mavi güven. Plus Jakarta Sans. Şeffaf fiyat cihaz+hizmet. 15dk+garanti badge.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::fullscreen_overlay', 'device_repair_pricing', 'warranty_badge::row', 'about::split_left', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['emergency_banner', 'device_repair_pricing', 'warranty_badge'], animationLevel: 'css-only', demoBusinessKey: 'ekran' },
  { id: 'telefon-cip', name: 'Çip', sectorId: 'telefon', plan: 'starter', description: 'Teknik servis. Koyu, turuncu, process steps, before/after.', designPhilosophy: 'Turuncu-siyah teknik. Process steps ile güven. İş öncesi/sonrası.', isDark: true, fonts: { heading: { family: 'Outfit', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#EA580C', '--color-accent-hover': '#C2410C', '--color-bg': '#111111', '--font-heading': "'Outfit', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::video_cinematic', 'device_repair_pricing', 'process_steps::horizontal_timeline', 'work_before_after', 'testimonials::carousel', 'service_area::list_only', 'warranty_badge::row', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'iletisim'], sectorSections: ['emergency_banner', 'device_repair_pricing', 'warranty_badge', 'service_area', 'work_before_after'], animationLevel: 'framer-basic', demoBusinessKey: 'cip' },
  { id: 'telefon-piksel', name: 'Piksel', sectorId: 'telefon', plan: 'growth', description: 'Multi-brand tamir. Mor, marka seçici, galeri.', designPhilosophy: 'Mor teknoloji. Marka/cihaz türü seçici ile hızlı yönlendirme.', isDark: false, fonts: { heading: { family: 'Space Grotesk', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--color-accent-hover': '#6D28D9', '--font-heading': "'Space Grotesk', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::video_cinematic', 'project_type_selector', 'device_repair_pricing', 'gallery::masonry', 'stats::animated_row', 'testimonials::carousel', 'warranty_badge::row', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'galeri', 'iletisim'], sectorSections: ['emergency_banner', 'device_repair_pricing', 'warranty_badge', 'project_type_selector'], animationLevel: 'framer-full', demoBusinessKey: 'piksel' },
  { id: 'telefon-lab', name: 'Lab', sectorId: 'telefon', plan: 'pro', description: 'Data recovery lab. Koyu yeşil, matrix estetiği.', designPhilosophy: 'Matrix yeşil laboratuvar. Filtered tabs hizmet. Mikro lehim teknoloji.', isDark: true, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#22C55E', '--color-accent-hover': '#16A34A', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::video_cinematic', 'services::filtered_tabs', 'technology_showcase', 'certifications::grid', 'blog_preview', 'testimonials::marquee', 'warranty_badge::row', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'teknoloji', 'blog', 'iletisim'], sectorSections: ['emergency_banner', 'device_repair_pricing', 'warranty_badge', 'technology_showcase', 'certifications'], animationLevel: 'gsap-allowed', demoBusinessKey: 'lab' },
  { id: 'telefon-servisplus', name: 'Servis+', sectorId: 'telefon', plan: 'enterprise', description: 'Teknik servis zinciri. Kurumsal, filo bakım, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, kurumsal filo cihaz bakım anlaşması.', isDark: false, fonts: { heading: { family: 'JetBrains Mono', weights: [400, 500, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'JetBrains Mono', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'multi_location', 'corporate_membership', 'franchise_section', 'career_listings'], pages: ['home', 'hizmetler', 'subeler', 'kurumsal', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['emergency_banner', 'device_repair_pricing', 'warranty_badge', 'multi_location', 'corporate_membership', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'servisplus' },
]

// ═══ KLİMA ═══
export const KLIMA_THEMES: P0ThemeDef[] = [
  { id: 'klima-serinlik', name: 'Serinlik', sectorId: 'klima', plan: 'free', description: 'Klima servisi. Açık mavi, mevsimsel kampanya, marka logoları.', designPhilosophy: 'Açık mavi serinlik. Plus Jakarta Sans. Mevsimsel kampanya + marka logoları.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0EA5E9', '--color-accent-hover': '#0284C7', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::fullscreen_overlay', 'services::card_grid', 'seasonal_service', 'vehicle_brands::row', 'warranty_badge::row', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['emergency_banner', 'seasonal_service', 'vehicle_brands', 'warranty_badge'], animationLevel: 'css-only', demoBusinessKey: 'serinlik' },
  { id: 'klima-derece', name: 'Derece', sectorId: 'klima', plan: 'starter', description: 'Klima teknik. Mavi+turuncu, process steps, before/after.', designPhilosophy: 'Mavi+turuncu sıcak/soğuk dualitesi. Process steps + iş öncesi/sonrası.', isDark: false, fonts: { heading: { family: 'Outfit', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0EA5E9', '--color-accent-hover': '#0284C7', '--font-heading': "'Outfit', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::video_cinematic', 'services::card_grid', 'process_steps::horizontal_timeline', 'work_before_after', 'testimonials::carousel', 'service_area::list_only', 'faq::accordion', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'iletisim'], sectorSections: ['emergency_banner', 'seasonal_service', 'vehicle_brands', 'warranty_badge', 'service_area', 'work_before_after'], animationLevel: 'framer-basic', demoBusinessKey: 'derece' },
  { id: 'klima-iklim', name: 'İklim', sectorId: 'klima', plan: 'growth', description: 'HVAC firma. Lacivert, proje seçici, filtered tabs.', designPhilosophy: 'Lacivert profesyonellik. Proje türü seçici + filtered tabs (Klima|Kombi|VRV).', isDark: false, fonts: { heading: { family: 'IBM Plex Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1E40AF', '--color-accent-hover': '#1E3A8A', '--font-heading': "'IBM Plex Sans', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::video_cinematic', 'project_type_selector', 'services::filtered_tabs', 'team::card_horizontal', 'stats::animated_row', 'blog_preview', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'blog', 'iletisim'], sectorSections: ['emergency_banner', 'seasonal_service', 'vehicle_brands', 'warranty_badge', 'project_type_selector'], animationLevel: 'framer-full', demoBusinessKey: 'iklim' },
  { id: 'klima-konfor', name: 'Konfor', sectorId: 'klima', plan: 'pro', description: 'Endüstriyel HVAC. Koyu, mavi, ticari projeler.', designPhilosophy: 'Mavi-koyu endüstriyel. VRF/chiller/havalandırma. Portfolio ticari projeler.', isDark: true, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::video_cinematic', 'services::filtered_tabs', 'portfolio_grid::masonry_lightbox', 'certifications::grid', 'blog_preview', 'testimonials::marquee', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'projeler', 'blog', 'iletisim'], sectorSections: ['emergency_banner', 'vehicle_brands', 'warranty_badge', 'certifications', 'portfolio_grid'], animationLevel: 'gsap-allowed', demoBusinessKey: 'konfor' },
  { id: 'klima-termo', name: 'Termo', sectorId: 'klima', plan: 'enterprise', description: 'Klima servis ağı. Kurumsal, bakım anlaşması, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, mevsimsel kampanya, bakım anlaşması.', isDark: false, fonts: { heading: { family: 'Archivo Black', weights: [400] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0EA5E9', '--color-accent-hover': '#0284C7', '--font-heading': "'Archivo Black', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'multi_location', 'seasonal_service', 'corporate_membership', 'franchise_section', 'career_listings'], pages: ['home', 'hizmetler', 'subeler', 'bakim', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['emergency_banner', 'seasonal_service', 'vehicle_brands', 'warranty_badge', 'multi_location', 'corporate_membership', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'termo' },
]
