/**
 * @kepenk/templates — P3 Themes Batch A: Optik, Pet Shop, Çiçekçi, Terzi, Halı Saha (25 themes)
 */
import type { P0ThemeDef } from './p0-themes'

export const OPTIK_THEMES: P0ThemeDef[] = [
  { id: 'optik-gorus', name: 'Görüş', sectorId: 'optik', plan: 'free', description: 'Optik mağaza. Mavi, göz muayene badge, sigorta logoları.', designPhilosophy: 'Mavi güven. Plus Jakarta Sans. Göz kontrolü CTA. Sigorta logoları.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'services::card_grid', 'gallery::masonry', 'insurance_logos::row', 'booking::cta_only', 'about::split_left', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['insurance_logos', 'booking'], animationLevel: 'css-only', demoBusinessKey: 'gorus' },
  { id: 'optik-cerceve', name: 'Çerçeve', sectorId: 'optik', plan: 'starter', description: 'Optik + marka. Teal, filterable galeri marka bazlı.', designPhilosophy: 'Teal şıklık. Marka bazlı çerçeve galerisi. Testimonials.', isDark: false, fonts: { heading: { family: 'Space Grotesk', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0D9488', '--font-heading': "'Space Grotesk', sans-serif",
    }, homeSections: ['hero::split_left', 'gallery::masonry', 'services::card_grid', 'insurance_logos::grid', 'testimonials::carousel', 'booking::inline_calendar', 'contact::split_form_map'], pages: ['home', 'urunler', 'iletisim'], sectorSections: ['insurance_logos', 'booking'], animationLevel: 'framer-basic', demoBusinessKey: 'cerceve' },
  { id: 'optik-lens', name: 'Lens', sectorId: 'optik', plan: 'growth', description: 'Göz sağlığı. Mavi, video, blog rehberler.', designPhilosophy: 'Mavi sağlık. Video tanıtım. Stats + blog göz sağlığı.', isDark: false, fonts: { heading: { family: 'IBM Plex Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--font-heading': "'IBM Plex Sans', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'services::card_grid', 'gallery::masonry', 'stats::animated_row', 'blog_preview', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'urunler', 'blog', 'iletisim'], sectorSections: ['insurance_logos', 'booking'], animationLevel: 'framer-full', demoBusinessKey: 'lens' },
  { id: 'optik-vizyon', name: 'Vizyon', sectorId: 'optik', plan: 'pro', description: 'Premium göz merkezi. Koyu, lüks çerçeve koleksiyonu.', designPhilosophy: 'Koyu lüks. Özel çerçeve koleksiyonu portfolyo. Newsletter.', isDark: true, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#C9A84C', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'portfolio_grid::masonry_lightbox', 'gallery::horizontal_snap', 'newsletter', 'testimonials::editorial_single', 'contact::split_form_map'], pages: ['home', 'koleksiyon', 'iletisim'], sectorSections: ['portfolio_grid'], animationLevel: 'gsap-allowed', demoBusinessKey: 'vizyon' },
  { id: 'optik-plus', name: 'Optik+', sectorId: 'optik', plan: 'enterprise', description: 'Optik zinciri. Mavi, çoklu mağaza, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, franchise.', isDark: false, fonts: { heading: { family: 'Montserrat', weights: [500, 600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--font-heading': "'Montserrat', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'multi_location', 'franchise_section', 'career_listings'], pages: ['home', 'urunler', 'magazalar', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['multi_location', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'optikplus' },
]

export const PETSHOP_THEMES: P0ThemeDef[] = [
  { id: 'petshop-pati', name: 'Pati', sectorId: 'petshop', plan: 'free', description: 'Pet shop. Turuncu, renkli, hayvan türü seçici.', designPhilosophy: 'Turuncu enerji. Nunito sıcak. Pet species emoji seçici.', isDark: false, fonts: { heading: { family: 'Nunito', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#EA580C', '--font-heading': "'Nunito', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'pet_species', 'services::card_grid', 'about::split_left', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['pet_species'], animationLevel: 'css-only', demoBusinessKey: 'pati' },
  { id: 'petshop-yuva', name: 'Yuva', sectorId: 'petshop', plan: 'starter', description: 'Pet market. Turuncu, galeri, kampanyalar.', designPhilosophy: 'Turuncu sıcaklık. Galeri + promotions + testimonials.', isDark: false, fonts: { heading: { family: 'Poppins', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#EA580C', '--font-heading': "'Poppins', sans-serif",
    }, homeSections: ['hero::split_left', 'pet_species', 'services::card_grid', 'gallery::masonry', 'promotions', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'urunler', 'iletisim'], sectorSections: ['pet_species', 'promotions'], animationLevel: 'framer-basic', demoBusinessKey: 'yuva' },
  { id: 'petshop-dost', name: 'Dost', sectorId: 'petshop', plan: 'growth', description: 'Pet & Grooming. Turuncu, visual ürünler, teslimat.', designPhilosophy: 'Turuncu modern. Visual grid ürün vitrini. Online teslimat.', isDark: false, fonts: { heading: { family: 'Quicksand', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#EA580C', '--font-heading': "'Quicksand', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'pet_species', 'menu_display::visual_grid', 'delivery_zone::list_only', 'instagram_feed', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'urunler', 'teslimat', 'iletisim'], sectorSections: ['pet_species', 'menu_display', 'delivery_zone'], animationLevel: 'framer-full', demoBusinessKey: 'dost' },
  { id: 'petshop-salon', name: 'Salon', sectorId: 'petshop', plan: 'pro', description: 'Premium pet. Mor, filtered tabs, grooming randevusu.', designPhilosophy: 'Mor premium. Filtered tabs (Mama|Aksesuar|Grooming|Eğitim). Booking.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'pet_species', 'services::filtered_tabs', 'booking::inline_calendar', 'gallery::horizontal_snap', 'blog_preview', 'testimonials::grid_cards', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'blog', 'iletisim'], sectorSections: ['pet_species', 'booking'], animationLevel: 'gsap-allowed', demoBusinessKey: 'salon' },
  { id: 'petshop-zincir', name: 'Zincir', sectorId: 'petshop', plan: 'enterprise', description: 'Pet mağaza zinciri. Turuncu, sadakat, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, loyalty, franchise.', isDark: false, fonts: { heading: { family: 'Raleway', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#EA580C', '--font-heading': "'Raleway', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'multi_location', 'loyalty_program', 'franchise_section', 'career_listings'], pages: ['home', 'urunler', 'magazalar', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['pet_species', 'multi_location', 'loyalty_program', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'zincir' },
]

export const CICEKCI_THEMES: P0ThemeDef[] = [
  { id: 'cicekci-tomurcuk', name: 'Tomurcuk', sectorId: 'cicekci', plan: 'free', description: 'Çiçekçi. Yeşil-krem, masonry galeri, aynı gün teslimat.', designPhilosophy: 'Yeşil tazelik. Lora serif sıcak. Krem background. Same day delivery CTA.', isDark: false, fonts: { heading: { family: 'Lora', weights: [400, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#22C55E', '--color-bg': '#FFFDF5', '--font-heading': "'Lora', serif",
    }, homeSections: ['hero::fullscreen_overlay', 'gallery::masonry', 'services::card_grid', 'about::split_left', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: [], animationLevel: 'css-only', demoBusinessKey: 'tomurcuk' },
  { id: 'cicekci-buket', name: 'Buket', sectorId: 'cicekci', plan: 'starter', description: 'Çiçek atölyesi. Yeşil, filterable galeri, teslimat.', designPhilosophy: 'Yeşil taze. Filterable galeri (Sevgililer|Doğum Günü|Taziye|Düğün). Teslimat.', isDark: false, fonts: { heading: { family: 'Crimson Text', weights: [400, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#22C55E', '--font-heading': "'Crimson Text', serif",
    }, homeSections: ['hero::split_left', 'gallery::masonry', 'delivery_zone::list_only', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'urunler', 'iletisim'], sectorSections: ['delivery_zone'], animationLevel: 'framer-basic', demoBusinessKey: 'buket' },
  { id: 'cicekci-sera', name: 'Sera', sectorId: 'cicekci', plan: 'growth', description: 'Çiçek e-ticaret. Koyu, yeşil, visual grid, mevsimsel.', designPhilosophy: 'Koyu lüks çiçek. Visual grid e-ticaret. Mevsimsel kampanya.', isDark: true, fonts: { heading: { family: 'Playfair Display', weights: [400, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#22C55E', '--font-heading': "'Playfair Display', serif",
    }, homeSections: ['hero::video_cinematic', 'menu_display::visual_grid', 'seasonal_service', 'promotions', 'testimonials::marquee', 'contact::split_form_map'], pages: ['home', 'urunler', 'iletisim'], sectorSections: ['menu_display', 'seasonal_service', 'promotions'], animationLevel: 'framer-full', demoBusinessKey: 'sera' },
  { id: 'cicekci-atolye', name: 'Atölye', sectorId: 'cicekci', plan: 'pro', description: 'Çiçek sanatı. Koyu, bakır, özel tasarım portfolyo.', designPhilosophy: 'Koyu + bakır zanaatçılık. Özel tasarım portfolyo. Booking inquiry.', isDark: true, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#B87333', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'portfolio_grid::masonry_lightbox', 'booking_inquiry', 'gallery::horizontal_snap', 'testimonials::editorial_single', 'contact::split_form_map'], pages: ['home', 'galeri', 'siparis', 'iletisim'], sectorSections: ['portfolio_grid', 'booking_inquiry'], animationLevel: 'gsap-allowed', demoBusinessKey: 'atolye' },
  { id: 'cicekci-bahce', name: 'Bahçe', sectorId: 'cicekci', plan: 'enterprise', description: 'Çiçekçi zinciri. Yeşil, ofis aboneliği, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, ofis çiçek aboneliği, franchise.', isDark: false, fonts: { heading: { family: 'Josefin Sans', weights: [400, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#22C55E', '--font-heading': "'Josefin Sans', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'multi_location', 'corporate_membership', 'franchise_section', 'career_listings'], pages: ['home', 'urunler', 'magazalar', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['multi_location', 'corporate_membership', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'bahce' },
]

export const TERZI_THEMES: P0ThemeDef[] = [
  { id: 'terzi-igne', name: 'İğne', sectorId: 'terzi', plan: 'free', description: 'Semt terzisi. Kahverengi-krem, fiyat listesi.', designPhilosophy: 'Kahverengi sıcaklık. Lora serif zanaatkar. Pricing accordion şeffaf fiyat.', isDark: false, fonts: { heading: { family: 'Lora', weights: [400, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C6048', '--color-bg': '#FFFBF5', '--font-heading': "'Lora', serif",
    }, homeSections: ['hero::fullscreen_overlay', 'services::card_grid', 'about::split_left', 'gallery::masonry', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: [], animationLevel: 'css-only', demoBusinessKey: 'igne' },
  { id: 'terzi-dikis', name: 'Dikiş', sectorId: 'terzi', plan: 'starter', description: 'Terzi atölyesi. Kahverengi, before/after, booking.', designPhilosophy: 'Kahverengi zanaatçılık. Before/after tadilat. Randevu.', isDark: false, fonts: { heading: { family: 'EB Garamond', weights: [400, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C6048', '--font-heading': "'EB Garamond', serif",
    }, homeSections: ['hero::split_left', 'services::card_grid', 'before_after::slider', 'testimonials::carousel', 'booking::inline_calendar', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'iletisim'], sectorSections: ['before_after', 'booking'], animationLevel: 'framer-basic', demoBusinessKey: 'dikis' },
  { id: 'terzi-kumas', name: 'Kumaş', sectorId: 'terzi', plan: 'growth', description: 'Butik terzi. Kahverengi, editoryal galeri, blog.', designPhilosophy: 'Kahverengi refined. Asimetrik editoryal galeri. Process steps + blog.', isDark: false, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C6048', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'services::card_grid', 'gallery::horizontal_snap', 'process_steps::horizontal_timeline', 'blog_preview', 'about::split_left', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'galeri', 'blog', 'iletisim'], sectorSections: [], animationLevel: 'framer-full', demoBusinessKey: 'kumas' },
  { id: 'terzi-haute', name: 'Haute', sectorId: 'terzi', plan: 'pro', description: 'Haute couture. Koyu, altın, lüks portfolyo.', designPhilosophy: 'Koyu lüks alta moda. Altın detay. Portfolyo + booking inquiry.', isDark: true, fonts: { heading: { family: 'Spectral', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#C9A84C', '--font-heading': "'Spectral', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'portfolio_grid::masonry_lightbox', 'gallery::horizontal_snap', 'team::full_page_snap', 'booking_inquiry', 'awards_press', 'testimonials::editorial_single', 'contact::split_form_map'], pages: ['home', 'koleksiyon', 'siparis', 'iletisim'], sectorSections: ['portfolio_grid', 'booking_inquiry', 'awards_press'], animationLevel: 'gsap-allowed', demoBusinessKey: 'haute' },
  { id: 'terzi-moda', name: 'Moda', sectorId: 'terzi', plan: 'enterprise', description: 'Tadilat zinciri. Kahverengi, üniforma, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, kurumsal üniforma anlaşması, franchise.', isDark: false, fonts: { heading: { family: 'Raleway', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C6048', '--font-heading': "'Raleway', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'services::filtered_tabs', 'multi_location', 'corporate_membership', 'stats::dark_bar', 'gallery::horizontal_snap', 'testimonials::marquee', 'franchise_section', 'career_listings'], pages: ['home', 'hizmetler', 'subeler', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['multi_location', 'corporate_membership', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'moda' },
]

export const HALISAHA_THEMES: P0ThemeDef[] = [
  { id: 'saha-saha', name: 'Saha', sectorId: 'halisaha', plan: 'free', description: 'Halı saha. Yeşil, müsaitlik takvimi, saatlik fiyat.', designPhilosophy: 'Yeşil saha. Outfit heading atletik. Müsaitlik takvimi gün×saat. Pricing saatlik.', isDark: false, fonts: { heading: { family: 'Outfit', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#22C55E', '--font-heading': "'Outfit', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'class_schedule::day_tabs', 'membership_pricing::columns', 'about::split_left', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['class_schedule', 'membership_pricing'], animationLevel: 'css-only', demoBusinessKey: 'saha' },
  { id: 'saha-gol', name: 'Gol', sectorId: 'halisaha', plan: 'starter', description: 'Spor tesisi. Yeşil, galeri, turnuva, kampanya.', designPhilosophy: 'Yeşil enerji. Galeri + turnuva promo + testimonials.', isDark: false, fonts: { heading: { family: 'Anton', weights: [400] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#22C55E', '--font-heading': "'Anton', sans-serif",
    }, homeSections: ['hero::split_left', 'class_schedule::day_tabs', 'membership_pricing::columns', 'gallery::masonry', 'promotions', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'saha', 'iletisim'], sectorSections: ['class_schedule', 'membership_pricing', 'promotions'], animationLevel: 'framer-basic', demoBusinessKey: 'gol' },
  { id: 'saha-turnuva', name: 'Turnuva', sectorId: 'halisaha', plan: 'growth', description: 'Profesyonel saha. Yeşil, video, turnuva takvimi.', designPhilosophy: 'Yeşil profesyonel. Video hero. Turnuva takvimi + stats.', isDark: false, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#22C55E', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'class_schedule::table', 'membership_pricing::columns', 'stats::animated_row', 'gallery::masonry', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'saha', 'turnuva', 'iletisim'], sectorSections: ['class_schedule', 'membership_pricing'], animationLevel: 'framer-full', demoBusinessKey: 'turnuva' },
  { id: 'saha-arena', name: 'Arena', sectorId: 'halisaha', plan: 'pro', description: 'Spor kompleksi. Koyu, çoklu spor, sadakat.', designPhilosophy: 'Koyu spor kompleksi. Filtered tabs (Halı Saha|Basketbol|Tenis|Yüzme). Loyalty.', isDark: true, fonts: { heading: { family: 'Oswald', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#22C55E', '--font-heading': "'Oswald', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'services::filtered_tabs', 'class_schedule::table', 'loyalty_program', 'gallery::horizontal_snap', 'testimonials::marquee', 'contact::split_form_map'], pages: ['home', 'sporlar', 'uyelik', 'iletisim'], sectorSections: ['class_schedule', 'membership_pricing', 'loyalty_program'], animationLevel: 'gsap-allowed', demoBusinessKey: 'arena' },
  { id: 'saha-stadyum', name: 'Stadyum', sectorId: 'halisaha', plan: 'enterprise', description: 'Spor tesisi ağı. Yeşil, çoklu tesis, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, kurumsal üyelik, franchise.', isDark: false, fonts: { heading: { family: 'Bebas Neue', weights: [400] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#22C55E', '--font-heading': "'Bebas Neue', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'multi_location', 'corporate_membership', 'franchise_section', 'career_listings'], pages: ['home', 'sporlar', 'tesisler', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['class_schedule', 'membership_pricing', 'multi_location', 'corporate_membership', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'stadyum' },
]
