/**
 * @kepenk/templates — P3 Themes Batch B: Yüzme, Catering, Kasap, Çilingir, Müzik (25 themes)
 */
import type { P0ThemeDef } from './p0-themes'

export const YUZME_THEMES: P0ThemeDef[] = [
  { id: 'yuzme-dalga', name: 'Dalga', sectorId: 'yuzme', plan: 'free', description: 'Yüzme havuzu. Açık mavi, ders programı, üyelik.', designPhilosophy: 'Açık mavi su teması. Ders programı + membership pricing.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0EA5E9', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'services::card_grid', 'class_schedule::day_tabs', 'membership_pricing::columns', 'about::split_left', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['class_schedule', 'membership_pricing'], animationLevel: 'css-only', demoBusinessKey: 'dalga' },
  { id: 'yuzme-havuz', name: 'Havuz', sectorId: 'yuzme', plan: 'starter', description: 'Spor merkezi. Mavi, eğitmenler, galeri.', designPhilosophy: 'Mavi sağlık. Eğitmen profilleri + galeri + testimonials.', isDark: false, fonts: { heading: { family: 'Quicksand', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0EA5E9', '--font-heading': "'Quicksand', sans-serif",
    }, homeSections: ['hero::split_left', 'services::card_grid', 'class_schedule::day_tabs', 'team::card_horizontal', 'gallery::masonry', 'testimonials::carousel', 'membership_pricing::columns', 'contact::split_form_map'], pages: ['home', 'dersler', 'iletisim'], sectorSections: ['class_schedule', 'membership_pricing', 'trainer_profile'], animationLevel: 'framer-basic', demoBusinessKey: 'havuz' },
  { id: 'yuzme-aqua', name: 'Aqua', sectorId: 'yuzme', plan: 'growth', description: 'Aqua fitness. Mavi, video, transformation, stats.', designPhilosophy: 'Mavi enerji. Video hero aqua fitness. Dönüşüm hikayeleri + stats.', isDark: false, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0EA5E9', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'services::card_grid', 'class_schedule::day_tabs', 'transformation::carousel', 'stats::animated_row', 'testimonials::carousel', 'membership_pricing::columns', 'contact::split_form_map'], pages: ['home', 'dersler', 'iletisim'], sectorSections: ['class_schedule', 'membership_pricing', 'transformation'], animationLevel: 'framer-full', demoBusinessKey: 'aqua' },
  { id: 'yuzme-okyanus', name: 'Okyanus', sectorId: 'yuzme', plan: 'pro', description: 'Premium spa+pool. Teal, wellness, newsletter, blog.', designPhilosophy: 'Teal premium wellness. Spa+sauna dahil paket. Blog + newsletter.', isDark: false, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0D9488', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'services::editorial_zigzag', 'class_schedule::day_tabs', 'newsletter', 'blog_preview', 'testimonials::editorial_single', 'membership_pricing::toggle', 'contact::split_form_map'], pages: ['home', 'dersler', 'blog', 'iletisim'], sectorSections: ['class_schedule', 'membership_pricing'], animationLevel: 'gsap-allowed', demoBusinessKey: 'okyanus' },
  { id: 'yuzme-olimpik', name: 'Olimpik', sectorId: 'yuzme', plan: 'enterprise', description: 'Havuz grubu. Mavi, çoklu tesis, kurumsal.', designPhilosophy: 'Syne kurumsal. Multi-location, kurumsal üyelik, kariyer.', isDark: false, fonts: { heading: { family: 'Manrope', weights: [500, 600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#0EA5E9', '--font-heading': "'Manrope', sans-serif", }, homeSections: ['hero::video_showreel', 'quick_access_cards', 'multi_location', 'corporate_membership', 'career_listings'], pages: ['home', 'dersler', 'tesisler', 'kariyer', 'iletisim'], sectorSections: ['class_schedule', 'membership_pricing', 'multi_location', 'corporate_membership', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'olimpik' },
]

export const CATERING_THEMES: P0ThemeDef[] = [
  { id: 'catering-sofra', name: 'Sofra', sectorId: 'catering', plan: 'free', description: 'Catering. Kahverengi-krem, visual menü, galeri.', designPhilosophy: 'Kahverengi sıcaklık. Lora serif. Visual grid menü. Galeri.', isDark: false, fonts: { heading: { family: 'Merriweather', weights: [400, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C6048', '--font-heading': "'Merriweather', serif",
    }, homeSections: ['hero::fullscreen_overlay', 'services::card_grid', 'menu_display::visual_grid', 'about::split_left', 'gallery::masonry', 'contact::simple_form'], pages: ['home'], sectorSections: ['menu_display'], animationLevel: 'css-only', demoBusinessKey: 'sofra' },
  { id: 'catering-ziyafet', name: 'Ziyafet', sectorId: 'catering', plan: 'starter', description: 'Event catering. Kahverengi, paketler, free quote.', designPhilosophy: 'Kahverengi etkinlik. Catering paketleri + free quote + testimonials.', isDark: false, fonts: { heading: { family: 'Lora', weights: [400, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C6048', '--font-heading': "'Lora', serif",
    }, homeSections: ['hero::soft_carousel', 'services::card_grid', 'wedding_packages', 'free_quote', 'testimonials::carousel', 'gallery::masonry', 'contact::split_form_map'], pages: ['home', 'paketler', 'iletisim'], sectorSections: ['menu_display', 'wedding_packages', 'free_quote'], animationLevel: 'framer-basic', demoBusinessKey: 'ziyafet' },
  { id: 'catering-sef', name: 'Şef', sectorId: 'catering', plan: 'growth', description: 'Şef catering. Koyu, video mutfak, editoryal.', designPhilosophy: 'Koyu lüks. Video mutfak sahne arkası. Editoryal proje hikayeleri.', isDark: true, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#C9A84C', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'philosophy', 'project_story', 'menu_display::visual_grid', 'gallery::horizontal_snap', 'testimonials::marquee', 'contact::split_form_map'], pages: ['home', 'referanslar', 'menu', 'iletisim'], sectorSections: ['menu_display', 'project_story'], animationLevel: 'framer-full', demoBusinessKey: 'sef' },
  { id: 'catering-banket', name: 'Banket', sectorId: 'catering', plan: 'pro', description: 'Büyük etkinlik. Siyah, portfolyo, referanslar.', designPhilosophy: 'Siyah kurumsal. Portfolyo büyük etkinlikler. Referans firma logoları.', isDark: false, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#1A1A1A', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'portfolio_grid::masonry_lightbox', 'team::card_horizontal', 'stats::animated_row', 'testimonials::grid_cards', 'contact::split_form_map'], pages: ['home', 'referanslar', 'ekip', 'iletisim'], sectorSections: ['portfolio_grid'], animationLevel: 'gsap-allowed', demoBusinessKey: 'banket' },
  { id: 'catering-lojistik', name: 'Lojistik', sectorId: 'catering', plan: 'enterprise', description: 'Endüstriyel yemek. Kurumsal, fabrika/otel, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, fabrika yemek anlaşması, franchise.', isDark: false, fonts: { heading: { family: 'Barlow', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C6048', '--font-heading': "'Barlow', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'multi_location', 'corporate_membership', 'franchise_section', 'career_listings'], pages: ['home', 'hizmetler', 'subeler', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['multi_location', 'corporate_membership', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'lojistik' },
]

export const KASAP_THEMES: P0ThemeDef[] = [
  { id: 'kasap-bicak', name: 'Bıçak', sectorId: 'kasap', plan: 'free', description: 'Kasap. Koyu, kırmızı, taze kesim, sertifika.', designPhilosophy: 'Kırmızı-koyu et estetiği. Daily special taze kesim. Helal sertifika.', isDark: true, fonts: { heading: { family: 'Outfit', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#DC2626', '--font-heading': "'Outfit', sans-serif",
    }, homeSections: ['daily_special::banner', 'hero::fullscreen_overlay', 'menu_display::tab_categories', 'certifications::grid', 'about::split_left', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['menu_display', 'daily_special', 'certifications'], animationLevel: 'css-only', demoBusinessKey: 'bicak' },
  { id: 'kasap-tezgah', name: 'Tezgah', sectorId: 'kasap', plan: 'starter', description: 'Et market. Kırmızı, galeri, mevsimsel, teslimat.', designPhilosophy: 'Kırmızı enerji. Galeri + Kurban Bayramı özel + teslimat.', isDark: false, fonts: { heading: { family: 'Oswald', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#DC2626', '--font-heading': "'Oswald', sans-serif",
    }, homeSections: ['daily_special::banner', 'hero::split_left', 'menu_display::tab_categories', 'gallery::masonry', 'seasonal_service', 'delivery_zone::list_only', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'urunler', 'iletisim'], sectorSections: ['menu_display', 'daily_special', 'seasonal_service', 'delivery_zone'], animationLevel: 'framer-basic', demoBusinessKey: 'tezgah' },
  { id: 'kasap-mangal', name: 'Mangal', sectorId: 'kasap', plan: 'growth', description: 'Et & Şarküteri. Koyu, online sipariş, process steps.', designPhilosophy: 'Koyu premium et. Online sipariş visual grid. Kesim→paketleme→teslim.', isDark: true, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#DC2626', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['daily_special::banner', 'hero::video_cinematic', 'menu_display::visual_grid', 'process_steps::horizontal_timeline', 'stats::dark_bar', 'testimonials::marquee', 'contact::split_form_map'], pages: ['home', 'urunler', 'siparis', 'iletisim'], sectorSections: ['menu_display', 'daily_special'], animationLevel: 'framer-full', demoBusinessKey: 'mangal' },
  { id: 'kasap-ciftlik', name: 'Çiftlik', sectorId: 'kasap', plan: 'pro', description: 'Organik butik kasap. Toprak tonları, çiftlik hikayeleri.', designPhilosophy: 'Toprak tonları organik. Çiftlikten sofraya izlenebilirlik. Blog.', isDark: false, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C6048', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'menu_display::tab_categories', 'portfolio_grid::masonry_lightbox', 'blog_preview', 'testimonials::editorial_single', 'contact::split_form_map'], pages: ['home', 'urunler', 'hikaye', 'blog', 'iletisim'], sectorSections: ['menu_display', 'daily_special', 'portfolio_grid'], animationLevel: 'gsap-allowed', demoBusinessKey: 'ciftlik' },
  { id: 'kasap-etplus', name: 'Et+', sectorId: 'kasap', plan: 'enterprise', description: 'Et mağaza zinciri. Kırmızı, toptan, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, restoran/otel toptan, franchise.', isDark: false, fonts: { heading: { family: 'Archivo Black', weights: [400] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#DC2626', '--font-heading': "'Archivo Black', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'multi_location', 'corporate_membership', 'franchise_section', 'career_listings'], pages: ['home', 'urunler', 'magazalar', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['menu_display', 'daily_special', 'multi_location', 'corporate_membership', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'etplus' },
]

export const CILINGIR_THEMES: P0ThemeDef[] = [
  { id: 'cilingir-kilit', name: 'Kilit', sectorId: 'cilingir', plan: 'free', description: 'Çilingir. Kırmızı, DEV TELEFON, acil banner, fiyat.', designPhilosophy: 'KRİZDE ARAYAN müşteri. DEV TELEFON text-6xl. 15dk badge. Kırmızı aciliyet.', isDark: false, fonts: { heading: { family: 'Rubik', weights: [400, 500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#DC2626', '--font-heading': "'Rubik', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::fullscreen_overlay', 'services::card_grid', 'warranty_badge::row', 'service_area::list_only', 'map::full_width', 'contact::simple_form'], pages: ['home'], sectorSections: ['emergency_banner', 'warranty_badge', 'service_area'], animationLevel: 'css-only', demoBusinessKey: 'kilit' },
  { id: 'cilingir-anahtar', name: 'Anahtar', sectorId: 'cilingir', plan: 'starter', description: 'Güvenlik. Koyu, kırmızı, process steps, before/after.', designPhilosophy: 'Koyu güvenlik. Process steps + iş öncesi/sonrası + testimonials.', isDark: true, fonts: { heading: { family: 'Outfit', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#DC2626', '--color-bg': '#111111', '--font-heading': "'Outfit', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::fullscreen_overlay', 'services::card_grid', 'process_steps::horizontal_timeline', 'work_before_after', 'testimonials::carousel', 'faq::accordion', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'iletisim'], sectorSections: ['emergency_banner', 'warranty_badge', 'service_area', 'work_before_after'], animationLevel: 'framer-basic', demoBusinessKey: 'anahtar' },
  { id: 'cilingir-guvenlik', name: 'Güvenlik', sectorId: 'cilingir', plan: 'growth', description: 'Kilit sistemleri. Mavi, akıllı kilit, filtered tabs.', designPhilosophy: 'Mavi teknoloji. Filtered tabs (Ev|Araç|İşyeri|Kasa|Güvenlik). Technology showcase.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#2563EB', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::video_cinematic', 'services::filtered_tabs', 'technology_showcase', 'stats::animated_row', 'gallery::masonry', 'testimonials::carousel', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'galeri', 'iletisim'], sectorSections: ['emergency_banner', 'warranty_badge', 'technology_showcase'], animationLevel: 'framer-full', demoBusinessKey: 'guvenlik' },
  { id: 'cilingir-kasa', name: 'Kasa', sectorId: 'cilingir', plan: 'pro', description: 'Endüstriyel güvenlik. Koyu, sertifika, blog.', designPhilosophy: 'Koyu endüstriyel. Sertifikalar + blog + booking inquiry.', isDark: true, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#DC2626', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['emergency_banner', 'hero::video_cinematic', 'services::filtered_tabs', 'certifications::grid', 'blog_preview', 'booking_inquiry', 'testimonials::marquee', 'contact::split_form_map'], pages: ['home', 'hizmetler', 'blog', 'iletisim'], sectorSections: ['emergency_banner', 'warranty_badge', 'certifications', 'booking_inquiry'], animationLevel: 'gsap-allowed', demoBusinessKey: 'kasa' },
  { id: 'cilingir-724', name: '7/24', sectorId: 'cilingir', plan: 'enterprise', description: 'Çilingir ağı. Kırmızı, şehir geneli, kariyer.', designPhilosophy: 'Syne kurumsal. 10+ ekip şehir geneli. Multi-location, kariyer.', isDark: false, fonts: { heading: { family: 'Bebas Neue', weights: [400] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#DC2626', '--font-heading': "'Bebas Neue', sans-serif", }, homeSections: ['emergency_banner', 'hero::promo_carousel', 'quick_access_cards', 'multi_location', 'career_listings'], pages: ['home', 'hizmetler', 'ekipler', 'kariyer', 'iletisim'], sectorSections: ['emergency_banner', 'warranty_badge', 'multi_location', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'yediyirmidort' },
]

export const MUZIK_THEMES: P0ThemeDef[] = [
  { id: 'muzik-nota', name: 'Nota', sectorId: 'muzik', plan: 'free', description: 'Müzik kursu. Mor, enstrüman grid, free trial, paketler.', designPhilosophy: 'Mor yaratıcılık. Enstrüman grid emoji. Free trial CTA. Ders paketleri.', isDark: false, fonts: { heading: { family: 'Plus Jakarta Sans', weights: [500, 600, 700] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--font-heading': "'Plus Jakarta Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_overlay', 'subject_grid', 'about::split_left', 'free_trial::banner', 'membership_pricing::columns', 'contact::simple_form'], pages: ['home'], sectorSections: ['subject_grid', 'free_trial', 'membership_pricing'], animationLevel: 'css-only', demoBusinessKey: 'nota' },
  { id: 'muzik-akor', name: 'Akor', sectorId: 'muzik', plan: 'starter', description: 'Müzik okulu. Mor, ders programı, öğretmenler, başarı.', designPhilosophy: 'Mor eğitim. Ders programı + öğretmen profilleri + konservatuar başarıları.', isDark: false, fonts: { heading: { family: 'DM Serif Display', weights: [400] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--font-heading': "'DM Serif Display', serif",
    }, homeSections: ['hero::split_left', 'subject_grid', 'class_schedule::day_tabs', 'team::card_horizontal', 'success_stories::cards', 'gallery::masonry', 'testimonials::carousel', 'membership_pricing::columns', 'contact::split_form_map'], pages: ['home', 'kurslar', 'iletisim'], sectorSections: ['subject_grid', 'free_trial', 'class_schedule', 'success_stories', 'membership_pricing'], animationLevel: 'framer-basic', demoBusinessKey: 'akor' },
  { id: 'muzik-studyo', name: 'Stüdyo', sectorId: 'muzik', plan: 'growth', description: 'Kayıt stüdyosu. Koyu, mor, video, portfolyo.', designPhilosophy: 'Koyu stüdyo. Video kayıt stüdyosu. Portfolyo öğrenci performansları.', isDark: true, fonts: { heading: { family: 'Syne', weights: [600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--font-heading': "'Syne', sans-serif",
    }, homeSections: ['hero::video_cinematic', 'subject_grid', 'portfolio_grid::masonry_lightbox', 'stats::dark_bar', 'class_schedule::day_tabs', 'testimonials::marquee', 'contact::split_form_map'], pages: ['home', 'kurslar', 'kayit', 'iletisim'], sectorSections: ['subject_grid', 'free_trial', 'class_schedule', 'portfolio_grid'], animationLevel: 'framer-full', demoBusinessKey: 'studyo' },
  { id: 'muzik-konservatuar', name: 'Konservatuar', sectorId: 'muzik', plan: 'pro', description: 'Müzik sanatları. Koyu, mor, editoryal, ödüller.', designPhilosophy: 'Koyu akademik.  Ödüller + blog + newsletter.', isDark: true, fonts: { heading: { family: 'Cormorant Garamond', weights: [400, 600, 700] }, body: { family: 'DM Sans', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'DM Sans', sans-serif",
    }, homeSections: ['hero::fullscreen_kenburns', 'philosophy', 'subject_grid', 'awards_press', 'blog_preview', 'newsletter', 'testimonials::editorial_single', 'contact::split_form_map'], pages: ['home', 'kurslar', 'blog', 'iletisim'], sectorSections: ['subject_grid', 'free_trial', 'awards_press'], animationLevel: 'gsap-allowed', demoBusinessKey: 'konservatuar' },
  { id: 'muzik-armoni', name: 'Armoni', sectorId: 'muzik', plan: 'enterprise', description: 'Müzik okulu zinciri. Mor, çoklu şube, franchise.', designPhilosophy: 'Syne kurumsal. Multi-location, franchise, kariyer.', isDark: false, fonts: { heading: { family: 'Montserrat', weights: [500, 600, 700, 800] }, body: { family: 'Inter', weights: [400, 500] } }, cssOverrides: { '--color-accent': '#7C3AED', '--font-heading': "'Montserrat', sans-serif", }, homeSections: ['hero::promo_carousel', 'quick_access_cards', 'subject_grid', 'multi_location', 'franchise_section', 'career_listings'], pages: ['home', 'kurslar', 'subeler', 'bayilik', 'kariyer', 'iletisim'], sectorSections: ['subject_grid', 'free_trial', 'multi_location', 'franchise_section', 'career_listings', 'quick_access_cards'], animationLevel: 'gsap-allowed', demoBusinessKey: 'armoni' },
]
