/**
 * @kepenk/templates — cicekci-mahalle Theme Configuration
 *
 * Mahalle cicekçisi, gunluk buket ve sepet
 * Plan: free (3 page sections, 3 global sections)
 * Font: Inter/Inter | Accent: #4A7C59
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const CICEKCI_MAHALLE_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#4A7C59',
  '--color-accent-hover': '#4A7C59',
  '--color-accent-active': '#4A7C59',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': "'Lora', sans-serif",
  '--font-body': "'Source Sans 3', system-ui, sans-serif",
}

// ═══ DEMO BUSINESS DATA ═══

export const CICEKCI_MAHALLE_BUSINESS = {
  name: 'Yesil Bahce Cicekcilik',
  ownerName: 'Gulsen Kaya',
  sectorId: 'Cicekci',
  slogan: 'Her gune bir cicek, her eve bir renk',
  phone: '0532 718 45 60',
  phoneClean: '905327184560',
  whatsapp: '905327184560',
  email: 'info@yesilbahcecicek.com',
  address: 'Moda Mah. Feridiye Cad. No:22, Kadikoy/Istanbul',
  city: 'Istanbul',
  district: 'Kadikoy',
  neighborhood: 'Moda',
  coordinates: { lat: 40.9815, lng: 29.0265 },
  socialMedia: { instagram: 'https://instagram.com/yesilbahcecicek' },
  photos: [],
  foundedYear: 2012,
  experience: '14 yil',
  customerCount: '18.000+',
  rating: 4.7,
  reviewCount: 650,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '08:00',
      close: '21:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Mevsim Buketi',
      price: '250 - 500 TL',
      duration: '15 dk',
      description: 'Mevsimin en taze cicekleriyle hazirlanan gunluk buket. Renk ve boyut tercihi yapilabilir.',
    },
    {
      id: 's2',
      name: 'Cicek Sepeti',
      price: '400 - 800 TL',
      duration: '20 dk',
      description: 'Hasir veya ahsap sepette ozenle duzenlenmis cicek aranjmani.',
    },
    {
      id: 's3',
      name: 'Saksi Cicegi',
      price: '150 - 600 TL',
      duration: 'hazir',
      description: 'Orkide, sukulent, bonsai ve mevsimlik saksi cicekleri.',
    },
    {
      id: 's4',
      name: 'Ayni Gun Teslimat',
      price: '+50 TL',
      duration: '2-4 saat',
      description: 'Kadikoy ve yakin ilcelere ayni gun icinde teslimat.',
    },
  ],
  team: [],
  testimonials: [],
  faq: [
    { q: 'Ayni gun teslimat yapabiliyor musunuz?', a: 'Evet, saat 15:00\'e kadar verilen siparisler ayni gun teslim edilir. Kadikoy, Uskudar ve Atasehir bolgesine teslimat yapiyoruz.' },
    { q: 'Cicekler ne kadar dayanir?', a: 'Taze kesim ciceklerimiz dogru bakimla 5-10 gun dayanir. Buketinizle birlikte bakim kartı veriyoruz.' },
    { q: 'Online siparis verebilir miyim?', a: 'Evet, WhatsApp uzerinden cicek secimi yapip siparis verebilirsiniz. Odeme havale veya kapıda nakit/kart ile yapilabilir.' },
    { q: 'Ozel gun indirimi var mi?', a: 'Sevgililer Gunu, Anneler Gunu ve oğretmenler gunu gibi ozel gunlerde erken siparis indirimi uyguluyoruz.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const CICEKCI_MAHALLE_CONFIG = {
  id: 'cicekci-mahalle',
  name: 'Mahalle',
  sectorId: 'cicekci',
  plan: 'free',
  description: 'Mahalle cicekçisi, gunluk buket ve sepet',
  designPhilosophy: 'Dogal, sicak, sade',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#4A7C59',
    '--color-accent-hover': '#4A7C59',
    '--color-accent-active': '#4A7C59',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': "'Lora', sans-serif",
    '--font-body': "'Source Sans 3', system-ui, sans-serif",
  },
  fonts: {
    heading: {
      family: 'Lora',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Source Sans 3',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'Florist',
  sectorSections: [],
  performanceBudget: {
    maxJS: '80kb',
    maxLCP: '3.0s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Yesil Bahce Cicekcilik' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905327184560',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Yesil Bahce Cicekcilik',
        copyright: '© 2026 Yesil Bahce Cicekcilik',
        contact: {
          phone: '0532 718 45 60',
          email: 'info@yesilbahcecicek.com',
          address: 'Moda Mah. Feridiye Cad. No:22, Kadikoy/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/yesilbahcecicek',
            icon: 'instagram',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905327184560', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Yesil Bahce Cicekcilik — Kadikoy',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: CICEKCI_MAHALLE_BUSINESS.name, subtitle: CICEKCI_MAHALLE_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
