/**
 * @kepenk/templates — cicekci-online Theme Configuration
 *
 * Online cicek siparisi ve teslimat odakli
 * Plan: starter (6 page sections, 4 global sections)
 * Font: DM Sans/Inter | Accent: #E87461
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const CICEKCI_ONLINE_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#E87461',
  '--color-accent-hover': '#E87461',
  '--color-accent-active': '#E87461',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'DM Sans\', sans-serif',
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const CICEKCI_ONLINE_BUSINESS = {
  name: 'CicekGo Online Cicekcilik',
  ownerName: 'Deniz Arslan',
  sectorId: 'Cicekci',
  slogan: 'Bir tikla kapinizda, taze cicek garantisi',
  phone: '0533 294 81 50',
  phoneClean: '905332948150',
  whatsapp: '905332948150',
  email: 'siparis@cicekgo.com.tr',
  address: 'Camlica Mah. Libadiye Cad. No:118, Uskudar/Istanbul',
  city: 'Istanbul',
  district: 'Uskudar',
  neighborhood: 'Camlica',
  coordinates: { lat: 41.027, lng: 29.062 },
  socialMedia: { instagram: 'https://instagram.com/cicekgoistanbul', facebook: 'https://facebook.com/cicekgo' },
  photos: [],
  foundedYear: 2020,
  experience: '6 yil',
  customerCount: '25.000+',
  rating: 4.6,
  reviewCount: 1800,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '07:00',
      close: '22:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '07:00',
      close: '22:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '07:00',
      close: '22:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '07:00',
      close: '22:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '07:00',
      close: '22:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '07:00',
      close: '22:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Ayni Gun Teslimat',
      price: '+75 TL',
      duration: '2-4 saat',
      description: 'Saat 17:00\'ye kadar verilen siparisler ayni gun teslim. Istanbul geneli.',
    },
    {
      id: 's2',
      name: 'Express Teslimat (2 Saat)',
      price: '+150 TL',
      duration: '2 saat',
      description: 'Acil teslimat, siparisiniz 2 saat icinde kapinizda. Sinirli bolge.',
    },
    {
      id: 's3',
      name: 'Romantik Buket',
      price: '350 - 1.200 TL',
      duration: '20 dk',
      description: 'Gul, lilyum ve ortanca ile romantik aranjman. Sevgiliye hediye icin ideal.',
    },
    {
      id: 's4',
      name: 'Dogum Gunu Paketi',
      price: '500 - 1.500 TL',
      duration: '25 dk',
      description: 'Cicek + balon + cikolata kutusu combo. Dogum gunune ozel hazirlik.',
    },
    {
      id: 's5',
      name: 'Taziye Celengi',
      price: '800 - 2.500 TL',
      duration: '30 dk',
      description: 'Cenaze ve taziye icin celenk, ayakli sepet. Saat ve kurdelali.',
    },
    {
      id: 's6',
      name: 'Abonelik Programi',
      price: '600 TL/hafta',
      duration: 'haftalik',
      description: 'Her hafta kapiniza taze mevsim buketi. 4 haftalik minimum taahhut.',
    },
  ],
  team: [
    {
      name: 'Deniz Arslan',
      role: 'Kurucu & Operasyon Muduru',
      bio: 'E-ticaret gecmisli girisimci. 2020\'de CicekGo\'yu kurdu, 6 yilda 25.000+ teslimat.',
    },
    {
      name: 'Ayca Korkmaz',
      role: 'Bas Cicek Tasarimcisi',
      bio: '10 yillik cicek aranjman deneyimi. Hollanda\'da sus bitkileri egitimi.',
    },
  ],
  testimonials: [
    {
      name: 'Ece Yilmaz',
      district: 'Besiktas',
      date: '2025-11',
      rating: 5,
      comment: 'Express teslimat gercekten 2 saatte geldi. Sevgilime surpriz yaptim, cok begendi. Buket fotograftakinden bile guzel cikti.',
    },
    {
      name: 'Mert Ozkan',
      district: 'Kadikoy',
      date: '2025-10',
      rating: 4,
      comment: 'Haftalik abonelik aliyorum, ofise her Pazartesi taze cicek geliyor. Moral veriyor. Sadece bir kez gecikme yasadik.',
    },
    {
      name: 'Seda Tekin',
      district: 'Atasehir',
      date: '2025-09',
      rating: 5,
      comment: 'Anneme dogum gunu paketi gonderdim. Cicek + balon + cikolata combo\'su cok hosuna gitti. Online siparis cok kolay.',
    },
  ],
  faq: [
    { q: 'Istanbul\'un her yerine teslimat yapiyor musunuz?', a: 'Evet, Istanbul Avrupa ve Anadolu yakasinin tamamina teslimat yapiyoruz. Express teslimat belirli bolgelerle sinirlidir.' },
    { q: 'Cicek begenilmezse degisim var mi?', a: 'Evet, teslimat aninda memnun kalmazsaniz ayni gun icinde degisim yapiyoruz. Memnuniyet garantisi veriyoruz.' },
    { q: 'Ozel tarih hatirlatmasi var mi?', a: 'Evet, dogum gunu ve yildonumu gibi ozel tarihlerinizi kayit edip, 3 gun onceden hatirlatma gonderiyoruz.' },
    { q: 'Fatura kesebiliyor musunuz?', a: 'Evet, bireysel ve kurumsal fatura kesiyoruz. Siparis sirasinda fatura bilgilerinizi iletebilirsiniz.' },
    { q: 'Odeme nasil yapilir?', a: 'Kredi karti, banka karti, havale/EFT ve kapida odeme seceneklerimiz mevcuttur.' },
    { q: 'Abonelik iptal edilebilir mi?', a: 'Evet, 4 haftalik minimum surenin ardindan istediginiz zaman iptal edebilirsiniz. Iptal bir sonraki haftadan gecerli olur.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const CICEKCI_ONLINE_CONFIG = {
  id: 'cicekci-online',
  name: 'Online',
  sectorId: 'cicekci',
  plan: 'starter',
  description: 'Online cicek siparisi ve teslimat odakli',
  designPhilosophy: 'Modern, renkli, pratik',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#E87461',
    '--color-accent-hover': '#E87461',
    '--color-accent-active': '#E87461',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'DM Sans\', sans-serif',
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'DM Sans',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'Florist',
  sectorSections: [],
  performanceBudget: {
    maxJS: '120kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-basic',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'CicekGo Online Cicekcilik' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905332948150',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'CicekGo Online Cicekcilik',
        copyright: '© 2026 CicekGo Online Cicekcilik',
        contact: {
          phone: '0533 294 81 50',
          email: 'siparis@cicekgo.com.tr',
          address: 'Camlica Mah. Libadiye Cad. No:118, Uskudar/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/cicekgoistanbul',
            icon: 'instagram',
          },
          {
            platform: 'facebook',
            url: 'https://facebook.com/cicekgo',
            icon: 'facebook',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905332948150', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'CicekGo Online Cicekcilik — Uskudar',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: CICEKCI_ONLINE_BUSINESS.name, subtitle: CICEKCI_ONLINE_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
