import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const ORGANIK_SUT_BUSINESS: BusinessData = {
  name: 'Sut Urunleri',
  ownerName: 'Fatma Sut',
  sectorId: 'organik',
  slogan: 'Taze sut urunleri',
  phone: '0534 400 33 44',
  phoneClean: '905344003344',
  whatsapp: '905344003344',
  email: 'bilgi@suturunleri.com',
  address: 'Istinye Mah. No:10, Sariyer, Istanbul',
  city: 'Istanbul',
  district: 'Sariyer',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"07:00","close":"20:00"},{"day":"tuesday","dayTr":"Sali","open":"07:00","close":"20:00"},{"day":"wednesday","dayTr":"Carsamba","open":"07:00","close":"20:00"},{"day":"thursday","dayTr":"Persembe","open":"07:00","close":"20:00"},{"day":"friday","dayTr":"Cuma","open":"07:00","close":"20:00"},{"day":"saturday","dayTr":"Cumartesi","open":"07:00","close":"20:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/organik-sut"},
  photos: [],
  services: []
}
export const ORGANIK_SUT_CONFIG: ThemeConfig = { id: 'organik-sut', name: 'Günlük Süt / Mandıra', sectorId: 'organik', plan: 'pro', isDark: false, cssVariables: { '--color-bg': '#FFFFFF', '--color-surface': '#F8FAFC', '--color-text': '#0F172A', '--color-accent': '#3B82F6',
    '--color-accent-light': '#e8fcf6',
    '--color-accent-hover': '#148f68',
    '--color-accent-active': '#127d5b', '--color-text-on-accent': '#FFFFFF', '--color-border': '#E2E8F0', '--font-heading': "'Outfit', sans-serif", '--font-body': "'Inter', sans-serif" }, fonts: { heading: { family: 'Outfit', weights: [600] }, body: { family: 'Inter', weights: [400] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Sut Urunleri' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Sut Urunleri',
        copyright: '© 2026 Sut Urunleri',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'Köy Mandırası', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'xl', containerWidth: 'xl', visible: true }, defaultContent: { badge: 'GÜNLÜK SÜT', title: 'En Doğal Peynir ve Süt Ürünleri' } } ] }] }