import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const RESTORAN_NAR_CSS: Record<string, string> = {
  '--container-default': '1280px',
  '--section-py': '96px',
  '--radius-md': '4px',
  '--radius-lg': '8px',
  '--color-bg': '#FAF8F5',
  '--color-surface': '#FFFFFF',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F5EFEB',
  '--color-text': '#1C1917',
  '--color-text-secondary': '#6B6661',
  '--color-text-muted': '#A8A29E',
  '--color-text-on-accent': '#FAF8F5',
  '--color-text-on-dark': '#FAF8F5',
  '--color-accent': '#8E1E31',
  '--color-accent-hover': '#721523',
  '--color-accent-active': '#580D17',
  '--color-accent-light': '#FCEEEF',
  '--color-border': '#E7E5E4',
  '--color-border-subtle': '#F5F5F4',
  '--font-heading': "'Playfair Display', serif",
  '--font-body': "'Montserrat', sans-serif",
}

export const RESTORAN_NAR_BUSINESS = {
  name: 'Nar & Kakule Osmanlı Saray Mutfağı',
  ownerName: 'Mümin Kaplan',
  sectorId: 'Restoran',
  slogan: 'Asırlık Osmanlı saray lezzetleri ve fütüristik gurme deneyimi',
  phone: '0212 555 12 18',
  phoneClean: '902125551218',
  whatsapp: '905355551218',
  email: 'iletisim@narkakule.com',
  address: 'Saray Cad. No:12, Sultanahmet, Fatih/İstanbul',
  city: 'İstanbul',
  district: 'Fatih',
  neighborhood: 'Sultanahmet',
  coordinates: { lat: 41.0082, lng: 28.9784 },
  socialMedia: { instagram: 'https://instagram.com/narkakulesaray' },
  photos: [],
  foundedYear: 2018,
  experience: '10 yıllık saray usta birikimi',
  customerCount: '25.000+',
  rating: 4.9,
  reviewCount: 1420,
  services: [
    {
      id: 's1',
      name: 'Hünkar Beğendi (Saray Usulü)',
      price: '480 TL',
      duration: '20 dk',
      description: 'Köz patlıcan yatağında, tereyağında ağır ağır pişmiş kuzu eti ve özel saray baharatları.',
    },
    {
      id: 's2',
      name: 'Vişneli Yaprak Sarma',
      price: '220 TL',
      duration: '10 dk',
      description: 'Zeytinyağlı vişne taneleriyle sarılmış narin asma yaprakları, sızma zeytinyağı ile.',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '12:00', close: '23:30', isOpen: true },
    { day: 'Salı', open: '12:00', close: '23:30', isOpen: true },
    { day: 'Çarşamba', open: '12:00', close: '23:30', isOpen: true },
    { day: 'Perşembe', open: '12:00', close: '23:30', isOpen: true },
    { day: 'Cuma', open: '12:00', close: '23:30', isOpen: true },
    { day: 'Cumartesi', open: '12:00', close: '00:00', isOpen: true },
    { day: 'Pazar', open: '12:00', close: '22:30', isOpen: true },
  ],
} as unknown as BusinessData

export const RESTORAN_NAR_CONFIG = {
  id: 'restoran-nar',
  name: 'Nar',
  sectorId: 'restoran',
  plan: 'growth',
  description: 'Lüks Osmanlı mutfağı, tarihi yarımada saray konseptli gurme tema',
  designPhilosophy: 'Derin nar kırmızısı asil vurgular, görkemli Playfair Display başlıkları',
  isDark: false,
  cssVariables: RESTORAN_NAR_CSS,
  fonts: {
    heading: {
      family: 'Playfair Display',
      weights: [600, 700],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Montserrat',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'Restaurant',
  sectorSections: ['menu_display', 'daily_special', 'reservation'],
  performanceBudget: {
    maxJS: '110kb',
    maxLCP: '2.1s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: RESTORAN_NAR_BUSINESS.name },
        menuItems: [
          { label: 'Saray Menüsü', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: { text: 'Masayı Ayırt', href: 'https://wa.me/905355551218', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'dark', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: RESTORAN_NAR_BUSINESS.name,
        copyright: '© 2026 Nar & Kakule Osmanlı Saray Mutfağı. Tüm hakları saklıdır.',
        contact: {
          phone: RESTORAN_NAR_BUSINESS.phone,
          email: RESTORAN_NAR_BUSINESS.email,
          address: RESTORAN_NAR_BUSINESS.address,
        },
        social: [{ platform: 'instagram', url: 'https://instagram.com/narkakulesaray', icon: 'instagram' }],
        legal: [
          { label: 'Sözleşme Şartları', href: '/sartlar' },
          { label: 'KVKK Bilgisi', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1000, removable: false, animation: 'none' },
      defaultContent: { phone: '905355551218', message: 'Tarihi Sultanahmet restoranınızda rezervasyon yapmak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${RESTORAN_NAR_BUSINESS.name} — Sultanahmet Osmanlı Gurme Lezzetler`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_editorial_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'TARİHİ SARAY LEZZETLERİ',
            title: RESTORAN_NAR_BUSINESS.name,
            subtitle: RESTORAN_NAR_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Kuruluş Yılı / Etiket', type: 'text' },
            { path: 'title', label: 'Kulüp İsmi', type: 'text' },
            { path: 'subtitle', label: 'Alt Başlık / Slogan', type: 'richtext' },
          ],
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_editorial_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: {
            badge: 'MİSAFİR AĞIRLAMA SANATI',
            title: 'Osmanlı Mirasını Günümüze Taşıyan Lezzet',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'Felsefe Başlığı', type: 'text' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_editorial_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'MENÜ SEANSLARI',
            title: 'Saray Gurme İstasyonlarımız',
          },
          editableFields: [
            { path: 'badge', label: 'Küçük Etiket', type: 'text' },
            { path: 'title', label: 'Ana Bölüm Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_editorial_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'SİZİ BEKLİYORUZ',
            title: 'Lüks Saray Sofrasında Rezervasyon',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
