/**
 * @kepenk/templates — terzi-tadilat Theme Configuration
 *
 * Mahalle terzisi, tadilat ve tamir odakli
 * Plan: free (3 page sections, 3 global sections)
 * Font: Inter/Inter | Accent: #6B4C3B
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const TERZI_TADILAT_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#6B4C3B',
  '--color-accent-hover': '#6B4C3B',
  '--color-accent-active': '#6B4C3B',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': "'Merriweather', sans-serif",
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const TERZI_TADILAT_BUSINESS = {
  name: 'Huseyin Usta Terzi',
  ownerName: 'Huseyin Celik',
  sectorId: 'Terzi',
  slogan: '40 yillik usta eli, her kiyafete cozum',
  phone: '0532 615 84 20',
  phoneClean: '905326158420',
  whatsapp: '905326158420',
  email: 'info@huseyinustaterzi.com',
  address: 'Rasimpasa Mah. Sogutlucesme Cad. No:31/B, Kadikoy/Istanbul',
  city: 'Istanbul',
  district: 'Kadikoy',
  neighborhood: 'Rasimpasa',
  coordinates: { lat: 40.9925, lng: 29.031 },
  socialMedia: { instagram: 'https://instagram.com/huseyinustaterzi' },
  photos: [],
  foundedYear: 1986,
  experience: '40 yil',
  customerCount: '60.000+',
  rating: 4.7,
  reviewCount: 890,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '08:30',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '08:30',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '08:30',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '08:30',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '08:30',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '09:00',
      close: '17:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '00:00',
      close: '00:00',
      isOpen: false,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Pantolon Paca Kisaltma',
      price: '150 TL',
      duration: '30 dk',
      description: 'Her turlu kumastan pantolon paca kisaltma. Orijinal dikisin korunmasi ile.',
    },
    {
      id: 's2',
      name: 'Fermuar Degisimi',
      price: '200 TL',
      duration: '45 dk',
      description: 'Pantolon, mont, etek fermuar degisimi. Orijinal renge uygun fermuar secimi.',
    },
    {
      id: 's3',
      name: 'Beden Daraltma/Genisletme',
      price: '300 TL',
      duration: '60 dk',
      description: 'Gomlek, ceket, pantolon beden ayarlama. Kalip bozulmadan profesyonel mudahale.',
    },
    {
      id: 's4',
      name: 'Yirtik/Soku Tamiri',
      price: '100 TL\'den baslayan',
      duration: '20 dk',
      description: 'Her turlu yirtik, soku ve delik tamiri. Gorunmez dikis teknigi ile.',
    },
  ],
  team: [],
  testimonials: [],
  faq: [
    { q: 'Tadilat ne kadar surede tamamlanir?', a: 'Basit islemler (paca, fermuar) ayni gun, karmasik islemler (beden degisikligi) 2-3 is gununde tamamlanir.' },
    { q: 'Deri ve suni deri urunlerde tadilat yapiyor musunuz?', a: 'Evet, deri ceket, mont ve canta tadilatı yapiyoruz. Deri islemlerde fiyat standart kumastan %30-50 daha yuksektir.' },
    { q: 'Gelinlik tadilatı yapiyor musunuz?', a: 'Evet, gelinlik beden ayarlama ve boy kisaltma yapiyoruz. Gelinlik islemleri icin onceden randevu almanizi oneririz.' },
    { q: 'Kargo ile gonderebilir miyim?', a: 'Maalesef tadilat islmelerinde prova gerektiginden, kiyafetin sahsen getirilmesi gerekmektedir.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const TERZI_TADILAT_CONFIG = {
  id: 'terzi-tadilat',
  name: 'Tadilat',
  sectorId: 'terzi',
  plan: 'free',
  description: 'Mahalle terzisi, tadilat ve tamir odakli',
  designPhilosophy: 'Sade, guvenilir, islevsel',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#6B4C3B',
    '--color-accent-hover': '#6B4C3B',
    '--color-accent-active': '#6B4C3B',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': "'Merriweather', sans-serif",
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Merriweather',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'TailorShop',
  sectorSections: [],
  performanceBudget: {
    maxJS: '80kb',
    maxLCP: '3.0s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Huseyin Usta Terzi' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905326158420',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Huseyin Usta Terzi',
        copyright: '© 2026 Huseyin Usta Terzi',
        contact: {
          phone: '0532 615 84 20',
          email: 'info@huseyinustaterzi.com',
          address: 'Rasimpasa Mah. Sogutlucesme Cad. No:31/B, Kadikoy/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/huseyinustaterzi',
            icon: 'instagram',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905326158420', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Huseyin Usta Terzi — Kadikoy',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: TERZI_TADILAT_BUSINESS.name, subtitle: TERZI_TADILAT_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
