import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const BERBER_SADE_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '4px',
  '--radius-lg': '8px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F9F9F9',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F0F0F0',
  '--color-text': '#111111',
  '--color-text-secondary': '#666666',
  '--color-text-muted': '#999999',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#000000',
  '--color-accent-hover': '#222222',
  '--color-accent-active': '#444444',
  '--color-accent-light': '#F5F5F5',
  '--color-border': '#E5E2DB',
  '--color-border-subtle': '#F0F0F0',
  '--font-heading': "'Inter', sans-serif",
  '--font-body': "'Inter', sans-serif",
}

export const BERBER_SADE_BUSINESS = {
  name: 'Sade Berber',
  ownerName: 'Mehmet Sade',
  sectorId: 'Berber',
  slogan: 'Karmaşadan uzak, net ve temiz kesim',
  phone: '0212 222 01 14',
  phoneClean: '902122220114',
  whatsapp: '905322221114',
  email: 'mehmet@sadeberber.com',
  address: 'Levent Mah. Çarşı Cad. No:14, Beşiktaş/İstanbul',
  city: 'İstanbul',
  district: 'Beşiktaş',
  neighborhood: 'Levent',
  coordinates: { lat: 41.0772, lng: 29.0143 },
  socialMedia: { instagram: 'https://instagram.com/sadeberber' },
  photos: [],
  foundedYear: 2020,
  experience: '10 yıl tecrübe',
  customerCount: '2.500+',
  rating: 4.6,
  reviewCount: 180,
  services: [
    {
      id: 's1',
      name: 'Modern Saç Kesimi',
      price: '600 TL',
      duration: '30 dk',
      description: 'Hızlı, minimalist yaklaşımla modern saç tasarımı ve şekillendirme.',
    },
    {
      id: 's2',
      name: 'Hızlı Sakal Düzeltme',
      price: '350 TL',
      duration: '15 dk',
      description: 'Makine ile sakal boyu kısaltma ve yanak çizgisi düzeltme seansı.',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '10:00', close: '20:00', isOpen: true },
    { day: 'Salı', open: '10:00', close: '20:00', isOpen: true },
    { day: 'Çarşamba', open: '10:00', close: '20:00', isOpen: true },
    { day: 'Perşembe', open: '10:00', close: '20:00', isOpen: true },
    { day: 'Cuma', open: '10:00', close: '20:00', isOpen: true },
    { day: 'Cumartesi', open: '09:00', close: '19:00', isOpen: true },
    { day: 'Pazar', open: null, close: null, isOpen: false },
  ],
} as unknown as BusinessData

export const BERBER_SADE_CONFIG = {
  id: 'berber-sade',
  name: 'Sade',
  sectorId: 'berber',
  plan: 'starter',
  description: 'Minimalist, modern ve sadece siyah-beyaz tonlarda tasarlanmış sade şablon',
  designPhilosophy: 'Siyah-beyaz minimalizm, monokrom şıklık ve net çizgiler',
  isDark: false,
  cssVariables: BERBER_SADE_CSS,
  fonts: {
    heading: {
      family: 'Inter',
      weights: [600, 700],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'BarberShop',
  sectorSections: ['before_after', 'booking'],
  performanceBudget: {
    maxJS: '50kb',
    maxLCP: '2.0s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: BERBER_SADE_BUSINESS.name },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: { text: 'İletişim', href: 'tel:902122220114', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'default', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: BERBER_SADE_BUSINESS.name,
        copyright: '© 2026 Sade Berber. Tüm hakları saklıdır.',
        contact: {
          phone: BERBER_SADE_BUSINESS.phone,
          email: BERBER_SADE_BUSINESS.email,
          address: BERBER_SADE_BUSINESS.address,
        },
        social: [],
        legal: [{ label: 'KVKK', href: '/kvkk' }],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${BERBER_SADE_BUSINESS.name} — Levent Minimalist Erkek Kuaförü`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'MİNİMAL BAKIM',
            title: BERBER_SADE_BUSINESS.name,
            subtitle: BERBER_SADE_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Eski Kurdele Yazısı', type: 'text' },
            { path: 'title', label: 'Dükkan Adı', type: 'text' },
            { path: 'subtitle', label: 'Slogan / Alt Metin', type: 'richtext' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 2,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'HİZMETLER',
            title: 'Net ve Temiz Fiyatlandırma',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'Servis Menüsü Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 3,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'KONUMUZ',
            title: 'Sade Tasarıma Gelin',
          },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
