import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const NAKLIYAT_SEHIRLER_BUSINESS: BusinessData = {
  name: 'Sehirlerarasi Nakliyat',
  ownerName: 'Murat Sehirler',
  sectorId: 'nakliyat',
  slogan: 'Sehirlerarasi nakliyat',
  phone: '0534 500 33 44',
  phoneClean: '905345003344',
  whatsapp: '905345003344',
  email: 'bilgi@sehirnakliyat.com',
  address: 'Barbaros Mah. No:30, Atasehir, Istanbul',
  city: 'Istanbul',
  district: 'Atasehir',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"07:00","close":"20:00"},{"day":"tuesday","dayTr":"Sali","open":"07:00","close":"20:00"},{"day":"wednesday","dayTr":"Carsamba","open":"07:00","close":"20:00"},{"day":"thursday","dayTr":"Persembe","open":"07:00","close":"20:00"},{"day":"friday","dayTr":"Cuma","open":"07:00","close":"20:00"},{"day":"saturday","dayTr":"Cumartesi","open":"07:00","close":"20:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/nakliyat-sehirler"},
  photos: [],
  services: []
}
export const NAKLIYAT_SEHIRLER_CONFIG: ThemeConfig = { id: 'nakliyat-sehirler', name: 'Şehirler Arası', sectorId: 'nakliyat', plan: 'pro', isDark: false, cssVariables: { '--color-bg': '#FFFFFF', '--color-surface': '#F8FAFC', '--color-text': '#0F172A', '--color-accent': '#F97316',
    '--color-accent-light': '#fcfae8',
    '--color-accent-hover': '#8f8114',
    '--color-accent-active': '#7d7012', '--color-text-on-accent': '#FFFFFF', '--color-border': '#E2E8F0', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif" }, fonts: { heading: { family: 'Outfit', weights: [700] }, body: { family: 'Inter', weights: [400] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Sehirlerarasi Nakliyat' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Sehirlerarasi Nakliyat',
        copyright: '© 2026 Sehirlerarasi Nakliyat',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'Tüm Türkiye Nakliyat', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'xl', containerWidth: 'xl', visible: true }, defaultContent: { badge: 'ŞEHİRLER ARASI', title: 'Türkiye\'nin Her Yerine Sigortalı Taşıma' } } ] }] }