import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const OZELDERS_KAMPUS_BUSINESS: BusinessData = {
  name: 'Kampus Ozel Ders',
  ownerName: 'Ogr. Deniz Kampus',
  sectorId: 'ozelders',
  slogan: 'Kampus ortaminda ders',
  phone: '0534 100 33 44',
  phoneClean: '905341003344',
  whatsapp: '905341003344',
  email: 'bilgi@kampusders.com',
  address: 'Barbaros Mah. No:18, Atasehir, Istanbul',
  city: 'Istanbul',
  district: 'Atasehir',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"09:00","close":"21:00"},{"day":"tuesday","dayTr":"Sali","open":"09:00","close":"21:00"},{"day":"wednesday","dayTr":"Carsamba","open":"09:00","close":"21:00"},{"day":"thursday","dayTr":"Persembe","open":"09:00","close":"21:00"},{"day":"friday","dayTr":"Cuma","open":"09:00","close":"21:00"},{"day":"saturday","dayTr":"Cumartesi","open":"09:00","close":"21:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/ozelders-kampus"},
  photos: [],
  services: []
}
export const OZELDERS_KAMPUS_CONFIG: ThemeConfig = { id: 'ozelders-kampus', name: 'Kampüs Hazırlık', sectorId: 'ozelders', plan: 'growth', isDark: false, cssVariables: { '--color-bg': '#FFFFFF', '--color-surface': '#F8FAFC', '--color-text': '#0F172A', '--color-accent': '#F59E0B',
    '--color-accent-light': '#fce8f2',
    '--color-accent-hover': '#ad1f64',
    '--color-accent-active': '#9c1c5a', '--color-text-on-accent': '#FFFFFF', '--color-border': '#E2E8F0', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif" }, fonts: { heading: { family: 'Inter', weights: [700] }, body: { family: 'Inter', weights: [400] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Kampus Ozel Ders' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Kampus Ozel Ders',
        copyright: '© 2026 Kampus Ozel Ders',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'Kampüs Hazırlık Anasayfa', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'xl', containerWidth: 'xl', visible: true }, defaultContent: { badge: 'KAMPÜS HAZIRLIK', title: 'Profesyonel Kampüs Hazırlık Hizmetleri' } } ] }] }