/**
 * @kepenk/templates — cicekci-lux Theme Configuration
 *
 * Premium cicek boutique, luks aranjman
 * Plan: pro (11 page sections, 4 global sections)
 * Font: Playfair Display/Lato | Accent: #8B6914
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const CICEKCI_LUX_CSS: Record<string, string> = {
  '--container-default': '1200px',
  '--section-py': '96px',
  '--radius-md': '2px',
  '--radius-lg': '4px',
  '--color-bg': '#FAFAF9',
  '--color-surface': '#F5F5F4',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#E7E5E4',
  '--color-text': '#1C1917',
  '--color-text-secondary': '#57534E',
  '--color-text-muted': '#A8A29E',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#8B6914',
  '--color-accent-hover': '#8B6914',
  '--color-accent-active': '#8B6914',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#D6D3D1',
  '--color-border-subtle': '#E7E5E4',
  '--font-heading': '\'Playfair Display\', sans-serif',
  '--font-body': '\'Lato\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const CICEKCI_LUX_BUSINESS = {
  name: 'Maison Florale Istanbul',
  ownerName: 'Ceren Oztürk',
  sectorId: 'Cicekci',
  slogan: 'Cicegi sanata donusturen eller',
  phone: '0535 482 17 90',
  phoneClean: '905354821790',
  whatsapp: '905354821790',
  email: 'atelier@maisonflorale.com.tr',
  address: 'Nisantasi Mah. Tesvikiye Cad. No:89/2, Sisli/Istanbul',
  city: 'Istanbul',
  district: 'Sisli',
  neighborhood: 'Nisantasi',
  coordinates: { lat: 41.0485, lng: 28.9936 },
  socialMedia: {
    instagram: 'https://instagram.com/maisonfloraleist',
    facebook: 'https://facebook.com/maisonflorale',
    pinterest: 'https://pinterest.com/maisonflorale',
    tiktok: 'https://tiktok.com/@maisonflorale',
  },
  photos: [],
  foundedYear: 2013,
  experience: '13 yil',
  customerCount: '12.000+',
  rating: 4.9,
  reviewCount: 1650,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '09:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '09:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '09:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '09:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '09:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '10:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '10:00',
      close: '17:00',
      isOpen: true,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Signature Buket',
      price: '800 - 3.000 TL',
      duration: '20 dk',
      description: 'Maison Florale imzali ozel tasarim buket. Premium cicekler, el yapimi ambalaj.',
    },
    {
      id: 's2',
      name: 'Kutuda Cicek (Flower Box)',
      price: '1.200 - 4.000 TL',
      duration: '25 dk',
      description: 'Kadife kutuda premium gul veya karisik cicek. Uzun omurlu korunmus cicek secenegi.',
    },
    {
      id: 's3',
      name: 'Orkide Koleksiyonu',
      price: '1.500 - 6.000 TL',
      duration: 'hazir',
      description: 'Nadir orkide cesitleri, tasarim saksilar ve ozel sunum. Hediye ve dekorasyon icin.',
    },
    {
      id: 's4',
      name: 'Kurumsal Abonelik',
      price: '2.500 TL/hafta',
      duration: 'haftalik',
      description: 'Otel, restoran, ofis lobbisi icin haftalik cicek degisimi. Mevsimsel tasarim.',
    },
    {
      id: 's5',
      name: 'Ev Icin Cicek Tasarimi',
      price: '1.000 - 5.000 TL/ziyaret',
      duration: '60 dk',
      description: 'Evinize gelerek mekan ve dekorasyona uygun cicek aranjmanlari olusturma.',
    },
    {
      id: 's6',
      name: 'Preserved (Korunmus) Cicekler',
      price: '2.000 - 8.000 TL',
      duration: 'hazir',
      description: '2-3 yil dayanan korunmus gul ve bitki aranjmanlari. Cam fanus ve kutu secenekleri.',
    },
    {
      id: 's7',
      name: 'VIP Hediye Paketi',
      price: '2.500 - 10.000 TL',
      duration: 'hazirlik',
      description: 'Cicek + premium cikolata + mum + kisisel kart. Ozel ambalaj ve kuryee teslimat.',
    },
    {
      id: 's8',
      name: 'Mekan Lansmanı Dekorasyonu',
      price: '5.000 - 25.000 TL',
      duration: '4-6 saat',
      description: 'Magaza acilis, restoran lansman, showroom cicek dekorasyonu.',
    },
    {
      id: 's9',
      name: 'Cicek Aranjman Workshopu',
      price: '800 TL/kisi',
      duration: '2 saat',
      description: 'Profesyonel cicek aranjman teknikleri. Malzeme dahil, 6-10 kisilik grup.',
    },
    {
      id: 's10',
      name: 'Sezonluk Dekoratif Bitki Bakimi',
      price: '500 TL/ay',
      duration: 'aylik',
      description: 'Evinizdeki saksi bitkilerinin bakim, sulama ve gubre programi. Aylik ziyaret.',
    },
    {
      id: 's11',
      name: 'Dogum Gunu Surpriz Servisi',
      price: '1.500 - 5.000 TL',
      duration: 'degisken',
      description: 'Cicek + balon + pasta koordinasyonu, surpriz mekan kurulumu.',
    },
    {
      id: 's12',
      name: 'Taziye & Basasagligi',
      price: '600 - 3.000 TL',
      duration: '20 dk',
      description: 'Cenaze celengi, taziye aranjmani. Saatli ve kurdelali, ozenli hazırlik.',
    },
    {
      id: 's13',
      name: 'Botanik Danismanlik',
      price: 'Ucretsiz',
      duration: '15 dk',
      description: 'Bitki secimi, bakim onerisi, ev/ofis icin uygun bitki danismanligi.',
    },
    {
      id: 's14',
      name: 'Ayin Cicegi Aboneligi',
      price: '1.200 TL/ay',
      duration: 'aylik',
      description: 'Her ay farkli tema ve ciceklerle ozel bir buket kapinizda.',
    },
  ],
  team: [
    {
      name: 'Ceren Ozturk',
      role: 'Kurucu & Kreatif Direktor',
      bio: 'Hollanda Boerma Instituut cicek tasarım okulu mezunu. 13 yillik deneyim, uluslararasi cicek yarismalari odul sahibi.',
    },
    {
      name: 'Aysun Demir',
      role: 'Preserved Cicek Uzmani',
      bio: 'Korunmus cicek teknikleri konusunda Turkiye\'nin ilk uzmanlarindan. 8 yillik deneyim.',
    },
    {
      name: 'Burcu Yilmaz',
      role: 'Kurumsal Hesap Yoneticisi',
      bio: '5 yuzun fazla otel, restoran ve ofis hesabini yonetiyor. Lojistik ve musteri iliskileri uzmani.',
    },
    {
      name: 'Kerem Aksoy',
      role: 'Cicek Tasarimcisi',
      bio: 'Guzel sanatlar mezunu. Minimal ve modern aranjman tarzinda uzman. Workshop egitmeni.',
    },
    {
      name: 'Fatma Cakir',
      role: 'Bitki Bakimi Danismani',
      bio: 'Botanik bolumu mezunu. Ev ve ofis bitkileri bakimi, sezonluk gecis planlama.',
    },
    {
      name: 'Ali Dogan',
      role: 'Teslimat & Kurulum Sefi',
      bio: '6 yildir Maison Florale teslimat ekibini yonetiyor. VIP teslimat ve mekan kurulumu.',
    },
  ],
  testimonials: [
    {
      name: 'Berna Aksoy',
      district: 'Nisantasi',
      date: '2025-12',
      rating: 5,
      comment: 'Kutuda cicek hediyelik olarak cok sik. Kadife kutu ve premium gullerin sunumu muhtesem. Alanlarin hepsi hayran kaliyor.',
    },
    {
      name: 'Selma Yildirim',
      district: 'Etiler',
      date: '2025-11',
      rating: 5,
      comment: 'Evim icin cicek tasarim hizmeti aldim. Ceren Hanim evime geldi, dekorasyonuma uygun aranjmanlar olusturdu. Ev bambaşka gorunuyor.',
    },
    {
      name: 'Hakan Ozturk',
      district: 'Levent',
      date: '2025-10',
      rating: 5,
      comment: 'Ofisimize kurumsal abonelik aldik. Her hafta lobbimizde taze ve farkli cicekler oluyor. Müsterilerimiz her geldiginde fark ediyor.',
    },
    {
      name: 'Cigdem Sahin',
      district: 'Bebek',
      date: '2025-09',
      rating: 5,
      comment: 'Preserved cicek aranjmani aldim, 2 yildir duruyor yeniymiş gibi. Cam fanustaki guller cok zarif gorunuyor.',
    },
    {
      name: 'Emre Polat',
      district: 'Sisli',
      date: '2025-08',
      rating: 5,
      comment: 'VIP hediye paketi gonderdim. Cicek + cikolata + mum + el yazisi kart. Alici cok duyulandu, sunum gercekten premium.',
    },
    {
      name: 'Nil Kaya',
      district: 'Kadikoy',
      date: '2025-07',
      rating: 4,
      comment: 'Workshop\'a katildim, cok keyifliydi. Kendi buketimi yaptim ve eve goturdüm. Tek elestiri: 2 saat biraz kisa geldi.',
    },
    {
      name: 'Duygu Arslan',
      district: 'Besiktas',
      date: '2025-06',
      rating: 5,
      comment: 'Restoran lansmanı icin dekorasyon yaptirdik. Giris ve masalar ciceklerle doluydu. Instagram\'da cok begeni aldi, harika iscilik.',
    },
    {
      name: 'Serkan Tekin',
      district: 'Uskudar',
      date: '2025-11',
      rating: 5,
      comment: 'Ayin cicegi aboneligini esime aldim. Her ay surpriz oluyor, farkli tema ve ciceklerle geliyor. En guzel hediye fikri.',
    },
  ],
  faq: [
    { q: 'Preserved (korunmus) cicek nedir?', a: 'Ozel bir kimyasal islemle 2-3 yil boyunca taze gorunumunu koruyan gercek ciceklerdir. Su, gunes isigi gerektirmez. Gul, hortensia ve okaliptus en populer turlerdir.' },
    { q: 'Kurumsal abonelik nasil calisiyor?', a: 'Mekana ozel boyut ve stil belirliyoruz. Her hafta belirli gunde ekibimiz gelir, eski aranjmani alir, yenisini bırakır. Mevsimsel degisim yapilir.' },
    { q: 'Ev icin cicek tasarimi nasil oluyor?', a: 'Ceren Hanim evinize gelir, mekani, dekorasyonu ve doğal isigi degerlendirir. Uygun cicek ve bitki aranjmanlari olusturur. Istenirse aylik bakim programi da ayarlanır.' },
    { q: 'Workshop\'a kimler katilabilir?', a: '18 yas ustu herkes katilabilir, deneyim gerekmez. Kurumsal grup workshoplari da duzenliyoruz. Malzeme dahildir, kendi buketinizi eve goturursuunuz.' },
    { q: 'Istanbul disi teslimat var mi?', a: 'Istanbul geneline teslimat yapiyoruz. Istanbul dışına preserved cicek ve kutuda cicek gondeerimi yapilabilir, kargo ile.' },
    { q: 'VIP hediye paketini kissellestirebilir miyim?', a: 'Evet, cicek cesidi, cikolata markasi, mum kokusu ve kart mesajini siz belirleyebilirsiniz. Tamamen kisisellestirilmis paketler hazırliyoruz.' },
    { q: 'Mekan dekorasyonu icin ne kadar onceden basvurmali?', a: 'En az 2 hafta once basvurmanizi oneririz. Buyuk organizasyonlar icin 1 ay ideal.' },
    { q: 'Taze cicek garrantisi var mi?', a: 'Evet, tum taze cicek urunlerimiz 5 gun tazelik garantilidir. Beklentinin altinda kalan urunlerde ucretsiz yenileme yapiyoruz.' },
    { q: 'Fatura ve taksit imkani var mi?', a: 'Evet, bireysel ve kurumsal fatura kesiyoruz. 1.000 TL ustu alisverislerde 3 taksit imkani sunuyoruz.' },
    { q: 'Bitki bakimi icin eve geliyor musunuz?', a: 'Evet, sezonluk bakım aboneligi ile ayda 1 kez evinize gelerek bitkillerinizin bakim, budama ve gubre islemlerini yapiyoruz.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const CICEKCI_LUX_CONFIG = {
  id: 'cicekci-lux',
  name: 'Lux',
  sectorId: 'cicekci',
  plan: 'pro',
  description: 'Premium cicek boutique, luks aranjman',
  designPhilosophy: 'Luks, minimal, rafine',
  isDark: false,
  cssVariables: {
    '--container-default': '1200px',
    '--section-py': '96px',
    '--radius-md': '2px',
    '--radius-lg': '4px',
    '--color-bg': '#FAFAF9',
    '--color-surface': '#F5F5F4',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#E7E5E4',
    '--color-text': '#1C1917',
    '--color-text-secondary': '#57534E',
    '--color-text-muted': '#A8A29E',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#8B6914',
    '--color-accent-hover': '#8B6914',
    '--color-accent-active': '#8B6914',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#D6D3D1',
    '--color-border-subtle': '#E7E5E4',
    '--font-heading': '\'Playfair Display\', sans-serif',
    '--font-body': '\'Lato\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Playfair Display',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Lato',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'Florist',
  sectorSections: [],
  performanceBudget: {
    maxJS: '250kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Maison Florale Istanbul' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905354821790',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Maison Florale Istanbul',
        copyright: '© 2026 Maison Florale Istanbul',
        contact: {
          phone: '0535 482 17 90',
          email: 'atelier@maisonflorale.com.tr',
          address: 'Nisantasi Mah. Tesvikiye Cad. No:89/2, Sisli/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/maisonfloraleist',
            icon: 'instagram',
          },
          {
            platform: 'facebook',
            url: 'https://facebook.com/maisonflorale',
            icon: 'facebook',
          },
          {
            platform: 'pinterest',
            url: 'https://pinterest.com/maisonflorale',
            icon: 'pinterest',
          },
          {
            platform: 'tiktok',
            url: 'https://tiktok.com/@maisonflorale',
            icon: 'tiktok',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905354821790', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Maison Florale Istanbul — Sisli',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_editorial_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'ÖZEL KONSEPT', title: CICEKCI_LUX_BUSINESS.name, subtitle: CICEKCI_LUX_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'about',
          variant: 'tier1_editorial_about',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { title: 'Felsefemiz' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_editorial_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'ATELIER', title: 'Seçkin Koleksiyon' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_editorial_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'text', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { title: 'Randevu & Danışmanlık' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
