/**
 * @kepenk/templates — dis-modern Theme Configuration
 *
 * Mahalle dis klinigi, temiz ve guvenilir
 * Plan: free (3 page sections, 3 global sections)
 * Font: Inter/Inter | Accent: #2B7A9E
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const DIS_MODERN_CSS: Record<string, string> = {
  '--container-default': '1120px',
  '--section-py': '80px',
  '--radius-md': '8px',
  '--radius-lg': '16px',
  '--color-bg': '#FCFCFD',
  '--color-surface': '#F1F3F5',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#E9ECEF',
  '--color-text': '#212529',
  '--color-text-secondary': '#495057',
  '--color-text-muted': '#868E96',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#2B7A9E',
  '--color-accent-hover': '#2B7A9E',
  '--color-accent-active': '#2B7A9E',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#DEE2E6',
  '--color-border-subtle': '#F1F3F5',
  '--font-heading': "'Oswald', sans-serif",
  '--font-body': "'Source Sans 3', system-ui, sans-serif",
}

// ═══ DEMO BUSINESS DATA ═══

export const DIS_MODERN_BUSINESS = {
  name: 'Dis Hekimi Ayse Korkmaz',
  ownerName: 'Ayse Korkmaz',
  sectorId: 'Dis',
  slogan: 'Saglikli gulus, mutlu hayat',
  phone: '0216 345 12 34',
  phoneClean: '902163451234',
  whatsapp: '905361234567',
  email: 'info@dthaysekorkmaz.com',
  address: 'Acıbadem Mah. Kucuksu Cad. No:45/B, Uskudar/Istanbul',
  city: 'Istanbul',
  district: 'Uskudar',
  neighborhood: 'Acibadem',
  coordinates: { lat: 41.0042, lng: 29.0391 },
  socialMedia: { instagram: 'https://instagram.com/dtaysekorkmaz' },
  photos: [],
  foundedYear: 2018,
  experience: '8 yil',
  customerCount: '6.500+',
  rating: 4.8,
  reviewCount: 520,
  services: [
    {
      id: 's1',
      name: 'Dis Dolgusu (Kompozit)',
      price: '800 - 1.500 TL',
      duration: '30-45 dk',
      description: 'Dis renginde estetik dolgular. Curuk tedavisi ve kirik dis onarimi icin kullanilan uzun omurlu kompozit dolgu.',
    },
    {
      id: 's2',
      name: 'Dis Cekimi',
      price: '500 - 2.000 TL',
      duration: '20-40 dk',
      description: 'Lokal anestezi altinda agrisiz dis cekimi. Gomulu 20 yas disi cekimi dahil. Cekim sonrasi bakim yonergeleri verilir.',
    },
    {
      id: 's3',
      name: 'Dis Tasi Temizligi',
      price: '600 TL',
      duration: '30 dk',
      description: 'Ultrasonik cihazla dis tasi ve plak temizligi. 6 ayda bir yapilmasi onerilen rutin bakim islemi.',
    },
    {
      id: 's4',
      name: 'Kanal Tedavisi',
      price: '2.000 - 3.500 TL',
      duration: '60-90 dk',
      description: 'Iltihaplanmis veya enfekte olmus dis sinirinin tedavisi. Disin cekilmeden kurtarilmasini saglayan endodontik islem.',
    },
  ],
  workingHours: [
    {
      day: 'Pazartesi',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '10:00',
      close: '14:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: null,
      close: null,
      isOpen: false,
    },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const DIS_MODERN_CONFIG = {
  id: 'dis-modern',
  name: 'Modern',
  sectorId: 'dis',
  plan: 'free',
  description: 'Mahalle dis klinigi, temiz ve guvenilir',
  designPhilosophy: 'Temiz, beyaz, saglik hissi',
  isDark: false,
  cssVariables: {
    '--container-default': '1120px',
    '--section-py': '80px',
    '--radius-md': '8px',
    '--radius-lg': '16px',
    '--color-bg': '#FCFCFD',
    '--color-surface': '#F1F3F5',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#E9ECEF',
    '--color-text': '#212529',
    '--color-text-secondary': '#495057',
    '--color-text-muted': '#868E96',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#2B7A9E',
    '--color-accent-hover': '#2B7A9E',
    '--color-accent-active': '#2B7A9E',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#DEE2E6',
    '--color-border-subtle': '#F1F3F5',
    '--font-heading': "'Oswald', sans-serif",
    '--font-body': "'Source Sans 3', system-ui, sans-serif",
  },
  fonts: {
    heading: {
      family: 'Oswald',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Source Sans 3',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'Dentist',
  sectorSections: ['smile_gallery', 'fear_reducer', 'technology_showcase'],
  performanceBudget: {
    maxJS: '80kb',
    maxLCP: '3.0s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Dis Hekimi Ayse Korkmaz' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905361234567',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Dis Hekimi Ayse Korkmaz',
        copyright: '© 2026 Dis Hekimi Ayse Korkmaz',
        contact: {
          phone: '0216 345 12 34',
          email: 'info@dthaysekorkmaz.com',
          address: 'Acıbadem Mah. Kucuksu Cad. No:45/B, Uskudar/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/dtaysekorkmaz',
            icon: 'instagram',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905361234567', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Dis Hekimi Ayse Korkmaz — Uskudar',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: DIS_MODERN_BUSINESS.name, subtitle: DIS_MODERN_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
