import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const NAKLIYAT_LUX_BUSINESS: BusinessData = {
  name: 'Lux Nakliyat',
  ownerName: 'Baris Lux',
  sectorId: 'nakliyat',
  slogan: 'Premium nakliyat hizmeti',
  phone: '0536 500 55 66',
  phoneClean: '905365005566',
  whatsapp: '905365005566',
  email: 'destek@luxnakliyat.com',
  address: 'Beylikduzu Mah. No:25, Beylikduzu, Istanbul',
  city: 'Istanbul',
  district: 'Beylikduzu',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"07:00","close":"20:00"},{"day":"tuesday","dayTr":"Sali","open":"07:00","close":"20:00"},{"day":"wednesday","dayTr":"Carsamba","open":"07:00","close":"20:00"},{"day":"thursday","dayTr":"Persembe","open":"07:00","close":"20:00"},{"day":"friday","dayTr":"Cuma","open":"07:00","close":"20:00"},{"day":"saturday","dayTr":"Cumartesi","open":"07:00","close":"20:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/nakliyat-lux"},
  photos: [],
  services: []
}
export const NAKLIYAT_LUX_CONFIG: ThemeConfig = { id: 'nakliyat-lux', name: 'VIP Taşımacılık', sectorId: 'nakliyat', plan: 'elite', isDark: true, cssVariables: { '--color-bg': '#FAFAF9', '--color-surface': '#F5F5F4', '--color-text': '#1C1917', '--color-accent': '#D4AF37',
    '--color-accent-light': '#2e1f2d',
    '--color-accent-hover': '#8e2f89',
    '--color-accent-active': '#7e2a7a', '--color-text-on-accent': '#000000', '--color-border': '#D6D3D1', '--font-heading': "'Syne', sans-serif", '--font-body': "'Inter', sans-serif" }, fonts: { heading: { family: 'Syne', weights: [700] }, body: { family: 'Source Sans 3', weights: [300] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Lux Nakliyat' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Lux Nakliyat',
        copyright: '© 2026 Lux Nakliyat',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'VIP Transport', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true }, defaultContent: { badge: 'VIP MOVING', title: 'Sanat Eseri Titizliğinde Taşıma' } } ] }] }