/**
 * @kepenk/templates — haliyikama-organik Theme Configuration
 *
 * Organik ve cevre dostu hali yikama
 * Plan: pro (11 page sections, 4 global sections)
 * Font: Playfair Display/Inter | Accent: #558B2F
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const HALIYIKAMA_ORGANIK_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '72px',
  '--radius-md': '12px',
  '--radius-lg': '24px',
  '--color-bg': '#FDFBF7',
  '--color-surface': '#F4F1EA',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#E8E4D9',
  '--color-text': '#3D3831',
  '--color-text-secondary': '#6B6356',
  '--color-text-muted': '#B3AAA0',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#558B2F',
  '--color-accent-hover': '#558B2F',
  '--color-accent-active': '#558B2F',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#DED8CE',
  '--color-border-subtle': '#F4F1EA',
  '--font-heading': '\'Playfair Display\', sans-serif',
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const HALIYIKAMA_ORGANIK_BUSINESS = {
  name: 'YesilYikama Organik Hali Temizlik',
  ownerName: 'Dr. Elif Tuncer',
  sectorId: 'Hali Yikama',
  slogan: 'Dogaya saygi, haliniza ozen',
  phone: '0535 748 21 60',
  phoneClean: '905357482160',
  whatsapp: '905357482160',
  email: 'info@yesilyikama.com.tr',
  address: 'Levent Mah. Nispetiye Cad. No:34/C, Besiktas/Istanbul',
  city: 'Istanbul',
  district: 'Besiktas',
  neighborhood: 'Levent',
  coordinates: { lat: 41.081, lng: 29.013 },
  socialMedia: {
    instagram: 'https://instagram.com/yesilyikama',
    facebook: 'https://facebook.com/yesilyikama',
    youtube: 'https://youtube.com/@yesilyikama',
    twitter: 'https://twitter.com/yesilyikama',
  },
  photos: [],
  foundedYear: 2016,
  experience: '10 yil',
  customerCount: '22.000+',
  rating: 4.9,
  reviewCount: 2100,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '08:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '10:00',
      close: '16:00',
      isOpen: true,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Organik Hali Yikama',
      price: '120 TL/m2',
      duration: '3-4 gun',
      description: 'Bitkisel bazli, kimyasal icermeyen organik solusyonlarla hali yikama. Cocuk ve evcil hayvan guvenli.',
    },
    {
      id: 's2',
      name: 'Yun Hali Ozel Bakim',
      price: '160 TL/m2',
      duration: '4-6 gun',
      description: 'El dokuma yun halilara ozel dogal sabun ve dusuk sicaklik programi. Lif koruma garantili.',
    },
    {
      id: 's3',
      name: 'Bebek Odasi Hali Temizligi',
      price: '140 TL/m2',
      duration: '2-3 gun',
      description: '%100 dogal urunlerle bebek odasi hali ve hali kaplama temizligi. Alerjen giderme dahil.',
    },
    {
      id: 's4',
      name: 'Organik Koltuk Yikama',
      price: '1.200 TL/takim',
      duration: '3 saat',
      description: 'Bitkisel solusyonlarla koltuk yikama. Deri bakim icin dogal balik yagi kremi.',
    },
    {
      id: 's5',
      name: 'Anti-Alerjen Hali Islemi',
      price: '50 TL/m2 ek',
      duration: 'isleme ek',
      description: 'Toz akari, polen ve evcil hayvan alerjeni giderme. Alerji hastalari icin ozel program.',
    },
    {
      id: 's6',
      name: 'Dogal Leke Cikarma',
      price: '180 TL/m2',
      duration: '3-5 gun',
      description: 'Bitkisel enzim bazli leke cikarma. Kimyasal kullanilmadan inatci lekelere cozum.',
    },
    {
      id: 's7',
      name: 'Ipek Hali Yikama',
      price: '200 TL/m2',
      duration: '5-7 gun',
      description: 'Saf ipek ve ipek karisim halilara ozel PH notr, elle yikama programi.',
    },
    {
      id: 's8',
      name: 'Hali Koku Giderme (Dogal)',
      price: '40 TL/m2 ek',
      duration: 'isleme ek',
      description: 'Karbonat ve essansiyel yag bazli dogal koku giderme ve ferahlama islemi.',
    },
    {
      id: 's9',
      name: 'Perde Yikama (Organik)',
      price: '55 TL/m2',
      duration: '2-3 gun',
      description: 'Tul ve fon perde dogal deterjanla yikama. Sokme-takma dahil.',
    },
    {
      id: 's10',
      name: 'Ozon Dezenfeksiyon',
      price: '60 TL/m2 ek',
      duration: '1 gun ek',
      description: 'Yikama sonrasi ozon gazi ile derinlemesine dezenfeksiyon. Virus ve bakteri yok etme.',
    },
    {
      id: 's11',
      name: 'Antika Hali Konservasyonu',
      price: '250 TL/m2',
      duration: '7-10 gun',
      description: 'Muzze standartlarinda antika hali temizleme ve konservasyonu. Yikama, onariim ve koruma.',
    },
    {
      id: 's12',
      name: 'Ev Tekstili Paket',
      price: '3.500 TL',
      duration: '3-5 gun',
      description: '5 adet hali + 1 koltuk takimi + perdeler komple organik yikama paketi.',
    },
    {
      id: 's13',
      name: 'Yorgan & Yastik (Organik)',
      price: '300 TL/adet',
      duration: '2-3 gun',
      description: 'Yun ve kus tuyu yorgan-yastik dogal solusyonla yikama ve ozonlama.',
    },
    {
      id: 's14',
      name: 'Cevre Etki Raporu',
      price: 'Ucretsiz',
      duration: 'hizmetle birlikte',
      description: 'Her yikamada kullanilan su, kimyasal ve enerji miktarini gosteren cevre etki raporu.',
    },
  ],
  team: [
    {
      name: 'Dr. Elif Tuncer',
      role: 'Kurucu & Cevre Danismani',
      bio: 'Cevre muhendisligi doktorasi. Organik temizlik formulleri gelistirme. 10 yillik sektfor deneyimi.',
    },
    {
      name: 'Baris Yilmaz',
      role: 'Uretim & Kalite Muduru',
      bio: 'Tekstil muhendisi. Organik sertifikali uretim hattini yonetiyor. Su geri donusum sistemi sorumlusu.',
    },
    {
      name: 'Seda Ozkan',
      role: 'Musteri Deneyimi Muduru',
      bio: '22.000+ organik bilinclii musteri portfoyunu yonetiyor. Alerji danismanligi da yapiyor.',
    },
    {
      name: 'Emre Dogan',
      role: 'Antika Hali Uzmani',
      bio: '15 yillik antika hali restorasyon deneyimi. El dokuma, ipek ve yun hali konservasyonunda uzman.',
    },
    {
      name: 'Zeynep Aksoy',
      role: 'Ar-Ge Sorumlusu',
      bio: 'Kimya muhendisi. Bitkisel bazli temizlik formulleri gelistiriyor. 3 patent sahibi.',
    },
    {
      name: 'Can Korkmaz',
      role: 'Lojistik Koordinatoru',
      bio: 'Elektrikli araclarla toplama-teslim filosunu yonetiyor. Karbon notr lojistik planlama.',
    },
  ],
  testimonials: [
    {
      name: 'Aylin Sahin',
      district: 'Besiktas',
      date: '2025-12',
      rating: 5,
      comment: 'Bebegim yerde oynuyor, kimyasal kullanilmadan yikama yaptilar. Icim rahat, haliniz tertemiz ve dogal kokuyor.',
    },
    {
      name: 'Mehmet Kara',
      district: 'Etiler',
      date: '2025-11',
      rating: 5,
      comment: 'Antika Hereke halimizi yikattim. Muze standartlarinda islem yaptilar, renkler canlanmis. Emre Bey\'in uzmanligi asikar.',
    },
    {
      name: 'Sinem Polat',
      district: 'Levent',
      date: '2025-10',
      rating: 5,
      comment: 'Alerji hastasiyim, anti-alerjen islem yaptirdim. Gercekten fark ediyor, hapsirma ve kasinti azaldi.',
    },
    {
      name: 'Burak Ozdemir',
      district: 'Ulus',
      date: '2025-09',
      rating: 5,
      comment: 'Ev tekstili paketini aldim — halillar, koltuk, perdeler. Hepsi organik yikandi, ev yenilenimmis gibi.',
    },
    {
      name: 'Deniz Arslan',
      district: 'Ortakoy',
      date: '2025-08',
      rating: 4,
      comment: 'Organik yikama biraz daha uzun suruyor ama sonuc buna deger. Cocuklar icin kimyasalsiz olmasi buyuk arti.',
    },
    {
      name: 'Pelin Celik',
      district: 'Bebek',
      date: '2025-07',
      rating: 5,
      comment: 'Cevre etki raporu cok hosuma gitti. Ne kadar su ve enerji harcadigini gormek bilinclii tuketici icin onemli.',
    },
    {
      name: 'Tamer Yildiz',
      district: 'Sisli',
      date: '2025-06',
      rating: 5,
      comment: 'Ipek halimiz vardi, baska yere vermekten korkuyordum. Buraya verdim, muhtesem sonuc. PH notr yikama fark yaratiyor.',
    },
    {
      name: 'Nurgul Dogan',
      district: 'Nisantasi',
      date: '2025-05',
      rating: 5,
      comment: '3 kedim var, hali surekli kirleniyor. Organik yikama kedilere zararsiz, koku da dogal yontemlerle gideriliyor. Duzenli musteri oldum.',
    },
  ],
  faq: [
    { q: 'Organik yikama nedir, normal yikamadan farki ne?', a: 'Organik yikamada bitkisel bazli, kimyasal icermeyen deterjanlar kullanilir. Cocuk, bebek ve evcil hayvanlar icin guvenlidir. Cevreye zararsizdir.' },
    { q: 'Organik urunler ayni temizligi sagliyor mu?', a: 'Evet, bitkisel enzimler lekeleri ayni etkinlikte cozer. Farkli olan kimyasal kalinti birakmamasidir. Sonuc olarak hem temiz hem saglikli.' },
    { q: 'Alerji icin hangi islemi onerirsiniz?', a: 'Anti-alerjen hali islemi oneriyoruz. Toz akari, polen ve pet alerjenleri ozel enzim formuluyle giderilir. 6 ay etkili koruma saglar.' },
    { q: 'Antika halimi teslim edebilir miyim?', a: 'Evet, antika ve degerli halillar sigorta kapsaminda teslim alinir. Konservasyon uzmanimmiz Emre Bey tarafindan degerlendirilir.' },
    { q: 'Cevre etki raporu ne iceriyor?', a: 'Yikamanizda kullanilan su miktari, enerji tuketimi, kimyasal kullanimi (sifir) ve karbon ayak izi bilgilerini iceren detayli rapordur.' },
    { q: 'Elektrikli aracla mi toplama yapiyorsunuz?', a: 'Evet, toplama ve teslim filomuz tamamen elektrikli araclardan olusmaktadir. Sifir emisyonlu lojistik hizmeti sunuyoruz.' },
    { q: 'Bebek halisi icin ozel program var mi?', a: 'Evet, %100 dogal urunlerle yikama, anti-alerjen islem ve ozon dezenfeksiyon iceren ozel bebek odasi programimiz var.' },
    { q: 'Ipek hali yikama riski var mi?', a: 'Ipek halillar uzman ellerde, PH notr solusyonla, elle yikanir. 15 yillik antika hali uzmanimmiz isllemi gerceklestirir. Hasar riski yoktur.' },
    { q: 'Ozon dezenfeksiyon nedir?', a: 'Yikama sonrasi ozon gazi ile derinlemesine dezenfeksiyon. Virus, bakteri ve mantar sporlarini yok eder. Kimyasal kalinti birakmaz.' },
    { q: 'Sertifikaniz var mi?', a: 'Evet, organik temizlik sertifikasi, ISO 14001 cevre yonetim sertifikasi ve karbon notr lojistik belgelerimiz mevcuttur.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const HALIYIKAMA_ORGANIK_CONFIG = {
  id: 'haliyikama-organik',
  name: 'Organik',
  sectorId: 'haliyikama',
  plan: 'pro',
  description: 'Organik ve cevre dostu hali yikama',
  designPhilosophy: 'Dogal, premium, cevre duyarli',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '72px',
    '--radius-md': '12px',
    '--radius-lg': '24px',
    '--color-bg': '#FDFBF7',
    '--color-surface': '#F4F1EA',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#E8E4D9',
    '--color-text': '#3D3831',
    '--color-text-secondary': '#6B6356',
    '--color-text-muted': '#B3AAA0',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#558B2F',
    '--color-accent-hover': '#558B2F',
    '--color-accent-active': '#558B2F',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#DED8CE',
    '--color-border-subtle': '#F4F1EA',
    '--font-heading': '\'Playfair Display\', sans-serif',
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Playfair Display',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'DryCleaningOrLaundry',
  sectorSections: [],
  performanceBudget: {
    maxJS: '250kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'YesilYikama Organik Hali Temizlik' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905357482160',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'YesilYikama Organik Hali Temizlik',
        copyright: '© 2026 YesilYikama Organik Hali Temizlik',
        contact: {
          phone: '0535 748 21 60',
          email: 'info@yesilyikama.com.tr',
          address: 'Levent Mah. Nispetiye Cad. No:34/C, Besiktas/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/yesilyikama',
            icon: 'instagram',
          },
          {
            platform: 'facebook',
            url: 'https://facebook.com/yesilyikama',
            icon: 'facebook',
          },
          {
            platform: 'youtube',
            url: 'https://youtube.com/@yesilyikama',
            icon: 'youtube',
          },
          {
            platform: 'twitter',
            url: 'https://twitter.com/yesilyikama',
            icon: 'twitter',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905357482160', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'YesilYikama Organik Hali Temizlik — Besiktas',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_editorial_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'ÖZEL KONSEPT', title: HALIYIKAMA_ORGANIK_BUSINESS.name, subtitle: HALIYIKAMA_ORGANIK_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'about',
          variant: 'tier1_editorial_about',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { title: 'Felsefemiz' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_editorial_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'ATELIER', title: 'Seçkin Koleksiyon' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_editorial_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'text', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { title: 'Randevu & Danışmanlık' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
