/**
 * @kepenk/templates — kuyumcu-altin Theme Configuration
 *
 * Mahalle kuyumcusu, altin alim-satim
 * Plan: free (3 page sections, 3 global sections)
 * Font: Playfair Display/Inter | Accent: #B8860B
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const KUYUMCU_ALTIN_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#B8860B',
  '--color-accent-hover': '#B8860B',
  '--color-accent-active': '#B8860B',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'Playfair Display\', sans-serif',
  '--font-body': "'DM Sans', system-ui, sans-serif",
}

// ═══ DEMO BUSINESS DATA ═══

export const KUYUMCU_ALTIN_BUSINESS = {
  name: 'Altinbas Kuyumculuk',
  ownerName: 'Huseyin Altinbas',
  sectorId: 'Kuyumcu',
  slogan: '3 neslin guvenilir kuyumcusu',
  phone: '0216 345 67 89',
  phoneClean: '902163456789',
  whatsapp: '905321234567',
  email: 'info@altinbaskuyum.com',
  address: 'Bostanci Mah. Bagdat Cad. No:380, Kadikoy/Istanbul',
  city: 'Istanbul',
  district: 'Kadikoy',
  mapEmbed: '',
  foundedYear: 1978,
  experience: '48 yil',
  employeeCount: 3,
  customerCount: '30.000+',
  rating: 4.8,
  reviewCount: 1450,
  workingHours: [
    {
      day: 'Pazartesi',
      dayTr: 'Pazartesi',
      open: '09:30',
      close: '19:30',
      isOpen: true,
    },
    {
      day: 'Sali',
      dayTr: 'Sali',
      open: '09:30',
      close: '19:30',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      dayTr: 'Carsamba',
      open: '09:30',
      close: '19:30',
      isOpen: true,
    },
    {
      day: 'Persembe',
      dayTr: 'Persembe',
      open: '09:30',
      close: '19:30',
      isOpen: true,
    },
    {
      day: 'Cuma',
      dayTr: 'Cuma',
      open: '09:30',
      close: '19:30',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      dayTr: 'Cumartesi',
      open: '10:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      dayTr: 'Pazar',
      open: '11:00',
      close: '17:00',
      isOpen: true,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Altin Alim-Satim',
      price: 'Gunluk kur',
      duration: 'Anlik',
      description: '22 ayar ve 24 ayar kulce/gram altin alim-satim. Guncel piyasa fiyatiyla anlik islem. Buyuk miktarlarda ozel fiyat.',
      icon: 'Coins',
    },
    {
      id: 's2',
      name: 'Altin Takim & Bilezik',
      price: 'Modele gore',
      duration: 'Anlik',
      description: '22 ayar set, bilezik, kolye, kupe ve yuzuk. Dugun, nisan ve ozel gun icin genis koleksiyon.',
      icon: 'Gem',
    },
    {
      id: 's3',
      name: 'Altin Tamir & Lehim',
      price: '100-500 TL',
      duration: '1-3 gun',
      description: 'Kopuk zincir, bozuk kilit, parca kaybi ve lehim isleri. Tum altin ayarlarda uzman tamir.',
      icon: 'Wrench',
    },
    {
      id: 's4',
      name: 'Altin Degerleme',
      price: 'Ucretsiz',
      duration: '10 dk',
      description: 'Altinlarinizin ayar tespiti ve guncel deger hesaplamasi. Mihenk tasi ve elektronik test.',
      icon: 'Scale',
    },
  ],
  team: [],
  testimonials: [],
  gallery: [],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const KUYUMCU_ALTIN_CONFIG = {
  id: 'kuyumcu-altin',
  name: 'Altin',
  sectorId: 'kuyumcu',
  plan: 'free',
  description: 'Mahalle kuyumcusu, altin alim-satim',
  designPhilosophy: 'Sicak, guvenilir, geleneksel',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#B8860B',
    '--color-accent-hover': '#B8860B',
    '--color-accent-active': '#B8860B',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'Playfair Display\', sans-serif',
    '--font-body': "'DM Sans', system-ui, sans-serif",
  },
  fonts: {
    heading: {
      family: 'Playfair Display',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'DM Sans',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'JewelryStore',
  sectorSections: [
    'gold_price_ticker',
    'jewelry_grid',
    'gold_buyback',
    'custom_design',
  ],
  performanceBudget: {
    maxJS: '80kb',
    maxLCP: '3.0s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Altinbas Kuyumculuk' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905321234567',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Altinbas Kuyumculuk',
        copyright: '© 2026 Altinbas Kuyumculuk',
        contact: {
          phone: '0216 345 67 89',
          email: 'info@altinbaskuyum.com',
          address: 'Bostanci Mah. Bagdat Cad. No:380, Kadikoy/Istanbul',
        },
        social: [],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905321234567', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Altinbas Kuyumculuk — Kadikoy',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: KUYUMCU_ALTIN_BUSINESS.name, subtitle: KUYUMCU_ALTIN_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
