import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const BERBER_BLADE_CSS: Record<string, string> = {
  '--container-default': '1280px',
  '--section-py': '96px',
  '--radius-md': '4px',
  '--radius-lg': '8px',
  '--color-bg': '#0A0A0A',
  '--color-surface': '#121212',
  '--color-surface-elevated': '#1E1212',
  '--color-surface-muted': '#1A1A1A',
  '--color-text': '#F5F5F5',
  '--color-text-secondary': '#CCCCCC',
  '--color-text-muted': '#666666',
  '--color-text-on-accent': '#0A0A0A',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#D4AF37',
  '--color-accent-hover': '#C5A028',
  '--color-accent-active': '#A48010',
  '--color-accent-light': '#3A321A',
  '--color-border': '#222222',
  '--color-border-subtle': '#1A1A1A',
  '--font-heading': "'Cinzel', serif",
  '--font-body': "'Montserrat', sans-serif",
}

export const BERBER_BLADE_BUSINESS = {
  name: 'Blade & Razor Gentlemen\'s Club',
  ownerName: 'Oktay Keskin',
  sectorId: 'Berber',
  slogan: 'Ustura sessizliği, çeliğin asaleti',
  phone: '0212 555 01 11',
  phoneClean: '902125550111',
  whatsapp: '905325551111',
  email: 'oktay@bladerazor.co',
  address: 'Etiler Mah. Nispetiye Cad. No:111/A, Beşiktaş/İstanbul',
  city: 'İstanbul',
  district: 'Beşiktaş',
  neighborhood: 'Etiler',
  coordinates: { lat: 41.0792, lng: 29.0275 },
  socialMedia: { instagram: 'https://instagram.com/bladerazor.club' },
  photos: [],
  foundedYear: 2018,
  experience: '15+ yıl tecrübe',
  customerCount: '4.500+',
  rating: 4.9,
  reviewCount: 512,
  services: [
    {
      id: 's1',
      name: 'Kral Tıraşı (Signature Shave)',
      price: '1.200 TL',
      duration: '45 dk',
      description: 'Sıcak havlu kompresi, özel ustura tıraşı, yüz masajı ve buzlu havlu uygulaması ile lüks bakım.',
    },
    {
      id: 's2',
      name: 'Sağlık & Saç Tasarımı',
      price: '1.500 TL',
      duration: '60 dk',
      description: 'Kişiye özel saç anatomisi analizi, yıkama, kesim ve saç derisi canlandırıcı tonik masajı.',
    },
    {
      id: 's3',
      name: 'Sakal Hattı Düzenleme',
      price: '600 TL',
      duration: '25 dk',
      description: 'Makine ve ustura ile sakal sınırlarının netleştirilmesi, sakal yağı bakımı.',
    },
    {
      id: 's4',
      name: 'Premium Cilt Bakımı',
      price: '1.000 TL',
      duration: '35 dk',
      description: 'Gözenek arındırıcı siyah maske, buhar terapisi ve nemlendirici masaj.',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '09:00', close: '21:00', isOpen: true },
    { day: 'Salı', open: '09:00', close: '21:00', isOpen: true },
    { day: 'Çarşamba', open: '09:00', close: '21:00', isOpen: true },
    { day: 'Perşembe', open: '09:00', close: '21:00', isOpen: true },
    { day: 'Cuma', open: '09:00', close: '21:00', isOpen: true },
    { day: 'Cumartesi', open: '09:00', close: '20:00', isOpen: true },
    { day: 'Pazar', open: '11:00', close: '18:00', isOpen: true },
  ],
} as unknown as BusinessData

export const BERBER_BLADE_CONFIG = {
  id: 'berber-blade',
  name: 'Blade',
  sectorId: 'berber',
  plan: 'enterprise',
  description: 'Ultra lüks berber salonu deneyimi',
  designPhilosophy: 'Asil, koyu tonlar, yüksek kontrast ve lüks detaylar',
  isDark: true,
  cssVariables: BERBER_BLADE_CSS,
  fonts: {
    heading: {
      family: 'Cinzel',
      weights: [500, 700],
      subsets: ['latin'],
    },
    body: {
      family: 'Montserrat',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'BarberShop',
  sectorSections: ['before_after', 'booking'],
  performanceBudget: {
    maxJS: '150kb',
    maxLCP: '2.0s',
    animationLevel: 'gsap-allowed',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: BERBER_BLADE_BUSINESS.name },
        menuItems: [
          { label: 'Ritüeller', href: '#hizmetler' },
          { label: 'Ekip', href: '#ekip' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: { text: 'Rezervasyon', href: 'https://wa.me/905325551111', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'dark', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: BERBER_BLADE_BUSINESS.name,
        copyright: '© 2026 Blade & Razor Gentlemen\'s Club. Tüm hakları saklıdır.',
        contact: {
          phone: BERBER_BLADE_BUSINESS.phone,
          email: BERBER_BLADE_BUSINESS.email,
          address: BERBER_BLADE_BUSINESS.address,
        },
        social: [{ platform: 'instagram', url: 'https://instagram.com/bladerazor.club', icon: 'instagram' }],
        legal: [
          { label: 'Gizlilik Sözleşmesi', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1000, removable: false, animation: 'none' },
      defaultContent: { phone: '905325551111', message: 'Lüks tıraş deneyimi için randevu almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${BERBER_BLADE_BUSINESS.name} — Etiler Lüks Erkek Kuaförü`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_editorial_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'EST. 2018',
            title: BERBER_BLADE_BUSINESS.name,
            subtitle: BERBER_BLADE_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Kuruluş Yılı / Etiket', type: 'text' },
            { path: 'title', label: 'Kulüp İsmi', type: 'text' },
            { path: 'subtitle', label: 'Alt Başlık / Slogan', type: 'richtext' },
          ],
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_editorial_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: {
            badge: 'FELSEFEMİZ',
            title: 'Hassas Çelik & Sıcak Havlu',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'Felsefe Başlığı', type: 'text' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_editorial_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'BAKIM SEANSLARI',
            title: 'Lüks Tıraş Ritüellerimiz',
          },
          editableFields: [
            { path: 'badge', label: 'Küçük Etiket', type: 'text' },
            { path: 'title', label: 'Ana Bölüm Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_editorial_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'REZERVASYON',
            title: 'Ayrıcalıklı Kulübe Katılın',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
