import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const ORGANIK_PREMIUM_BUSINESS: BusinessData = {
  name: 'Premium Organik',
  ownerName: 'Baris Premium',
  sectorId: 'organik',
  slogan: 'Premium organik yasam',
  phone: '0536 400 55 66',
  phoneClean: '905364005566',
  whatsapp: '905364005566',
  email: 'destek@premiumorganik.com',
  address: 'Barbaros Mah. No:25, Atasehir, Istanbul',
  city: 'Istanbul',
  district: 'Atasehir',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"07:00","close":"20:00"},{"day":"tuesday","dayTr":"Sali","open":"07:00","close":"20:00"},{"day":"wednesday","dayTr":"Carsamba","open":"07:00","close":"20:00"},{"day":"thursday","dayTr":"Persembe","open":"07:00","close":"20:00"},{"day":"friday","dayTr":"Cuma","open":"07:00","close":"20:00"},{"day":"saturday","dayTr":"Cumartesi","open":"07:00","close":"20:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/organik-premium"},
  photos: [],
  services: []
}
export const ORGANIK_PREMIUM_CONFIG: ThemeConfig = { id: 'organik-premium', name: 'Premium Doğal', sectorId: 'organik', plan: 'elite', isDark: true, cssVariables: { '--color-bg': '#FAFAF9', '--color-surface': '#F5F5F4', '--color-text': '#1C1917', '--color-accent': '#FDE047',
    '--color-accent-light': '#1f2e23',
    '--color-accent-hover': '#2f8e4d',
    '--color-accent-active': '#2a7e45', '--color-text-on-accent': '#000000', '--color-border': '#D6D3D1', '--font-heading': "'Syne', sans-serif", '--font-body': "'Inter', sans-serif" }, fonts: { heading: { family: 'Syne', weights: [600] }, body: { family: 'Inter', weights: [300] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Premium Organik' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Premium Organik',
        copyright: '© 2026 Premium Organik',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'Organic Premium', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true }, defaultContent: { badge: 'PREMIUM QUALITY', title: 'Sertifikalı Doğal Gurme' } } ] }] }