/**
 * @kepenk/templates — mobilya-ofis Theme Configuration
 *
 * Ofis mobilyası — kurumsal, profesyonel tasarım
 * Plan: growth (9 page sections, 4 global sections)
 * Font: Poppins/Inter | Accent: #1976D2
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const MOBILYA_OFIS_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#1976D2',
  '--color-accent-hover': '#1565C0',
  '--color-accent-active': '#1976D2',
  '--color-accent-light': '#E3F2FD',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'Poppins\', sans-serif',
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const MOBILYA_OFIS_BUSINESS = {
  name: 'ErgoDesk Ofis Mobilyaları',
  sectorId: 'mobilyaci',
  ownerName: 'Tolga Erdoğan',
  slogan: 'Ergonomik ofis çözümleriyle verimliliği artırın',
  phone: '0212 234 5678',
  phoneClean: '02122345678',
  email: 'info@ergodesk.com.tr',
  address: 'Merter Mah. İş Kuleleri Cad. No:10, Güngören/İstanbul',
  city: 'İstanbul',
  district: 'Güngören',
  coordinates: { lat: 41.015, lng: 28.89 },
  socialMedia: {
    instagram: 'ergodeskmobilya',
    facebook: 'ergodesk',
    linkedin: 'ergodesk-ofis',
  },
  photos: [],
  foundedYear: 2010,
  experience: '16 yıl',
  customerCount: '8.000+',
  rating: 4.8,
  reviewCount: 640,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Salı',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Çarşamba',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Perşembe',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '10:00',
      close: '16:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '',
      close: '',
      isOpen: false,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Yönetici Masası',
      price: '12.000 TL\'den başlayan',
      duration: '7 iş günü',
      description: 'L veya U tipi yönetici masası, kablo yönetim sistemi dahil.',
    },
    {
      id: 's2',
      name: 'Operasyon Masası',
      price: '4.500 TL\'den başlayan',
      duration: '5 iş günü',
      description: 'Modüler operasyonel çalışma masaları, seperatör seçenekli.',
    },
    {
      id: 's3',
      name: 'Ergonomik Ofis Koltuğu',
      price: '6.000 TL\'den başlayan',
      duration: 'Stoktan',
      description: 'Ayarlanabilir bel desteği, başlık ve kol dayama, mesh veya deri.',
    },
    {
      id: 's4',
      name: 'Toplantı Masası',
      price: '15.000 TL\'den başlayan',
      duration: '10 iş günü',
      description: '6-20 kişilik toplantı masası, elektrik prizi ve data bağlantısı entegreli.',
    },
    {
      id: 's5',
      name: 'Dosya Dolabı / Arşiv',
      price: '3.500 TL\'den başlayan',
      duration: '5 iş günü',
      description: 'Kilitli çekmeceli dosya dolabı, açık raf veya kapaklı seçenekler.',
    },
    {
      id: 's6',
      name: 'Bölme Sistemleri',
      price: '800 TL/m²',
      duration: '3-5 iş günü',
      description: 'Cam, ahşap veya alüminyum bölme duvar sistemleri.',
    },
    {
      id: 's7',
      name: 'Resepsiyon Bankosu',
      price: '18.000 TL\'den başlayan',
      duration: '10-15 iş günü',
      description: 'Özel tasarım resepsiyon bankosu, LED aydınlatma seçenekli.',
    },
    {
      id: 's8',
      name: 'Yükselen Masa (Sit-Stand)',
      price: '8.000 TL\'den başlayan',
      duration: 'Stoktan',
      description: 'Elektrikli yükseklik ayarlı masa, hafıza fonksiyonlu.',
    },
    {
      id: 's9',
      name: 'Ofis Taşıma & Kurulum',
      price: 'Proje bazlı',
      duration: '1-3 gün',
      description: 'Komple ofis mobilya taşıma, kurulum ve yerleşim planlaması.',
    },
    {
      id: 's10',
      name: '3D Ofis Tasarımı',
      price: 'Ücretsiz',
      duration: '3 iş günü',
      description: 'Ofis alanınız için ücretsiz 3D yerleşim planı ve görselleştirme.',
    },
  ],
  team: [
    {
      name: 'Tolga Erdoğan',
      title: 'Kurucu & Genel Müdür',
      description: 'İTÜ Endüstri Ürünleri Tasarımı, 20 yıl ofis mobilyası sektörü.',
    },
    {
      name: 'Ayşe Kılıç',
      title: 'İç Mimar',
      description: 'Ofis ergonomisi ve alan optimizasyonu uzmanı.',
    },
    {
      name: 'Can Yılmaz',
      title: 'Satış Müdürü',
      description: 'Kurumsal satış ve proje yönetimi.',
    },
    {
      name: 'Zehra Arslan',
      title: 'Lojistik Koordinatör',
      description: 'Ofis mobilya teslimat ve montaj koordinasyonu.',
    },
  ],
  testimonials: [
    {
      name: 'İK Müdürü Selin A.',
      district: 'Maslak',
      date: '2026-01',
      rating: 5,
      comment: '150 kişilik ofisimizi komple döşediler. Sit-stand masalar çalışan memnuniyetini çok artırdı.',
    },
    {
      name: 'Startup kurucusu Mert B.',
      district: 'Levent',
      date: '2025-12',
      rating: 5,
      comment: 'Co-working alanımız için modüler çözümler sundular. Esnek, modern ve ekonomik.',
    },
    {
      name: 'Avukat Hande K.',
      district: 'Şişli',
      date: '2025-11',
      rating: 4,
      comment: 'Yönetici masamız çok şık. Kablo yönetim sistemi ofisi düzenli tutuyor.',
    },
    {
      name: 'Muhasebe firması sahibi Oğuz T.',
      district: 'Mecidiyeköy',
      date: '2025-10',
      rating: 5,
      comment: 'Dosya dolabı ve arşiv çözümleri çok pratik. 3D tasarım sayesinde ofisi önceden gördük.',
    },
    {
      name: 'Mimar Elif D.',
      district: 'Beşiktaş',
      date: '2026-02',
      rating: 5,
      comment: 'Cam bölme sistemi ofise ferahlık kattı. Montaj ekibi temiz ve hızlı çalıştı.',
    },
    {
      name: 'Banka şubesi müdürü Ali S.',
      district: 'Kadıköy',
      date: '2025-09',
      rating: 5,
      comment: 'Resepsiyon bankosu çok etkileyici oldu. Müşterilerimizden çok olumlu geri dönüş alıyoruz.',
    },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const MOBILYA_OFIS_CONFIG = {
  id: 'mobilyaci-ofis',
  name: 'Ofis',
  sectorId: 'mobilyaci',
  plan: 'growth',
  description: 'Ofis mobilyası — kurumsal, profesyonel tasarım',
  designPhilosophy: 'Kurumsal, ergonomik, verimlilik odaklı',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#1976D2',
    '--color-accent-hover': '#1565C0',
    '--color-accent-active': '#1976D2',
    '--color-accent-light': '#E3F2FD',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'Poppins\', sans-serif',
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Poppins',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'FurnitureStore',
  sectorSections: [],
  performanceBudget: {
    maxJS: '180kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'ErgoDesk Ofis Mobilyaları' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'Ara',
          href: 'tel:02122345678',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'ErgoDesk Ofis Mobilyaları',
        copyright: '© 2026 ErgoDesk Ofis Mobilyaları',
        contact: {
          phone: '0212 234 5678',
          email: 'info@ergodesk.com.tr',
          address: 'Merter Mah. İş Kuleleri Cad. No:10, Güngören/İstanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'ergodeskmobilya',
            icon: 'instagram',
          },
          {
            platform: 'facebook',
            url: 'ergodesk',
            icon: 'facebook',
          },
          {
            platform: 'linkedin',
            url: 'ergodesk-ofis',
            icon: 'linkedin',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '02122345678', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'ErgoDesk Ofis Mobilyaları — Güngören',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: MOBILYA_OFIS_BUSINESS.name, subtitle: MOBILYA_OFIS_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
