/**
 * @kepenk/templates — lastikci-jant Theme Configuration
 *
 * Premium jant ve lastik boutique
 * Plan: pro (11 page sections, 4 global sections)
 * Font: Montserrat/Inter | Accent: #B71C1C
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const LASTIKCI_JANT_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#B71C1C',
  '--color-accent-hover': '#B71C1C',
  '--color-accent-active': '#B71C1C',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'Montserrat\', sans-serif',
  '--font-body': "'DM Sans', system-ui, sans-serif",
}

// ═══ DEMO BUSINESS DATA ═══

export const LASTIKCI_JANT_BUSINESS = {
  name: 'WheelHouse Jant & Performance',
  ownerName: 'Baris Ozturk',
  sectorId: 'Lastikci',
  slogan: 'Performans lastigi ve premium jant uzmanligi',
  phone: '0535 714 28 50',
  phoneClean: '905357142850',
  whatsapp: '905357142850',
  email: 'info@wheelhouseist.com',
  address: 'Kavacik Mah. Ekinciler Cad. No:22/A, Beykoz/Istanbul',
  city: 'Istanbul',
  district: 'Beykoz',
  neighborhood: 'Kavacik',
  coordinates: { lat: 41.094, lng: 29.078 },
  socialMedia: {
    instagram: 'https://instagram.com/wheelhouseist',
    facebook: 'https://facebook.com/wheelhouseist',
    youtube: 'https://youtube.com/@wheelhouse',
    tiktok: 'https://tiktok.com/@wheelhouseist',
  },
  photos: [],
  foundedYear: 2014,
  experience: '12 yil',
  customerCount: '8.000+',
  rating: 4.9,
  reviewCount: 1450,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '09:00',
      close: '19:30',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '09:00',
      close: '19:30',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '09:00',
      close: '19:30',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '09:00',
      close: '19:30',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '09:00',
      close: '19:30',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '09:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '10:00',
      close: '15:00',
      isOpen: true,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Performans Lastik Satisi',
      price: 'degisken',
      duration: 'hazir',
      description: 'Michelin Pilot Sport, Continental SportContact, Bridgestone Potenza gibi UHP lastikler.',
    },
    {
      id: 's2',
      name: 'Aftermarket Jant Satisi',
      price: '2.000 - 15.000 TL/adet',
      duration: 'hazir/siparis',
      description: 'BBS, OZ Racing, Vossen, Rotiform, HRE gibi premium jant markalari. Ozel siparis.',
    },
    {
      id: 's3',
      name: 'Jant Boyama & Kaplama',
      price: '1.200 TL/adet',
      duration: '3-5 gun',
      description: 'Toz boya, hidrolik boyama, PVD kaplama. 200+ renk secenegi.',
    },
    {
      id: 's4',
      name: 'Jant Onarimi',
      price: '500 - 2.000 TL/adet',
      duration: '1-3 gun',
      description: 'Egrilik duzeltme, cizik giderme, curuk tamiri. Orijinal gorunum garantisi.',
    },
    {
      id: 's5',
      name: 'Spacer & Adaptior Montaji',
      price: '300 TL/adet',
      duration: '30 dk',
      description: 'Jant genisletme spacer ve farkli bolt pattern adaptoru montaji.',
    },
    {
      id: 's6',
      name: 'Hava Suspansiyon Sistemi',
      price: '15.000 - 40.000 TL',
      duration: '1-2 gun',
      description: 'Air ride suspansiyon kurulumu. Yukseklik ayari, showcar look.',
    },
    {
      id: 's7',
      name: 'Lastik Yazisi (Tire Lettering)',
      price: '600 TL/set',
      duration: '2 saat',
      description: 'Lastik yan yuzeyine ozel yazi/logo uygulamasi. Dayanikli kaucuk malzeme.',
    },
    {
      id: 's8',
      name: '3D Rot Ayari',
      price: '600 TL',
      duration: '30 dk',
      description: 'Hunter 3D rot cihazi ile hassas acı olcumu ve ayarlama.',
    },
    {
      id: 's9',
      name: 'Pist Gunu Lastik Hazirlik',
      price: '1.500 TL',
      duration: '2 saat',
      description: 'Pist gunu oncesi lastik basinc ayari, sicaklik onerisi, yedek lastik hazirlik.',
    },
    {
      id: 's10',
      name: 'Arac Fotograf Cekimi',
      price: '800 TL',
      duration: '1 saat',
      description: 'Jant/lastik degisimi sonrasi profesyonel arac fotograf cekimi. Sosyal medya icin.',
    },
    {
      id: 's11',
      name: 'Nitrogen (Azot) Dolum',
      price: '100 TL/4 lastik',
      duration: '15 dk',
      description: 'Azot gazı ile lastik sisme. Basinc kaybini azaltir, lastik isısını duser.',
    },
    {
      id: 's12',
      name: 'Lastik & Jant Sigorta',
      price: '500 TL/yil',
      duration: 'yillik',
      description: 'Yol hasari, hirsizlik ve kaza icin lastik/jant sigorta paketi.',
    },
    {
      id: 's13',
      name: 'Custom Fitment Danismanligi',
      price: 'Ucretsiz',
      duration: '30 dk',
      description: 'Arac modelinize ozel jant boyutu, offset, camber onerisi. 3D gorselestirme.',
    },
    {
      id: 's14',
      name: 'Seramik Jant Kaplama',
      price: '1.500 TL/set',
      duration: '1 gun',
      description: 'Nano seramik kaplama ile jantlarin leke, fren tozu ve ciziğe karsi korunmasi.',
    },
  ],
  team: [
    {
      name: 'Baris Ozturk',
      role: 'Kurucu & Jant Uzmani',
      bio: 'Otomotiv tutkunu, 12 yillik jant ve performans lastik deneyimi. BBS ve OZ Racing Turkiye distributorlugu.',
    },
    {
      name: 'Can Aksoy',
      role: 'Performans Lastik Danismani',
      bio: 'Ex-pist pilotu. UHP lastik secimi ve pist gunu hazirlik konusunda uzman.',
    },
    {
      name: 'Efe Dogan',
      role: 'Jant Boyama & Onarim Ustasi',
      bio: '10 yillik jant restorasyon deneyimi. PVD kaplama ve ozel renk uzmani.',
    },
    {
      name: 'Mert Yilmaz',
      role: 'Suspansiyon & Fitment Uzmani',
      bio: 'Air ride ve coilover sistemlerinde uzman. Custom fitment ve camber ayari.',
    },
    {
      name: 'Selin Korkmaz',
      role: 'Satis & Sosyal Medya',
      bio: 'Otomotiv sosyal medya icerigi ve musteri danismanligi. Car meet organizasyonu.',
    },
    {
      name: 'Ahmet Celik',
      role: 'Montaj Ustasi',
      bio: '15 yillik lastik montaj deneyimi. Hunter 3D rot cihazinda uzman.',
    },
  ],
  testimonials: [
    {
      name: 'Kaan Yildiz',
      district: 'Kavacik',
      date: '2025-12',
      rating: 5,
      comment: 'BMW M4\'ume Vossen HF-5 jant taktirdim. Fitment danismanligi muhtesem, offset ve camber ayari kusursuz. Aracim bambaaska gorunuyor.',
    },
    {
      name: 'Arda Sahin',
      district: 'Atasehir',
      date: '2025-11',
      rating: 5,
      comment: 'Pist gunu icin Michelin Pilot Sport 4S aldim. Can Bey basınc ve sicaklik ayarlarini yapti. Pisttte guvenim artti.',
    },
    {
      name: 'Deniz Polat',
      district: 'Besiktas',
      date: '2025-10',
      rating: 5,
      comment: 'Jant boyama yaptirdim, mat siyahtan parlak bronza gecis. Efe Usta\'nin iscligi mukemmel, fabrika cikisi gibi.',
    },
    {
      name: 'Emre Aksoy',
      district: 'Sariyer',
      date: '2025-09',
      rating: 5,
      comment: 'Air ride suspansiyon kurdurduk, show seviyesinde dusuk profil. Mert Bey her detayi dusunmus. Arabam sosyal medyada patladi.',
    },
    {
      name: 'Selin Ozcan',
      district: 'Kadikoy',
      date: '2025-08',
      rating: 4,
      comment: 'Seramik jant kaplama yaptirdim, fren tozu artik yapismiyor. Tek sorun: randevu almak yogun donemde zor olabiliyor.',
    },
    {
      name: 'Tolga Demirel',
      district: 'Umraniye',
      date: '2025-07',
      rating: 5,
      comment: 'BBS CH-R jant + Continental SportContact 7 lastik kombinasyonu. Baris Bey\'in onerisi tam isabet. Yol tutusu inanilmaz.',
    },
    {
      name: 'Cagla Tekin',
      district: 'Maltepe',
      date: '2025-06',
      rating: 5,
      comment: 'Lastik yazisi yaptirdim, beyaz Toyo Proxes yazisi cok sik duruyor. Uygulamasi cok duzenli, 6 aydir durumu muhtesem.',
    },
    {
      name: 'Hakan Yilmaz',
      district: 'Beykoz',
      date: '2025-11',
      rating: 5,
      comment: 'Jant egrilik onarimi yaptirdim, bordur carpmasindan egrilmisti. Efe Usta duzzeltti, yeni gibi oldu. Balans sorunu da cozuldu.',
    },
  ],
  faq: [
    { q: 'UHP lastik nedir, normal lastikten farki ne?', a: 'Ultra High Performance lastikler yuksek hiz dayanimi, keskin viraj tutusu ve kisa fren mesafesi sunar. Sportif ve performans araclari icin idealdir.' },
    { q: 'Aftermarket jant montaji garanti kapsaminda mi?', a: 'Jant montaji 1 yil iscilik garantili. Jant uretici garantisi ayrica gecerlidir. BBS ve OZ Racing 2 yil uretici garantisi sunar.' },
    { q: 'Jant boyutu buyutmek guvenli mi?', a: 'Arac modelinize uygun boyut aralıginda buyutme guvenlidir. Custom fitment danismanligimizda 3D modelleme ile gosteriyoruz, lastiğin govdeye surmemesini garanti ediyoruz.' },
    { q: 'Air ride suspansiyon yasal mi?', a: 'Evet, air ride sistemleri yasal yol yuksekligiinde kullanildigi surece yasaldir. Arac muayenesinde standart yukseklige cikarmak yeterlidir.' },
    { q: 'Pist gunu lastik hazirlik nedir?', a: 'Pist kosullarına gore lastik basinc ayari, isinma turu onerisi, yedek lastik hazirligi ve olcum sonrasi sicaklik analizi yapiyoruz.' },
    { q: 'Seramik kaplama ne kadar dayanır?', a: 'Profesyonel seramik jant kaplama ortalama 2-3 yil dayanir. Fren tozu, yol kirliligi ve kimyasallara karsi koruma saglar.' },
    { q: 'Ozel siparis jant ne kadar surede gelir?', a: 'Stokta olan modeller hemen teslim. Ozel siparis jantlar marka ve modele gore 2-6 hafta icerisinde teslim edilir.' },
    { q: 'PVD kaplama ile toz boya arasindaki fark ne?', a: 'PVD vakum ortaminda metal kaplama olup krom gorunumu verir, daha dayanikli ve hafiftir. Toz boya daha genis renk secenegi sunar ve daha ekonomiktir.' },
    { q: 'Nitrogen (azot) avantaji ne?', a: 'Azot basinc kaybini %30-40 azaltir, lastik ici sicakligi dusurur ve jant ici korozyonu onler. Ozellikle performans lastiklerinde onerilir.' },
    { q: 'Jant/lastik sigortasi neyi kapsiyor?', a: 'Yol hasari (cukur, kaldirm carpmasi), hirsizlik ve kaza sonucu hasar. Yillik prim ile 4 jant ve 4 lastik icin gecerlidir.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const LASTIKCI_JANT_CONFIG = {
  id: 'lastikci-jant',
  name: 'Jant',
  sectorId: 'lastikci',
  plan: 'pro',
  description: 'Premium jant ve lastik boutique',
  designPhilosophy: 'Sportif, luks, performans',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#B71C1C',
    '--color-accent-hover': '#B71C1C',
    '--color-accent-active': '#B71C1C',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'Montserrat\', sans-serif',
    '--font-body': "'DM Sans', system-ui, sans-serif",
  },
  fonts: {
    heading: {
      family: 'Montserrat',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'DM Sans',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'TireShop',
  sectorSections: [],
  performanceBudget: {
    maxJS: '250kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'WheelHouse Jant & Performance' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905357142850',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'WheelHouse Jant & Performance',
        copyright: '© 2026 WheelHouse Jant & Performance',
        contact: {
          phone: '0535 714 28 50',
          email: 'info@wheelhouseist.com',
          address: 'Kavacik Mah. Ekinciler Cad. No:22/A, Beykoz/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/wheelhouseist',
            icon: 'instagram',
          },
          {
            platform: 'facebook',
            url: 'https://facebook.com/wheelhouseist',
            icon: 'facebook',
          },
          {
            platform: 'youtube',
            url: 'https://youtube.com/@wheelhouse',
            icon: 'youtube',
          },
          {
            platform: 'tiktok',
            url: 'https://tiktok.com/@wheelhouseist',
            icon: 'tiktok',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905357142850', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'WheelHouse Jant & Performance — Beykoz',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: LASTIKCI_JANT_BUSINESS.name, subtitle: LASTIKCI_JANT_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
