/**
 * @kepenk/templates — kres-montessori Theme Configuration
 *
 * Montessori eğitim yaklaşımlı kreş — doğal tonlar, organize tasarım
 * Plan: starter (6 page sections, 4 global sections)
 * Font: Inter/Inter | Accent: #7B8F6A
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const KRES_MONTESSORI_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#7B8F6A',
  '--color-accent-hover': '#6A7D5A',
  '--color-accent-active': '#7B8F6A',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': "'Lora', sans-serif",
  '--font-body': "'Source Sans 3', system-ui, sans-serif",
}

// ═══ DEMO BUSINESS DATA ═══

export const KRES_MONTESSORI_BUSINESS = {
  name: 'Doğa Montessori Kreşi',
  sectorId: 'kres',
  ownerName: 'Dr. Elif Demir',
  slogan: 'Doğanın rehberliğinde, kendi hızında öğrenen çocuklar',
  phone: '0216 890 4523',
  phoneClean: '02168904523',
  email: 'info@dogamontessori.com',
  address: 'Ataşehir Bulvarı No:55 Kat:1, Ataşehir/İstanbul',
  city: 'İstanbul',
  district: 'Ataşehir',
  coordinates: { lat: 40.9923, lng: 29.1244 },
  socialMedia: { instagram: 'dogamontessorikresi', facebook: 'dogamontessori' },
  photos: [],
  foundedYear: 2015,
  experience: '11 yıl',
  customerCount: '1.500+',
  rating: 4.9,
  reviewCount: 340,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '07:30',
      close: '18:30',
      isOpen: true,
    },
    {
      day: 'Salı',
      open: '07:30',
      close: '18:30',
      isOpen: true,
    },
    {
      day: 'Çarşamba',
      open: '07:30',
      close: '18:30',
      isOpen: true,
    },
    {
      day: 'Perşembe',
      open: '07:30',
      close: '18:30',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '07:30',
      close: '18:30',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '09:00',
      close: '13:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '',
      close: '',
      isOpen: false,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Montessori Bebek Grubu (0-18 Ay)',
      price: '12.000 TL/ay',
      duration: 'Tam gün',
      description: 'Nido sınıfında duyusal keşif ve motor gelişim odaklı Montessori programı.',
    },
    {
      id: 's2',
      name: 'Montessori Yürüme Grubu (18-36 Ay)',
      price: '11.500 TL/ay',
      duration: 'Tam gün',
      description: 'Pratik yaşam becerileri ve dil gelişimi odaklı Montessori müfredatı.',
    },
    {
      id: 's3',
      name: 'Montessori Anaokulu (3-6 Yaş)',
      price: '13.000 TL/ay',
      duration: 'Tam gün',
      description: 'Okuma-yazma hazırlığı, matematik ve kozmik eğitim içeren kapsamlı Montessori programı.',
    },
    {
      id: 's4',
      name: 'Yarım Gün Montessori',
      price: '8.000 TL/ay',
      duration: 'Yarım gün',
      description: 'Sabah 07:30-12:30 arası yoğunlaştırılmış Montessori eğitim programı.',
    },
    {
      id: 's5',
      name: 'Montessori Atölyeleri',
      price: '2.500 TL/ay',
      duration: 'Hafta sonu',
      description: 'Cumartesi günleri sanat, müzik ve doğa atölyeleri.',
    },
    {
      id: 's6',
      name: 'Yaz Kampı',
      price: '9.500 TL/ay',
      duration: 'Haziran-Ağustos',
      description: 'Açık hava Montessori aktiviteleri, bahçe tarımı ve su oyunları.',
    },
  ],
  team: [
    {
      name: 'Dr. Elif Demir',
      title: 'Kurucu & Eğitim Direktörü',
      description: 'AMI diplomalı Montessori eğitimci, çocuk gelişimi doktoru.',
    },
    {
      name: 'Zeynep Arslan',
      title: 'Baş Eğitimci',
      description: '12 yıllık Montessori deneyimi, 0-3 yaş uzmanı.',
    },
  ],
  testimonials: [
    {
      name: 'Burcu K.',
      district: 'Ataşehir',
      date: '2025-11',
      rating: 5,
      comment: 'Oğlum 2 yaşında başladı, 6 ayda inanılmaz gelişim gösterdi. Montessori yaklaşımı gerçekten fark yaratıyor.',
    },
    {
      name: 'Mehmet A.',
      district: 'Ümraniye',
      date: '2025-09',
      rating: 5,
      comment: 'Kızımız burada çok mutlu. Eğitimciler gerçekten işinin ehli, ortam muhteşem.',
    },
    {
      name: 'Seda T.',
      district: 'Kadıköy',
      date: '2025-12',
      rating: 5,
      comment: 'Servis dahil herşey çok profesyonel. Montessori materyalleri çok zengin.',
    },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const KRES_MONTESSORI_CONFIG = {
  id: 'kres-montessori',
  name: 'Montessori',
  sectorId: 'kres',
  plan: 'starter',
  description: 'Montessori eğitim yaklaşımlı kreş — doğal tonlar, organize tasarım',
  designPhilosophy: 'Düzenli, doğal malzeme hissi, Montessori felsefesi yansıtan minimalizm',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#7B8F6A',
    '--color-accent-hover': '#6A7D5A',
    '--color-accent-active': '#7B8F6A',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': "'Lora', sans-serif",
    '--font-body': "'Source Sans 3', system-ui, sans-serif",
  },
  fonts: {
    heading: {
      family: 'Lora',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Source Sans 3',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'ChildCare',
  sectorSections: [],
  performanceBudget: {
    maxJS: '120kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-basic',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Doğa Montessori Kreşi' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'Ara',
          href: 'tel:02168904523',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Doğa Montessori Kreşi',
        copyright: '© 2026 Doğa Montessori Kreşi',
        contact: {
          phone: '0216 890 4523',
          email: 'info@dogamontessori.com',
          address: 'Ataşehir Bulvarı No:55 Kat:1, Ataşehir/İstanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'dogamontessorikresi',
            icon: 'instagram',
          },
          {
            platform: 'facebook',
            url: 'dogamontessori',
            icon: 'facebook',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '02168904523', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Doğa Montessori Kreşi — Ataşehir',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: KRES_MONTESSORI_BUSINESS.name, subtitle: KRES_MONTESSORI_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
