import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const RESTORAN_ZINCIR_CSS: Record<string, string> = {
  '--container-default': '1200px',
  '--section-py': '80px',
  '--radius-md': '12px',
  '--radius-lg': '24px',
  '--color-bg': '#0B0F19',
  '--color-surface': '#111827',
  '--color-surface-elevated': '#1F2937',
  '--color-surface-muted': '#0F172A',
  '--color-text': '#F9FAFB',
  '--color-text-secondary': '#9CA3AF',
  '--color-text-muted': '#4B5563',
  '--color-text-on-accent': '#0B0F19',
  '--color-text-on-dark': '#F9FAFB',
  '--color-accent': '#6366F1',
  '--color-accent-hover': '#4F46E5',
  '--color-accent-active': '#4338CA',
  '--color-accent-light': '#1E1B4B',
  '--color-border': '#374151',
  '--color-border-subtle': '#1F2937',
  '--font-heading': "'Syne', sans-serif",
  '--font-body': "'Plus Jakarta Sans', sans-serif",
}

export const RESTORAN_ZINCIR_BUSINESS = {
  name: 'Burger & Co. Zincir Lezzetleri',
  ownerName: 'Umut Kaan',
  sectorId: 'Restoran',
  slogan: 'Gurme el yapımı burgerler ve fütüristik sokak lezzetleri zinciri',
  phone: '0212 555 12 20',
  phoneClean: '902125551220',
  whatsapp: '905335551220',
  email: 'info@burgercozincir.com',
  address: 'Karaköy Merkez Şube, Mumhane Cad. No:45, Beyoğlu/İstanbul',
  city: 'İstanbul',
  district: 'Beyoğlu',
  neighborhood: 'Karaköy',
  coordinates: { lat: 41.0245, lng: 28.9792 },
  socialMedia: { instagram: 'https://instagram.com/burgercozincir' },
  photos: [],
  foundedYear: 2021,
  experience: '8 zincir restoran şubesi',
  customerCount: '250.000+/yıl mutlu müşteri',
  rating: 4.9,
  reviewCount: 1850,
  services: [
    {
      id: 's1',
      name: 'Double Smash Burger Menü',
      price: '340 TL',
      duration: '12 dk',
      description: '2 adet 100gr smash kuzu-dana köftesi, cheddar peyniri, karamelize soğan, ev yapımı sos ve çıtır patates ile.',
    },
    {
      id: 's2',
      name: 'Truffle & Parmesan Fries',
      price: '150 TL',
      duration: '8 dk',
      description: 'Sıcak çıtır taze patatesler üzerine sızma trüf yağı, rendelenmiş parmesan peyniri ve taze biberiye.',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '11:30', close: '02:00', isOpen: true },
    { day: 'Salı', open: '11:30', close: '02:00', isOpen: true },
    { day: 'Çarşamba', open: '11:30', close: '02:00', isOpen: true },
    { day: 'Perşembe', open: '11:30', close: '02:00', isOpen: true },
    { day: 'Cuma', open: '11:30', close: '04:00', isOpen: true },
    { day: 'Cumartesi', open: '11:30', close: '04:00', isOpen: true },
    { day: 'Pazar', open: '12:00', close: '01:00', isOpen: true },
  ],
} as unknown as BusinessData

export const RESTORAN_ZINCIR_CONFIG = {
  id: 'restoran-zincir',
  name: 'Zincir',
  sectorId: 'restoran',
  plan: 'growth',
  description: 'Gurme burger restoranları, genç enerjik modern sokak modası zincir şablonu',
  designPhilosophy: 'Fütüristik neon indigo tonları, modern Syne başlıkları, çarpıcı koyu sokak stili görsel şeması',
  isDark: true,
  cssVariables: RESTORAN_ZINCIR_CSS,
  fonts: {
    heading: {
      family: 'Syne',
      weights: [700, 800],
      subsets: ['latin'],
    },
    body: {
      family: 'Plus Jakarta Sans',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'FastFoodRestaurant',
  sectorSections: ['menu_display', 'daily_special', 'reservation'],
  performanceBudget: {
    maxJS: '120kb',
    maxLCP: '2.2s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: RESTORAN_ZINCIR_BUSINESS.name },
        menuItems: [
          { label: 'Burgerler', href: '#hizmetler' },
          { label: 'Şubeler', href: '#ekip' },
          { label: 'Online Sipariş', href: '#iletisim' },
        ],
        cta: { text: 'Sipariş Ver', href: 'https://wa.me/905335551220', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'dark', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: RESTORAN_ZINCIR_BUSINESS.name,
        copyright: '© 2026 Burger & Co. Zincir Lezzetleri. Tüm hakları saklıdır.',
        contact: {
          phone: RESTORAN_ZINCIR_BUSINESS.phone,
          email: RESTORAN_ZINCIR_BUSINESS.email,
          address: RESTORAN_ZINCIR_BUSINESS.address,
        },
        social: [{ platform: 'instagram', url: 'https://instagram.com/burgercozincir', icon: 'instagram' }],
        legal: [
          { label: 'Gizlilik ve Şartlar', href: '/gizlilik' },
          { label: 'KVKK Hak Bildirimi', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1000, removable: false, animation: 'none' },
      defaultContent: { phone: '905335551220', message: 'Karaköy şubesinden sipariş vermek istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${RESTORAN_ZINCIR_BUSINESS.name} — Karaköy Fütüristik Gurme Burgerler`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'SMASH BURGER RİTÜELİ',
            title: RESTORAN_ZINCIR_BUSINESS.name,
            subtitle: RESTORAN_ZINCIR_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Stüdyo İsmi', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
          ],
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: {
            badge: 'EL YAPIMI LEZZET',
            title: 'Sadece En Kaliteli Malzeme Felsefesi',
          },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'SMASH MENÜSÜ',
            title: 'Eşsiz Lezzet Kombinasyonlarımız',
          },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'ONLINE SIPARİŞ',
            title: 'Sıcak Gurme Burger Siparişi Verin',
          },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
