import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const OTO_BAKIM_CSS: Record<string, string> = {
  '--container-default': '1120px',
  '--section-py': '80px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#2563EB',
  '--color-accent-hover': '#1D4ED8',
  '--color-accent-active': '#1E40AF',
  '--color-accent-light': '#DBEAFE',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': "'Plus Jakarta Sans', sans-serif",
  '--font-body': "'Plus Jakarta Sans', sans-serif",
}

export const OTO_BAKIM_BUSINESS = {
  name: 'OtoServis Pro Bakım Merkezi',
  ownerName: 'Murat Demirci',
  sectorId: 'Oto',
  slogan: 'Aracınız için profesyonel periyodik bakım',
  phone: '0212 555 12 12',
  phoneClean: '902125551212',
  whatsapp: '905325551212',
  email: 'iletisim@otoservispro.com',
  address: 'İkitelli OSB, Dolapdere Sanayi Sitesi 22. Ada No:12, Başakşehir/İstanbul',
  city: 'İstanbul',
  district: 'Başakşehir',
  neighborhood: 'İkitelli OSB',
  coordinates: { lat: 41.0765, lng: 28.7932 },
  socialMedia: { instagram: 'https://instagram.com/otoservispro' },
  photos: [],
  foundedYear: 2010,
  experience: '14 yıldır',
  customerCount: '8.500+',
  rating: 4.8,
  reviewCount: 650,
  services: [
    {
      id: 's1',
      name: 'Periyodik Bakım Paketi',
      price: '3.500 TL\'den başlayan',
      duration: '90 dk',
      description: 'Motor yağı, yağ filtresi, hava filtresi ve polen filtresi değişimi. 40 nokta güvenlik kontrolü dahildir.',
    },
    {
      id: 's2',
      name: 'Fren Sistemi Bakımı',
      price: '1.200 TL',
      duration: '45 dk',
      description: 'Ön/arka fren balata değişimi, fren disk kontrolü ve fren hidrolik sıvısı seviye tamamlaması.',
    },
    {
      id: 's3',
      name: 'Bilgisayarlı Arıza Tespit',
      price: '500 TL',
      duration: '30 dk',
      description: 'Orijinal OBD2 cihazı ile motor, şanzıman ve elektronik sistem arıza kodu okuma, hata silme.',
    },
    {
      id: 's4',
      name: 'Akü Değişimi & Kontrol',
      price: 'Akü fiyatına göre',
      duration: '20 dk',
      description: 'Akü şarj ölçümü, alternatör kontrolü ve gerekirse yeni akü montajı ve kodlaması.',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Salı', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Çarşamba', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Perşembe', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Cuma', open: '08:30', close: '19:00', isOpen: true },
    { day: 'Cumartesi', open: '08:30', close: '15:00', isOpen: true },
    { day: 'Pazar', open: null, close: null, isOpen: false },
  ],
} as unknown as BusinessData

export const OTO_BAKIM_CONFIG = {
  id: 'oto-bakim',
  name: 'Bakım',
  sectorId: 'oto',
  plan: 'starter',
  description: 'Modern oto bakım merkezi, düzenli müşteri odaklı net tasarım',
  designPhilosophy: 'Güven veren mavi tonları, profesyonel sans-serif tipografi ve yüksek okunabilirlik',
  isDark: false,
  cssVariables: OTO_BAKIM_CSS,
  fonts: {
    heading: {
      family: 'Plus Jakarta Sans',
      weights: [600, 700],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Plus Jakarta Sans',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'AutoRepair',
  sectorSections: ['vehicle_brands', 'warranty_badge', 'service_area'],
  performanceBudget: {
    maxJS: '70kb',
    maxLCP: '2.8s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: OTO_BAKIM_BUSINESS.name },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: { text: 'WhatsApp', href: 'https://wa.me/905325551212', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'dark', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: OTO_BAKIM_BUSINESS.name,
        copyright: '© 2026 OtoServis Pro Bakım Merkezi. Tüm hakları saklıdır.',
        contact: {
          phone: OTO_BAKIM_BUSINESS.phone,
          email: OTO_BAKIM_BUSINESS.email,
          address: OTO_BAKIM_BUSINESS.address,
        },
        social: [{ platform: 'instagram', url: 'https://instagram.com/otoservispro', icon: 'instagram' }],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1000, removable: false, animation: 'none' },
      defaultContent: { phone: '905325551212', message: 'Periyodik bakım için bilgi almak ve randevu oluşturmak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${OTO_BAKIM_BUSINESS.name} — İkitelli Periyodik Araç Bakımı`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'TSE ONAYLI SERVİS',
            title: OTO_BAKIM_BUSINESS.name,
            subtitle: OTO_BAKIM_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Eski Kurdele Yazısı', type: 'text' },
            { path: 'title', label: 'Dükkan Adı', type: 'text' },
            { path: 'subtitle', label: 'Slogan / Alt Metin', type: 'richtext' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 2,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'HİZMET MENÜSÜ',
            title: 'Profesyonel Bakım ve Onarım',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'Servis Menüsü Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 3,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'ULAŞIM VE RANDEVU',
            title: 'Sanayideki Adresimiz',
          },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
