/**
 * @kepenk/templates — pastane-simit Theme Configuration
 *
 * Simitci ve unlu mamuller
 * Plan: free (3 page sections, 3 global sections)
 * Font: Inter/Inter | Accent: #EA580C
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const PASTANE_SIMIT_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#EA580C',
  '--color-accent-hover': '#EA580C',
  '--color-accent-active': '#EA580C',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': "'Outfit', sans-serif",
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const PASTANE_SIMIT_BUSINESS = {
  name: 'Ankara Simit Sarayi',
  ownerName: 'Hayri Sahin',
  sectorId: 'Pastane',
  slogan: 'Firindan cikan sicacik lezzet',
  phone: '0532 800 22 00',
  phoneClean: '905328002200',
  whatsapp: '905328002200',
  email: 'info@ankarasimit.com',
  address: 'Osmanaga Mah. Bahariye Cad. No:58, Kadikoy/Istanbul',
  city: 'Istanbul',
  district: 'Kadikoy',
  neighborhood: 'Osmanaga',
  coordinates: { lat: 40.9905, lng: 29.027 },
  socialMedia: { instagram: 'https://instagram.com/ankarasimit' },
  photos: [],
  foundedYear: 2012,
  experience: '12 yil',
  customerCount: '500.000+',
  rating: 4.5,
  reviewCount: 1200,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '06:00',
      close: '22:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '06:00',
      close: '22:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '06:00',
      close: '22:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '06:00',
      close: '22:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '06:00',
      close: '22:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '06:00',
      close: '23:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '07:00',
      close: '22:00',
      isOpen: true,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Taze Simit',
      price: '15 TL',
      duration: 'Aninda',
      description: 'Firindan yeni cikmis gevrek simit. Susam ve corekotlu secenekler.',
    },
    {
      id: 's2',
      name: 'Pogaca Cesitleri',
      price: '20 TL',
      duration: 'Aninda',
      description: 'Peynirli, zeytinli, patatesli ve kiymali pogaca.',
    },
    {
      id: 's3',
      name: 'Kahvalti Tabagi',
      price: '120 TL',
      duration: '10 dk',
      description: 'Simit, peynir, zeytin, domates, salatalik ve cay dahil kahvalti seti.',
    },
    {
      id: 's4',
      name: 'Taze Sikma Portakal Suyu',
      price: '35 TL',
      duration: 'Aninda',
      description: 'Taze sikilmis dogal portakal suyu.',
    },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const PASTANE_SIMIT_CONFIG = {
  id: 'pastane-simit',
  name: 'Simit',
  sectorId: 'pastane',
  plan: 'free',
  description: 'Simitci ve unlu mamuller',
  designPhilosophy: 'Sicak, samimi, geleneksel',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#EA580C',
    '--color-accent-hover': '#EA580C',
    '--color-accent-active': '#EA580C',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': "'Outfit', sans-serif",
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Outfit',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'Bakery',
  sectorSections: [],
  performanceBudget: {
    maxJS: '80kb',
    maxLCP: '3.0s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Ankara Simit Sarayi' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905328002200',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Ankara Simit Sarayi',
        copyright: '© 2026 Ankara Simit Sarayi',
        contact: {
          phone: '0532 800 22 00',
          email: 'info@ankarasimit.com',
          address: 'Osmanaga Mah. Bahariye Cad. No:58, Kadikoy/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/ankarasimit',
            icon: 'instagram',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905328002200', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Ankara Simit Sarayi — Kadikoy',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: PASTANE_SIMIT_BUSINESS.name, subtitle: PASTANE_SIMIT_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
