#!/usr/bin/env npx tsx
/**
 * @kepenk/templates — Build-Time Config Generator
 *
 * Reads content-manifests/*.json → calls generateThemeConfig() → writes TypeScript config files.
 *
 * Usage:
 *   npx tsx scripts/generate-configs.ts           # generate all
 *   npx tsx scripts/generate-configs.ts berber     # generate single sector
 *
 * Output:
 *   packages/templates/src/themes/configs/{id}-config.ts
 */

import fs from 'node:fs'
import path from 'node:path'
import { generateThemeConfig, type ConfigGeneratorInput } from '../packages/templates/src/utils/config-generator'

// ─────────────────────────────────────────────
// Paths
// ─────────────────────────────────────────────

const ROOT = path.resolve(import.meta.dirname ?? __dirname)
const MANIFESTS_DIR = path.resolve(ROOT, '../packages/templates/src/content-manifests')
const CONFIGS_DIR = path.resolve(ROOT, '../packages/templates/src/themes/configs')

// ─────────────────────────────────────────────
// Manifest types (mirrors JSON structure)
// ─────────────────────────────────────────────

interface ManifestVariant {
  id: string
  variantName: string
  plan: 'free' | 'starter' | 'growth' | 'pro' | 'enterprise' | 'elite'
  description: string
  designPhilosophy: string
  isDark: boolean
  colors: {
    bg: string
    surface: string
    text: string
    accent: string
    accentHover?: string
    accentLight?: string
    surfaceElevated?: string
    textSecondary?: string
  }
  fonts: { heading: string; body: string }
  business: Record<string, unknown>
  content: Record<string, Record<string, unknown>>
}

interface Manifest {
  sectorId: string
  seoSchemaType: string
  variants: ManifestVariant[]
}

// ─────────────────────────────────────────────
// Serialization helpers
// ─────────────────────────────────────────────

/**
 * Serialize a JS value to TypeScript source code.
 * Handles: strings, numbers, booleans, null, undefined, arrays, objects.
 */
function toTS(value: unknown, indent = 0): string {
  const pad = '  '.repeat(indent)
  const padInner = '  '.repeat(indent + 1)

  if (value === undefined) return 'undefined'
  if (value === null) return 'null'
  if (typeof value === 'string') return quoteString(value)
  if (typeof value === 'number' || typeof value === 'boolean') return String(value)

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]'
    // Short arrays of primitives on one line
    if (value.length <= 3 && value.every(v => typeof v !== 'object' || v === null)) {
      return `[${value.map(v => toTS(v, 0)).join(', ')}]`
    }
    const items = value.map(v => `${padInner}${toTS(v, indent + 1)},`).join('\n')
    return `[\n${items}\n${pad}]`
  }

  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, v]) => v !== undefined)
    if (entries.length === 0) return '{}'

    // Short objects on one line
    if (entries.length <= 2 && entries.every(([, v]) => typeof v !== 'object' || v === null)) {
      return `{ ${entries.map(([k, v]) => `${safeKey(k)}: ${toTS(v, 0)}`).join(', ')} }`
    }

    const props = entries.map(([k, v]) => `${padInner}${safeKey(k)}: ${toTS(v, indent + 1)},`).join('\n')
    return `{\n${props}\n${pad}}`
  }

  return String(value)
}

/** Quote a string with single quotes, escaping as needed */
function quoteString(s: string): string {
  const escaped = s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t')
  return `'${escaped}'`
}

/** Return a safe property key (quoted if needed) */
function safeKey(key: string): string {
  if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) return key
  return quoteString(key)
}

// ─────────────────────────────────────────────
// TypeScript file generator
// ─────────────────────────────────────────────

function generateTypeScriptFile(
  themeId: string,
  prefix: string,
  config: Record<string, unknown>,
  business: Record<string, unknown>,
  css: Record<string, string>,
  variant: ManifestVariant,
): string {
  const sectionCount = (config as any).pages?.[0]?.sections?.length ?? 0
  const globalCount = ((config as any).globalSections as unknown[])?.length ?? 0

  const header = [
    '/**',
    ` * @kepenk/templates — ${themeId} Theme Configuration`,
    ` *`,
    ` * ${variant.description}`,
    ` * Plan: ${variant.plan} (${sectionCount} page sections, ${globalCount} global sections)`,
    ` * Font: ${variant.fonts.heading}/${variant.fonts.body} | Accent: ${variant.colors.accent}`,
    ` * Generated by: scripts/generate-configs.ts`,
    ' */',
    '',
    "import type { ThemeConfig, BusinessData } from '../../types/section-types'",
    '',
  ].join('\n')

  const cssBlock = [
    `// ═══ CSS VARIABLES ═══`,
    '',
    `export const ${prefix}_CSS: Record<string, string> = ${toTS(css, 0)}`,
    '',
  ].join('\n')

  const businessBlock = [
    `// ═══ DEMO BUSINESS DATA ═══`,
    '',
    `export const ${prefix}_BUSINESS = ${toTS(business, 0)} as unknown as BusinessData`,
    '',
  ].join('\n')

  const configBlock = [
    `// ═══ THEME CONFIG ═══`,
    '',
    `export const ${prefix}_CONFIG = ${toTS(config, 0)} as unknown as ThemeConfig`,
    '',
  ].join('\n')

  return [header, cssBlock, businessBlock, configBlock].join('\n')
}

// ─────────────────────────────────────────────
// Manifest → ConfigGeneratorInput mapper
// ─────────────────────────────────────────────

function manifestToInput(manifest: Manifest, variant: ManifestVariant): ConfigGeneratorInput {
  return {
    sectorId: manifest.sectorId,
    variantName: variant.variantName,
    plan: variant.plan,
    businessData: variant.business as any,
    colorScheme: {
      bg: variant.colors.bg,
      surface: variant.colors.surface,
      text: variant.colors.text,
      accent: variant.colors.accent,
      accentHover: variant.colors.accentHover,
      accentLight: variant.colors.accentLight,
      surfaceElevated: variant.colors.surfaceElevated,
      textSecondary: variant.colors.textSecondary,
    },
    fonts: variant.fonts,
    isDark: variant.isDark,
    description: variant.description,
    designPhilosophy: variant.designPhilosophy,
    seoSchemaType: manifest.seoSchemaType,
    contentOverrides: variant.content as any,
  }
}

// ─────────────────────────────────────────────
// Uniqueness validation
// ─────────────────────────────────────────────

interface UniquenessTracker {
  names: Map<string, string>      // name → themeId
  addresses: Map<string, string>  // address → themeId
  slogans: Map<string, string>    // slogan → themeId
  ids: Map<string, string>        // id → file
}

function checkUniqueness(
  tracker: UniquenessTracker,
  themeId: string,
  business: Record<string, unknown>,
): string[] {
  const errors: string[] = []
  const name = String(business.name || '')
  const address = String(business.address || '')
  const slogan = String(business.slogan || '')

  if (name && tracker.names.has(name)) {
    errors.push(`Duplicate name "${name}" in ${themeId} (already in ${tracker.names.get(name)})`)
  }
  tracker.names.set(name, themeId)

  if (address && tracker.addresses.has(address)) {
    errors.push(`Duplicate address "${address}" in ${themeId} (already in ${tracker.addresses.get(address)})`)
  }
  tracker.addresses.set(address, themeId)

  if (slogan && tracker.slogans.has(slogan)) {
    errors.push(`Duplicate slogan "${slogan}" in ${themeId} (already in ${tracker.slogans.get(slogan)})`)
  }
  tracker.slogans.set(slogan, themeId)

  if (tracker.ids.has(themeId)) {
    errors.push(`Duplicate theme ID "${themeId}" (already exists)`)
  }
  tracker.ids.set(themeId, `${themeId}-config.ts`)

  return errors
}

// ─────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────

function main() {
  const startTime = Date.now()
  const filterSector = process.argv[2] // optional: single sector filter

  // Ensure output dir exists
  if (!fs.existsSync(CONFIGS_DIR)) {
    fs.mkdirSync(CONFIGS_DIR, { recursive: true })
  }

  // Read manifests
  const manifestFiles = fs.readdirSync(MANIFESTS_DIR)
    .filter(f => f.endsWith('.json'))
    .filter(f => !filterSector || f.startsWith(filterSector))

  if (manifestFiles.length === 0) {
    console.error(`No manifest files found in ${MANIFESTS_DIR}`)
    if (filterSector) console.error(`  (filter: "${filterSector}")`)
    process.exit(1)
  }

  console.log(`\n  Config Generator`)
  console.log(`  ${'─'.repeat(40)}`)
  console.log(`  Manifests: ${manifestFiles.length}`)
  if (filterSector) console.log(`  Filter: ${filterSector}`)
  console.log()

  const tracker: UniquenessTracker = {
    names: new Map(),
    addresses: new Map(),
    slogans: new Map(),
    ids: new Map(),
  }

  let totalGenerated = 0
  let totalErrors = 0
  const allErrors: string[] = []
  const sectorSummaries: { sector: string; count: number; plans: string[] }[] = []

  for (const file of manifestFiles) {
    const filePath = path.join(MANIFESTS_DIR, file)
    let manifest: Manifest

    try {
      manifest = JSON.parse(fs.readFileSync(filePath, 'utf-8'))
    } catch (err) {
      const msg = `Failed to parse ${file}: ${err}`
      console.error(`  [ERROR] ${msg}`)
      allErrors.push(msg)
      totalErrors++
      continue
    }

    const plans: string[] = []

    for (const variant of manifest.variants) {
      const themeId = variant.id

      // Map manifest → generator input
      const input = manifestToInput(manifest, variant)

      // Generate config
      const { config, business, css } = generateThemeConfig(input)

      // Uniqueness check
      const uniqueErrors = checkUniqueness(tracker, themeId, business as Record<string, unknown>)
      if (uniqueErrors.length > 0) {
        allErrors.push(...uniqueErrors)
        totalErrors += uniqueErrors.length
      }

      // Serialize to TypeScript
      const prefix = themeId.toUpperCase().replace(/-/g, '_')
      const tsSource = generateTypeScriptFile(
        themeId,
        prefix,
        config as unknown as Record<string, unknown>,
        business as unknown as Record<string, unknown>,
        css,
        variant,
      )

      // Write file
      const outPath = path.join(CONFIGS_DIR, `${themeId}-config.ts`)
      fs.writeFileSync(outPath, tsSource, 'utf-8')

      plans.push(variant.plan)
      totalGenerated++
    }

    sectorSummaries.push({
      sector: manifest.sectorId,
      count: manifest.variants.length,
      plans,
    })

    console.log(`  [OK] ${manifest.sectorId}: ${manifest.variants.length} configs generated`)
  }

  // ── Summary ──
  const elapsed = Date.now() - startTime
  console.log()
  console.log(`  ${'─'.repeat(40)}`)
  console.log(`  Summary`)
  console.log(`  ${'─'.repeat(40)}`)
  console.log(`  Total configs generated: ${totalGenerated}`)
  console.log(`  Sectors processed: ${sectorSummaries.length}`)
  console.log(`  Unique business names: ${tracker.names.size}`)
  console.log(`  Time: ${elapsed}ms`)
  console.log()

  // Plan distribution
  const planCounts: Record<string, number> = {}
  for (const s of sectorSummaries) {
    for (const p of s.plans) {
      planCounts[p] = (planCounts[p] || 0) + 1
    }
  }
  console.log(`  Plan distribution:`)
  for (const [plan, count] of Object.entries(planCounts).sort()) {
    console.log(`    ${plan}: ${count}`)
  }
  console.log()

  // Errors
  if (allErrors.length > 0) {
    console.log(`  Warnings/Errors (${allErrors.length}):`)
    for (const err of allErrors) {
      console.log(`    - ${err}`)
    }
    console.log()
  }

  if (totalErrors > 0) {
    console.error(`  ${totalErrors} issues found. Review above.`)
  } else {
    console.log(`  All configs generated successfully.`)
  }
  console.log()
}

main()
