/**
 * @kepenk/templates — cilingir-kasa Theme Configuration
 *
 * Kasa acma ve guvenlik danismanligi
 * Plan: pro (11 page sections, 4 global sections)
 * Font: Montserrat/Inter | Accent: #37474F
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const CILINGIR_KASA_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#37474F',
  '--color-accent-hover': '#37474F',
  '--color-accent-active': '#37474F',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'Montserrat\', sans-serif',
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const CILINGIR_KASA_BUSINESS = {
  name: 'SafeGuard Kasa & Guvenlik Sistemleri',
  ownerName: 'Bulent Ozturk',
  sectorId: 'Cilingir',
  slogan: 'Degerleriniz guvenli ellerde',
  phone: '0535 481 93 20',
  phoneClean: '905354819320',
  whatsapp: '905354819320',
  email: 'info@safeguardtr.com',
  address: 'Merter Mah. Fatih Cad. No:33/1, Gungoren/Istanbul',
  city: 'Istanbul',
  district: 'Gungoren',
  neighborhood: 'Merter',
  coordinates: { lat: 41.0152, lng: 28.8905 },
  socialMedia: {
    instagram: 'https://instagram.com/safeguardtr',
    facebook: 'https://facebook.com/safeguardtr',
    linkedin: 'https://linkedin.com/company/safeguardtr',
    youtube: 'https://youtube.com/@safeguard',
  },
  photos: [],
  foundedYear: 2005,
  experience: '21 yil',
  customerCount: '12.000+',
  rating: 4.9,
  reviewCount: 1500,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '09:00',
      close: '16:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '00:00',
      close: '00:00',
      isOpen: false,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Para Kasasi Acma',
      price: '1.000 - 5.000 TL',
      duration: '30-120 dk',
      description: 'Sifre unutma, mekanik ariza, anahtar kaybi durumunda hasarsiz kasa acma.',
    },
    {
      id: 's2',
      name: 'Kasa Satis & Montaj',
      price: '3.000 - 50.000 TL',
      duration: '2-4 saat',
      description: 'Yangin dayanikli, hirsizlik onleyici kasalar. Duvar ve zemine sabitleme.',
    },
    {
      id: 's3',
      name: 'Kasa Kilit Degisimi',
      price: '800 - 3.000 TL',
      duration: '45 dk',
      description: 'Mekanik veya elektronik kasa kilidi degisimi ve yenileme.',
    },
    {
      id: 's4',
      name: 'Celik Oda Yapimi',
      price: '25.000 - 150.000 TL',
      duration: '1-3 hafta',
      description: 'Kuyumcu, banka ve ozel koleksiyon icin celik oda/hazine odasi yapimi.',
    },
    {
      id: 's5',
      name: 'Guvenlik Danismanligi',
      price: '2.000 TL',
      duration: '2 saat',
      description: 'Ev ve is yeri guvenlik analizi, risk degerlendirmesi, sistem onerisi.',
    },
    {
      id: 's6',
      name: 'CCTV Kamera Sistemi',
      price: '3.000 - 20.000 TL',
      duration: '1-2 gun',
      description: 'IP kamera, NVR kayit, uzaktan izleme. Ic ve dis mekan.',
    },
    {
      id: 's7',
      name: 'Erisiim Kontrol Sistemi',
      price: '5.000 - 30.000 TL',
      duration: '2-5 gun',
      description: 'Kart, parmak izi, yuz tanima ile giris-cikis kontrol sistemi.',
    },
    {
      id: 's8',
      name: 'Yangin Algilama Sistemi',
      price: '2.000 - 15.000 TL',
      duration: '1-2 gun',
      description: 'Duman/isi dedektoru, yangin alarm paneli, otomatik bildirim.',
    },
    {
      id: 's9',
      name: 'Kasa Tasima',
      price: '1.000 - 5.000 TL',
      duration: '2-4 saat',
      description: 'Agir kasalarin guvenli tasimasi. Ozel ekipman ve sigorta ile.',
    },
    {
      id: 's10',
      name: 'Elektronik Kasa Programlama',
      price: '500 - 1.500 TL',
      duration: '30 dk',
      description: 'Dijital kasa sifre degistirme, kullanici ekleme/silme, audit log.',
    },
    {
      id: 's11',
      name: 'Periyodik Bakim Sozlesmesi',
      price: '1.500 TL/yil',
      duration: 'ceyreklik',
      description: 'Yilda 4 kasa kontrol ziyareti. Kilit bakimi, pil degisimi, fonksiyon testi.',
    },
    {
      id: 's12',
      name: 'Otopark Bariyer Sistemi',
      price: '5.000 - 25.000 TL',
      duration: '2-4 gun',
      description: 'Otopark bariyer, plaka tanima, kartli giris sistemi.',
    },
    {
      id: 's13',
      name: 'Panik Butonu & Acil Alarm',
      price: '1.000 - 3.000 TL',
      duration: '2 saat',
      description: 'Tezgah alti panik butonu, SOS alarm sistemi. Guvenlik sirketi entegrasyonu.',
    },
    {
      id: 's14',
      name: 'Anahtar Kasasi (Key Box)',
      price: '1.000 - 5.000 TL',
      duration: '1 saat',
      description: 'Coklu anahtar yonetimi icin mekanik veya dijital anahtar kasasi.',
    },
  ],
  team: [
    {
      name: 'Bulent Ozturk',
      role: 'Kurucu & Guvenlik Danismani',
      bio: '21 yillik guvenlik sektoru deneyimi. Kasa acma ve guvenlik sistemleri uzmani. CPP sertifikali.',
    },
    {
      name: 'Ahmet Kara',
      role: 'Kasa Ustasi',
      bio: '18 yillik kasa acma ve kilit degisimi deneyimi. Her marka ve model kasayla calisiyor.',
    },
    {
      name: 'Elif Sahin',
      role: 'Elektronik Guvenlik Uzmani',
      bio: 'CCTV, erisim kontrol ve alarm sistemleri projelendirme ve montaj. 10 yillik deneyim.',
    },
    {
      name: 'Murat Aksoy',
      role: 'Celik Oda Proje Muduru',
      bio: 'Celik oda, hazine odasi ve ozel depo projelerinde 15 yil deneyim.',
    },
    {
      name: 'Derya Yilmaz',
      role: 'Satis & Musteri Iliskileri',
      bio: 'Kasa satis danismanligi, kurumsal hesap yonetimi. 8 yillik sektoor deneyimi.',
    },
    {
      name: 'Hasan Polat',
      role: 'Yangin & Alarm Uzmani',
      bio: 'Yangin algilama ve alarm sistemleri sertifikali. Itfaiye gecmisli.',
    },
  ],
  testimonials: [
    {
      name: 'Kapalicarsı Kuyumcular Dernegi',
      district: 'Fatih',
      date: '2025-12',
      rating: 5,
      comment: '50+ kuyumcu dukkaninin kasa ve guvenlik sistemleri SafeGuard tarafindan yapildi. Celik oda yapimi ve kasa bakımı konusunda sektorun en iyileri.',
    },
    {
      name: 'Mehmet Demirel (Avukat)',
      district: 'Sisli',
      date: '2025-11',
      rating: 5,
      comment: 'Ofisim icin guvenlik danismanligi aldim. CCTV, erisim kontrol ve celik kasa onerisi yapildi. Projelendirme ve montaj kusursuz.',
    },
    {
      name: 'ABC Bankacilik',
      district: 'Levent',
      date: '2025-10',
      rating: 5,
      comment: 'Sube kasalarimizin periyodik bakim sozlesmesini SafeGuard ile yaptik. Ceyreklik kontroller ve acil mudahale hizi muhtesem.',
    },
    {
      name: 'Selin Aksoy',
      district: 'Bakirkoy',
      date: '2025-09',
      rating: 5,
      comment: 'Evdeki kasanin sifresiini unuttum. Bulent Bey geldi, 45 dakikada hasarsiz acti. Yeni sifre tanimladi. Gercek profesyonel.',
    },
    {
      name: 'Demir Insaat',
      district: 'Kagithane',
      date: '2025-08',
      rating: 5,
      comment: 'Santiye icin otopark bariyeri ve plaka tanima sistemi kurdurduk. Taseron giriiş-cikislari artik kayit altinda.',
    },
    {
      name: 'Ayse Korkmaz',
      district: 'Besiktas',
      date: '2025-07',
      rating: 5,
      comment: 'Kuyumcu dukkanum icin celik oda yaptirdik. Murat Bey projeyi basından sonuna yonetti. Sigorta sirketi belgelerini hemen onayladi.',
    },
    {
      name: 'Hilton Istanbul',
      district: 'Sisli',
      date: '2025-06',
      rating: 4,
      comment: 'Otel kasalarinin toplu bakim ve kilit degisimini yaptirdik. Kalite yuksek, tek sorun: proje basllangıci planlanandan 1 hafta gecikti.',
    },
    {
      name: 'Tarim Kredi Kooperatifi',
      district: 'Bagcilar',
      date: '2025-11',
      rating: 5,
      comment: '15 subemizin yangin algilama sistemi SafeGuard tarafindan kuruldu. Duman dedektorleri ve otomatik bildirim sistemi calisiyor.',
    },
  ],
  faq: [
    { q: 'Kasa acma isleminde kasaya zarar verilir mi?', a: 'Hasarsiz acma teknikleriyle calisiyoruz. %90+ vakada kasaya hicbir zarar vermeden aciyoruz. Nadir durumlarda kucuk mudahale gerekebilir, onceden bilgi verilir.' },
    { q: 'Celik oda yapimi kac gunde tamamlanir?', a: 'Oda boyutuna gore 1-3 hafta surmektedir. Proje cizimi, malzeme tedaariki ve montaj dahildir.' },
    { q: 'Yangin dayanikli kasa ne kadar dayanir?', a: 'Sertifika sinifina gore 30 dakika ile 2 saat arasi yangin dayanimi sunar. En yaygin standart 1 saatlik yangin daayanimi olan kasalardir.' },
    { q: 'CCTV kayitlari ne kadar sureyle saklanir?', a: 'Hard disk kapasitesine gore 7-90 gun arasi kayit saklanir. Standart kurulumda 30 gun kayit oneeriyoruz.' },
    { q: 'Erisim kontrol sistemi kac kisiyi destekler?', a: 'Sistemee gore 50 ile 10.000 kullanici arasi desteklenir. Kucuk ofis icin kart sistemi, buyuk tesis icin yuz tanıma oneriyoruz.' },
    { q: 'Kasa tasima sigorta kapsaminda mi?', a: 'Evet, tasima sirasinda olusan hasarlar sigortamiz kapsamindadir. Ozel ekipman ile guvenli tasima garanti edilir.' },
    { q: 'Periyodik bakim sozlesmesi ne icerir?', a: 'Yilda 4 ziyaret: kilit mekanizma kontrolu, yaglama, pil degisimi, sifre testi, mentese kontrolu. Aciil durumlarda oncelikli mudahale.' },
    { q: 'Panik butonu nereye baglanir?', a: 'Guvenlik sirketi, polis veya ozel alarm merkezine baglanabilir. Basildıgında sessiz alarm gonderir.' },
    { q: 'Anahtar kasasi (key box) ne ise yarar?', a: 'Birden fazla anahtar yonetimii gerektiren isletmeler (otel, gayrimenkul, filo) icin merkezi anahtar depolama ve takip sistemidir.' },
    { q: 'Garanti sureleriniz nedir?', a: 'Kasa satisinda 5 yil, kilit degisiminde 2 yil, CCTV/alarm sistemlerinde 2 yil garanti veriyoruz. Periyodik bakim sozlesmesiyle garanti uzar.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const CILINGIR_KASA_CONFIG = {
  id: 'cilingir-kasa',
  name: 'Kasa',
  sectorId: 'cilingir',
  plan: 'pro',
  description: 'Kasa acma ve guvenlik danismanligi',
  designPhilosophy: 'Guclu, gizli, ozel',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#37474F',
    '--color-accent-hover': '#37474F',
    '--color-accent-active': '#37474F',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'Montserrat\', sans-serif',
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Montserrat',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'Locksmith',
  sectorSections: [],
  performanceBudget: {
    maxJS: '250kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'SafeGuard Kasa & Guvenlik Sistemleri' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905354819320',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'SafeGuard Kasa & Guvenlik Sistemleri',
        copyright: '© 2026 SafeGuard Kasa & Guvenlik Sistemleri',
        contact: {
          phone: '0535 481 93 20',
          email: 'info@safeguardtr.com',
          address: 'Merter Mah. Fatih Cad. No:33/1, Gungoren/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/safeguardtr',
            icon: 'instagram',
          },
          {
            platform: 'facebook',
            url: 'https://facebook.com/safeguardtr',
            icon: 'facebook',
          },
          {
            platform: 'linkedin',
            url: 'https://linkedin.com/company/safeguardtr',
            icon: 'linkedin',
          },
          {
            platform: 'youtube',
            url: 'https://youtube.com/@safeguard',
            icon: 'youtube',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905354819320', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'SafeGuard Kasa & Guvenlik Sistemleri — Gungoren',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: CILINGIR_KASA_BUSINESS.name, subtitle: CILINGIR_KASA_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
