import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const NAKLIYAT_EV_BUSINESS: BusinessData = {
  name: 'Ev Nakliyat',
  ownerName: 'Hasan Nakliye',
  sectorId: 'nakliyat',
  slogan: 'Guvenli ev tasimaciligi',
  phone: '0532 500 11 22',
  phoneClean: '905325001122',
  whatsapp: '905325001122',
  email: 'info@evnakliyat.com',
  address: 'Pendik Mah. No:20, Pendik, Istanbul',
  city: 'Istanbul',
  district: 'Pendik',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"07:00","close":"20:00"},{"day":"tuesday","dayTr":"Sali","open":"07:00","close":"20:00"},{"day":"wednesday","dayTr":"Carsamba","open":"07:00","close":"20:00"},{"day":"thursday","dayTr":"Persembe","open":"07:00","close":"20:00"},{"day":"friday","dayTr":"Cuma","open":"07:00","close":"20:00"},{"day":"saturday","dayTr":"Cumartesi","open":"07:00","close":"20:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/nakliyat-ev"},
  photos: [],
  services: []
}
export const NAKLIYAT_EV_CONFIG: ThemeConfig = { id: 'nakliyat-ev', name: 'Evden Eve', sectorId: 'nakliyat', plan: 'free', isDark: false, cssVariables: { '--color-bg': '#FFFFFF', '--color-surface': '#F8FAFC', '--color-text': '#0F172A', '--color-accent': '#5e39ac',
    '--color-accent-light': '#efe8fc',
    '--color-accent-hover': '#4d2f8e',
    '--color-accent-active': '#452a7e', '--color-text-on-accent': '#FFFFFF', '--color-border': '#E2E8F0', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif" }, fonts: { heading: { family: 'Bodoni Moda', weights: [700] }, body: { family: 'Inter', weights: [500] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Ev Nakliyat' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Ev Nakliyat',
        copyright: '© 2026 Ev Nakliyat',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'Güven Nakliyat', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'xl', containerWidth: 'xl', visible: true }, defaultContent: { badge: 'EVDEN EVE', title: 'Eşyalarınız Bize Emanet' } } ] }] }