/**
 * @kepenk/templates — kres-oyun Theme Configuration
 *
 * Oyun odaklı kreş — sıcak renkler, davetkar tasarım
 * Plan: free (3 page sections, 3 global sections)
 * Font: Inter/Inter | Accent: #FF8C42
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const KRES_OYUN_CSS: Record<string, string> = {
  '--container-default': '960px',
  '--section-py': '64px',
  '--radius-md': '16px',
  '--radius-lg': '32px',
  '--color-bg': '#FFFAFA',
  '--color-surface': '#FFF0F0',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#FFE4E4',
  '--color-text': '#4A3B3B',
  '--color-text-secondary': '#7A6B6B',
  '--color-text-muted': '#B3A1A1',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#FF8C42',
  '--color-accent-hover': '#FF8C42',
  '--color-accent-active': '#FF8C42',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#FFD6D6',
  '--color-border-subtle': '#FFF0F0',
  '--font-heading': "'Bebas Neue', sans-serif",
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const KRES_OYUN_BUSINESS = {
  name: 'Minik Adımlar Kreşi',
  sectorId: 'kres',
  ownerName: 'Ayşe Kaya',
  slogan: 'Oyunla öğrenen, sevgiyle büyüyen çocuklar',
  phone: '0212 345 6701',
  phoneClean: '02123456701',
  email: 'info@minikadimlar.com',
  address: 'Caferağa Mah. Moda Cad. No:28, Kadıköy/İstanbul',
  city: 'İstanbul',
  district: 'Kadıköy',
  coordinates: { lat: 40.9868, lng: 29.0257 },
  socialMedia: { instagram: 'minikadimlarkresi', facebook: 'minikadimlarkresi' },
  photos: [],
  foundedYear: 2018,
  experience: '6 yıl',
  customerCount: '800+',
  rating: 4.7,
  reviewCount: 180,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '07:30',
      close: '18:30',
      isOpen: true,
    },
    {
      day: 'Salı',
      open: '07:30',
      close: '18:30',
      isOpen: true,
    },
    {
      day: 'Çarşamba',
      open: '07:30',
      close: '18:30',
      isOpen: true,
    },
    {
      day: 'Perşembe',
      open: '07:30',
      close: '18:30',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '07:30',
      close: '18:30',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '09:00',
      close: '14:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '',
      close: '',
      isOpen: false,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Tam Gün Kreş (0-3 Yaş)',
      price: '8.500 TL/ay',
      duration: 'Tam gün',
      description: 'Bebek grubu için güvenli, hijyenik ortamda tam gün bakım ve erken gelişim programı.',
    },
    {
      id: 's2',
      name: 'Yarım Gün Kreş (0-3 Yaş)',
      price: '5.500 TL/ay',
      duration: 'Yarım gün',
      description: 'Sabah veya öğleden sonra seçenekli yarım gün bakım programı.',
    },
    {
      id: 's3',
      name: 'Anaokulu (3-6 Yaş)',
      price: '9.000 TL/ay',
      duration: 'Tam gün',
      description: 'Okul öncesi eğitim müfredatı ile akademik ve sosyal gelişim programı.',
    },
    {
      id: 's4',
      name: 'Yaz Okulu',
      price: '7.000 TL/ay',
      duration: 'Haziran-Ağustos',
      description: 'Yaz aylarında eğlenceli aktiviteler, yüzme ve açık hava etkinlikleri.',
    },
  ],
  team: [],
  testimonials: [],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const KRES_OYUN_CONFIG = {
  id: 'kres-oyun',
  name: 'Oyun',
  sectorId: 'kres',
  plan: 'free',
  description: 'Oyun odaklı kreş — sıcak renkler, davetkar tasarım',
  designPhilosophy: 'Çocuk dostu, yumuşak köşeler, pastel vurgular',
  isDark: false,
  cssVariables: {
    '--container-default': '960px',
    '--section-py': '64px',
    '--radius-md': '16px',
    '--radius-lg': '32px',
    '--color-bg': '#FFFAFA',
    '--color-surface': '#FFF0F0',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#FFE4E4',
    '--color-text': '#4A3B3B',
    '--color-text-secondary': '#7A6B6B',
    '--color-text-muted': '#B3A1A1',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#FF8C42',
    '--color-accent-hover': '#FF8C42',
    '--color-accent-active': '#FF8C42',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#FFD6D6',
    '--color-border-subtle': '#FFF0F0',
    '--font-heading': "'Bebas Neue', sans-serif",
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Bebas Neue',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'ChildCare',
  sectorSections: [],
  performanceBudget: {
    maxJS: '80kb',
    maxLCP: '3.0s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Minik Adımlar Kreşi' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'Ara',
          href: 'tel:02123456701',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Minik Adımlar Kreşi',
        copyright: '© 2026 Minik Adımlar Kreşi',
        contact: {
          phone: '0212 345 6701',
          email: 'info@minikadimlar.com',
          address: 'Caferağa Mah. Moda Cad. No:28, Kadıköy/İstanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'minikadimlarkresi',
            icon: 'instagram',
          },
          {
            platform: 'facebook',
            url: 'minikadimlarkresi',
            icon: 'facebook',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '02123456701', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Minik Adımlar Kreşi — Kadıköy',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: KRES_OYUN_BUSINESS.name, subtitle: KRES_OYUN_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
