/**
 * @kepenk/templates — kargo-agir Theme Configuration
 *
 * Agir yuk ve ozel tasima
 * Plan: pro (11 page sections, 4 global sections)
 * Font: Playfair Display/Inter | Accent: #7C3AED
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const KARGO_AGIR_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#7C3AED',
  '--color-accent-hover': '#6D28D9',
  '--color-accent-active': '#7C3AED',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'Playfair Display\', sans-serif',
  '--font-body': "'DM Sans', system-ui, sans-serif",
}

// ═══ DEMO BUSINESS DATA ═══

export const KARGO_AGIR_BUSINESS = {
  name: 'TitanCargo Agir Yuk Tasimaciligi',
  ownerName: 'Erhan Toprak',
  sectorId: 'Kargo',
  slogan: 'Agir yuklerin guvencesi',
  phone: '0532 900 11 03',
  phoneClean: '905329001103',
  whatsapp: '905329001103',
  email: 'info@titancargo.com.tr',
  address: 'Fatih Mah. E-5 Yan Yol No:155, Buyukcekmece/Istanbul',
  city: 'Istanbul',
  district: 'Buyukcekmece',
  neighborhood: 'Fatih',
  coordinates: { lat: 41.02, lng: 28.58 },
  socialMedia: { instagram: 'https://instagram.com/titancargo', linkedin: 'https://linkedin.com/company/titancargo' },
  photos: [],
  foundedYear: 2003,
  experience: '21 yil',
  customerCount: '6.000+',
  rating: 4.8,
  reviewCount: 850,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '08:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '08:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '08:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '08:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '08:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '09:00',
      close: '14:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: 'Kapali',
      close: 'Kapali',
      isOpen: false,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Agir Yuk Tasimaciligi',
      price: 'Projeye Ozel',
      duration: '1-5 gun',
      description: '5 tondan 100 tona kadar agir yuk tasimaciligi.',
    },
    {
      id: 's2',
      name: 'Gabari Disi Tasima',
      price: 'Projeye Ozel',
      duration: '1-7 gun',
      description: 'Boyutlari standart olmayan buyuk parcalarin ozel izinli tasimasi.',
    },
    {
      id: 's3',
      name: 'Makine ve Ekipman Tasima',
      price: '5.000 TL',
      duration: '1-3 gun',
      description: 'Fabrika makinesi, jenerator ve agir ekipman tasimaciligi.',
    },
    {
      id: 's4',
      name: 'Konteyner Tasima',
      price: '3.000 TL',
      duration: '1 gun',
      description: 'Liman-fabrika arasi konteyner tasimaaciligi.',
    },
    {
      id: 's5',
      name: 'Insaat Malzemesi Nakliye',
      price: '2.500 TL',
      duration: '1 gun',
      description: 'Demir, cimento, beton prefabrik ve insaat malzemesi tasima.',
    },
    {
      id: 's6',
      name: 'Vinc ve Forklift Hizmeti',
      price: '3.500 TL/gun',
      duration: 'Gunluk',
      description: 'Yukleme ve bosaltma icin vinc ve forklift kiralama.',
    },
    {
      id: 's7',
      name: 'Proje Kargo',
      price: 'Projeye Ozel',
      duration: 'Projeye Gore',
      description: 'Enerji, madencilik ve altyapi projeleri icin ozel kargo planlama.',
    },
    {
      id: 's8',
      name: 'Ozel Izin ve Eskort',
      price: '2.000 TL',
      duration: '1 gun',
      description: 'Gabari disi yukler icin karayollari izni ve eskort araci temini.',
    },
    {
      id: 's9',
      name: 'Depolama ve Antrepo',
      price: '50 TL/m2/ay',
      duration: 'Aylik',
      description: 'Acik ve kapali alan depolama. Gumruklu antrepo hizmeti.',
    },
    {
      id: 's10',
      name: 'Sabitleme ve Paketleme',
      price: '1.500 TL',
      duration: '2-4 saat',
      description: 'Agir yuklerin arac uzerine guvenli sabitleme ve ozel paketleme.',
    },
    {
      id: 's11',
      name: 'Uluslararasi Agir Yuk',
      price: 'Projeye Ozel',
      duration: '3-15 gun',
      description: 'Sinir otesi agir yuk tasimaciligi. Gumruk islemleri dahil.',
    },
    {
      id: 's12',
      name: 'Rutin Filo Tasima',
      price: 'Sozlesmeye Gore',
      duration: 'Surekli',
      description: 'Fabrikalar icin duzennli hammadde ve urun tasima sozlesmesi.',
    },
    {
      id: 's13',
      name: 'Tehlikeli Madde Tasima (ADR)',
      price: 'Projeye Ozel',
      duration: '1-5 gun',
      description: 'ADR sertifikali araclarla tehlikeli madde tasimaciligi.',
    },
    {
      id: 's14',
      name: 'Lojistik Danismanlik',
      price: '5.000 TL',
      duration: '1-3 gun',
      description: 'Tasima rotasi optimizasyonu, maliyet analizi ve lojistik planlama.',
    },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const KARGO_AGIR_CONFIG = {
  id: 'kargo-agir',
  name: 'Agir',
  sectorId: 'kargo',
  plan: 'pro',
  description: 'Agir yuk ve ozel tasima',
  designPhilosophy: 'Guclu, teknik, endustriyel',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#7C3AED',
    '--color-accent-hover': '#6D28D9',
    '--color-accent-active': '#7C3AED',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'Playfair Display\', sans-serif',
    '--font-body': "'DM Sans', system-ui, sans-serif",
  },
  fonts: {
    heading: {
      family: 'Playfair Display',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'DM Sans',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'DeliveryService',
  sectorSections: [],
  performanceBudget: {
    maxJS: '250kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'TitanCargo Agir Yuk Tasimaciligi' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905329001103',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'TitanCargo Agir Yuk Tasimaciligi',
        copyright: '© 2026 TitanCargo Agir Yuk Tasimaciligi',
        contact: {
          phone: '0532 900 11 03',
          email: 'info@titancargo.com.tr',
          address: 'Fatih Mah. E-5 Yan Yol No:155, Buyukcekmece/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/titancargo',
            icon: 'instagram',
          },
          {
            platform: 'linkedin',
            url: 'https://linkedin.com/company/titancargo',
            icon: 'linkedin',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905329001103', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'TitanCargo Agir Yuk Tasimaciligi — Buyukcekmece',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: KARGO_AGIR_BUSINESS.name, subtitle: KARGO_AGIR_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
