import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const ORGANIZASYON_KONSER_BUSINESS: BusinessData = {
  name: 'Konser Organizasyon',
  ownerName: 'Kaan Konser',
  sectorId: 'organizasyon',
  slogan: 'Konser ve festival',
  phone: '0535 200 44 55',
  phoneClean: '905352004455',
  whatsapp: '905352004455',
  email: 'info@konserorg.com',
  address: 'Istinye Mah. No:20, Sariyer, Istanbul',
  city: 'Istanbul',
  district: 'Sariyer',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"09:00","close":"21:00"},{"day":"tuesday","dayTr":"Sali","open":"09:00","close":"21:00"},{"day":"wednesday","dayTr":"Carsamba","open":"09:00","close":"21:00"},{"day":"thursday","dayTr":"Persembe","open":"09:00","close":"21:00"},{"day":"friday","dayTr":"Cuma","open":"09:00","close":"21:00"},{"day":"saturday","dayTr":"Cumartesi","open":"09:00","close":"21:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/organizasyon-konser"},
  photos: [],
  services: []
}
export const ORGANIZASYON_KONSER_CONFIG: ThemeConfig = { id: 'organizasyon-konser', name: 'Festival / Konser', sectorId: 'organizasyon', plan: 'pro', isDark: true, cssVariables: { '--color-bg': '#FFFFFF', '--color-surface': '#F8FAFC', '--color-text': '#0F172A', '--color-accent': '#F97316',
    '--color-accent-light': '#2e251f',
    '--color-accent-hover': '#8f4914',
    '--color-accent-active': '#7d4012', '--color-text-on-accent': '#FFFFFF', '--color-border': '#E2E8F0', '--font-heading': "'Teko', sans-serif", '--font-body': "'Inter', sans-serif" }, fonts: { heading: { family: 'Teko', weights: [700] }, body: { family: 'DM Sans', weights: [400] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Konser Organizasyon' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Konser Organizasyon',
        copyright: '© 2026 Konser Organizasyon',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'Live Events', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true }, defaultContent: { badge: 'LIVE MUSIC', title: 'On Binlerce Kişiyle Çoşkuya Ortak Ol' } } ] }] }