import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const ORGANIK_VEGAN_BUSINESS: BusinessData = {
  name: 'Vegan Market',
  ownerName: 'Zeynep Vegan',
  sectorId: 'organik',
  slogan: 'Vegan ve dogal urunler',
  phone: '0535 400 44 55',
  phoneClean: '905354004455',
  whatsapp: '905354004455',
  email: 'info@veganmarket.com',
  address: 'Atakoy Mah. No:20, Bakirkoy, Istanbul',
  city: 'Istanbul',
  district: 'Bakirkoy',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"07:00","close":"20:00"},{"day":"tuesday","dayTr":"Sali","open":"07:00","close":"20:00"},{"day":"wednesday","dayTr":"Carsamba","open":"07:00","close":"20:00"},{"day":"thursday","dayTr":"Persembe","open":"07:00","close":"20:00"},{"day":"friday","dayTr":"Cuma","open":"07:00","close":"20:00"},{"day":"saturday","dayTr":"Cumartesi","open":"07:00","close":"20:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/organik-vegan"},
  photos: [],
  services: []
}
export const ORGANIK_VEGAN_CONFIG: ThemeConfig = { id: 'organik-vegan', name: 'Vegan Ürünler', sectorId: 'organik', plan: 'pro', isDark: false, cssVariables: { '--color-bg': '#FDFBF7', '--color-surface': '#F4F1EA', '--color-text': '#3D3831', '--color-accent': '#059669',
    '--color-accent-light': '#e8fbfc',
    '--color-accent-hover': '#14898f',
    '--color-accent-active': '#12787d', '--color-text-on-accent': '#FFFFFF', '--color-border': '#DED8CE', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif" }, fonts: { heading: { family: 'Montserrat', weights: [700] }, body: { family: 'Inter', weights: [400] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Vegan Market' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Vegan Market',
        copyright: '© 2026 Vegan Market',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'Vegan Çözümler', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'xl', containerWidth: 'xl', visible: true }, defaultContent: { badge: '100% VEGAN', title: 'Doğaya Saygılı Sağlıklı Yaşam' } } ] }] }