/**
 * @kepenk/templates — doktor-medikal Theme Configuration
 *
 * Dahiliye uzmani, guvenilir klinik
 * Plan: starter (6 page sections, 4 global sections)
 * Font: Plus Jakarta Sans/Inter | Accent: #0369A1
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const DOKTOR_MEDIKAL_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#0369A1',
  '--color-accent-hover': '#0369A1',
  '--color-accent-active': '#0369A1',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'Plus Jakarta Sans\', sans-serif',
  '--font-body': "'DM Sans', system-ui, sans-serif",
}

// ═══ DEMO BUSINESS DATA ═══

export const DOKTOR_MEDIKAL_BUSINESS = {
  name: 'MediPark Dahiliye Klinigi',
  ownerName: 'Doc. Dr. Ayse Celik',
  sectorId: 'Doktor',
  slogan: 'Bilimsel tibbi, insani sicaklikla bulusturuyoruz',
  phone: '0212 567 89 01',
  phoneClean: '902125678901',
  whatsapp: '905425678901',
  email: 'randevu@mediparkdahiliye.com',
  address: 'Caglayan Mah. Halaskargazi Cad. No:220/3, Sisli/Istanbul',
  city: 'Istanbul',
  district: 'Sisli',
  neighborhood: 'Caglayan',
  coordinates: { lat: 41.0612, lng: 28.988 },
  socialMedia: { instagram: 'https://instagram.com/mediparkdahiliye', youtube: 'https://youtube.com/@drayseclik' },
  photos: [],
  foundedYear: 2015,
  experience: '22 yil',
  customerCount: '40.000+',
  rating: 4.8,
  reviewCount: 1560,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '08:30',
      close: '18:30',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '08:30',
      close: '18:30',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '08:30',
      close: '18:30',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '08:30',
      close: '18:30',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '08:30',
      close: '17:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '09:00',
      close: '14:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: null,
      close: null,
      isOpen: false,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Dahiliye Muayenesi',
      price: '800 TL',
      duration: '30 dk',
      description: 'Kapsamli dahiliye muayenesi, hikaye alma, fizik muayene ve tedavi plani.',
    },
    {
      id: 's2',
      name: 'Executive Check-Up',
      price: '4.500 TL',
      duration: '120 dk',
      description: '60+ parametre kan tahlili, EKG, ultrason, akciger grafisi, goz dibi muayenesi dahil.',
    },
    {
      id: 's3',
      name: 'Tiroid Takibi',
      price: '1.200 TL',
      duration: '30 dk',
      description: 'Tiroid fonksiyon testleri, ultrason ve muayene. Ilaç doz ayarlamasi.',
    },
    {
      id: 's4',
      name: 'Diyabet Yonetimi',
      price: '1.000 TL',
      duration: '45 dk',
      description: 'HbA1c, aclik sekeri, insülin direnci testleri ve diyet danismanligi.',
    },
    {
      id: 's5',
      name: 'Hipertansiyon Takibi',
      price: '600 TL',
      duration: '20 dk',
      description: '24 saatlik tansiyon holter, ilac ayarlamasi ve yasam tarzı enerileri.',
    },
    {
      id: 's6',
      name: 'Gastroenteroloji Konsultasyonu',
      price: '1.000 TL',
      duration: '30 dk',
      description: 'Mide-barsak sistemi sikayetleri, ulsdr, reflü tedavisi, diyet program.',
    },
  ],
  team: [
    {
      id: 't1',
      name: 'Doc. Dr. Ayse Celik',
      role: 'Ic Hastaliklari Uzmani',
      experience: '22 yil',
    },
    {
      id: 't2',
      name: 'Dr. Burak Ozdemir',
      role: 'Dahiliye Uzmani',
      experience: '10 yil',
    },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const DOKTOR_MEDIKAL_CONFIG = {
  id: 'doktor-medikal',
  name: 'Medikal',
  sectorId: 'doktor',
  plan: 'starter',
  description: 'Dahiliye uzmani, guvenilir klinik',
  designPhilosophy: 'Profesyonel, guven veren, medikal estetik',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#0369A1',
    '--color-accent-hover': '#0369A1',
    '--color-accent-active': '#0369A1',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'Plus Jakarta Sans\', sans-serif',
    '--font-body': "'DM Sans', system-ui, sans-serif",
  },
  fonts: {
    heading: {
      family: 'Plus Jakarta Sans',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'DM Sans',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'MedicalBusiness',
  sectorSections: ['doctor_profile', 'insurance_logos', 'booking'],
  performanceBudget: {
    maxJS: '120kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-basic',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'MediPark Dahiliye Klinigi' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905425678901',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'MediPark Dahiliye Klinigi',
        copyright: '© 2026 MediPark Dahiliye Klinigi',
        contact: {
          phone: '0212 567 89 01',
          email: 'randevu@mediparkdahiliye.com',
          address: 'Caglayan Mah. Halaskargazi Cad. No:220/3, Sisli/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/mediparkdahiliye',
            icon: 'instagram',
          },
          {
            platform: 'youtube',
            url: 'https://youtube.com/@drayseclik',
            icon: 'youtube',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905425678901', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'MediPark Dahiliye Klinigi — Sisli',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: DOKTOR_MEDIKAL_BUSINESS.name, subtitle: DOKTOR_MEDIKAL_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
