import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const CAMBALKON_ISICAMLI_CSS: Record<string, string> = { '--color-bg': '#FFFBEB', '--color-surface': '#FEF3C7', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#FDE68A', '--color-text': '#1C1800', '--color-text-secondary': '#5C5019', '--color-text-muted': '#9E9055', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#D97706', '--color-accent-hover': '#B45309', '--color-accent-light': '#FFFBEB', '--color-border': '#FCD34D', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const CAMBALKON_ISICAMLI_BUSINESS: BusinessData = { name: 'Thermo Glass', ownerName: 'Selim Isi', sector: 'cambalkon', slogan: 'Isicamli cambalkon', phone: '0534 300 30 40', phoneClean: '905343003040', whatsapp: '905343003040', email: 'info@cambalkonisicamli.com.tr', address: 'Beylikduzu, Istanbul', city: 'Istanbul', district: 'Beylikduzu', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '18:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '18:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '18:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '18:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '18:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '14:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/cambalkonisicamli' }, photos: [], services: [{ id: 's1', name: 'Isicamli', icon: '🏗️' }], team: [{ id: 't1', name: 'Selim Isi', role: 'Usta', experience: '15 yil' }], experience: '15 yil', rating: 4.8, reviewCount: 500, foundedYear: 2010 }
export const CAMBALKON_ISICAMLI_CONFIG: ThemeConfig = { id: 'cambalkon-isicamli', name: 'Isicamli', sectorId: 'cambalkon', plan: 'growth', description: 'Isicamli cambalkon. Beylikduzu.', designPhilosophy: 'Isicamli theme.', isDark: false, cssVariables: CAMBALKON_ISICAMLI_CSS, fonts: { heading: { family: 'Playfair Display', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'HomeAndConstructionBusiness', sectorSections: [], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'fadeIn' }, defaultContent: { logo: { type: 'text', text: 'Thermo Glass' }, menuItems: [{ label: 'Hizmetler', href: '#hizmetler' },{ label: 'Iletisim', href: '#iletisim' }], cta: { text: 'Iletisim', href: '#iletisim', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'fadeIn' }, defaultContent: { businessName: 'Thermo Glass', copyright: '© 2024', contact: { phone: '0534 300 30 40', address: 'Beylikduzu, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/cambalkonisicamli', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1000, removable: false, animation: 'fadeIn' }, defaultContent: { phone: '905343003040', message: 'Merhaba, bilgi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 1001, removable: false, animation: 'fadeIn' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Thermo Glass — Beylikduzu", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'Beylikduzu', title: "Thermo Glass", subtitle: "Isicamli cambalkon", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'fadeIn' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'cambalkon_services', order: 3, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'simple_form', order: 4, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905343003040" }, editableFields: [] }
    ]
  }]
}
