import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const CICEKCI_ONLINE_CSS: Record<string, string> = { '--color-bg': '#ECFDF5', '--color-surface': '#D1FAE5', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#A7F3D0', '--color-text': '#052E16', '--color-text-secondary': '#166534', '--color-text-muted': '#6B7280', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#059669', '--color-accent-hover': '#047857', '--color-accent-light': '#ECFDF5', '--color-border': '#6EE7B7', '--font-heading': "'Nunito', sans-serif", '--font-body': "'Nunito', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const CICEKCI_ONLINE_BUSINESS: BusinessData = { name: 'ÇiçekSepeti Plus', ownerName: 'Ali Bloom', sector: 'cicekci', slogan: 'Online cicekci', phone: '0532 111 22 33', phoneClean: '905321112233', whatsapp: '905321112233', email: 'info@cicekcionline.com.tr', address: 'Kadıköy, Istanbul', city: 'Istanbul', district: 'Kadıköy', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '20:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '20:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '20:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '20:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '20:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '19:00' },{ day: 'sunday', dayTr: 'Pazar', open: '10:00', close: '18:00' }], socialMedia: { instagram: 'https://instagram.com/cicekcionline' }, photos: [], services: [{ id: 's1', name: 'Buket', icon: '💐' },{ id: 's2', name: 'Aranjman', icon: '🌸' }], team: [{ id: 't1', name: 'Ali Bloom', role: 'Cicekci', experience: '10 yil' }], experience: '10 yil', rating: 4.9, reviewCount: 400, foundedYear: 2014 }
export const CICEKCI_ONLINE_CONFIG: ThemeConfig = { id: 'cicekci-online', name: 'Online', sectorId: 'cicekci', plan: 'starter', description: 'Online cicekci. Kadıköy.', designPhilosophy: 'Online theme.', isDark: false, cssVariables: CICEKCI_ONLINE_CSS, fonts: { heading: { family: 'Montserrat', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Nunito', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'Florist', sectorSections: ['florist_products', 'florist_occasions', 'florist_delivery', 'florist_order'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'ÇiçekSepeti Plus 💐' }, menuItems: [{ label: 'Cicekler', href: '#cicekler' },{ label: 'Siparis', href: '#siparis' }], cta: { text: 'Siparis', href: '#siparis', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'ÇiçekSepeti Plus', copyright: '© 2024', contact: { phone: '0532 111 22 33', address: 'Kadıköy, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/cicekcionline', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905321112233', message: 'Merhaba, cicek siparisi vermek istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "ÇiçekSepeti Plus — Kadıköy", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Kadıköy', title: "ÇiçekSepeti Plus", subtitle: "Online cicekci", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'cicekci_services', order: 2, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'simple_form', order: 3, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 3, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905321112233" }, editableFields: [] }
    ]
  }]
}
