import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const CICEKCI_DUGUN_CSS: Record<string, string> = { '--color-bg': '#FFFBEB', '--color-surface': '#FEF3C7', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#FDE68A', '--color-text': '#1C1800', '--color-text-secondary': '#5C5019', '--color-text-muted': '#9E9055', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#D97706', '--color-accent-hover': '#B45309', '--color-accent-light': '#FFFBEB', '--color-border': '#FCD34D', '--font-heading': "'Nunito', sans-serif", '--font-body': "'Nunito', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const CICEKCI_DUGUN_BUSINESS: BusinessData = { name: 'Amore Flowers', ownerName: 'Zeynep Gül', sector: 'cicekci', slogan: 'Düğün cicekci', phone: '0534 333 44 55', phoneClean: '905343334455', whatsapp: '905343334455', email: 'info@cicekcidugun.com.tr', address: 'Nişantaşı, Istanbul', city: 'Istanbul', district: 'Nişantaşı', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '20:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '20:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '20:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '20:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '20:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '19:00' },{ day: 'sunday', dayTr: 'Pazar', open: '10:00', close: '18:00' }], socialMedia: { instagram: 'https://instagram.com/cicekcidugun' }, photos: [], services: [{ id: 's1', name: 'Buket', icon: '💐' },{ id: 's2', name: 'Aranjman', icon: '🌸' }], team: [{ id: 't1', name: 'Zeynep Gül', role: 'Cicekci', experience: '10 yil' }], experience: '10 yil', rating: 4.9, reviewCount: 400, foundedYear: 2014 }
export const CICEKCI_DUGUN_CONFIG: ThemeConfig = { id: 'cicekci-dugun', name: 'Düğün', sectorId: 'cicekci', plan: 'growth', description: 'Düğün cicekci. Nişantaşı.', designPhilosophy: 'Düğün theme.', isDark: false, cssVariables: CICEKCI_DUGUN_CSS, fonts: { heading: { family: 'Raleway', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Nunito', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'Florist', sectorSections: ['florist_products', 'florist_occasions', 'florist_delivery', 'florist_order'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Amore Flowers 💐' }, menuItems: [{ label: 'Cicekler', href: '#cicekler' },{ label: 'Siparis', href: '#siparis' }], cta: { text: 'Siparis', href: '#siparis', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Amore Flowers', copyright: '© 2024', contact: { phone: '0534 333 44 55', address: 'Nişantaşı, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/cicekcidugun', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905343334455', message: 'Merhaba, cicek siparisi vermek istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Amore Flowers — Nişantaşı", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Nişantaşı', title: "Amore Flowers", subtitle: "Düğün cicekci", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'cicekci_services', order: 3, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 3, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'simple_form', order: 4, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 4, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905343334455" }, editableFields: [] }
    ]
  }]
}
