import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const CICEKCI_MAHALLE_CSS: Record<string, string> = { '--color-bg': '#FFF5F7', '--color-surface': '#FFE4ED', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#FBBFD0', '--color-text': '#2E0316', '--color-text-secondary': '#6E1443', '--color-text-muted': '#B06585', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#DB2777', '--color-accent-hover': '#BE185D', '--color-accent-light': '#FDF2F8', '--color-border': '#F9A8D4', '--font-heading': "'Nunito', sans-serif", '--font-body': "'Nunito', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const CICEKCI_MAHALLE_BUSINESS: BusinessData = { name: 'Gül Bahçesi', ownerName: 'Fatma Çiçek', sector: 'cicekci', slogan: 'Mahalle cicekci', phone: '0533 600 70 80', phoneClean: '905336007080', whatsapp: '905336007080', email: 'info@cicekcimahalle.com.tr', address: 'Fatih, Istanbul', city: 'Istanbul', district: 'Fatih', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '20:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '20:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '20:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '20:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '20:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '19:00' },{ day: 'sunday', dayTr: 'Pazar', open: '10:00', close: '18:00' }], socialMedia: { instagram: 'https://instagram.com/cicekcimahalle' }, photos: [], services: [{ id: 's1', name: 'Buket', icon: '💐' },{ id: 's2', name: 'Aranjman', icon: '🌸' }], team: [{ id: 't1', name: 'Fatma Çiçek', role: 'Cicekci', experience: '10 yil' }], experience: '10 yil', rating: 4.9, reviewCount: 400, foundedYear: 2014 }
export const CICEKCI_MAHALLE_CONFIG: ThemeConfig = { id: 'cicekci-mahalle', name: 'Mahalle', sectorId: 'cicekci', plan: 'free', description: 'Mahalle cicekci. Fatih.', designPhilosophy: 'Mahalle theme.', isDark: false, cssVariables: CICEKCI_MAHALLE_CSS, fonts: { heading: { family: 'Lora', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Nunito', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'Florist', sectorSections: ['florist_products', 'florist_occasions', 'florist_delivery', 'florist_order'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Gül Bahçesi 💐' }, menuItems: [{ label: 'Cicekler', href: '#cicekler' },{ label: 'Siparis', href: '#siparis' }], cta: { text: 'Siparis', href: '#siparis', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Gül Bahçesi', copyright: '© 2024', contact: { phone: '0533 600 70 80', address: 'Fatih, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/cicekcimahalle', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905336007080', message: 'Merhaba, cicek siparisi vermek istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Gül Bahçesi — Fatih", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'fullscreen_overlay', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Fatih', title: "Gül Bahçesi", subtitle: "Mahalle cicekci", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'istatistik', type: 'stats', variant: 'animated_row', order: 3, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'xl', visible: true, order: 3, removable: true, animation: 'fadeUp' }, defaultContent: { stats: [{value: '10+', label: 'Yıl'}, {value: '100+', label: 'Müşteri'}] }, editableFields: [] },
{ id: 'galeri', type: 'gallery', variant: 'masonry', order: 4, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 4, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'GALERİ', title: 'Çalışmalarımız', items: [{ id: 'g1', url: '/placeholder.jpg' }] }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'cicekci_services', order: 5, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 5, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'detailed_form', order: 6, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 6, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905336007080" }, editableFields: [] }
    ]
  }]
}
