import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const ELEKTRIKCI_GUNES_CSS: Record<string, string> = { '--color-bg': '#ECFDF5', '--color-surface': '#D1FAE5', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#A7F3D0', '--color-text': '#052E16', '--color-text-secondary': '#166534', '--color-text-muted': '#6B7280', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#059669', '--color-accent-hover': '#047857', '--color-accent-light': '#ECFDF5', '--color-border': '#6EE7B7', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const ELEKTRIKCI_GUNES_BUSINESS: BusinessData = { name: 'Solar Enerji', ownerName: 'Selim Panel', sector: 'elektrikci', slogan: 'Gunes elektrikci', phone: '0534 300 30 40', phoneClean: '905343003040', whatsapp: '905343003040', email: 'info@elektrikcigunes.com.tr', address: 'Atasehir, Istanbul', city: 'Istanbul', district: 'Atasehir', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '18:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '18:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '18:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '18:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '18:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '14:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/elektrikcigunes' }, photos: [], services: [{ id: 's1', name: 'Gunes', icon: '🔧' }], team: [{ id: 't1', name: 'Selim Panel', role: 'Usta', experience: '15 yil' }], experience: '15 yil', rating: 4.8, reviewCount: 600, foundedYear: 2008 }
export const ELEKTRIKCI_GUNES_CONFIG: ThemeConfig = { id: 'elektrikci-gunes', name: 'Gunes', sectorId: 'elektrikci', plan: 'growth', description: 'Gunes elektrikci. Atasehir.', designPhilosophy: 'Gunes theme.', isDark: false, cssVariables: ELEKTRIKCI_GUNES_CSS, fonts: { heading: { family: 'Montserrat', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'Electrician', sectorSections: [], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Solar Enerji' }, menuItems: [{ label: 'Hizmetler', href: '#hizmetler' },{ label: 'Iletisim', href: '#iletisim' }], cta: { text: 'Iletisim', href: '#iletisim', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Solar Enerji', copyright: '© 2024', contact: { phone: '0534 300 30 40', address: 'Atasehir, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/elektrikcigunes', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905343003040', message: 'Merhaba, bilgi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Solar Enerji — Atasehir", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Atasehir', title: "Solar Enerji", subtitle: "Gunes elektrikci", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'istatistik', type: 'stats', variant: 'animated_row', order: 3, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'xl', visible: true, order: 3, removable: true, animation: 'fadeUp' }, defaultContent: { stats: [{value: '10+', label: 'Yıl'}, {value: '100+', label: 'Müşteri'}] }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'elektrikci_services', order: 4, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 4, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'galeri', type: 'gallery', variant: 'masonry', order: 5, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 5, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'GALERİ', title: 'Çalışmalarımız', items: [{ id: 'g1', url: '/placeholder.jpg' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'detailed_form', order: 6, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 6, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905343003040" }, editableFields: [] }
    ]
  }]
}
