import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const KAHVECI_3NESIL_CSS: Record<string, string> = { '--color-bg': '#ECFDF5', '--color-surface': '#D1FAE5', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#A7F3D0', '--color-text': '#052E16', '--color-text-secondary': '#166534', '--color-text-muted': '#6B7280', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#059669', '--color-accent-hover': '#047857', '--color-accent-light': '#ECFDF5', '--color-border': '#6EE7B7', '--font-heading': "'Nunito', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const KAHVECI_3NESIL_BUSINESS: BusinessData = { name: 'Brew Lab', ownerName: 'Can Barista', sector: 'kahveci', slogan: '3. Nesil kahveci', phone: '0532 200 30 40', phoneClean: '905322003040', whatsapp: '905322003040', email: 'info@kahveci3nesil.com.tr', address: 'Kadıköy, Istanbul', city: 'Istanbul', district: 'Kadıköy', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '07:30', close: '22:00' },{ day: 'tuesday', dayTr: 'Sali', open: '07:30', close: '22:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '07:30', close: '22:00' },{ day: 'thursday', dayTr: 'Persembe', open: '07:30', close: '22:00' },{ day: 'friday', dayTr: 'Cuma', open: '07:30', close: '23:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '08:00', close: '23:00' },{ day: 'sunday', dayTr: 'Pazar', open: '09:00', close: '22:00' }], socialMedia: { instagram: 'https://instagram.com/kahveci3nesil' }, photos: [], services: [{ id: 's1', name: 'Kahve', icon: '☕' },{ id: 's2', name: 'Yiyecek', icon: '🥐' }], team: [{ id: 't1', name: 'Can Barista', role: 'Barista', experience: '8 yil' }], experience: '8 yil', rating: 4.8, reviewCount: 500, foundedYear: 2016 }
export const KAHVECI_3NESIL_CONFIG: ThemeConfig = { id: 'kahveci-3nesil', name: '3. Nesil', sectorId: 'kahveci', plan: 'starter', description: '3. Nesil kahveci. Kadıköy.', designPhilosophy: '3. Nesil theme.', isDark: false, cssVariables: KAHVECI_3NESIL_CSS, fonts: { heading: { family: 'Playfair Display', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'CafeOrCoffeeShop', sectorSections: ['coffee_menu_grid', 'coffee_beans', 'coffee_atmosphere', 'coffee_order'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Brew Lab ☕' }, menuItems: [{ label: 'Menu', href: '#menu' },{ label: 'Siparis', href: '#siparis' }], cta: { text: 'Siparis', href: '#siparis', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Brew Lab', copyright: '© 2024', contact: { phone: '0532 200 30 40', address: 'Kadıköy, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/kahveci3nesil', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905322003040', message: 'Merhaba, siparis vermek istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Brew Lab — Kadıköy", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Kadıköy', title: "Brew Lab", subtitle: "3. Nesil kahveci", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'kahveci_services', order: 3, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 3, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'simple_form', order: 4, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 4, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905322003040" }, editableFields: [] }
    ]
  }]
}
