import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const KAHVECI_BRUNCH_CSS: Record<string, string> = { '--color-bg': '#FFFBEB', '--color-surface': '#FEF3C7', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#FDE68A', '--color-text': '#1C1800', '--color-text-secondary': '#5C5019', '--color-text-muted': '#9E9055', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#D97706', '--color-accent-hover': '#B45309', '--color-accent-light': '#FFFBEB', '--color-border': '#FCD34D', '--font-heading': "'Nunito', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const KAHVECI_BRUNCH_BUSINESS: BusinessData = { name: 'Morning Glory', ownerName: 'Selin Sabah', sector: 'kahveci', slogan: 'Brunch kahveci', phone: '0535 400 50 60', phoneClean: '905354005060', whatsapp: '905354005060', email: 'info@kahvecibrunch.com.tr', address: 'Cihangir, Istanbul', city: 'Istanbul', district: 'Cihangir', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '07:30', close: '22:00' },{ day: 'tuesday', dayTr: 'Sali', open: '07:30', close: '22:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '07:30', close: '22:00' },{ day: 'thursday', dayTr: 'Persembe', open: '07:30', close: '22:00' },{ day: 'friday', dayTr: 'Cuma', open: '07:30', close: '23:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '08:00', close: '23:00' },{ day: 'sunday', dayTr: 'Pazar', open: '09:00', close: '22:00' }], socialMedia: { instagram: 'https://instagram.com/kahvecibrunch' }, photos: [], services: [{ id: 's1', name: 'Kahve', icon: '☕' },{ id: 's2', name: 'Yiyecek', icon: '🥐' }], team: [{ id: 't1', name: 'Selin Sabah', role: 'Barista', experience: '8 yil' }], experience: '8 yil', rating: 4.8, reviewCount: 500, foundedYear: 2016 }
export const KAHVECI_BRUNCH_CONFIG: ThemeConfig = { id: 'kahveci-brunch', name: 'Brunch', sectorId: 'kahveci', plan: 'pro', description: 'Brunch kahveci. Cihangir.', designPhilosophy: 'Brunch theme.', isDark: false, cssVariables: KAHVECI_BRUNCH_CSS, fonts: { heading: { family: 'Montserrat', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'CafeOrCoffeeShop', sectorSections: ['coffee_menu_grid', 'coffee_beans', 'coffee_atmosphere', 'coffee_order'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Morning Glory ☕' }, menuItems: [{ label: 'Menu', href: '#menu' },{ label: 'Siparis', href: '#siparis' }], cta: { text: 'Siparis', href: '#siparis', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Morning Glory', copyright: '© 2024', contact: { phone: '0535 400 50 60', address: 'Cihangir, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/kahvecibrunch', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905354005060', message: 'Merhaba, siparis vermek istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Morning Glory — Cihangir", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'fullscreen_overlay', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Cihangir', title: "Morning Glory", subtitle: "Brunch kahveci", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'istatistik', type: 'stats', variant: 'animated_row', order: 3, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'xl', visible: true, order: 3, removable: true, animation: 'fadeUp' }, defaultContent: { stats: [{value: '10+', label: 'Yıl'}, {value: '100+', label: 'Müşteri'}] }, editableFields: [] },
{ id: 'galeri', type: 'gallery', variant: 'masonry', order: 4, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 4, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'GALERİ', title: 'Çalışmalarımız', items: [{ id: 'g1', url: '/placeholder.jpg' }] }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'kahveci_services', order: 5, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 5, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'cta', type: 'cta', variant: 'simple_banner', order: 6, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'full', visible: true, order: 6, removable: true, animation: 'fadeUp' }, defaultContent: { title: 'Hemen Başlayın', cta: { text: 'Bize Ulaşın' } }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'detailed_form', order: 7, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 7, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905354005060" }, editableFields: [] }
    ]
  }]
}
