import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const KAHVECI_KAVURMA_CSS: Record<string, string> = { '--color-bg': '#1C1917', '--color-surface': '#292524', '--color-surface-elevated': '#44403C', '--color-surface-muted': '#1C1917', '--color-text': '#FAFAF9', '--color-text-secondary': '#D6D3D1', '--color-text-muted': '#A8A29E', '--color-text-on-accent': '#1C1917', '--color-accent': '#EA580C', '--color-accent-hover': '#C2410C', '--color-accent-light': 'rgba(234,88,12,0.12)', '--color-border': 'rgba(234,88,12,0.18)', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const KAHVECI_KAVURMA_BUSINESS: BusinessData = { name: 'Roast House', ownerName: 'Emre Kavur', sector: 'kahveci', slogan: 'Kavurma kahveci', phone: '0534 300 40 50', phoneClean: '905343004050', whatsapp: '905343004050', email: 'info@kahvecikavurma.com.tr', address: 'Beşiktaş, Istanbul', city: 'Istanbul', district: 'Beşiktaş', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '07:30', close: '22:00' },{ day: 'tuesday', dayTr: 'Sali', open: '07:30', close: '22:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '07:30', close: '22:00' },{ day: 'thursday', dayTr: 'Persembe', open: '07:30', close: '22:00' },{ day: 'friday', dayTr: 'Cuma', open: '07:30', close: '23:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '08:00', close: '23:00' },{ day: 'sunday', dayTr: 'Pazar', open: '09:00', close: '22:00' }], socialMedia: { instagram: 'https://instagram.com/kahvecikavurma' }, photos: [], services: [{ id: 's1', name: 'Kahve', icon: '☕' },{ id: 's2', name: 'Yiyecek', icon: '🥐' }], team: [{ id: 't1', name: 'Emre Kavur', role: 'Barista', experience: '8 yil' }], experience: '8 yil', rating: 4.8, reviewCount: 500, foundedYear: 2016 }
export const KAHVECI_KAVURMA_CONFIG: ThemeConfig = { id: 'kahveci-kavurma', name: 'Kavurma', sectorId: 'kahveci', plan: 'growth', description: 'Kavurma kahveci. Beşiktaş.', designPhilosophy: 'Kavurma theme.', isDark: true, cssVariables: KAHVECI_KAVURMA_CSS, fonts: { heading: { family: 'Syne', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'CafeOrCoffeeShop', sectorSections: ['coffee_menu_grid', 'coffee_beans', 'coffee_atmosphere', 'coffee_order'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Roast House ☕' }, menuItems: [{ label: 'Menu', href: '#menu' },{ label: 'Siparis', href: '#siparis' }], cta: { text: 'Siparis', href: '#siparis', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Roast House', copyright: '© 2024', contact: { phone: '0534 300 40 50', address: 'Beşiktaş, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/kahvecikavurma', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905343004050', message: 'Merhaba, siparis vermek istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Roast House — Beşiktaş", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'fullscreen_overlay', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Beşiktaş', title: "Roast House", subtitle: "Kavurma kahveci", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'istatistik', type: 'stats', variant: 'animated_row', order: 3, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'xl', visible: true, order: 3, removable: true, animation: 'fadeUp' }, defaultContent: { stats: [{value: '10+', label: 'Yıl'}, {value: '100+', label: 'Müşteri'}] }, editableFields: [] },
{ id: 'galeri', type: 'gallery', variant: 'masonry', order: 4, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 4, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'GALERİ', title: 'Çalışmalarımız', items: [{ id: 'g1', url: '/placeholder.jpg' }] }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'kahveci_services', order: 5, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 5, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'detailed_form', order: 6, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 6, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905343004050" }, editableFields: [] }
    ]
  }]
}
