import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const KAHVECI_TURK_CSS: Record<string, string> = { '--color-bg': '#F5F0EB', '--color-surface': '#E8DFD4', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#D4C5B2', '--color-text': '#1C1408', '--color-text-secondary': '#5C4B32', '--color-text-muted': '#9E8855', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#78350F', '--color-accent-hover': '#5C2D0E', '--color-accent-light': '#FFFBEB', '--color-border': '#D6D3D1', '--font-heading': "'Nunito', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const KAHVECI_TURK_BUSINESS: BusinessData = { name: 'Türk Kahvesi Evi', ownerName: 'Ahmet Kahveci', sector: 'kahveci', slogan: 'Türk kahveci', phone: '0533 100 20 30', phoneClean: '905331002030', whatsapp: '905331002030', email: 'info@kahveciturk.com.tr', address: 'Fatih, Istanbul', city: 'Istanbul', district: 'Fatih', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '07:30', close: '22:00' },{ day: 'tuesday', dayTr: 'Sali', open: '07:30', close: '22:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '07:30', close: '22:00' },{ day: 'thursday', dayTr: 'Persembe', open: '07:30', close: '22:00' },{ day: 'friday', dayTr: 'Cuma', open: '07:30', close: '23:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '08:00', close: '23:00' },{ day: 'sunday', dayTr: 'Pazar', open: '09:00', close: '22:00' }], socialMedia: { instagram: 'https://instagram.com/kahveciturk' }, photos: [], services: [{ id: 's1', name: 'Kahve', icon: '☕' },{ id: 's2', name: 'Yiyecek', icon: '🥐' }], team: [{ id: 't1', name: 'Ahmet Kahveci', role: 'Barista', experience: '8 yil' }], experience: '8 yil', rating: 4.8, reviewCount: 500, foundedYear: 2016 }
export const KAHVECI_TURK_CONFIG: ThemeConfig = { id: 'kahveci-turk', name: 'Türk', sectorId: 'kahveci', plan: 'free', description: 'Türk kahveci. Fatih.', designPhilosophy: 'Türk theme.', isDark: false, cssVariables: KAHVECI_TURK_CSS, fonts: { heading: { family: 'Bodoni Moda', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'CafeOrCoffeeShop', sectorSections: ['coffee_menu_grid', 'coffee_beans', 'coffee_atmosphere', 'coffee_order'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Türk Kahvesi Evi ☕' }, menuItems: [{ label: 'Menu', href: '#menu' },{ label: 'Siparis', href: '#siparis' }], cta: { text: 'Siparis', href: '#siparis', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Türk Kahvesi Evi', copyright: '© 2024', contact: { phone: '0533 100 20 30', address: 'Fatih, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/kahveciturk', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905331002030', message: 'Merhaba, siparis vermek istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Türk Kahvesi Evi — Fatih", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Fatih', title: "Türk Kahvesi Evi", subtitle: "Türk kahveci", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'kahveci_services', order: 2, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'simple_form', order: 3, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 3, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905331002030" }, editableFields: [] }
    ]
  }]
}
