import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const KRES_OYUN_CSS: Record<string, string> = { '--color-bg': '#FFF5F7', '--color-surface': '#FFE4ED', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#FBBFD0', '--color-text': '#2E0316', '--color-text-secondary': '#6E1443', '--color-text-muted': '#B06585', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#DB2777', '--color-accent-hover': '#BE185D', '--color-accent-light': '#FDF2F8', '--color-border': '#F9A8D4', '--font-heading': "'Nunito', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const KRES_OYUN_BUSINESS: BusinessData = { name: 'Minik Eller', ownerName: 'Ayse Ogretmen', sector: 'kres', slogan: 'Oyun kres', phone: '0533 100 10 20', phoneClean: '905331001020', whatsapp: '905331001020', email: 'info@kresoyun.com.tr', address: 'Kadikoy, Istanbul', city: 'Istanbul', district: 'Kadikoy', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '18:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '18:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '18:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '18:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '18:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '14:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/kresoyun' }, photos: [], services: [{ id: 's1', name: 'Oyun', icon: '🏢' }], team: [{ id: 't1', name: 'Ayse Ogretmen', role: 'Yonetici', experience: '10 yil' }], experience: '10 yil', rating: 4.9, reviewCount: 400, foundedYear: 2014 }
export const KRES_OYUN_CONFIG: ThemeConfig = { id: 'kres-oyun', name: 'Oyun', sectorId: 'kres', plan: 'free', description: 'Oyun kres. Kadikoy.', designPhilosophy: 'Oyun theme.', isDark: false, cssVariables: KRES_OYUN_CSS, fonts: { heading: { family: 'Bebas Neue', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'ChildCare', sectorSections: ['kinder_programs', 'kinder_age_groups', 'kinder_facilities', 'kinder_enroll'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Minik Eller' }, menuItems: [{ label: 'Hizmetler', href: '#hizmetler' },{ label: 'Iletisim', href: '#iletisim' }], cta: { text: 'Iletisim', href: '#iletisim', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Minik Eller', copyright: '© 2024', contact: { phone: '0533 100 10 20', address: 'Kadikoy, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/kresoyun', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905331001020', message: 'Merhaba, bilgi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Minik Eller — Kadikoy", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Kadikoy', title: "Minik Eller", subtitle: "Oyun kres", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'kres_services', order: 2, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'simple_form', order: 3, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 3, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905331001020" }, editableFields: [] }
    ]
  }]
}
