import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const KUYUMCU_GUMUS_CSS: Record<string, string> = { '--color-bg': '#EFF6FF', '--color-surface': '#DBEAFE', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#BFDBFE', '--color-text': '#0C1B2A', '--color-text-secondary': '#1E3A5F', '--color-text-muted': '#6B7280', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--color-accent-light': '#EFF6FF', '--color-border': '#93C5FD', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const KUYUMCU_GUMUS_BUSINESS: BusinessData = { name: 'Silver Line', ownerName: 'Selim Gumus', sector: 'kuyumcu', slogan: 'Gumus kuyumcu', phone: '0534 700 70 80', phoneClean: '905347007080', whatsapp: '905347007080', email: 'info@kuyumcugumus.com.tr', address: 'Beyoglu, Istanbul', city: 'Istanbul', district: 'Beyoglu', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '18:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '18:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '18:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '18:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '18:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '14:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/kuyumcugumus' }, photos: [], services: [{ id: 's1', name: 'Gumus', icon: '💎' }], team: [{ id: 't1', name: 'Selim Gumus', role: 'Yonetici', experience: '12 yil' }], experience: '12 yil', rating: 4.9, reviewCount: 500, foundedYear: 2012 }
export const KUYUMCU_GUMUS_CONFIG: ThemeConfig = { id: 'kuyumcu-gumus', name: 'Gumus', sectorId: 'kuyumcu', plan: 'growth', description: 'Gumus kuyumcu. Beyoglu.', designPhilosophy: 'Gumus theme.', isDark: false, cssVariables: KUYUMCU_GUMUS_CSS, fonts: { heading: { family: 'Oswald', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'JewelryStore', sectorSections: [], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'fadeIn' }, defaultContent: { logo: { type: 'text', text: 'Silver Line' }, menuItems: [{ label: 'Hizmetler', href: '#hizmetler' },{ label: 'Iletisim', href: '#iletisim' }], cta: { text: 'Iletisim', href: '#iletisim', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'fadeIn' }, defaultContent: { businessName: 'Silver Line', copyright: '© 2024', contact: { phone: '0534 700 70 80', address: 'Beyoglu, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/kuyumcugumus', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1000, removable: false, animation: 'fadeIn' }, defaultContent: { phone: '905347007080', message: 'Merhaba, bilgi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 1001, removable: false, animation: 'fadeIn' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Silver Line — Beyoglu", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'fullscreen_overlay', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'Beyoglu', title: "Silver Line", subtitle: "Gumus kuyumcu", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'fadeIn' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'istatistik', type: 'stats', variant: 'animated_row', order: 3, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'full', visible: true, order: 3, removable: true, animation: 'fadeIn' }, defaultContent: { stats: [{value: '10+', label: 'Yıl'}, {value: '100+', label: 'Müşteri'}] }, editableFields: [] },
{ id: 'galeri', type: 'gallery', variant: 'masonry', order: 4, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'full', visible: true, order: 4, removable: true, animation: 'fadeIn' }, defaultContent: { badge: 'GALERİ', title: 'Çalışmalarımız', items: [{ id: 'g1', url: '/placeholder.jpg' }] }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'kuyumcu_services', order: 5, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'full', visible: true, order: 5, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'detailed_form', order: 6, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'full', visible: true, order: 6, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905347007080" }, editableFields: [] }
    ]
  }]
}
