import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const KUYUMCU_PIRLANTA_CSS: Record<string, string> = { '--color-bg': '#F0F0F0', '--color-surface': '#E0E0E0', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#D0D0D0', '--color-text': '#111111', '--color-text-secondary': '#333333', '--color-text-muted': '#888888', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#1E3A5F', '--color-accent-hover': '#0F2238', '--color-accent-light': '#EFF6FF', '--color-border': '#94A3B8', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const KUYUMCU_PIRLANTA_BUSINESS: BusinessData = { name: 'Diamond House', ownerName: 'Mehmet Pirlanta', sector: 'kuyumcu', slogan: 'Pirlanta kuyumcu', phone: '0532 600 60 70', phoneClean: '905326006070', whatsapp: '905326006070', email: 'info@kuyumcupirlanta.com.tr', address: 'Nisantasi, Istanbul', city: 'Istanbul', district: 'Nisantasi', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '18:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '18:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '18:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '18:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '18:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '14:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/kuyumcupirlanta' }, photos: [], services: [{ id: 's1', name: 'Pirlanta', icon: '💎' }], team: [{ id: 't1', name: 'Mehmet Pirlanta', role: 'Yonetici', experience: '12 yil' }], experience: '12 yil', rating: 4.9, reviewCount: 500, foundedYear: 2012 }
export const KUYUMCU_PIRLANTA_CONFIG: ThemeConfig = { id: 'kuyumcu-pirlanta', name: 'Pirlanta', sectorId: 'kuyumcu', plan: 'starter', description: 'Pirlanta kuyumcu. Nisantasi.', designPhilosophy: 'Pirlanta theme.', isDark: false, cssVariables: KUYUMCU_PIRLANTA_CSS, fonts: { heading: { family: 'Space Grotesk', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'JewelryStore', sectorSections: [], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'md', visible: true, order: 0, removable: false, animation: 'fadeIn' }, defaultContent: { logo: { type: 'text', text: 'Diamond House' }, menuItems: [{ label: 'Hizmetler', href: '#hizmetler' },{ label: 'Iletisim', href: '#iletisim' }], cta: { text: 'Iletisim', href: '#iletisim', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'md', visible: true, order: 999, removable: false, animation: 'fadeIn' }, defaultContent: { businessName: 'Diamond House', copyright: '© 2024', contact: { phone: '0532 600 60 70', address: 'Nisantasi, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/kuyumcupirlanta', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'md', visible: true, order: 1000, removable: false, animation: 'fadeIn' }, defaultContent: { phone: '905326006070', message: 'Merhaba, bilgi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'md', visible: true, order: 1001, removable: false, animation: 'fadeIn' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Diamond House — Nisantasi", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'md', visible: true, order: 1, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'Nisantasi', title: "Diamond House", subtitle: "Pirlanta kuyumcu", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'md', visible: true, order: 2, removable: true, animation: 'fadeIn' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'istatistik', type: 'stats', variant: 'animated_row', order: 3, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'md', visible: true, order: 3, removable: true, animation: 'fadeIn' }, defaultContent: { stats: [{value: '10+', label: 'Yıl'}, {value: '100+', label: 'Müşteri'}] }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'kuyumcu_services', order: 4, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'md', visible: true, order: 4, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'galeri', type: 'gallery', variant: 'masonry', order: 5, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'md', visible: true, order: 5, removable: true, animation: 'fadeIn' }, defaultContent: { badge: 'GALERİ', title: 'Çalışmalarımız', items: [{ id: 'g1', url: '/placeholder.jpg' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'detailed_form', order: 6, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'md', visible: true, order: 6, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905326006070" }, editableFields: [] }
    ]
  }]
}
