import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const KUYUMCU_DUGUN_CSS: Record<string, string> = { '--color-bg': '#FFF8F0', '--color-surface': '#FFEDD5', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#FED7AA', '--color-text': '#1C0A00', '--color-text-secondary': '#5C3819', '--color-text-muted': '#9E7555', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#EA580C', '--color-accent-hover': '#C2410C', '--color-accent-light': '#FFF7ED', '--color-border': '#FDBA74', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const KUYUMCU_DUGUN_BUSINESS: BusinessData = { name: 'Gelin Takı', ownerName: 'Fatma Çeyiz', sector: 'kuyumcu', slogan: 'Düğün koleksiyonu', phone: '0534 555 66 77', phoneClean: '905345556677', whatsapp: '905345556677', email: 'info@kuyumcudugun.com.tr', address: 'Laleli Cad. No.66, Fatih, İstanbul', city: 'İstanbul', district: 'Laleli', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '09:00', close: '19:00' },{ day: 'tuesday', dayTr: 'Salı', open: '09:00', close: '19:00' },{ day: 'wednesday', dayTr: 'Çarşamba', open: '09:00', close: '19:00' },{ day: 'thursday', dayTr: 'Perşembe', open: '09:00', close: '19:00' },{ day: 'friday', dayTr: 'Cuma', open: '09:00', close: '19:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '10:00', close: '18:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/kuyumcudugun' }, photos: [], services: [{ id: 's1', name: 'Düğün', icon: '💎' },{ id: 's2', name: 'Tamir', icon: '🔧' }], team: [{ id: 't1', name: 'Fatma Çeyiz', role: 'Kuyumcu', experience: '15 yıl' }], experience: '15 yıl', rating: 4.9, reviewCount: 300, foundedYear: 2010 }
export const KUYUMCU_DUGUN_CONFIG: ThemeConfig = { id: 'kuyumcu-dugun', name: 'Düğün', sectorId: 'kuyumcu', plan: 'pro', description: 'Düğün temalı kuyumcu. Laleli.', designPhilosophy: 'Düğün theme.', isDark: false, cssVariables: KUYUMCU_DUGUN_CSS, fonts: { heading: { family: 'Cinzel', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter, sans-serif', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'JewelryStore', sectorSections: ['jewelry_collection', 'gold_price_widget', 'jewelry_services_grid', 'jewelry_contact'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Gelin Takı 💎' }, menuItems: [{ label: 'Koleksiyon', href: '#koleksiyon' },{ label: 'İletişim', href: '#iletisim' }], cta: { text: 'İletişim', href: '#iletisim', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Gelin Takı', copyright: '© 2024', contact: { phone: '0534 555 66 77', address: 'Laleli, İstanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/kuyumcudugun', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905345556677', message: 'Merhaba, bilgi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Çerez kullanıyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Gelin Takı — Laleli", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Laleli', title: "Gelin Takı", subtitle: "Düğün koleksiyonu", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'kuyumcu_services', order: 2, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'simple_form', order: 3, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 3, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905345556677" }, editableFields: [] }
    ]
  }]
}
