import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const LASTIKCI_KIS_CSS: Record<string, string> = { '--color-bg': '#EFF6FF', '--color-surface': '#DBEAFE', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#BFDBFE', '--color-text': '#0C1B2A', '--color-text-secondary': '#1E3A5F', '--color-text-muted': '#6B7280', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--color-accent-light': '#EFF6FF', '--color-border': '#93C5FD', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const LASTIKCI_KIS_BUSINESS: BusinessData = { name: 'Winter Tire', ownerName: 'Mehmet Tekerlek', sector: 'lastikci', slogan: 'Kis lastikci', phone: '0532 200 20 30', phoneClean: '905322002030', whatsapp: '905322002030', email: 'info@lastikcikis.com.tr', address: 'Pendik, Istanbul', city: 'Istanbul', district: 'Pendik', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '18:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '18:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '18:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '18:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '18:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '14:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/lastikcikis' }, photos: [], services: [{ id: 's1', name: 'Kis', icon: '🛞' }], team: [{ id: 't1', name: 'Mehmet Tekerlek', role: 'Usta', experience: '15 yil' }], experience: '15 yil', rating: 4.8, reviewCount: 600, foundedYear: 2008 }
export const LASTIKCI_KIS_CONFIG: ThemeConfig = { id: 'lastikci-kis', name: 'Kis', sectorId: 'lastikci', plan: 'starter', description: 'Kis lastikci. Pendik.', designPhilosophy: 'Kis theme.', isDark: false, cssVariables: LASTIKCI_KIS_CSS, fonts: { heading: { family: 'Oswald', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'TireShop', sectorSections: [], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'zoomIn' }, defaultContent: { logo: { type: 'text', text: 'Winter Tire' }, menuItems: [{ label: 'Hizmetler', href: '#hizmetler' },{ label: 'Iletisim', href: '#iletisim' }], cta: { text: 'Iletisim', href: '#iletisim', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'zoomIn' }, defaultContent: { businessName: 'Winter Tire', copyright: '© 2024', contact: { phone: '0532 200 20 30', address: 'Pendik, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/lastikcikis', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'zoomIn' }, defaultContent: { phone: '905322002030', message: 'Merhaba, bilgi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'zoomIn' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Winter Tire — Pendik", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'fullscreen_overlay', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'zoomIn' }, defaultContent: { badge: 'Pendik', title: "Winter Tire", subtitle: "Kis lastikci", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: true, animation: 'zoomIn' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'istatistik', type: 'stats', variant: 'animated_row', order: 3, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'xl', visible: true, order: 3, removable: true, animation: 'zoomIn' }, defaultContent: { stats: [{value: '10+', label: 'Yıl'}, {value: '100+', label: 'Müşteri'}] }, editableFields: [] },
{ id: 'galeri', type: 'gallery', variant: 'masonry', order: 4, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 4, removable: true, animation: 'zoomIn' }, defaultContent: { badge: 'GALERİ', title: 'Çalışmalarımız', items: [{ id: 'g1', url: '/placeholder.jpg' }] }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'lastikci_services', order: 5, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 5, removable: false, animation: 'zoomIn' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'detailed_form', order: 6, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 6, removable: false, animation: 'zoomIn' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905322002030" }, editableFields: [] }
    ]
  }]
}
