import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const MOBILYA_OFIS_CSS: Record<string, string> = { '--color-bg': '#F0F0F0', '--color-surface': '#E0E0E0', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#D0D0D0', '--color-text': '#111111', '--color-text-secondary': '#333333', '--color-text-muted': '#888888', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#1E3A5F', '--color-accent-hover': '#0F2238', '--color-accent-light': '#EFF6FF', '--color-border': '#94A3B8', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const MOBILYA_OFIS_BUSINESS: BusinessData = { name: 'Office Plus', ownerName: 'Mehmet Ofis', sector: 'mobilyaci', slogan: 'Ofis mobilyaci', phone: '0532 600 60 70', phoneClean: '905326006070', whatsapp: '905326006070', email: 'info@mobilyaofis.com.tr', address: 'Masko, Istanbul', city: 'Istanbul', district: 'Masko', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '18:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '18:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '18:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '18:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '18:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '14:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/mobilyaofis' }, photos: [], services: [{ id: 's1', name: 'Ofis', icon: '🛞' }], team: [{ id: 't1', name: 'Mehmet Ofis', role: 'Usta', experience: '15 yil' }], experience: '15 yil', rating: 4.8, reviewCount: 600, foundedYear: 2008 }
export const MOBILYA_OFIS_CONFIG: ThemeConfig = { id: 'mobilya-ofis', name: 'Ofis', sectorId: 'mobilyaci', plan: 'starter', description: 'Ofis mobilyaci. Masko.', designPhilosophy: 'Ofis theme.', isDark: false, cssVariables: MOBILYA_OFIS_CSS, fonts: { heading: { family: 'Space Grotesk', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'FurnitureStore', sectorSections: [], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'md', visible: true, order: 0, removable: false, animation: 'fadeIn' }, defaultContent: { logo: { type: 'text', text: 'Office Plus' }, menuItems: [{ label: 'Hizmetler', href: '#hizmetler' },{ label: 'Iletisim', href: '#iletisim' }], cta: { text: 'Iletisim', href: '#iletisim', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'md', visible: true, order: 999, removable: false, animation: 'fadeIn' }, defaultContent: { businessName: 'Office Plus', copyright: '© 2024', contact: { phone: '0532 600 60 70', address: 'Masko, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/mobilyaofis', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'md', visible: true, order: 1000, removable: false, animation: 'fadeIn' }, defaultContent: { phone: '905326006070', message: 'Merhaba, bilgi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'md', visible: true, order: 1001, removable: false, animation: 'fadeIn' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Office Plus — Masko", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'md', visible: true, order: 1, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'Masko', title: "Office Plus", subtitle: "Ofis mobilyaci", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'mobilyaci_services', order: 2, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'md', visible: true, order: 2, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'simple_form', order: 3, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'md', visible: true, order: 3, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905326006070" }, editableFields: [] }
    ]
  }]
}
