import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const MOBILYA_LUX_CSS: Record<string, string> = { '--color-bg': '#080808', '--color-surface': '#111111', '--color-surface-elevated': '#1A1A1A', '--color-surface-muted': '#222222', '--color-text': '#F5EDD6', '--color-text-secondary': '#C9AD7A', '--color-text-muted': '#80663A', '--color-text-on-accent': '#080808', '--color-accent': '#D4AF37', '--color-accent-hover': '#B8943A', '--color-accent-light': 'rgba(212,175,55,0.12)', '--color-border': 'rgba(212,175,55,0.18)', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const MOBILYA_LUX_BUSINESS: BusinessData = { name: 'Prestige Interiors', ownerName: 'Pierre', sector: 'mobilyaci', slogan: 'Luks mobilyaci', phone: '0212 227 90 00', phoneClean: '902122279000', whatsapp: '902122279000', email: 'info@mobilyalux.com.tr', address: 'Nisantasi, Istanbul', city: 'Istanbul', district: 'Nisantasi', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '18:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '18:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '18:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '18:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '18:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '14:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/mobilyalux' }, photos: [], services: [{ id: 's1', name: 'Luks', icon: '🛞' }], team: [{ id: 't1', name: 'Pierre', role: 'Usta', experience: '15 yil' }], experience: '15 yil', rating: 4.8, reviewCount: 600, foundedYear: 2008 }
export const MOBILYA_LUX_CONFIG: ThemeConfig = { id: 'mobilya-lux', name: 'Luks', sectorId: 'mobilyaci', plan: 'enterprise', description: 'Luks mobilyaci. Nisantasi.', designPhilosophy: 'Luks theme.', isDark: true, cssVariables: MOBILYA_LUX_CSS, fonts: { heading: { family: 'Lora', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'FurnitureStore', sectorSections: [], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Prestige Interiors' }, menuItems: [{ label: 'Hizmetler', href: '#hizmetler' },{ label: 'Iletisim', href: '#iletisim' }], cta: { text: 'Iletisim', href: '#iletisim', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Prestige Interiors', copyright: '© 2024', contact: { phone: '0212 227 90 00', address: 'Nisantasi, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/mobilyalux', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '902122279000', message: 'Merhaba, bilgi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Prestige Interiors — Nisantasi", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Nisantasi', title: "Prestige Interiors", subtitle: "Luks mobilyaci", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'istatistik', type: 'stats', variant: 'animated_row', order: 3, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'xl', visible: true, order: 3, removable: true, animation: 'fadeUp' }, defaultContent: { stats: [{value: '10+', label: 'Yıl'}, {value: '100+', label: 'Müşteri'}] }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'mobilyaci_services', order: 4, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 4, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'galeri', type: 'gallery', variant: 'masonry', order: 5, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 5, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'GALERİ', title: 'Çalışmalarımız', items: [{ id: 'g1', url: '/placeholder.jpg' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'detailed_form', order: 6, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 6, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "902122279000" }, editableFields: [] }
    ]
  }]
}
