import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const MUZIK_ROCK_CSS: Record<string, string> = { '--color-bg': '#1C1917', '--color-surface': '#292524', '--color-surface-elevated': '#44403C', '--color-surface-muted': '#1C1917', '--color-text': '#FAFAF9', '--color-text-secondary': '#D6D3D1', '--color-text-muted': '#A8A29E', '--color-text-on-accent': '#1C1917', '--color-accent': '#DC2626', '--color-accent-hover': '#B91C1C', '--color-accent-light': 'rgba(220,38,38,0.12)', '--color-border': 'rgba(220,38,38,0.18)', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const MUZIK_ROCK_BUSINESS: BusinessData = { name: 'Garage Studio', ownerName: 'Emre Bas', sector: 'muzik', slogan: 'Rock muzik okulu', phone: '0534 400 50 60', phoneClean: '905344005060', whatsapp: '905344005060', email: 'info@muzikrock.com.tr', address: 'Beyoglu, Istanbul', city: 'Istanbul', district: 'Beyoglu', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '10:00', close: '21:00' },{ day: 'tuesday', dayTr: 'Sali', open: '10:00', close: '21:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '10:00', close: '21:00' },{ day: 'thursday', dayTr: 'Persembe', open: '10:00', close: '21:00' },{ day: 'friday', dayTr: 'Cuma', open: '10:00', close: '21:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '10:00', close: '18:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/muzikrock' }, photos: [], services: [{ id: 's1', name: 'Ders', icon: '🎵' },{ id: 's2', name: 'Stud', icon: '🎧' }], team: [{ id: 't1', name: 'Emre Bas', role: 'Ogretmen', experience: '12 yil' }], experience: '12 yil', rating: 4.9, reviewCount: 350, foundedYear: 2012 }
export const MUZIK_ROCK_CONFIG: ThemeConfig = { id: 'muzik-rock', name: 'Rock', sectorId: 'muzik', plan: 'growth', description: 'Rock muzik okulu. Beyoglu.', designPhilosophy: 'Rock theme.', isDark: true, cssVariables: MUZIK_ROCK_CSS, fonts: { heading: { family: 'Outfit', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'MusicSchool', sectorSections: ['music_course_grid', 'music_teacher_grid', 'music_pricing', 'music_trial'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Garage Studio 🎵' }, menuItems: [{ label: 'Kurslar', href: '#kurslar' },{ label: 'Kayit', href: '#kayit' }], cta: { text: 'Deneme Dersi', href: '#kayit', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Garage Studio', copyright: '© 2024', contact: { phone: '0534 400 50 60', address: 'Beyoglu, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/muzikrock', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905344005060', message: 'Merhaba, deneme dersi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Garage Studio — Beyoglu", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Beyoglu', title: "Garage Studio", subtitle: "Rock muzik okulu", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'istatistik', type: 'stats', variant: 'animated_row', order: 3, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'xl', visible: true, order: 3, removable: true, animation: 'fadeUp' }, defaultContent: { stats: [{value: '10+', label: 'Yıl'}, {value: '100+', label: 'Müşteri'}] }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'muzik_services', order: 4, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 4, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'galeri', type: 'gallery', variant: 'masonry', order: 5, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 5, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'GALERİ', title: 'Çalışmalarımız', items: [{ id: 'g1', url: '/placeholder.jpg' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'detailed_form', order: 6, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 6, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905344005060" }, editableFields: [] }
    ]
  }]
}
