import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const MUZIK_KLASIK_CSS: Record<string, string> = { '--color-bg': '#F5F0EB', '--color-surface': '#E8DFD4', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#D4C5B2', '--color-text': '#1C1408', '--color-text-secondary': '#5C4B32', '--color-text-muted': '#9E8855', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#78350F', '--color-accent-hover': '#5C2D0E', '--color-accent-light': '#FFFBEB', '--color-border': '#D6D3D1', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const MUZIK_KLASIK_BUSINESS: BusinessData = { name: 'Nota Muzik', ownerName: 'Ayse Piyano', sector: 'muzik', slogan: 'Klasik muzik okulu', phone: '0533 200 30 40', phoneClean: '905332003040', whatsapp: '905332003040', email: 'info@muzikklasik.com.tr', address: 'Kadikoy, Istanbul', city: 'Istanbul', district: 'Kadikoy', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '10:00', close: '21:00' },{ day: 'tuesday', dayTr: 'Sali', open: '10:00', close: '21:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '10:00', close: '21:00' },{ day: 'thursday', dayTr: 'Persembe', open: '10:00', close: '21:00' },{ day: 'friday', dayTr: 'Cuma', open: '10:00', close: '21:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '10:00', close: '18:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/muzikklasik' }, photos: [], services: [{ id: 's1', name: 'Ders', icon: '🎵' },{ id: 's2', name: 'Stud', icon: '🎧' }], team: [{ id: 't1', name: 'Ayse Piyano', role: 'Ogretmen', experience: '12 yil' }], experience: '12 yil', rating: 4.9, reviewCount: 350, foundedYear: 2012 }
export const MUZIK_KLASIK_CONFIG: ThemeConfig = { id: 'muzik-klasik', name: 'Klasik', sectorId: 'muzik', plan: 'free', description: 'Klasik muzik okulu. Kadikoy.', designPhilosophy: 'Klasik theme.', isDark: false, cssVariables: MUZIK_KLASIK_CSS, fonts: { heading: { family: 'Merriweather', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'MusicSchool', sectorSections: ['music_course_grid', 'music_teacher_grid', 'music_pricing', 'music_trial'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'md', visible: true, order: 0, removable: false, animation: 'fadeIn' }, defaultContent: { logo: { type: 'text', text: 'Nota Muzik 🎵' }, menuItems: [{ label: 'Kurslar', href: '#kurslar' },{ label: 'Kayit', href: '#kayit' }], cta: { text: 'Deneme Dersi', href: '#kayit', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'md', visible: true, order: 999, removable: false, animation: 'fadeIn' }, defaultContent: { businessName: 'Nota Muzik', copyright: '© 2024', contact: { phone: '0533 200 30 40', address: 'Kadikoy, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/muzikklasik', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'md', visible: true, order: 1000, removable: false, animation: 'fadeIn' }, defaultContent: { phone: '905332003040', message: 'Merhaba, deneme dersi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'md', visible: true, order: 1001, removable: false, animation: 'fadeIn' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Nota Muzik — Kadikoy", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'md', visible: true, order: 1, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'Kadikoy', title: "Nota Muzik", subtitle: "Klasik muzik okulu", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'muzik_services', order: 2, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'md', visible: true, order: 2, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'simple_form', order: 3, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'md', visible: true, order: 3, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905332003040" }, editableFields: [] }
    ]
  }]
}
