import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const MUZIK_POP_CSS: Record<string, string> = { '--color-bg': '#F0F9FF', '--color-surface': '#E0F2FE', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#BAE6FD', '--color-text': '#0C1B2A', '--color-text-secondary': '#1E3A5F', '--color-text-muted': '#6B7280', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#0284C7', '--color-accent-hover': '#0369A1', '--color-accent-light': '#F0F9FF', '--color-border': '#7DD3FC', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const MUZIK_POP_BUSINESS: BusinessData = { name: 'Beat Academy', ownerName: 'Can Ritm', sector: 'muzik', slogan: 'Pop muzik okulu', phone: '0532 300 40 50', phoneClean: '905323004050', whatsapp: '905323004050', email: 'info@muzikpop.com.tr', address: 'Besiktas, Istanbul', city: 'Istanbul', district: 'Besiktas', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '10:00', close: '21:00' },{ day: 'tuesday', dayTr: 'Sali', open: '10:00', close: '21:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '10:00', close: '21:00' },{ day: 'thursday', dayTr: 'Persembe', open: '10:00', close: '21:00' },{ day: 'friday', dayTr: 'Cuma', open: '10:00', close: '21:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '10:00', close: '18:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/muzikpop' }, photos: [], services: [{ id: 's1', name: 'Ders', icon: '🎵' },{ id: 's2', name: 'Stud', icon: '🎧' }], team: [{ id: 't1', name: 'Can Ritm', role: 'Ogretmen', experience: '12 yil' }], experience: '12 yil', rating: 4.9, reviewCount: 350, foundedYear: 2012 }
export const MUZIK_POP_CONFIG: ThemeConfig = { id: 'muzik-pop', name: 'Pop', sectorId: 'muzik', plan: 'starter', description: 'Pop muzik okulu. Besiktas.', designPhilosophy: 'Pop theme.', isDark: false, cssVariables: MUZIK_POP_CSS, fonts: { heading: { family: 'Cinzel', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'MusicSchool', sectorSections: ['music_course_grid', 'music_teacher_grid', 'music_pricing', 'music_trial'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Beat Academy 🎵' }, menuItems: [{ label: 'Kurslar', href: '#kurslar' },{ label: 'Kayit', href: '#kayit' }], cta: { text: 'Deneme Dersi', href: '#kayit', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Beat Academy', copyright: '© 2024', contact: { phone: '0532 300 40 50', address: 'Besiktas, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/muzikpop', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905323004050', message: 'Merhaba, deneme dersi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Beat Academy — Besiktas", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'fullscreen_overlay', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Besiktas', title: "Beat Academy", subtitle: "Pop muzik okulu", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'istatistik', type: 'stats', variant: 'animated_row', order: 3, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'xl', visible: true, order: 3, removable: true, animation: 'fadeUp' }, defaultContent: { stats: [{value: '10+', label: 'Yıl'}, {value: '100+', label: 'Müşteri'}] }, editableFields: [] },
{ id: 'galeri', type: 'gallery', variant: 'masonry', order: 4, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 4, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'GALERİ', title: 'Çalışmalarımız', items: [{ id: 'g1', url: '/placeholder.jpg' }] }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'muzik_services', order: 5, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 5, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'cta', type: 'cta', variant: 'simple_banner', order: 6, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'full', visible: true, order: 6, removable: true, animation: 'fadeUp' }, defaultContent: { title: 'Hemen Başlayın', cta: { text: 'Bize Ulaşın' } }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'detailed_form', order: 7, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 7, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905323004050" }, editableFields: [] }
    ]
  }]
}
