import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const MUZIK_COCUK_CSS: Record<string, string> = { '--color-bg': '#FFF5F7', '--color-surface': '#FFE4ED', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#FBBFD0', '--color-text': '#2E0316', '--color-text-secondary': '#6E1443', '--color-text-muted': '#B06585', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#DB2777', '--color-accent-hover': '#BE185D', '--color-accent-light': '#FDF2F8', '--color-border': '#F9A8D4', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const MUZIK_COCUK_BUSINESS: BusinessData = { name: 'Mini Mozart', ownerName: 'Elif Nota', sector: 'muzik', slogan: 'Cocuk muzik okulu', phone: '0535 500 60 70', phoneClean: '905355006070', whatsapp: '905355006070', email: 'info@muzikcocuk.com.tr', address: 'Bakirkoy, Istanbul', city: 'Istanbul', district: 'Bakirkoy', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '10:00', close: '21:00' },{ day: 'tuesday', dayTr: 'Sali', open: '10:00', close: '21:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '10:00', close: '21:00' },{ day: 'thursday', dayTr: 'Persembe', open: '10:00', close: '21:00' },{ day: 'friday', dayTr: 'Cuma', open: '10:00', close: '21:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '10:00', close: '18:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/muzikcocuk' }, photos: [], services: [{ id: 's1', name: 'Ders', icon: '🎵' },{ id: 's2', name: 'Stud', icon: '🎧' }], team: [{ id: 't1', name: 'Elif Nota', role: 'Ogretmen', experience: '12 yil' }], experience: '12 yil', rating: 4.9, reviewCount: 350, foundedYear: 2012 }
export const MUZIK_COCUK_CONFIG: ThemeConfig = { id: 'muzik-cocuk', name: 'Cocuk', sectorId: 'muzik', plan: 'pro', description: 'Cocuk muzik okulu. Bakirkoy.', designPhilosophy: 'Cocuk theme.', isDark: false, cssVariables: MUZIK_COCUK_CSS, fonts: { heading: { family: 'Raleway', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'MusicSchool', sectorSections: ['music_course_grid', 'music_teacher_grid', 'music_pricing', 'music_trial'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Mini Mozart 🎵' }, menuItems: [{ label: 'Kurslar', href: '#kurslar' },{ label: 'Kayit', href: '#kayit' }], cta: { text: 'Deneme Dersi', href: '#kayit', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Mini Mozart', copyright: '© 2024', contact: { phone: '0535 500 60 70', address: 'Bakirkoy, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/muzikcocuk', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905355006070', message: 'Merhaba, deneme dersi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Mini Mozart — Bakirkoy", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Bakirkoy', title: "Mini Mozart", subtitle: "Cocuk muzik okulu", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'muzik_services', order: 3, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 3, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'simple_form', order: 4, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 4, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905355006070" }, editableFields: [] }
    ]
  }]
}
