import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const NAKLIYAT_EV_CSS: Record<string, string> = { '--color-bg': '#EFF6FF', '--color-surface': '#DBEAFE', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#BFDBFE', '--color-text': '#0C1B2A', '--color-text-secondary': '#1E3A5F', '--color-text-muted': '#6B7280', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--color-accent-light': '#EFF6FF', '--color-border': '#93C5FD', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const NAKLIYAT_EV_BUSINESS: BusinessData = { name: 'Guvenli Tasima', ownerName: 'Ali Nakliye', sector: 'nakliyat', slogan: 'Ev nakliyat', phone: '0533 100 10 20', phoneClean: '905331001020', whatsapp: '905331001020', email: 'info@nakliyatev.com.tr', address: 'Kartal, Istanbul', city: 'Istanbul', district: 'Kartal', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '18:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '18:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '18:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '18:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '18:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '14:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/nakliyatev' }, photos: [], services: [{ id: 's1', name: 'Ev', icon: '🏢' }], team: [{ id: 't1', name: 'Ali Nakliye', role: 'Yonetici', experience: '10 yil' }], experience: '10 yil', rating: 4.9, reviewCount: 400, foundedYear: 2014 }
export const NAKLIYAT_EV_CONFIG: ThemeConfig = { id: 'nakliyat-ev', name: 'Ev', sectorId: 'nakliyat', plan: 'free', description: 'Ev nakliyat. Kartal.', designPhilosophy: 'Ev theme.', isDark: false, cssVariables: NAKLIYAT_EV_CSS, fonts: { heading: { family: 'Bodoni Moda', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'MovingCompany', sectorSections: [], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'sm', visible: true, order: 0, removable: false, animation: 'none' }, defaultContent: { logo: { type: 'text', text: 'Guvenli Tasima' }, menuItems: [{ label: 'Hizmetler', href: '#hizmetler' },{ label: 'Iletisim', href: '#iletisim' }], cta: { text: 'Iletisim', href: '#iletisim', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'sm', visible: true, order: 999, removable: false, animation: 'none' }, defaultContent: { businessName: 'Guvenli Tasima', copyright: '© 2024', contact: { phone: '0533 100 10 20', address: 'Kartal, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/nakliyatev', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'sm', visible: true, order: 1000, removable: false, animation: 'none' }, defaultContent: { phone: '905331001020', message: 'Merhaba, bilgi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'sm', visible: true, order: 1001, removable: false, animation: 'none' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Guvenli Tasima — Kartal", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'sm', visible: true, order: 1, removable: false, animation: 'none' }, defaultContent: { badge: 'Kartal', title: "Guvenli Tasima", subtitle: "Ev nakliyat", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'sm', visible: true, order: 2, removable: true, animation: 'none' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'nakliyat_services', order: 3, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'sm', visible: true, order: 3, removable: false, animation: 'none' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'simple_form', order: 4, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'sm', visible: true, order: 4, removable: false, animation: 'none' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905331001020" }, editableFields: [] }
    ]
  }]
}
