import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const NAKLIYAT_OFIS_CSS: Record<string, string> = { '--color-bg': '#F0F0F0', '--color-surface': '#E0E0E0', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#D0D0D0', '--color-text': '#111111', '--color-text-secondary': '#333333', '--color-text-muted': '#888888', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#1E3A5F', '--color-accent-hover': '#0F2238', '--color-accent-light': '#EFF6FF', '--color-border': '#94A3B8', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const NAKLIYAT_OFIS_BUSINESS: BusinessData = { name: 'Corporate Move', ownerName: 'Mehmet Ofis', sector: 'nakliyat', slogan: 'Ofis nakliyat', phone: '0532 200 20 30', phoneClean: '905322002030', whatsapp: '905322002030', email: 'info@nakliyatofis.com.tr', address: 'Levent, Istanbul', city: 'Istanbul', district: 'Levent', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '18:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '18:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '18:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '18:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '18:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '14:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/nakliyatofis' }, photos: [], services: [{ id: 's1', name: 'Ofis', icon: '🏢' }], team: [{ id: 't1', name: 'Mehmet Ofis', role: 'Yonetici', experience: '10 yil' }], experience: '10 yil', rating: 4.9, reviewCount: 400, foundedYear: 2014 }
export const NAKLIYAT_OFIS_CONFIG: ThemeConfig = { id: 'nakliyat-ofis', name: 'Ofis', sectorId: 'nakliyat', plan: 'starter', description: 'Ofis nakliyat. Levent.', designPhilosophy: 'Ofis theme.', isDark: false, cssVariables: NAKLIYAT_OFIS_CSS, fonts: { heading: { family: 'Raleway', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'MovingCompany', sectorSections: [], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'lg', visible: true, order: 0, removable: false, animation: 'fadeIn' }, defaultContent: { logo: { type: 'text', text: 'Corporate Move' }, menuItems: [{ label: 'Hizmetler', href: '#hizmetler' },{ label: 'Iletisim', href: '#iletisim' }], cta: { text: 'Iletisim', href: '#iletisim', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'lg', visible: true, order: 999, removable: false, animation: 'fadeIn' }, defaultContent: { businessName: 'Corporate Move', copyright: '© 2024', contact: { phone: '0532 200 20 30', address: 'Levent, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/nakliyatofis', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'lg', visible: true, order: 1000, removable: false, animation: 'fadeIn' }, defaultContent: { phone: '905322002030', message: 'Merhaba, bilgi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'lg', visible: true, order: 1001, removable: false, animation: 'fadeIn' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Corporate Move — Levent", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'lg', visible: true, order: 1, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'Levent', title: "Corporate Move", subtitle: "Ofis nakliyat", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'lg', visible: true, order: 2, removable: true, animation: 'fadeIn' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'istatistik', type: 'stats', variant: 'animated_row', order: 3, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'lg', visible: true, order: 3, removable: true, animation: 'fadeIn' }, defaultContent: { stats: [{value: '10+', label: 'Yıl'}, {value: '100+', label: 'Müşteri'}] }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'nakliyat_services', order: 4, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'lg', visible: true, order: 4, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'galeri', type: 'gallery', variant: 'masonry', order: 5, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'lg', visible: true, order: 5, removable: true, animation: 'fadeIn' }, defaultContent: { badge: 'GALERİ', title: 'Çalışmalarımız', items: [{ id: 'g1', url: '/placeholder.jpg' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'detailed_form', order: 6, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'lg', visible: true, order: 6, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905322002030" }, editableFields: [] }
    ]
  }]
}
