import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const OTOYIKAMA_OTO_CSS: Record<string, string> = { '--color-bg': '#ECFDF5', '--color-surface': '#D1FAE5', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#A7F3D0', '--color-text': '#052E16', '--color-text-secondary': '#166534', '--color-text-muted': '#6B7280', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#059669', '--color-accent-hover': '#047857', '--color-accent-light': '#ECFDF5', '--color-border': '#6EE7B7', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const OTOYIKAMA_OTO_BUSINESS: BusinessData = { name: 'Aqua Car Wash', ownerName: 'Selim Su', sector: 'otoyikama', slogan: 'Oto yikama', phone: '0534 600 70 80', phoneClean: '905346007080', whatsapp: '905346007080', email: 'info@otoyikamaoto.com.tr', address: 'Bakirkoy, Istanbul', city: 'Istanbul', district: 'Bakirkoy', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '20:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '20:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '20:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '20:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '20:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '08:00', close: '19:00' },{ day: 'sunday', dayTr: 'Pazar', open: '09:00', close: '18:00' }], socialMedia: { instagram: 'https://instagram.com/otoyikamaoto' }, photos: [], services: [{ id: 's1', name: 'Yikama', icon: '🚗' },{ id: 's2', name: 'Detay', icon: '✨' }], team: [{ id: 't1', name: 'Selim Su', role: 'Isletmeci', experience: '10 yil' }], experience: '10 yil', rating: 4.8, reviewCount: 600, foundedYear: 2014 }
export const OTOYIKAMA_OTO_CONFIG: ThemeConfig = { id: 'otoyikama-oto', name: 'Oto', sectorId: 'otoyikama', plan: 'growth', description: 'Oto oto yikama. Bakirkoy.', designPhilosophy: 'Oto theme.', isDark: false, cssVariables: OTOYIKAMA_OTO_CSS, fonts: { heading: { family: 'Bebas Neue', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'AutoWash', sectorSections: ['carwash_packages', 'carwash_services', 'carwash_before_after', 'carwash_booking'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'md', visible: true, order: 0, removable: false, animation: 'fadeIn' }, defaultContent: { logo: { type: 'text', text: 'Aqua Car Wash 🚗' }, menuItems: [{ label: 'Paketler', href: '#paketler' },{ label: 'Randevu', href: '#randevu' }], cta: { text: 'Randevu', href: '#randevu', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'md', visible: true, order: 999, removable: false, animation: 'fadeIn' }, defaultContent: { businessName: 'Aqua Car Wash', copyright: '© 2024', contact: { phone: '0534 600 70 80', address: 'Bakirkoy, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/otoyikamaoto', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'md', visible: true, order: 1000, removable: false, animation: 'fadeIn' }, defaultContent: { phone: '905346007080', message: 'Merhaba, yikama randevusu almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'md', visible: true, order: 1001, removable: false, animation: 'fadeIn' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Aqua Car Wash — Bakirkoy", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'md', visible: true, order: 1, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'Bakirkoy', title: "Aqua Car Wash", subtitle: "Oto yikama", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'otoyikama_services', order: 2, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'md', visible: true, order: 2, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'simple_form', order: 3, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'md', visible: true, order: 3, removable: false, animation: 'fadeIn' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905346007080" }, editableFields: [] }
    ]
  }]
}
