import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const OTOYIKAMA_EKSPRES_CSS: Record<string, string> = { '--color-bg': '#EFF6FF', '--color-surface': '#DBEAFE', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#BFDBFE', '--color-text': '#0C1B2A', '--color-text-secondary': '#1E3A5F', '--color-text-muted': '#6B7280', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#2563EB', '--color-accent-hover': '#1D4ED8', '--color-accent-light': '#EFF6FF', '--color-border': '#93C5FD', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const OTOYIKAMA_EKSPRES_BUSINESS: BusinessData = { name: 'Hizli Yikama', ownerName: 'Ali Temiz', sector: 'otoyikama', slogan: 'Ekspres yikama', phone: '0533 700 80 90', phoneClean: '905337008090', whatsapp: '905337008090', email: 'info@otoyikamaekspres.com.tr', address: 'Kartal, Istanbul', city: 'Istanbul', district: 'Kartal', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '20:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '20:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '20:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '20:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '20:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '08:00', close: '19:00' },{ day: 'sunday', dayTr: 'Pazar', open: '09:00', close: '18:00' }], socialMedia: { instagram: 'https://instagram.com/otoyikamaekspres' }, photos: [], services: [{ id: 's1', name: 'Yikama', icon: '🚗' },{ id: 's2', name: 'Detay', icon: '✨' }], team: [{ id: 't1', name: 'Ali Temiz', role: 'Isletmeci', experience: '10 yil' }], experience: '10 yil', rating: 4.8, reviewCount: 600, foundedYear: 2014 }
export const OTOYIKAMA_EKSPRES_CONFIG: ThemeConfig = { id: 'otoyikama-ekspres', name: 'Ekspres', sectorId: 'otoyikama', plan: 'free', description: 'Ekspres oto yikama. Kartal.', designPhilosophy: 'Ekspres theme.', isDark: false, cssVariables: OTOYIKAMA_EKSPRES_CSS, fonts: { heading: { family: 'Outfit', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'AutoWash', sectorSections: ['carwash_packages', 'carwash_services', 'carwash_before_after', 'carwash_booking'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Hizli Yikama 🚗' }, menuItems: [{ label: 'Paketler', href: '#paketler' },{ label: 'Randevu', href: '#randevu' }], cta: { text: 'Randevu', href: '#randevu', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Hizli Yikama', copyright: '© 2024', contact: { phone: '0533 700 80 90', address: 'Kartal, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/otoyikamaekspres', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905337008090', message: 'Merhaba, yikama randevusu almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Hizli Yikama — Kartal", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'fullscreen_overlay', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Kartal', title: "Hizli Yikama", subtitle: "Ekspres yikama", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'istatistik', type: 'stats', variant: 'animated_row', order: 3, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'xl', visible: true, order: 3, removable: true, animation: 'fadeUp' }, defaultContent: { stats: [{value: '10+', label: 'Yıl'}, {value: '100+', label: 'Müşteri'}] }, editableFields: [] },
{ id: 'galeri', type: 'gallery', variant: 'masonry', order: 4, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 4, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'GALERİ', title: 'Çalışmalarımız', items: [{ id: 'g1', url: '/placeholder.jpg' }] }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'otoyikama_services', order: 5, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 5, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'cta', type: 'cta', variant: 'simple_banner', order: 6, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'full', visible: true, order: 6, removable: true, animation: 'fadeUp' }, defaultContent: { title: 'Hemen Başlayın', cta: { text: 'Bize Ulaşın' } }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'detailed_form', order: 7, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 7, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905337008090" }, editableFields: [] }
    ]
  }]
}
