import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const TEMIZLIK_DEZENFEKTAN_CSS: Record<string, string> = { '--color-bg': '#ECFDF5', '--color-surface': '#D1FAE5', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#A7F3D0', '--color-text': '#052E16', '--color-text-secondary': '#166534', '--color-text-muted': '#6B7280', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#059669', '--color-accent-hover': '#047857', '--color-accent-light': '#ECFDF5', '--color-border': '#6EE7B7', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const TEMIZLIK_DEZENFEKTAN_BUSINESS: BusinessData = { name: 'Safe Clean', ownerName: 'Hasan Hijyen', sector: 'temizlik', slogan: 'Dezenfeksiyon temizlik', phone: '0535 400 40 50', phoneClean: '905354004050', whatsapp: '905354004050', email: 'info@temizlikdezenfektan.com.tr', address: 'Bakirkoy, Istanbul', city: 'Istanbul', district: 'Bakirkoy', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '08:00', close: '18:00' },{ day: 'tuesday', dayTr: 'Sali', open: '08:00', close: '18:00' },{ day: 'wednesday', dayTr: 'Carsamba', open: '08:00', close: '18:00' },{ day: 'thursday', dayTr: 'Persembe', open: '08:00', close: '18:00' },{ day: 'friday', dayTr: 'Cuma', open: '08:00', close: '18:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '09:00', close: '14:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/temizlikdezenfektan' }, photos: [], services: [{ id: 's1', name: 'Dezenfeksiyon', icon: '💎' }], team: [{ id: 't1', name: 'Hasan Hijyen', role: 'Yonetici', experience: '12 yil' }], experience: '12 yil', rating: 4.9, reviewCount: 500, foundedYear: 2012 }
export const TEMIZLIK_DEZENFEKTAN_CONFIG: ThemeConfig = { id: 'temizlik-dezenfektan', name: 'Dezenfeksiyon', sectorId: 'temizlik', plan: 'pro', description: 'Dezenfeksiyon temizlik. Bakirkoy.', designPhilosophy: 'Dezenfeksiyon theme.', isDark: false, cssVariables: TEMIZLIK_DEZENFEKTAN_CSS, fonts: { heading: { family: 'Bebas Neue', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'CleaningService', sectorSections: [], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'zoomIn' }, defaultContent: { logo: { type: 'text', text: 'Safe Clean' }, menuItems: [{ label: 'Hizmetler', href: '#hizmetler' },{ label: 'Iletisim', href: '#iletisim' }], cta: { text: 'Iletisim', href: '#iletisim', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'zoomIn' }, defaultContent: { businessName: 'Safe Clean', copyright: '© 2024', contact: { phone: '0535 400 40 50', address: 'Bakirkoy, Istanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/temizlikdezenfektan', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'zoomIn' }, defaultContent: { phone: '905354004050', message: 'Merhaba, bilgi almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'zoomIn' }, defaultContent: { text: 'Cerez kullaniyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Safe Clean — Bakirkoy", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'zoomIn' }, defaultContent: { badge: 'Bakirkoy', title: "Safe Clean", subtitle: "Dezenfeksiyon temizlik", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: true, animation: 'zoomIn' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'istatistik', type: 'stats', variant: 'animated_row', order: 3, required: false, settings: { bgMode: 'accent', paddingY: 'md', containerWidth: 'xl', visible: true, order: 3, removable: true, animation: 'zoomIn' }, defaultContent: { stats: [{value: '10+', label: 'Yıl'}, {value: '100+', label: 'Müşteri'}] }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'temizlik_services', order: 4, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 4, removable: false, animation: 'zoomIn' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'galeri', type: 'gallery', variant: 'masonry', order: 5, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 5, removable: true, animation: 'zoomIn' }, defaultContent: { badge: 'GALERİ', title: 'Çalışmalarımız', items: [{ id: 'g1', url: '/placeholder.jpg' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'detailed_form', order: 6, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 6, removable: false, animation: 'zoomIn' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905354004050" }, editableFields: [] }
    ]
  }]
}
