import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const TERZI_TADILAT_CSS: Record<string, string> = { '--color-bg': '#F5F0EB', '--color-surface': '#E8DFD4', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#D4C5B2', '--color-text': '#1C1408', '--color-text-secondary': '#5C4B32', '--color-text-muted': '#9E8855', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#92400E', '--color-accent-hover': '#78350F', '--color-accent-light': '#FFFBEB', '--color-border': '#D6D3D1', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const TERZI_TADILAT_BUSINESS: BusinessData = { name: 'Usta Terzi', ownerName: 'Hasan Dikiş', sector: 'terzi', slogan: 'Tadilat uzmanı', phone: '0533 400 50 60', phoneClean: '905334005060', whatsapp: '905334005060', email: 'info@terzitadilat.com.tr', address: 'Fatih Cad. No.22, Fatih, İstanbul', city: 'İstanbul', district: 'Fatih', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '09:00', close: '19:00' },{ day: 'tuesday', dayTr: 'Salı', open: '09:00', close: '19:00' },{ day: 'wednesday', dayTr: 'Çarşamba', open: '09:00', close: '19:00' },{ day: 'thursday', dayTr: 'Perşembe', open: '09:00', close: '19:00' },{ day: 'friday', dayTr: 'Cuma', open: '09:00', close: '19:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '10:00', close: '17:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/terzitadilat' }, photos: [], services: [{ id: 's1', name: 'Tadilat', icon: '🧵' },{ id: 's2', name: 'Ölçü', icon: '📏' }], team: [{ id: 't1', name: 'Hasan Dikiş', role: 'Terzi', experience: '15 yıl' }], experience: '15 yıl', rating: 4.9, reviewCount: 300, foundedYear: 2010 }
export const TERZI_TADILAT_CONFIG: ThemeConfig = { id: 'terzi-tadilat', name: 'Tadilat', sectorId: 'terzi', plan: 'free', description: 'Tadilat temalı terzi. Fatih.', designPhilosophy: 'Tadilat theme.', isDark: false, cssVariables: TERZI_TADILAT_CSS, fonts: { heading: { family: 'Merriweather', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'TailorShop', sectorSections: ['tailor_services_grid', 'fabric_showcase', 'tailor_portfolio', 'tailor_booking'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Usta Terzi 🧵' }, menuItems: [{ label: 'Hizmetler', href: '#hizmetler' },{ label: 'Randevu', href: '#randevu' }], cta: { text: 'Randevu', href: '#randevu', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Usta Terzi', copyright: '© 2024', contact: { phone: '0533 400 50 60', address: 'Fatih, İstanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/terzitadilat', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905334005060', message: 'Merhaba, randevu almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Çerez kullanıyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Usta Terzi — Fatih", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Fatih', title: "Usta Terzi", subtitle: "Tadilat uzmanı", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hakkimizda', type: 'about', variant: 'split_left', order: 2, required: false, settings: { bgMode: 'default', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: true, animation: 'fadeUp' }, defaultContent: { badge: 'HAKKIMIZDA', title: "Biz Kimiz?", description: "Yılların tecrübesiyle hizmetinizdeyiz." }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'terzi_services', order: 3, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 3, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'simple_form', order: 4, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 4, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905334005060" }, editableFields: [] }
    ]
  }]
}
