import type { ThemeConfig, BusinessData } from '../../types/section-types'
export const TERZI_ERKEK_CSS: Record<string, string> = { '--color-bg': '#F0F0F0', '--color-surface': '#E0E0E0', '--color-surface-elevated': '#FFFFFF', '--color-surface-muted': '#D0D0D0', '--color-text': '#111111', '--color-text-secondary': '#333333', '--color-text-muted': '#888888', '--color-text-on-accent': '#FFFFFF', '--color-accent': '#1E3A5F', '--color-accent-hover': '#0F2238', '--color-accent-light': '#EFF6FF', '--color-border': '#94A3B8', '--font-heading': "'Cormorant Garamond', serif", '--font-body': "'Inter', sans-serif", '--radius-card': '14px', '--radius-btn': '9999px' }
export const TERZI_ERKEK_BUSINESS: BusinessData = { name: 'Mr. Bespoke', ownerName: 'Ahmet Takım', sector: 'terzi', slogan: 'Erkek uzmanı', phone: '0534 111 22 33', phoneClean: '905341112233', whatsapp: '905341112233', email: 'info@terzierkek.com.tr', address: 'Teşvikiye Cad. No.40, Şişli, İstanbul', city: 'İstanbul', district: 'Teşvikiye', coordinates: { lat: 41.01, lng: 28.97 }, workingHours: [{ day: 'monday', dayTr: 'Pazartesi', open: '09:00', close: '19:00' },{ day: 'tuesday', dayTr: 'Salı', open: '09:00', close: '19:00' },{ day: 'wednesday', dayTr: 'Çarşamba', open: '09:00', close: '19:00' },{ day: 'thursday', dayTr: 'Perşembe', open: '09:00', close: '19:00' },{ day: 'friday', dayTr: 'Cuma', open: '09:00', close: '19:00' },{ day: 'saturday', dayTr: 'Cumartesi', open: '10:00', close: '17:00' },{ day: 'sunday', dayTr: 'Pazar', open: null, close: null }], socialMedia: { instagram: 'https://instagram.com/terzierkek' }, photos: [], services: [{ id: 's1', name: 'Erkek', icon: '🧵' },{ id: 's2', name: 'Ölçü', icon: '📏' }], team: [{ id: 't1', name: 'Ahmet Takım', role: 'Terzi', experience: '15 yıl' }], experience: '15 yıl', rating: 4.9, reviewCount: 300, foundedYear: 2010 }
export const TERZI_ERKEK_CONFIG: ThemeConfig = { id: 'terzi-erkek', name: 'Erkek', sectorId: 'terzi', plan: 'growth', description: 'Erkek temalı terzi. Teşvikiye.', designPhilosophy: 'Erkek theme.', isDark: false, cssVariables: TERZI_ERKEK_CSS, fonts: { heading: { family: 'Bodoni Moda', weights: [600, 700], subsets: ['latin-ext'] }, body: { family: 'Inter', weights: [400, 500], subsets: ['latin-ext'] } }, seoSchemaType: 'TailorShop', sectorSections: ['tailor_services_grid', 'fabric_showcase', 'tailor_portfolio', 'tailor_booking'], performanceBudget: { maxJS: '120kb', maxLCP: '2.2s', animationLevel: 'css-only' }, globalSections: [{ id: 'global-header', type: 'header', variant: 'minimal_sticky', order: 0, required: true, position: 'top', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 0, removable: false, animation: 'fadeUp' }, defaultContent: { logo: { type: 'text', text: 'Mr. Bespoke 🧵' }, menuItems: [{ label: 'Hizmetler', href: '#hizmetler' },{ label: 'Randevu', href: '#randevu' }], cta: { text: 'Randevu', href: '#randevu', variant: 'solid' } }, editableFields: [] },{ id: 'global-footer', type: 'footer', variant: 'warm_columns', order: 999, required: true, position: 'bottom', settings: { bgMode: 'surface', paddingY: 'sm', containerWidth: 'xl', visible: true, order: 999, removable: false, animation: 'fadeUp' }, defaultContent: { businessName: 'Mr. Bespoke', copyright: '© 2024', contact: { phone: '0534 111 22 33', address: 'Teşvikiye, İstanbul' }, social: [{ platform: 'instagram', url: 'https://instagram.com/terzierkek', icon: 'instagram' }], legal: [{ label: 'KVKK', href: '/kvkk' }], poweredBy: '⚡ kepenk.ai' }, editableFields: [] },{ id: 'global-whatsapp', type: 'whatsapp_cta', variant: 'floating', order: 1000, required: true, position: 'floating', settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1000, removable: false, animation: 'fadeUp' }, defaultContent: { phone: '905341112233', message: 'Merhaba, randevu almak istiyorum.' }, editableFields: [] },{ id: 'global-cookie', type: 'cookie_banner', variant: 'bottom_bar', order: 1001, required: true, position: 'floating', settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1001, removable: false, animation: 'fadeUp' }, defaultContent: { text: 'Çerez kullanıyoruz.', acceptText: 'Kabul', rejectText: 'Red', detailsLink: '/gizlilik' }, editableFields: [] }], pages: [{
    id: 'anasayfa', slug: '/', title: "Mr. Bespoke — Teşvikiye", titleTr: 'Ana Sayfa', isHomePage: true, includeInNav: false,
    sections: [
{ id: 'hero', type: 'hero', variant: 'split_image', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'xl', visible: true, order: 1, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'Teşvikiye', title: "Mr. Bespoke", subtitle: "Erkek uzmanı", cta1: { text: 'İletişim', href: '#iletisim' } }, editableFields: [] },
{ id: 'hizmetler', type: 'services', variant: 'terzi_services', order: 2, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 2, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'HİZMETLER', title: 'Hizmetlerimiz', services: [{ id: 's1', name: 'Premium Hizmet', description: 'Detaylı bilgi için iletişime geçin.', icon: 'star' }] }, editableFields: [] },
{ id: 'iletisim', type: 'contact', variant: 'simple_form', order: 3, required: true, settings: { bgMode: 'surface', paddingY: 'lg', containerWidth: 'xl', visible: true, order: 3, removable: false, animation: 'fadeUp' }, defaultContent: { badge: 'İLETİŞİM', title: 'Bize Ulaşın', whatsapp: "905341112233" }, editableFields: [] }
    ]
  }]
}
