import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const BERBER_STUDIO_CSS: Record<string, string> = {
  '--container-default': '1200px',
  '--section-py': '80px',
  '--radius-md': '12px',
  '--radius-lg': '24px',
  '--color-bg': '#0B0F19',
  '--color-surface': '#111827',
  '--color-surface-elevated': '#1F2937',
  '--color-surface-muted': '#0F172A',
  '--color-text': '#F9FAFB',
  '--color-text-secondary': '#9CA3AF',
  '--color-text-muted': '#4B5563',
  '--color-text-on-accent': '#0B0F19',
  '--color-text-on-dark': '#F9FAFB',
  '--color-accent': '#6366F1',
  '--color-accent-hover': '#4F46E5',
  '--color-accent-active': '#4338CA',
  '--color-accent-light': '#1E1B4B',
  '--color-border': '#374151',
  '--color-border-subtle': '#1F2937',
  '--font-heading': "'Syne', sans-serif",
  '--font-body': "'Plus Jakarta Sans', sans-serif",
}

export const BERBER_STUDIO_BUSINESS = {
  name: 'Studio Razor & Ink',
  ownerName: 'Caner Koç',
  sectorId: 'Berber',
  slogan: 'Saç tasarımı ve modern sokak stili',
  phone: '0212 666 01 15',
  phoneClean: '902126660115',
  whatsapp: '905336661115',
  email: 'caner@razorink.studio',
  address: 'Karaköy Mah. Rıhtım Cad. No:115, Beyoğlu/İstanbul',
  city: 'İstanbul',
  district: 'Beyoğlu',
  neighborhood: 'Karaköy',
  coordinates: { lat: 41.0253, lng: 28.9754 },
  socialMedia: { instagram: 'https://instagram.com/razorink.studio' },
  photos: [],
  foundedYear: 2021,
  experience: '8 yıl tecrübe',
  customerCount: '3.000+',
  rating: 4.9,
  reviewCount: 220,
  services: [
    {
      id: 's1',
      name: 'Fade Saç Kesimi (Sokak Stili)',
      price: '750 TL',
      duration: '45 dk',
      description: 'Profesyonel fade geçişli saç kesimi, kafa derisi masajı ve şekillendirici pomad bakımı.',
    },
    {
      id: 's2',
      name: 'Modern Sakal Tasarımı & Razor',
      price: '450 TL',
      duration: '25 dk',
      description: 'Sakal kontürünün ustura ile jilet gibi çizilmesi, nemlendirici krem bakımı.',
    },
    {
      id: 's3',
      name: 'Renk Değişimi & Platin Saç',
      price: '1.800 TL',
      duration: '90 dk',
      description: 'Modern tarzda saç rengi açma, platin, gri veya gri-mavi marjinal renklendirme.',
    },
    {
      id: 's4',
      name: 'Kulak & Burun Ağda Bakımı',
      price: '200 TL',
      duration: '10 dk',
      description: 'Kulak ve burun çevresindeki tüylerin profesyonelce arındırılması.',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '11:00', close: '22:00', isOpen: true },
    { day: 'Salı', open: '11:00', close: '22:00', isOpen: true },
    { day: 'Çarşamba', open: '11:00', close: '22:00', isOpen: true },
    { day: 'Perşembe', open: '11:00', close: '22:00', isOpen: true },
    { day: 'Cuma', open: '11:00', close: '22:00', isOpen: true },
    { day: 'Cumartesi', open: '11:00', close: '21:00', isOpen: true },
    { day: 'Pazar', open: '12:00', close: '19:00', isOpen: true },
  ],
} as unknown as BusinessData

export const BERBER_STUDIO_CONFIG = {
  id: 'berber-studio',
  name: 'Studio',
  sectorId: 'berber',
  plan: 'growth',
  description: 'Genç, enerjik ve sokak modası esintili modern kuaför stüdyosu şablonu',
  designPhilosophy: 'Neon mor tonları, modern Syne yazı tipi ve fütüristik çizgiler',
  isDark: true,
  cssVariables: BERBER_STUDIO_CSS,
  fonts: {
    heading: {
      family: 'Syne',
      weights: [700, 800],
      subsets: ['latin'],
    },
    body: {
      family: 'Plus Jakarta Sans',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'BarberShop',
  sectorSections: ['before_after', 'booking'],
  performanceBudget: {
    maxJS: '120kb',
    maxLCP: '2.2s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: BERBER_STUDIO_BUSINESS.name },
        menuItems: [
          { label: 'Servisler', href: '#hizmetler' },
          { label: 'Stilistler', href: '#ekip' },
          { label: 'Rezervasyon', href: '#iletisim' },
        ],
        cta: { text: 'Randevu', href: 'https://wa.me/905336661115', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'dark', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: BERBER_STUDIO_BUSINESS.name,
        copyright: '© 2026 Studio Razor & Ink. Tüm hakları saklıdır.',
        contact: {
          phone: BERBER_STUDIO_BUSINESS.phone,
          email: BERBER_STUDIO_BUSINESS.email,
          address: BERBER_STUDIO_BUSINESS.address,
        },
        social: [{ platform: 'instagram', url: 'https://instagram.com/razorink.studio', icon: 'instagram' }],
        legal: [
          { label: 'Gizlilik Bildirimi', href: '/gizlilik' },
          { label: 'KVKK Hakları', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1000, removable: false, animation: 'none' },
      defaultContent: { phone: '905336661115', message: 'Karaköy şubesi saç sakal tasarımı randevusu almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${BERBER_STUDIO_BUSINESS.name} — Karaköy Fütüristik Saç Stüdyosu`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'NEON RİTÜELİ',
            title: BERBER_STUDIO_BUSINESS.name,
            subtitle: BERBER_STUDIO_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Stüdyo İsmi', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
          ],
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: {
            badge: 'SOKAK MODASI',
            title: 'Razor & Ink Felsefesi',
          },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'FADE MENÜSÜ',
            title: 'Modern Sokak Tarzları',
          },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'REZERVASYON',
            title: 'Koltuktaki Yerinizi Ayırın',
          },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
