/**
 * @kepenk/templates — spor-studio Theme Configuration
 *
 * Butik fitness stüdyosu, kisisel hizmet
 * Plan: starter (6 page sections, 4 global sections)
 * Font: Outfit/Inter | Accent: #EA580C
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const SPOR_STUDIO_CSS: Record<string, string> = {
  '--container-default': '1200px',
  '--section-py': '96px',
  '--radius-md': '2px',
  '--radius-lg': '4px',
  '--color-bg': '#1C1917',
  '--color-surface': '#292524',
  '--color-surface-elevated': '#44403C',
  '--color-surface-muted': '#171717',
  '--color-text': '#FAFAF9',
  '--color-text-secondary': '#D6D3D1',
  '--color-text-muted': '#78716C',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#EA580C',
  '--color-accent-hover': '#EA580C',
  '--color-accent-active': '#EA580C',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#57534E',
  '--color-border-subtle': '#44403C',
  '--font-heading': '\'Outfit\', sans-serif',
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const SPOR_STUDIO_BUSINESS = {
  name: 'FitStudio Butik Spor',
  ownerName: 'Elif Dogan',
  sectorId: 'Spor',
  slogan: 'Kucuk grup, buyuk sonuclar',
  phone: '0212 280 44 55',
  phoneClean: '902122804455',
  whatsapp: '905441234567',
  email: 'info@fitstudio.com.tr',
  address: 'Cihangir Mah. Akarsu Cad. No:20/1, Beyoglu/Istanbul',
  city: 'Istanbul',
  district: 'Beyoglu',
  neighborhood: 'Cihangir',
  coordinates: { lat: 41.0318, lng: 28.9836 },
  socialMedia: { instagram: 'https://instagram.com/fitstudioist', youtube: 'https://youtube.com/@fitstudio' },
  photos: [],
  foundedYear: 2019,
  experience: '7 yil',
  customerCount: '3.200+',
  rating: 4.9,
  reviewCount: 620,
  services: [
    {
      id: 's1',
      name: 'Reformer Pilates',
      price: '350 TL/ders',
      duration: '55 dk',
      description: 'Kucuk grup (max 6 kisi) reformer pilates dersleri. Core guclendirme, esneklik ve postür düzeltme.',
    },
    {
      id: 's2',
      name: 'HIIT Fonksiyonel',
      price: '250 TL/ders',
      duration: '45 dk',
      description: 'Yuksek yogunluklu aralikli antrenman. Kucuk gruplarla (max 10) kardio ve guc birlesimi.',
    },
    {
      id: 's3',
      name: 'Yoga',
      price: '300 TL/ders',
      duration: '60 dk',
      description: 'Vinyasa, Hatha ve Yin yoga dersleri. Nefes calismasi, esneklik ve zihinsel denge.',
    },
    {
      id: 's4',
      name: '1-1 Personal Training',
      price: '700 TL/seans',
      duration: '60 dk',
      description: 'Birebir kisisel antrenman. Kisiye ozel program, beslenme rehberligi ve ilerleme takibi.',
    },
    {
      id: 's5',
      name: '10\'lu Ders Paketi',
      price: '2.800 TL',
      duration: '10 ders',
      description: 'Herhangi bir grup dersinden 10 ders paketi. 3 ay gecerlilik suresi. %20 indirimli.',
    },
    {
      id: 's6',
      name: 'Aylik Sinirsiz Uyelik',
      price: '2.200 TL/ay',
      duration: 'Sinirsiz',
      description: 'Tum grup derslerine sinirsiz katilim. Rezervasyon onceligi ve ucretsiz beslenme danismanligi.',
    },
  ],
  team: [
    {
      name: 'Elif Dogan',
      title: 'Kurucu | Pilates & Yoga Egitmeni',
      bio: 'ACE sertifkali fitness egitmeni. 7 yildir pilates ve yoga egitimi veriyor. 200 saat YTT Yoga sertifikasi.',
      photo: '',
    },
    {
      name: 'Can Erturk',
      title: 'HIIT & Fonksiyonel Antrenor',
      bio: 'CrossFit Level 2, NASM-CPT. 5 yillik antrenorlik deneyimi. TRX ve kettlebell uzmani.',
      photo: '',
    },
  ],
  workingHours: [
    {
      day: 'Pazartesi',
      open: '07:00',
      close: '21:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '07:00',
      close: '21:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '07:00',
      close: '21:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '07:00',
      close: '21:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '07:00',
      close: '21:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '09:00',
      close: '16:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '10:00',
      close: '14:00',
      isOpen: true,
    },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const SPOR_STUDIO_CONFIG = {
  id: 'spor-studio',
  name: 'Studio',
  sectorId: 'spor',
  plan: 'starter',
  description: 'Butik fitness stüdyosu, kisisel hizmet',
  designPhilosophy: 'Sicak, kisisel, motivasyonel',
  isDark: false,
  cssVariables: {
    '--container-default': '1200px',
    '--section-py': '96px',
    '--radius-md': '2px',
    '--radius-lg': '4px',
    '--color-bg': '#1C1917',
    '--color-surface': '#292524',
    '--color-surface-elevated': '#44403C',
    '--color-surface-muted': '#171717',
    '--color-text': '#FAFAF9',
    '--color-text-secondary': '#D6D3D1',
    '--color-text-muted': '#78716C',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#EA580C',
    '--color-accent-hover': '#EA580C',
    '--color-accent-active': '#EA580C',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#57534E',
    '--color-border-subtle': '#44403C',
    '--font-heading': '\'Outfit\', sans-serif',
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Outfit',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'SportsActivityLocation',
  sectorSections: ['class_schedule', 'membership_pricing'],
  performanceBudget: {
    maxJS: '120kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-basic',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'FitStudio Butik Spor' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905441234567',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'FitStudio Butik Spor',
        copyright: '© 2026 FitStudio Butik Spor',
        contact: {
          phone: '0212 280 44 55',
          email: 'info@fitstudio.com.tr',
          address: 'Cihangir Mah. Akarsu Cad. No:20/1, Beyoglu/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/fitstudioist',
            icon: 'instagram',
          },
          {
            platform: 'youtube',
            url: 'https://youtube.com/@fitstudio',
            icon: 'youtube',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905441234567', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'FitStudio Butik Spor — Beyoglu',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_editorial_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'ÖZEL KONSEPT', title: SPOR_STUDIO_BUSINESS.name, subtitle: SPOR_STUDIO_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'about',
          variant: 'tier1_editorial_about',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { title: 'Felsefemiz' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_editorial_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'ATELIER', title: 'Seçkin Koleksiyon' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_editorial_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'text', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { title: 'Randevu & Danışmanlık' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
