/**
 * @kepenk/templates — boyaci-lux Theme Configuration
 *
 * Premium boyama ve dekorasyon grubu
 * Plan: enterprise (14 page sections, 4 global sections)
 * Font: Cormorant Garamond/Inter | Accent: #C9A84C
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const BOYACI_LUX_CSS: Record<string, string> = {
  '--container-default': '1200px',
  '--section-py': '96px',
  '--radius-md': '2px',
  '--radius-lg': '4px',
  '--color-bg': '#FAFAF9',
  '--color-surface': '#F5F5F4',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#E7E5E4',
  '--color-text': '#1C1917',
  '--color-text-secondary': '#57534E',
  '--color-text-muted': '#A8A29E',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F0EDE8',
  '--color-accent': '#40931f',
  '--color-accent-hover': '#D4B85C',
  '--color-accent-active': '#C9A84C',
  '--color-accent-light': '#1A1808',
  '--color-border': '#D6D3D1',
  '--color-border-subtle': '#E7E5E4',
  '--font-heading': '\'Cormorant Garamond\', sans-serif',
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const BOYACI_LUX_BUSINESS = {
  name: 'ColorElite Premium Boyama ve Dekorasyon',
  ownerName: 'Sinan Erkoc',
  sectorId: 'Boyaci',
  slogan: 'Rengin en rafine hali',
  phone: '0532 845 12 34',
  phoneClean: '905328451234',
  whatsapp: '905328451234',
  email: 'info@colorelite.com.tr',
  address: 'Maslak Mah. Eski Buyukdere Cad. No:65 Maslak 1453 B Blok Kat:12, Sariyer/Istanbul',
  city: 'Istanbul',
  district: 'Sariyer',
  neighborhood: 'Maslak',
  coordinates: { lat: 41.1085, lng: 29.02 },
  socialMedia: {
    instagram: 'https://instagram.com/colorelite',
    linkedin: 'https://linkedin.com/company/colorelite',
    pinterest: 'https://pinterest.com/colorelite',
  },
  photos: [],
  foundedYear: 1995,
  experience: '29 yil',
  customerCount: '12.000+',
  rating: 4.9,
  reviewCount: 1850,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '08:00',
      close: '19:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '09:00',
      close: '15:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: 'Kapali',
      close: 'Kapali',
      isOpen: false,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'VIP Konut Boyama Paketi',
      price: '150 TL/m2',
      duration: '5-10 gun',
      description: 'Mobilya koruma, premium malzeme, renk danismanligi ve detay iscilik dahil ust segment konut boyama.',
    },
    {
      id: 's2',
      name: 'Luks Villa Komple Boyama',
      price: '200.000 TL',
      duration: '15-25 gun',
      description: 'Ic ve dis cephe, garaj, peyzaj duvar dahil villa projesi.',
    },
    {
      id: 's3',
      name: 'Otel ve Resort Boyama',
      price: 'Projeye Ozel',
      duration: '30-60 gun',
      description: '5 yildizli otel, butik otel ve resort projelerine ozel boyama cozumleri.',
    },
    {
      id: 's4',
      name: 'Italyan Dekoratif Siva',
      price: '250 TL/m2',
      duration: '3-7 gun',
      description: 'San Marco ve Candis ithal dekoratif sivalar ile ust segment uygulamalar.',
    },
    {
      id: 's5',
      name: 'Saray Tavan ve Kartonpiyer Boyama',
      price: '350 TL/m2',
      duration: '5-10 gun',
      description: 'Alci tavan susleri, kartonpiyer ve rozet boyama ile varak uygulamasi.',
    },
    {
      id: 's6',
      name: 'Antika Restorasyon Boyama',
      price: '5.000 TL/parca',
      duration: '5-15 gun',
      description: 'Antika mobilya, kapi ve ahsap aksam orijinal renk restorasyonu.',
    },
    {
      id: 's7',
      name: 'Epoksi Sanat Zemin',
      price: '300 TL/m2',
      duration: '3-7 gun',
      description: '3D gorunumlu, metalik ve mermer efektli sanatsal epoksi zemin uygulamasi.',
    },
    {
      id: 's8',
      name: 'Dis Cephe Premium Boyama',
      price: '85 TL/m2',
      duration: '10-20 gun',
      description: 'Bina dis cephesi icin premium silikon bazli boyalar ile uzun omurlu uygulama.',
    },
    {
      id: 's9',
      name: 'Ofis ve Plaza Boyama',
      price: 'Projeye Ozel',
      duration: '10-30 gun',
      description: 'Kurumsal renk kilavuzuna uygun plaza ve ofis ic cephe boyama.',
    },
    {
      id: 's10',
      name: 'AVM ve Magaza Boyama',
      price: 'Projeye Ozel',
      duration: 'Gece Calismasi',
      description: 'Perakende mekanlar icin gece calismasi ile isletme aksatmadan boyama.',
    },
    {
      id: 's11',
      name: 'Hastane ve Saglik Tesisi Boyama',
      price: '80 TL/m2',
      duration: '10-20 gun',
      description: 'Antibakteriyel ve hijyenik boyalarla saglik tesisi boyama.',
    },
    {
      id: 's12',
      name: 'Okul ve Kreser Boyama',
      price: '55 TL/m2',
      duration: '5-10 gun',
      description: 'Cocuk dostu, kokusuz ve alerjen icermeyen boyalarla egitim kurumu boyama.',
    },
    {
      id: 's13',
      name: 'Cami ve Ibadet Yeri Boyama',
      price: 'Projeye Ozel',
      duration: '15-30 gun',
      description: 'Dini mekanlar icin ozel motif, hat ve susleme boyama.',
    },
    {
      id: 's14',
      name: 'Tarihi Yapi Restorasyon Boyama',
      price: 'Projeye Ozel',
      duration: '30-90 gun',
      description: 'Koruma kurulu onayli tarihi bina ve konak boyama restorasyonu.',
    },
    {
      id: 's15',
      name: 'Renk Danismanligi ve Proje Yonetimi',
      price: '10.000 TL',
      duration: '3-5 gun',
      description: 'Buyuk projeler icin renk paleti olusturma, malzeme secimi ve is programi hazirlama.',
    },
    {
      id: 's16',
      name: 'Yat ve Tekne Boyama',
      price: '200 TL/m2',
      duration: '10-20 gun',
      description: 'Luks yat ve tekneler icin gelcoat, antifouling ve kozmetik boyama.',
    },
    {
      id: 's17',
      name: 'Havuz ve Spa Boyama',
      price: '180 TL/m2',
      duration: '5-10 gun',
      description: 'Yuzme havuzu ve spa alanlari icin kloura dayanikli ozel kaplama.',
    },
    {
      id: 's18',
      name: 'Teras ve Balkon Boyama',
      price: '70 TL/m2',
      duration: '2-4 gun',
      description: 'Dis mekana dayanikli zemin ve duvar boyama uygulamasi.',
    },
    {
      id: 's19',
      name: 'Garanti Bakim Programi',
      price: '15.000 TL/yil',
      duration: 'Yillik',
      description: 'Yillik kontrole, kucuk onarimlar ve retus dahil VIP bakim programi.',
    },
    {
      id: 's20',
      name: 'Acil Hasar Onarim',
      price: 'Projeye Ozel',
      duration: '1-3 gun',
      description: 'Su baskin, yangin ve diger hasarlardan sonra acil boya ve restorasyon mudahalesi.',
    },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const BOYACI_LUX_CONFIG = {
  id: 'boyaci-lux',
  name: 'Lux',
  sectorId: 'boyaci',
  plan: 'enterprise',
  description: 'Premium boyama ve dekorasyon grubu',
  designPhilosophy: 'Luks, prestijli, ust segment',
  isDark: true,
  cssVariables: {
    '--container-default': '1200px',
    '--section-py': '96px',
    '--radius-md': '2px',
    '--radius-lg': '4px',
    '--color-bg': '#FAFAF9',
    '--color-surface': '#F5F5F4',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#E7E5E4',
    '--color-text': '#1C1917',
    '--color-text-secondary': '#57534E',
    '--color-text-muted': '#A8A29E',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F0EDE8',
    '--color-accent': '#C9A84C',
    '--color-accent-hover': '#D4B85C',
    '--color-accent-active': '#C9A84C',
    '--color-accent-light': '#1A1808',
    '--color-border': '#D6D3D1',
    '--color-border-subtle': '#E7E5E4',
    '--font-heading': '\'Cormorant Garamond\', sans-serif',
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Cormorant Garamond',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'HousePainter',
  sectorSections: [],
  performanceBudget: {
    maxJS: '350kb',
    maxLCP: '2.5s',
    animationLevel: 'gsap-allowed',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'ColorElite Premium Boyama ve Dekorasyon' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905328451234',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'ColorElite Premium Boyama ve Dekorasyon',
        copyright: '© 2026 ColorElite Premium Boyama ve Dekorasyon',
        contact: {
          phone: '0532 845 12 34',
          email: 'info@colorelite.com.tr',
          address: 'Maslak Mah. Eski Buyukdere Cad. No:65 Maslak 1453 B Blok Kat:12, Sariyer/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/colorelite',
            icon: 'instagram',
          },
          {
            platform: 'linkedin',
            url: 'https://linkedin.com/company/colorelite',
            icon: 'linkedin',
          },
          {
            platform: 'pinterest',
            url: 'https://pinterest.com/colorelite',
            icon: 'pinterest',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905328451234', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'ColorElite Premium Boyama ve Dekorasyon — Sariyer',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_editorial_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'ÖZEL KONSEPT', title: BOYACI_LUX_BUSINESS.name, subtitle: BOYACI_LUX_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'about',
          variant: 'tier1_editorial_about',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { title: 'Felsefemiz' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_editorial_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'ATELIER', title: 'Seçkin Koleksiyon' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_editorial_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'text', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { title: 'Randevu & Danışmanlık' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
