import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const ORGANIK_PAZAR_BUSINESS: BusinessData = {
  name: 'Organik Pazar',
  ownerName: 'Mehmet Pazar',
  sectorId: 'organik',
  slogan: 'Dogal organik urunler',
  phone: '0532 400 11 22',
  phoneClean: '905324001122',
  whatsapp: '905324001122',
  email: 'info@organikpazar.com',
  address: 'Caferaga Mah. No:5, Kadikoy, Istanbul',
  city: 'Istanbul',
  district: 'Kadikoy',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"07:00","close":"20:00"},{"day":"tuesday","dayTr":"Sali","open":"07:00","close":"20:00"},{"day":"wednesday","dayTr":"Carsamba","open":"07:00","close":"20:00"},{"day":"thursday","dayTr":"Persembe","open":"07:00","close":"20:00"},{"day":"friday","dayTr":"Cuma","open":"07:00","close":"20:00"},{"day":"saturday","dayTr":"Cumartesi","open":"07:00","close":"20:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/organik-pazar"},
  photos: [],
  services: []
}
export const ORGANIK_PAZAR_CONFIG: ThemeConfig = { id: 'organik-pazar', name: 'Organik Pazar', sectorId: 'organik', plan: 'free', isDark: false, cssVariables: { '--color-bg': '#FFFFFF', '--color-surface': '#F8FAFC', '--color-text': '#0F172A', '--color-accent': '#10B981',
    '--color-accent-light': '#e9fce8',
    '--color-accent-hover': '#348e2f',
    '--color-accent-active': '#2e7e2a', '--color-text-on-accent': '#FFFFFF', '--color-border': '#E2E8F0', '--font-heading': "'Inter', sans-serif", '--font-body': "'Inter', sans-serif" }, fonts: { heading: { family: 'DM Sans', weights: [700] }, body: { family: 'DM Sans', weights: [500] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Organik Pazar' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Organik Pazar',
        copyright: '© 2026 Organik Pazar',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'Köy Pazarı', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'xl', containerWidth: 'xl', visible: true }, defaultContent: { badge: 'TAZE SEBZE', title: 'Günlük Toplanan Organik Ürünler' } } ] }] }