import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const NAKLIYAT_OFIS_BUSINESS: BusinessData = {
  name: 'Ofis Nakliyat',
  ownerName: 'Selim Ofis',
  sectorId: 'nakliyat',
  slogan: 'Ofis tasima uzmani',
  phone: '0533 500 22 33',
  phoneClean: '905335002233',
  whatsapp: '905335002233',
  email: 'iletisim@ofisnakliyat.com',
  address: 'Kartal Mah. No:15, Kartal, Istanbul',
  city: 'Istanbul',
  district: 'Kartal',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"07:00","close":"20:00"},{"day":"tuesday","dayTr":"Sali","open":"07:00","close":"20:00"},{"day":"wednesday","dayTr":"Carsamba","open":"07:00","close":"20:00"},{"day":"thursday","dayTr":"Persembe","open":"07:00","close":"20:00"},{"day":"friday","dayTr":"Cuma","open":"07:00","close":"20:00"},{"day":"saturday","dayTr":"Cumartesi","open":"07:00","close":"20:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/nakliyat-ofis"},
  photos: [],
  services: []
}
export const NAKLIYAT_OFIS_CONFIG: ThemeConfig = { id: 'nakliyat-ofis', name: 'Kurumsal Taşıma', sectorId: 'nakliyat', plan: 'pro', isDark: false, cssVariables: { '--color-bg': '#FFFFFF', '--color-surface': '#F8FAFC', '--color-text': '#0F172A', '--color-accent': '#b31973',
    '--color-accent-light': '#fce8f4',
    '--color-accent-hover': '#8f145c',
    '--color-accent-active': '#7d1250', '--color-text-on-accent': '#FFFFFF', '--color-border': '#E2E8F0', '--font-heading': "'Inter', sans-serif", '--font-body': "'Roboto', sans-serif" }, fonts: { heading: { family: 'Raleway', weights: [700] }, body: { family: 'Roboto', weights: [400] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Ofis Nakliyat' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Ofis Nakliyat',
        copyright: '© 2026 Ofis Nakliyat',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'Ofis Nakliyat', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true }, defaultContent: { badge: 'KURUMSAL', title: 'İşinize Ara Vermeden Uzman Taşıma' } } ] }] }