import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const ORGANIZASYON_LUX_BUSINESS: BusinessData = {
  name: 'Lux Organizasyon',
  ownerName: 'Baris Lux',
  sectorId: 'organizasyon',
  slogan: 'Premium organizasyon',
  phone: '0536 200 55 66',
  phoneClean: '905362005566',
  whatsapp: '905362005566',
  email: 'destek@luxorg.com',
  address: 'Halaskargazi Cad. No:40, Sisli, Istanbul',
  city: 'Istanbul',
  district: 'Sisli',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"09:00","close":"21:00"},{"day":"tuesday","dayTr":"Sali","open":"09:00","close":"21:00"},{"day":"wednesday","dayTr":"Carsamba","open":"09:00","close":"21:00"},{"day":"thursday","dayTr":"Persembe","open":"09:00","close":"21:00"},{"day":"friday","dayTr":"Cuma","open":"09:00","close":"21:00"},{"day":"saturday","dayTr":"Cumartesi","open":"09:00","close":"21:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/organizasyon-lux"},
  photos: [],
  services: []
}
export const ORGANIZASYON_LUX_CONFIG: ThemeConfig = { id: 'organizasyon-lux', name: 'VIP Davet (Lounge)', sectorId: 'organizasyon', plan: 'elite', isDark: true, cssVariables: { '--color-bg': '#FAFAF9', '--color-surface': '#F5F5F4', '--color-text': '#1C1917', '--color-accent': '#D4AF37',
    '--color-accent-light': '#2b2e1f',
    '--color-accent-hover': '#7e8e2f',
    '--color-accent-active': '#707e2a', '--color-text-on-accent': '#000000', '--color-border': '#D6D3D1', '--font-heading': "'Syne', sans-serif", '--font-body': "'Inter', sans-serif" }, fonts: { heading: { family: 'Syne', weights: [700] }, body: { family: 'Inter', weights: [300] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Lux Organizasyon' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Lux Organizasyon',
        copyright: '© 2026 Lux Organizasyon',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'Exclusive Events', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true }, defaultContent: { badge: 'VIP INVITATION', title: 'Elit Davetler İçin Lüks Çözümler' } } ] }] }