import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

export const RESTORAN_LEZZET_CSS: Record<string, string> = {
  '--container-default': '1120px',
  '--section-py': '80px',
  '--radius-md': '8px',
  '--radius-lg': '16px',
  '--color-bg': '#FAF6F0',
  '--color-surface': '#FFFFFF',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#EFECE6',
  '--color-text': '#2C1B15',
  '--color-text-secondary': '#6B5A51',
  '--color-text-muted': '#A89B92',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#FAF6F0',
  '--color-accent': '#C2410C',
  '--color-accent-hover': '#9A3412',
  '--color-accent-active': '#7C2D12',
  '--color-accent-light': '#FFEDD5',
  '--color-border': '#EAE1D8',
  '--color-border-subtle': '#F5EFE6',
  '--font-heading': "'Playfair Display', serif",
  '--font-body': "'Inter', sans-serif",
}

export const RESTORAN_LEZZET_BUSINESS = {
  name: 'Lezzet-i Şahane Kebap & Lahmacun',
  ownerName: 'Süleyman Usta',
  sectorId: 'Restoran',
  slogan: 'Odun ateşinde pişen eşsiz kebap lezzetleri',
  phone: '0212 555 12 14',
  phoneClean: '902125551214',
  whatsapp: '905335551214',
  email: 'iletisim@lezzetisahane.com',
  address: 'Fatih Cad. No:88/A, Fatih/İstanbul',
  city: 'İstanbul',
  district: 'Fatih',
  neighborhood: 'Mimar Sinan',
  coordinates: { lat: 41.0182, lng: 28.9431 },
  socialMedia: { instagram: 'https://instagram.com/lezzetisahane.kebap' },
  photos: [],
  foundedYear: 2005,
  experience: '19 yıldır',
  customerCount: '50.000+',
  rating: 4.8,
  reviewCount: 1250,
  services: [
    {
      id: 's1',
      name: 'Adana Kebap (Zırh Kıyma)',
      price: '380 TL',
      duration: '15 dk',
      description: 'Zırhla çekilmiş kuzu eti, közlenmiş biber ve domates, özel tırnak pide eşliğinde.',
    },
    {
      id: 's2',
      name: 'Çıtır Taş Fırın Lahmacun',
      price: '110 TL',
      duration: '8 dk',
      description: 'Özel baharatlı kıyma harcı, incecik açılmış hamur, odun ateşinde taş fırında çıtır çıtır.',
    },
    {
      id: 's3',
      name: 'Karışık Kebap Tepsisi (2 Kişilik)',
      price: '950 TL',
      duration: '25 dk',
      description: 'Adana, tavuk şiş, kuzu şiş, kanat ve döner. Pilav, közlenmiş sebzeler ve yeşillik ile.',
    },
    {
      id: 's4',
      name: 'Fıstıklı Ev Yapımı Baklava',
      price: '180 TL',
      duration: '5 dk',
      description: 'Gaziantep boz fıstığı ile hazırlanmış, tereyağlı çıtır sıcak şerbetli ev baklavası (2 dilim).',
    },
  ],
  workingHours: [
    { day: 'Pazartesi', open: '11:00', close: '23:00', isOpen: true },
    { day: 'Salı', open: '11:00', close: '23:00', isOpen: true },
    { day: 'Çarşamba', open: '11:00', close: '23:00', isOpen: true },
    { day: 'Perşembe', open: '11:00', close: '23:00', isOpen: true },
    { day: 'Cuma', open: '11:00', close: '23:00', isOpen: true },
    { day: 'Cumartesi', open: '11:00', close: '23:30', isOpen: true },
    { day: 'Pazar', open: '11:00', close: '22:30', isOpen: true },
  ],
} as unknown as BusinessData

export const RESTORAN_LEZZET_CONFIG = {
  id: 'restoran-lezzet',
  name: 'Lezzet',
  sectorId: 'restoran',
  plan: 'pro',
  description: 'Kebapçı, lahmacun ve geleneksel Türk mutfağı restoranları için sıcak iştah açıcı şablon',
  designPhilosophy: 'Sıcak kiremit kırmızısı/turuncu tonları, asil Playfair Display başlıkları, iştah açıcı görsel düzen',
  isDark: false,
  cssVariables: RESTORAN_LEZZET_CSS,
  fonts: {
    heading: {
      family: 'Playfair Display',
      weights: [600, 700],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'Restaurant',
  sectorSections: ['menu_display', 'daily_special', 'reservation'],
  performanceBudget: {
    maxJS: '100kb',
    maxLCP: '2.5s',
    animationLevel: 'framer-basic',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 0, removable: false, animation: 'none' },
      defaultContent: {
        logo: { type: 'text', text: RESTORAN_LEZZET_BUSINESS.name },
        menuItems: [
          { label: 'Yemek Menüsü', href: '#hizmetler' },
          { label: 'Hikayemiz', href: '#hakkimizda' },
          { label: 'Rezervasyon', href: '#iletisim' },
        ],
        cta: { text: 'Paket Servis', href: 'tel:902125551214', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: { bgMode: 'dark', paddingY: 'sm', containerWidth: 'full', visible: true, order: 999, removable: false, animation: 'none' },
      defaultContent: {
        businessName: RESTORAN_LEZZET_BUSINESS.name,
        copyright: '© 2026 Lezzet-i Şahane Kebap & Lahmacun. Tüm hakları saklıdır.',
        contact: {
          phone: RESTORAN_LEZZET_BUSINESS.phone,
          email: RESTORAN_LEZZET_BUSINESS.email,
          address: RESTORAN_LEZZET_BUSINESS.address,
        },
        social: [{ platform: 'instagram', url: 'https://instagram.com/lezzetisahane.kebap', icon: 'instagram' }],
        legal: [
          { label: 'Kullanım Sözleşmesi', href: '/sartlar' },
          { label: 'KVKK Kuralları', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1000, removable: false, animation: 'none' },
      defaultContent: { phone: '905335551214', message: 'Evlere paket servis siparişi vermek istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: `${RESTORAN_LEZZET_BUSINESS.name} — Fatih Odun Ateşi Lahmacun`,
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_asymmetric_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'TAŞ FIRINDAN SOFRAYA',
            title: RESTORAN_LEZZET_BUSINESS.name,
            subtitle: RESTORAN_LEZZET_BUSINESS.slogan,
          },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Alt Başlık / Açıklama', type: 'richtext' },
          ],
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_asymmetric_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: {
            badge: '20 YILLIK USTALIK',
            title: 'Kebaba Hayat Veren Geleneksel Tarif',
          },
          editableFields: [
            { path: 'badge', label: 'Küçük Rozet', type: 'text' },
            { path: 'title', label: 'Galeri Bölüm Başlığı', type: 'text' },
          ],
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_asymmetric_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'YEMEK MENÜSÜ',
            title: 'Zırhtan Çıkan Gurme Kebap Kartımız',
          },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' },
          ],
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_asymmetric_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: {
            badge: 'REZERVASYON YAPIN',
            title: 'Sıcak Taş Fırın Sofrasına Rezervasyon Alın',
          },
          editableFields: [
            { path: 'badge', label: 'Etiket', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' },
          ],
        },
      ],
    },
  ],
} as unknown as ThemeConfig
