/**
 * @kepenk/templates — boyaci-ev Theme Configuration
 *
 * Ev boyama ve badana hizmeti
 * Plan: free (3 page sections, 3 global sections)
 * Font: Inter/Inter | Accent: #3B82F6
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const BOYACI_EV_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#3B82F6',
  '--color-accent-hover': '#3B82F6',
  '--color-accent-active': '#3B82F6',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': "'Montserrat', sans-serif",
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const BOYACI_EV_BUSINESS = {
  name: 'Usta Boyaci Mehmet',
  ownerName: 'Mehmet Karatas',
  sectorId: 'Boyaci',
  slogan: 'Evinize renk, hayatiniza enerji',
  phone: '0532 845 12 30',
  phoneClean: '905328451230',
  whatsapp: '905328451230',
  email: 'info@ustaboyacimehmet.com',
  address: 'Osmanaga Mah. Bahariye Cad. No:112/B, Kadikoy/Istanbul',
  city: 'Istanbul',
  district: 'Kadikoy',
  neighborhood: 'Osmanaga',
  coordinates: { lat: 40.9905, lng: 29.028 },
  socialMedia: { instagram: 'https://instagram.com/ustaboyacimehmet' },
  photos: [],
  foundedYear: 2010,
  experience: '14 yil',
  customerCount: '3.200+',
  rating: 4.6,
  reviewCount: 410,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '08:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '08:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '08:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '08:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '08:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '09:00',
      close: '15:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: 'Kapali',
      close: 'Kapali',
      isOpen: false,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Ic Cephe Boyama',
      price: '35 TL/m2',
      duration: '1-3 gun',
      description: 'Tavan ve duvar boyama, macun ve astar dahil komple ic cephe boyama hizmeti.',
    },
    {
      id: 's2',
      name: 'Badana',
      price: '20 TL/m2',
      duration: '1-2 gun',
      description: 'Ekonomik badana uygulamasi. Kirac ve ev sahipleri icin uygun fiyatli cozum.',
    },
    {
      id: 's3',
      name: 'Alci ve Macun Islemleri',
      price: '45 TL/m2',
      duration: '1-2 gun',
      description: 'Duvar catlaklari, derz bosluklari ve yuzey duzeltme islemleri.',
    },
    {
      id: 's4',
      name: 'Tavan Boyama',
      price: '30 TL/m2',
      duration: '1 gun',
      description: 'Tavan yuzeyinin temizlenmesi, astarlanmasi ve boyanmasi.',
    },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const BOYACI_EV_CONFIG = {
  id: 'boyaci-ev',
  name: 'Ev',
  sectorId: 'boyaci',
  plan: 'free',
  description: 'Ev boyama ve badana hizmeti',
  designPhilosophy: 'Sade, temiz, pratik',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#3B82F6',
    '--color-accent-hover': '#3B82F6',
    '--color-accent-active': '#3B82F6',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': "'Montserrat', sans-serif",
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Montserrat',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'HousePainter',
  sectorSections: [],
  performanceBudget: {
    maxJS: '80kb',
    maxLCP: '3.0s',
    animationLevel: 'css-only',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Usta Boyaci Mehmet' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'İletişim', href: '#iletisim' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905328451230',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Usta Boyaci Mehmet',
        copyright: '© 2026 Usta Boyaci Mehmet',
        contact: {
          phone: '0532 845 12 30',
          email: 'info@ustaboyacimehmet.com',
          address: 'Osmanaga Mah. Bahariye Cad. No:112/B, Kadikoy/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/ustaboyacimehmet',
            icon: 'instagram',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905328451230', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Usta Boyaci Mehmet — Kadikoy',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: BOYACI_EV_BUSINESS.name, subtitle: BOYACI_EV_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
