import type { ThemeConfig, BusinessData } from '../../../../types/section-types'
export const ORGANIZASYON_FIRMA_BUSINESS: BusinessData = {
  name: 'Firma Etkinlik',
  ownerName: 'Tolga Etkinlik',
  sectorId: 'organizasyon',
  slogan: 'Kurumsal etkinlik yonetimi',
  phone: '0534 200 33 44',
  phoneClean: '905342003344',
  whatsapp: '905342003344',
  email: 'bilgi@firmaetkinlik.com',
  address: 'Bagdat Cad. No:30, Kadikoy, Istanbul',
  city: 'Istanbul',
  district: 'Kadikoy',
  workingHours: [{"day":"monday","dayTr":"Pazartesi","open":"09:00","close":"21:00"},{"day":"tuesday","dayTr":"Sali","open":"09:00","close":"21:00"},{"day":"wednesday","dayTr":"Carsamba","open":"09:00","close":"21:00"},{"day":"thursday","dayTr":"Persembe","open":"09:00","close":"21:00"},{"day":"friday","dayTr":"Cuma","open":"09:00","close":"21:00"},{"day":"saturday","dayTr":"Cumartesi","open":"09:00","close":"21:00"},{"day":"sunday","dayTr":"Pazar","open":null,"close":null}],
  socialMedia: {"instagram":"https://instagram.com/organizasyon-firma"},
  photos: [],
  services: []
}
export const ORGANIZASYON_FIRMA_CONFIG: ThemeConfig = { id: 'organizasyon-firma', name: 'Kurumsal Etkinlik (B2B)', sectorId: 'organizasyon', plan: 'pro', isDark: false, cssVariables: { '--color-bg': '#FFFFFF', '--color-surface': '#F8FAFC', '--color-text': '#0F172A', '--color-accent': '#b32419',
    '--color-accent-light': '#fce9e8',
    '--color-accent-hover': '#8f1d14',
    '--color-accent-active': '#7d1912', '--color-text-on-accent': '#FFFFFF', '--color-border': '#E2E8F0', '--font-heading': "'Outfit', sans-serif", '--font-body': "'Roboto', sans-serif" }, fonts: { heading: { family: 'Outfit', weights: [600] }, body: { family: 'Roboto', weights: [400] } },   globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 0, removable: false, animation: 'none' as const },
      defaultContent: {
        logo: { type: 'text', text: 'Firma Etkinlik' },
        menuItems: [{ label: 'Hizmetler', href: '#hizmetler' }, { label: 'İletişim', href: '#iletisim' }],
        cta: { text: 'Ara', href: 'tel:0532 000 00 00', variant: 'solid' },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom' as const,
      settings: { bgMode: 'dark' as const, paddingY: 'sm' as const, containerWidth: 'full' as const, visible: true, order: 999, removable: false, animation: 'none' as const },
      defaultContent: {
        businessName: 'Firma Etkinlik',
        copyright: '© 2026 Firma Etkinlik',
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating' as const,
      settings: { bgMode: 'default' as const, paddingY: 'none' as const, containerWidth: 'full' as const, visible: true, order: 1000, removable: false, animation: 'none' as const },
      defaultContent: { phone: '905320000000', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
  ], pages: [{ id: 'anasayfa', slug: '/', title: 'Kurumsal Event', isHomePage: true, includeInNav: false, sections: [ { id: 'hero', type: 'hero', variant: 'auto', order: 1, required: true, settings: { bgMode: 'default', paddingY: 'xl', containerWidth: 'xl', visible: true }, defaultContent: { badge: 'KURUMSAL KİMLİK', title: 'Profesyonel İş ve Motivasyon Etkinlikleri' } } ] }] }