/**
 * @kepenk/templates — temizlik-hali Theme Configuration
 *
 * Hali yikama ve koltuk temizleme uzmani
 * Plan: growth (9 page sections, 4 global sections)
 * Font: Poppins/Inter | Accent: #2196F3
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const TEMIZLIK_HALI_CSS: Record<string, string> = {
  '--container-default': '1024px',
  '--section-py': '64px',
  '--radius-md': '6px',
  '--radius-lg': '12px',
  '--color-bg': '#FFFFFF',
  '--color-surface': '#F8FAFC',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#F1F5F9',
  '--color-text': '#0F172A',
  '--color-text-secondary': '#475569',
  '--color-text-muted': '#94A3B8',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#2196F3',
  '--color-accent-hover': '#2196F3',
  '--color-accent-active': '#2196F3',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#E2E8F0',
  '--color-border-subtle': '#F1F5F9',
  '--font-heading': '\'Poppins\', sans-serif',
  '--font-body': '\'Inter\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const TEMIZLIK_HALI_BUSINESS = {
  name: 'YikaPlus Hali & Koltuk Yikama',
  ownerName: 'Hasan Korkmaz',
  sectorId: 'Temizlik',
  slogan: 'Haliniz ve koltugunuz fabrika cikisi gibi',
  phone: '0534 281 93 70',
  phoneClean: '905342819370',
  whatsapp: '905342819370',
  email: 'info@yikaplus.com.tr',
  address: 'Icerenkoy Mah. Kayisdagi Cad. No:72, Atasehir/Istanbul',
  city: 'Istanbul',
  district: 'Atasehir',
  neighborhood: 'Icerenkoy',
  coordinates: { lat: 40.979, lng: 29.103 },
  socialMedia: {
    instagram: 'https://instagram.com/yikaplus',
    facebook: 'https://facebook.com/yikaplus',
    youtube: 'https://youtube.com/@yikaplus',
  },
  photos: [],
  foundedYear: 2011,
  experience: '15 yil',
  customerCount: '35.000+',
  rating: 4.8,
  reviewCount: 2200,
  workingHours: [
    {
      day: 'Pazartesi',
      open: '07:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '07:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '07:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '07:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '07:00',
      close: '20:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '08:00',
      close: '18:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '09:00',
      close: '15:00',
      isOpen: true,
    },
  ],
  services: [
    {
      id: 's1',
      name: 'Makine Hali Yikama',
      price: '40 TL/m2',
      duration: '2-3 gun',
      description: 'Fabrikada makine yikama, sifir atik su sistemi. Teslim alma ve birakma dahil.',
    },
    {
      id: 's2',
      name: 'El Hali Yikama',
      price: '80 TL/m2',
      duration: '3-5 gun',
      description: 'Ipek, yun ve el dokuma halilar icin nazik el yikama. Ozel deterjan.',
    },
    {
      id: 's3',
      name: 'Koltuk Yikama (Yerinde)',
      price: '300 TL/koltuk',
      duration: '45 dk/koltuk',
      description: 'Evinizde koltuk yikama. Leke cikarma, dezenfeksiyon, 2-3 saatte kuruma.',
    },
    {
      id: 's4',
      name: 'Yatak/Siltee Yikama',
      price: '500 TL/adet',
      duration: '60 dk',
      description: 'Yerinde yatak ve silte temizligi. Akar buharli dezenfeksiyon.',
    },
    {
      id: 's5',
      name: 'Perde Yikama & Asma',
      price: '25 TL/m2',
      duration: '2 gun',
      description: 'Perde sokme, yikama, utuleme ve yeniden asma. Tul ve kalin perde.',
    },
    {
      id: 's6',
      name: 'Hali Onarimi',
      price: '100 - 500 TL',
      duration: '3-7 gun',
      description: 'Hali kirpigi, saçak onarimi, delik tamiri. El dokuma halilarda uzman iscilik.',
    },
    {
      id: 's7',
      name: 'Leke Cikarma (Ozel)',
      price: '200 TL',
      duration: 'degisken',
      description: 'Inatci lekeler icin ozel islem: boya, murekkkep, pet lekesi, kan.',
    },
    {
      id: 's8',
      name: 'Anti-Alerjen Islem',
      price: '30 TL/m2',
      duration: 'ek',
      description: 'Akar, toz ve alerjen giderme ozel islemi. Alerji hastalaari icin oneriliir.',
    },
    {
      id: 's9',
      name: 'Hali Motalama',
      price: '20 TL/m2',
      duration: '1-2 gun',
      description: 'Temizlik sonrasi guveye karsi motalama islemi. 6 ay koruma.',
    },
    {
      id: 's10',
      name: 'Ucretsiz Teslim Alma/Birakma',
      price: 'Ucretsiz',
      duration: 'degisken',
      description: 'Kadikoy, Atasehir, Uskudar, Maltepe bolgesinde ucretsiz servis.',
    },
  ],
  team: [
    {
      name: 'Hasan Korkmaz',
      role: 'Kurucu & Genel Mudur',
      bio: '2. nesil hali yikamaci. Babasi 1985\'ten beri sektorde. 15 yillik deneyim, modern fabrika yatirimi.',
    },
    {
      name: 'Mustafa Yilmaz',
      role: 'El Yikama Ustasi',
      bio: '25 yillik el hali yikama ustasi. Ipek ve antika hali yikamada uzman.',
    },
    {
      name: 'Serkan Demir',
      role: 'Yerinde Hizmet Ekip Sefi',
      bio: 'Koltuk, yatak ve perde temizliginde 10 yil deneyim. 5 kisilik mobil ekip yonetiyor.',
    },
    {
      name: 'Elif Ozturk',
      role: 'Musteri Iliskileri',
      bio: 'Siparis koordinasyonu, teslim takibi ve memnuniyet yonetimi. 8 yildir YikaPlus\'ta.',
    },
  ],
  testimonials: [
    {
      name: 'Ayse Demir',
      district: 'Atasehir',
      date: '2025-11',
      rating: 5,
      comment: '3 halimiizi yikattik, hepsi piril piril geldi. Renkler canlanmis, koku tamamen gitmis. Ucretsiz servis de buyuk kolaylik.',
    },
    {
      name: 'Murat Sahin',
      district: 'Kadikoy',
      date: '2025-10',
      rating: 5,
      comment: 'Koltuk yikama icin eve geldiler. L koltuk + 2 tekli 1.5 saatte bitti. Lekeler tamamen cikmis. Cok memnunuuz.',
    },
    {
      name: 'Zehra Kaya',
      district: 'Uskudar',
      date: '2025-09',
      rating: 5,
      comment: 'El dokuma ipek halimi burada yikattim. Mustafa Usta cok dikkatli, el ile yuuzarak yikadi. Sonuc muhtesem.',
    },
    {
      name: 'Burak Yildiz',
      district: 'Maltepe',
      date: '2025-08',
      rating: 4,
      comment: 'Perde yikama hizmetini denedik. Sokme ve asma dahil, cok pratik. Tek sorun: teslim 1 gun gecikti.',
    },
    {
      name: 'Neslihan Aksoy',
      district: 'Kartal',
      date: '2025-07',
      rating: 5,
      comment: 'Anti-alerjen islem yaptirdik, cocugumun alerjisi vardi. Islem sonrasi belirgin rahatlama oldu. Artik duzenli yaptiriyoruz.',
    },
    {
      name: 'Hakan Tekin',
      district: 'Umraniye',
      date: '2025-12',
      rating: 5,
      comment: 'Antika halimizin saçaklari dokulmustu. Onarim yaptillar, yeni gibi oldu. El isciiligi gercekten farkli.',
    },
  ],
  faq: [
    { q: 'Hali yikama ne kadar suruyor?', a: 'Makine yikama 2-3 is gunu, el yikama 3-5 is gunu surmektedir. Yogun sezon (bahar/yaz) biraz daha uzayabilir.' },
    { q: 'Ucretsiz servis hangi bolgeler?', a: 'Kadikoy, Atasehir, Uskudar, Maltepe, Kartal, Pendik ve Umraniye bolgesinde ucretsiz teslim alma ve birakma yapiyoruz.' },
    { q: 'Ipek hali yikayabiliyor musunuz?', a: 'Evet, ipek ve el dokuma halilar icin ozel el yikama hizmetimiz var. Ustamiz 25 yillik deneyimlidir, haliniz guvenli ellerde.' },
    { q: 'Koltuk yikama sonrasi ne kadar surede kuruyor?', a: 'Ortalama 2-4 saatte kuruyor. Havalandirilmis ortamda daha hizli kururr. Fan kullanmanizi oneririz.' },
    { q: 'Anti-alerjen islem nedir?', a: 'Halinizdeki toz akarilari, alerjenler ve bakterileri ozel islemle giderir. Alerji ve astim hastalarına oneriliir. Yikama sonrasi ek islem olarak uygulanir.' },
    { q: 'Hali onarimi yapiyor musunuz?', a: 'Evet, kirpik, sacak, delik tamiri ve renk rotuslama yapiyoruz. El dokuma haliler icin ustamiz el isciilgiyle onarim yapar.' },
    { q: 'Garanti veriyor musunuz?', a: 'Evet, yikama sonrasi 3 gun icinde memnun kalmazsaniz ucretsiz yeniden yikama yapiyoruz.' },
    { q: 'Odeme nasil yapiliir?', a: 'Nakit, kredi karti ve havale kabul ediyoruz. Teslimatta odeme yapilir.' },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const TEMIZLIK_HALI_CONFIG = {
  id: 'temizlik-hali',
  name: 'Hali',
  sectorId: 'temizlik',
  plan: 'growth',
  description: 'Hali yikama ve koltuk temizleme uzmani',
  designPhilosophy: 'Dinamik, guvenilir, temiz',
  isDark: false,
  cssVariables: {
    '--container-default': '1024px',
    '--section-py': '64px',
    '--radius-md': '6px',
    '--radius-lg': '12px',
    '--color-bg': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#F1F5F9',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#475569',
    '--color-text-muted': '#94A3B8',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#2196F3',
    '--color-accent-hover': '#2196F3',
    '--color-accent-active': '#2196F3',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#E2E8F0',
    '--color-border-subtle': '#F1F5F9',
    '--font-heading': '\'Poppins\', sans-serif',
    '--font-body': '\'Inter\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Poppins',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Inter',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'CleaningService',
  sectorSections: [],
  performanceBudget: {
    maxJS: '180kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'YikaPlus Hali & Koltuk Yikama' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905342819370',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'YikaPlus Hali & Koltuk Yikama',
        copyright: '© 2026 YikaPlus Hali & Koltuk Yikama',
        contact: {
          phone: '0534 281 93 70',
          email: 'info@yikaplus.com.tr',
          address: 'Icerenkoy Mah. Kayisdagi Cad. No:72, Atasehir/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/yikaplus',
            icon: 'instagram',
          },
          {
            platform: 'facebook',
            url: 'https://facebook.com/yikaplus',
            icon: 'facebook',
          },
          {
            platform: 'youtube',
            url: 'https://youtube.com/@yikaplus',
            icon: 'youtube',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905342819370', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'YikaPlus Hali & Koltuk Yikama — Atasehir',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_bento_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'GÜVENAL A.Ş.', title: TEMIZLIK_HALI_BUSINESS.name, subtitle: TEMIZLIK_HALI_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'gallery',
          variant: 'tier1_bento_gallery',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { badge: 'VİTRİN', title: 'KURUMSAL KİMLİK' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_bento_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'YETKİNLİKLER', title: 'Sektörel Çözümler' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_bento_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { badge: 'İLETİŞİM', title: 'Görüşme Ayarla' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
