/**
 * @kepenk/templates — kahveci-lux Theme Configuration
 *
 * Premium kahve deneyimi, luks ortam
 * Plan: pro (11 page sections, 4 global sections)
 * Font: Cormorant Garamond/Lato | Accent: #854D0E
 * Generated by: scripts/generate-configs.ts
 */

import type { ThemeConfig, BusinessData } from '../../../../types/section-types'

// ═══ CSS VARIABLES ═══

export const KAHVECI_LUX_CSS: Record<string, string> = {
  '--container-default': '1200px',
  '--section-py': '96px',
  '--radius-md': '2px',
  '--radius-lg': '4px',
  '--color-bg': '#FAFAF9',
  '--color-surface': '#F5F5F4',
  '--color-surface-elevated': '#FFFFFF',
  '--color-surface-muted': '#E7E5E4',
  '--color-text': '#1C1917',
  '--color-text-secondary': '#57534E',
  '--color-text-muted': '#A8A29E',
  '--color-text-on-accent': '#FFFFFF',
  '--color-text-on-dark': '#F5F5F5',
  '--color-accent': '#854D0E',
  '--color-accent-hover': '#854D0E',
  '--color-accent-active': '#854D0E',
  '--color-accent-light': '#FEF3C7',
  '--color-border': '#D6D3D1',
  '--color-border-subtle': '#E7E5E4',
  '--font-heading': '\'Cormorant Garamond\', sans-serif',
  '--font-body': '\'Lato\', system-ui, sans-serif',
}

// ═══ DEMO BUSINESS DATA ═══

export const KAHVECI_LUX_BUSINESS = {
  name: 'Maison du Cafe Istanbul',
  ownerName: 'Selim Akkaya',
  sectorId: 'Kahveci',
  slogan: 'Kahvenin sanat hali',
  phone: '0212 260 33 44',
  phoneClean: '902122603344',
  whatsapp: '905481234567',
  email: 'reservation@maisoncafe.ist',
  address: 'Nisantasi Mah. Abdi Ipekci Cad. No:34, Sisli/Istanbul',
  city: 'Istanbul',
  district: 'Sisli',
  neighborhood: 'Nisantasi',
  coordinates: { lat: 41.0501, lng: 28.9918 },
  socialMedia: {
    instagram: 'https://instagram.com/maisoncafeist',
    youtube: 'https://youtube.com/@maisoncafe',
    pinterest: 'https://pinterest.com/maisoncafeist',
  },
  photos: [],
  foundedYear: 2015,
  experience: '11 yil',
  customerCount: '20.000+',
  rating: 4.9,
  reviewCount: 3200,
  services: [
    {
      id: 's1',
      name: 'Single Origin Tasting',
      price: '150 - 250 TL',
      duration: 'Ozel sunum',
      description: 'Sectiginiz tek origin kahve, ozel sunumla, origin hikayesi ve tasting note kartiyla.',
    },
    {
      id: 's2',
      name: 'Signature Coffee Cocktails',
      price: '180 - 280 TL',
      duration: '5-7 dk',
      description: 'Kahve bazli kokteiller: espresso martini, coffee negroni, cold brew spritz.',
    },
    {
      id: 's3',
      name: 'Artisan Pastry & Patisserie',
      price: '120 - 300 TL',
      duration: 'Servis',
      description: 'Fransiz pastane sefi tarafindan hazirlanan kruvasan, eclair, tart, macaron.',
    },
    {
      id: 's4',
      name: 'Brunch Experience',
      price: '450 - 800 TL/kisi',
      duration: 'Set menu',
      description: 'Premium brunch: eggs royale, truffle scramble, smoked salmon, pastry basket, kahve.',
    },
    {
      id: 's5',
      name: 'Private Tasting Room',
      price: '2.500 TL (6 kisilik)',
      duration: '90 dk',
      description: 'Ozel oda\'da 6 kisiye kadar cupping deneyimi. 5 farkli origin, food pairing.',
    },
    {
      id: 's6',
      name: 'Kisisel Kavurma Profili',
      price: '500 TL/500g',
      duration: '1 hafta',
      description: 'Damak tadınıza ozel kavurma profili gelistirme. Tadim sonrasi kisisel cekirdek uretimi.',
    },
    {
      id: 's7',
      name: 'Coffee Concierge',
      price: 'Uyelik bazli',
      duration: 'Surekli',
      description: 'Aylik ozel kavurma, oncelikli masa, etkinlik daveti ve kisisel barista hizmeti.',
    },
    {
      id: 's8',
      name: 'Ozel Etkinlik & Lansman',
      price: '15.000 TL\'den',
      duration: '3-5 saat',
      description: 'Marka lansmanı, ozel davet veya kurumsal etkinlik icin mekanin tamami veya ozel odalarin kiralanmasi.',
    },
    {
      id: 's9',
      name: 'Coffee & Chocolate Pairing',
      price: '350 TL/kisi',
      duration: '60 dk',
      description: '3 farkli origin kahve ile 3 farkli cikolata eslesstirme deneyimi. Max 10 kisi.',
    },
    {
      id: 's10',
      name: 'Barista Masterclass',
      price: '1.200 TL/kisi',
      duration: '4 saat',
      description: 'Profesyonel barista egitimi: espresso, latte art, pour over, sensory skills.',
    },
    {
      id: 's11',
      name: 'Premium Hediye Seti',
      price: '1.500 - 5.000 TL',
      duration: 'Ozel paketleme',
      description: 'El yapimi seramik fincan, ozel kavurma cekirdek, cikolata ve not kartiyla hediye seti.',
    },
    {
      id: 's12',
      name: 'Kurumsal Toplanti Paketi',
      price: '250 TL/kisi',
      duration: '2-4 saat',
      description: 'Is toplantilari icin ozel oda, kahve servisi, pastry ve hafif yemek.',
    },
    {
      id: 's13',
      name: 'Latte Art Workshop',
      price: '600 TL/kisi',
      duration: '2 saat',
      description: 'Latte art egitimi: kalp, yaprak, rozetta, tulip. Teknik ve pratik uygulamali.',
    },
    {
      id: 's14',
      name: 'Home Brewing Consultation',
      price: '800 TL',
      duration: '90 dk',
      description: 'Evinize uygun ekipman onerisi, kurulum ve uygulamali demleme egitimi.',
    },
  ],
  team: [
    {
      name: 'Selim Akkaya',
      title: 'Kurucu | Coffee Director',
      bio: 'SCA Q Grader, AST. 11 yillik specialty coffee deneyimi. Londra ve Melbourne\'da egitim. 15 origin ulke deneyimi.',
      photo: '',
    },
    {
      name: 'Chef Marie Dubois',
      title: 'Pastry Chef',
      bio: 'Le Cordon Bleu Paris mezunu. 12 yillik pastane deneyimi. Michelin yildizli restoranlarda calisma gecmisi.',
      photo: '',
    },
    {
      name: 'Cem Onder',
      title: 'Head Barista & Trainer',
      bio: 'Turkiye Barista Sampiyonu (2022). World Barista Championship katilimcisi. SCA AST.',
      photo: '',
    },
    {
      name: 'Eda Sari',
      title: 'Roast Master',
      bio: 'SCA Roasting Professional. Probat ve Loring kavurma makinelerinde uzmanlik. Green bean sourcing.',
      photo: '',
    },
    {
      name: 'Bora Akin',
      title: 'Bar Manager | Mixologist',
      bio: '8 yillik mixology deneyimi. Coffee cocktail gelistirme. Diageo World Class katilimcisi.',
      photo: '',
    },
    {
      name: 'Sevgi Yilmaz',
      title: 'Musteri Deneyimi Muduru',
      bio: '10 yillik luxury hospitality deneyimi. Four Seasons ve Raffles otellerinde calisma gecmisi.',
      photo: '',
    },
  ],
  workingHours: [
    {
      day: 'Pazartesi',
      open: '08:00',
      close: '23:00',
      isOpen: true,
    },
    {
      day: 'Sali',
      open: '08:00',
      close: '23:00',
      isOpen: true,
    },
    {
      day: 'Carsamba',
      open: '08:00',
      close: '23:00',
      isOpen: true,
    },
    {
      day: 'Persembe',
      open: '08:00',
      close: '23:00',
      isOpen: true,
    },
    {
      day: 'Cuma',
      open: '08:00',
      close: '00:00',
      isOpen: true,
    },
    {
      day: 'Cumartesi',
      open: '09:00',
      close: '00:00',
      isOpen: true,
    },
    {
      day: 'Pazar',
      open: '09:00',
      close: '22:00',
      isOpen: true,
    },
  ],
} as unknown as BusinessData

// ═══ THEME CONFIG ═══

export const KAHVECI_LUX_CONFIG = {
  id: 'kahveci-lux',
  name: 'Lux',
  sectorId: 'kahveci',
  plan: 'pro',
  description: 'Premium kahve deneyimi, luks ortam',
  designPhilosophy: 'Luks, zarif, deneyim odakli',
  isDark: false,
  cssVariables: {
    '--container-default': '1200px',
    '--section-py': '96px',
    '--radius-md': '2px',
    '--radius-lg': '4px',
    '--color-bg': '#FAFAF9',
    '--color-surface': '#F5F5F4',
    '--color-surface-elevated': '#FFFFFF',
    '--color-surface-muted': '#E7E5E4',
    '--color-text': '#1C1917',
    '--color-text-secondary': '#57534E',
    '--color-text-muted': '#A8A29E',
    '--color-text-on-accent': '#FFFFFF',
    '--color-text-on-dark': '#F5F5F5',
    '--color-accent': '#854D0E',
    '--color-accent-hover': '#854D0E',
    '--color-accent-active': '#854D0E',
    '--color-accent-light': '#FEF3C7',
    '--color-border': '#D6D3D1',
    '--color-border-subtle': '#E7E5E4',
    '--font-heading': '\'Cormorant Garamond\', sans-serif',
    '--font-body': '\'Lato\', system-ui, sans-serif',
  },
  fonts: {
    heading: {
      family: 'Cormorant Garamond',
      weights: [700, 800],
      subsets: ['latin-ext'],
    },
    body: {
      family: 'Lato',
      weights: [400, 500, 600],
      subsets: ['latin-ext'],
    },
  },
  seoSchemaType: 'CafeOrCoffeeShop',
  sectorSections: [],
  performanceBudget: {
    maxJS: '250kb',
    maxLCP: '3.0s',
    animationLevel: 'framer-full',
  },
  globalSections: [
    {
      id: 'global-header',
      type: 'header',
      variant: 'auto',
      order: 0,
      required: true,
      position: 'top',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 0,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        logo: { type: 'text', text: 'Maison du Cafe Istanbul' },
        menuItems: [
          { label: 'Hizmetler', href: '#hizmetler' },
          { label: 'Hakkımızda', href: '#hakkimizda' },
          { label: 'İletişim', href: '#iletisim' },
          { label: 'SSS', href: '#faq' },
        ],
        cta: {
          text: 'WhatsApp',
          href: 'https://wa.me/905481234567',
          variant: 'solid',
        },
      },
      editableFields: [],
    },
    {
      id: 'global-footer',
      type: 'footer',
      variant: 'auto',
      order: 999,
      required: true,
      position: 'bottom',
      settings: {
        bgMode: 'dark',
        paddingY: 'sm',
        containerWidth: 'full',
        visible: true,
        order: 999,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        businessName: 'Maison du Cafe Istanbul',
        copyright: '© 2026 Maison du Cafe Istanbul',
        contact: {
          phone: '0212 260 33 44',
          email: 'reservation@maisoncafe.ist',
          address: 'Nisantasi Mah. Abdi Ipekci Cad. No:34, Sisli/Istanbul',
        },
        social: [
          {
            platform: 'instagram',
            url: 'https://instagram.com/maisoncafeist',
            icon: 'instagram',
          },
          {
            platform: 'youtube',
            url: 'https://youtube.com/@maisoncafe',
            icon: 'youtube',
          },
          {
            platform: 'pinterest',
            url: 'https://pinterest.com/maisoncafeist',
            icon: 'pinterest',
          },
        ],
        legal: [
          { label: 'Gizlilik', href: '/gizlilik' },
          { label: 'KVKK', href: '/kvkk' },
        ],
        poweredBy: 'kepenk.ai',
      },
      editableFields: [],
    },
    {
      id: 'global-whatsapp',
      type: 'whatsapp_cta',
      variant: 'floating',
      order: 1000,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'default',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1000,
        removable: false,
        animation: 'none',
      },
      defaultContent: { phone: '905481234567', message: 'Merhaba, bilgi almak istiyorum.' },
      editableFields: [],
    },
    {
      id: 'global-cookie',
      type: 'cookie_banner',
      variant: 'bottom_bar',
      order: 1001,
      required: true,
      position: 'floating',
      settings: {
        bgMode: 'surface',
        paddingY: 'none',
        containerWidth: 'full',
        visible: true,
        order: 1001,
        removable: false,
        animation: 'none',
      },
      defaultContent: {
        text: 'Çerezleri en iyi deneyim için kullanıyoruz.',
        acceptText: 'Kabul Et',
        rejectText: 'Reddet',
        detailsLink: '/gizlilik',
      },
      editableFields: [],
    },
  ],
  pages: [
    {
      id: 'anasayfa',
      slug: '/',
      title: 'Maison du Cafe Istanbul — Sisli',
      titleTr: 'Ana Sayfa',
      isHomePage: true,
      includeInNav: false,
      sections: [
        {
          id: 'hero',
          type: 'hero',
          variant: 'tier1_editorial_hero',
          order: 1,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 1, removable: false, animation: 'none' },
          defaultContent: { badge: 'ÖZEL KONSEPT', title: KAHVECI_LUX_BUSINESS.name, subtitle: KAHVECI_LUX_BUSINESS.slogan },
          editableFields: [
            { path: 'badge', label: 'Rozet / Etiket', type: 'text' },
            { path: 'title', label: 'Ana Başlık', type: 'text' },
            { path: 'subtitle', label: 'Açıklama / Slogan', type: 'richtext' },
            { path: 'cta1.text', label: 'Buton Yazısı', type: 'text' }
          ]
        },
        {
          id: 'hakkimizda',
          type: 'about',
          variant: 'tier1_editorial_about',
          order: 2,
          required: true,
          settings: { bgMode: 'surface', paddingY: 'none', containerWidth: 'full', visible: true, order: 2, removable: true, animation: 'none' },
          defaultContent: { title: 'Felsefemiz' },
          editableFields: [
            { path: 'badge', label: 'Rozet', type: 'text' },
            { path: 'title', label: 'Bölüm Başlığı', type: 'text' },
            { path: 'description', label: 'Açıklama Metni', type: 'richtext' }
          ]
        },
        {
          id: 'hizmetler',
          type: 'services',
          variant: 'tier1_editorial_services',
          order: 3,
          required: true,
          settings: { bgMode: 'default', paddingY: 'none', containerWidth: 'full', visible: true, order: 3, removable: false, animation: 'none' },
          defaultContent: { badge: 'ATELIER', title: 'Seçkin Koleksiyon' },
          editableFields: [
            { path: 'badge', label: 'Servis Rozeti', type: 'text' },
            { path: 'title', label: 'Servis Başlığı', type: 'text' }
          ]
        },
        {
          id: 'iletisim',
          type: 'contact',
          variant: 'tier1_editorial_contact',
          order: 4,
          required: true,
          settings: { bgMode: 'text', paddingY: 'none', containerWidth: 'full', visible: true, order: 4, removable: false, animation: 'none' },
          defaultContent: { title: 'Randevu & Danışmanlık' },
          editableFields: [
            { path: 'badge', label: 'İletişim Rozeti', type: 'text' },
            { path: 'title', label: 'İletişim Başlığı', type: 'text' }
          ]
        }
      ],
    },
  ],
} as unknown as ThemeConfig
